# Find closest sequence

Typically, ClinVar uses only one or a few reference sequences for a human gene.  We
should find the sequences from other species that are most similar to the human
reference sequence.  

To illustrate, let's consider ALPL.  Below we see that there are XXX variants
in the ClinVar database. 

**Note:** I had to update the code for the `get_variant_details()` function.
The `@RecordType` appears to have changed to `classified`.  I suspect that this
is due to the expansion of the database to include both germline and somatic
mutations.  The new function needs more comprehensive testing but it seems to
work fine on the ABCD1 variants.

In [2]:
run kondrashov

### Step 1 identify reference human sequence
##### I check each Clinvar variant per gene in 'pathogenic' directory and sift througth to identify unique transcripts

In [3]:
import os
os.getcwd()
os.listdir()
os.chdir("/Users/adesinamary/Documents/kondrashov")

In [ ]:
import pandas as pd
from tqdm import tqdm

ABCD1_df = pd.read_csv("pathogenic_lociii/ABCD1.csv", sep= '\t')
varids = ABCD1_df["VariationID"].astype(str).tolist()
#ABCD1_df.head()
varids

['11292',
 '11293',
 '11294',
 '11296',
 '11297',
 '11298',
 '11299',
 '11300',
 '11301',
 '11302',
 '11304',
 '11305',
 '11307',
 '11308',
 '11310',
 '11312',
 '11313',
 '11315',
 '11316',
 '35642',
 '35643',
 '92314',
 '92317',
 '92318',
 '92319',
 '92320',
 '92321',
 '92322',
 '92323',
 '92325',
 '92326',
 '166625',
 '166626',
 '166624',
 '193033',
 '193035',
 '197096',
 '198687',
 '218418',
 '281336',
 '369726',
 '372736',
 '419446',
 '430349',
 '430026',
 '452524',
 '449353',
 '458642',
 '458644',
 '458635',
 '458637',
 '458636',
 '458641',
 '458646',
 '458629',
 '458639',
 '488393',
 '496882',
 '522793',
 '523312',
 '523894',
 '528338',
 '528341',
 '528337',
 '528343',
 '528346',
 '528345',
 '572502',
 '577418',
 '570327',
 '576910',
 '580587',
 '585300',
 '585301',
 '585302',
 '590972',
 '592198',
 '623112',
 '623113',
 '623114',
 '623115',
 '623118',
 '624451',
 '665836',
 '651954',
 '665751',
 '651649',
 '656786',
 '642905',
 '665959',
 '659797',
 '689439',
 '689462',
 '691979',
 '691977',
 '693988',
 '694632',
 '804104',
 '804105',
 '804106',
 '804107',
 '804111',
 '851448',
 '862617',
 '863311',
 '839969',
 '835571',
 '839309',
 '837244',
 '855099',
 '839877',
 '842966',
 '870532',
 '872954',
 '915334',
 '951267',
 '948303',
 '949359',
 '952828',
 '947381',
 '951851',
 '943867',
 '943180',
 '937387',
 '935868',
 '940780',
 '947117',
 '963694',
 '957421',
 '957802',
 '966099',
 '976237',
 '975891',
 '976062',
 '987500',
 '995867',
 '996091',
 '996792',
 '1009241',
 '1039444',
 '1037296',
 '1067768',
 '1066681',
 '1075691',
 '1068643',
 '1072909',
 '1076801',
 '1073700',
 '1172518',
 '1172887',
 '1176607',
 '1192215',
 '1204276',
 '1207933',
 '1213362',
 '4710901',
 '1322441',
 '1323829',
 '1323830',
 '1323832',
 '1323833',
 '2630273',
 '1323835',
 '1339238',
 '1521520',
 '1509311',
 '1509371',
 '1509409',
 '1357576',
 '1385113',
 '1455734',
 '1455740',
 '1455744',
 '1455747',
 '1375264',
 '1457370',
 '1459053',
 '1368917',
 '1479518',
 '1456610',
 '1512177',
 '1483831',
 '1403263',
 '1524740',
 '1469544',
 '1379703',
 '1410844',
 '1410853',
 '1685231',
 '1687351',
 '1704409',
 '1710079',
 '1718168',
 '1724267',
 '1724351',
 '1726921',
 '1750003',
 '1767303',
 '1774964',
 '1784451',
 '1784111',
 '1800630',
 '1803989',
 '1806364',
 '2138760',
 '2138761',
 '2138765',
 '2138766',
 '2138768',
 '2138769',
 '2138770',
 '2138772',
 '2138774',
 '2151644',
 '2152355',
 '1973153',
 '1978762',
 '1983290',
 '2122038',
 '2131471',
 '2129372',
 '2435953',
 '2436863',
 '2438719',
 '2501670',
 '2501953',
 '2503797',
 '2504924',
 '2506019',
 '2574959',
 '2628324',
 '2637174',
 '2635257',
 '2635355',
 '2679143',
 '2686052',
 '2690501',
 '2690502',
 '2691890',
 '2700761',
 '2719512',
 '2708443',
 '2718203',
 '2723850',
 '2732781',
 '2738141',
 '2737398',
 '2737399',
 '2737401',
 '2737402',
 '2737405',
 '2737408',
 '2737409',
 '2737410',
 '2737414',
 '2737415',
 '2737416',
 '2737417',
 '2737418',
 '2737420',
 '2745952',
 '2747582',
 '2738619',
 '2766757',
 '2807830',
 '2817425',
 '2825518',
 '2825615',
 '2829099',
 '2828351',
 '2836431',
 '2856657',
 '2884134',
 '3068231',
 '3240094',
 '3338820',
 '3338821',
 '3340680',
 '3347149',
 '3391299',
 '3636349',
 '3636352',
 '3636355',
 '3637474',
 '3649646',
 '3661074',
 '3724595',
 '3724612',
 '3724613',
 '3724614',
 '3724615',
 '3724618',
 '3724620',
 '3724627',
 '3724631',
 '3724632',
 '3717416',
 '3729247',
 '3764502',
 '3773728',
 '3902430',
 '3906116',
 '4063763',
 '4072425',
 '4077528',
 '4081076',
 '4081078',
 '4136564',
 '4280627',
 '4291723',
 '4705094',
 '4710903',
 '4710908',
 '4710909',
 '4734900',
 '4736175',
 '4755481',
 '4802198',
 '4802199',
 '4802200',
 '4802205',
 '4802208',
 '4818088',
 '4849478',
 '4851269',
 '4885746',
 '4887817']

In [ ]:
import pandas as pd
from tqdm import tqdm

F7_df = pd.read_csv("pathogenic_lociii/F7.csv", sep= '\t')
varids = F7_df["VariationID"].astype(str).tolist()

unique_acc = set()

for varid in tqdm(varids):
    varrec = get_variant(varid)
    #print(varrec)
    name, acc, mut, pmut, muttype = get_variant_details(varrec)
    
    #name, acc, mut, pmut, muttype, status = get_variant_details(varrec)

    if acc is not None:
        unique_acc.add(acc)

print(f"Found {len(unique_acc)} unique accession(s):")
print(sorted(unique_acc))

100%|██████████| 81/81 [00:38<00:00,  2.10it/s]

Found 4 unique accession(s):
['NM_000131.4', 'NM_000131.5', 'NM_019616.4', 'none']

## Variant naming style varies let's take a look at ABCD1 and F7; 
### ABCD1:  NM_000033.4(ABCD1):c.1256T>C (p.Val419Ala)
### F7: NC_000023.11:g.155022771G>A 

Preferred style is the first example (ABCD1), because it tells us the protein mutant

In [ ]:
var_name = varrec["@VariationName"]
print(var_name)
var_name_split1 = var_name.split("(")
var_name_split2 = var_name_split1[1].split(")")
gene_name = var_name_split2[0]
transcript = var_name_split1[0]
nucl = var_name_split2[1][3:-1]
print(var_name_split1)
print(gene_name, transcript, nucl)

var = varrec["@RecordType"]

if varrec["@RecordType"] == "classified":
        rec_type = "ClassifiedRecord"
effect = varrec[rec_type]
#["Interpretations"]["Interpretation"]["Description"]
#effect

NM_019616.4(F7):c.1022C>G (p.Pro341Arg)
['NM_019616.4', 'F7):c.1022C>G ', 'p.Pro341Arg)']
F7 NM_019616.4 1022C>G

### STEP 2 Obtain corresponding protein of each unique human transcript

In [ ]:
transcript_record = get_transcript("NM_000478.6")
xx= get_protein_from_transcript(transcript_record)
xx

(Seq('atgatttcaccattcttagtactggccattggcacctgccttactaactcctta...tga'),
 Seq('MISPFLVLAIGTCLTNSLVPEKEKDPKYWRDQAQETLKYALELQKLNTNVAKNV...VLF'),
 'NP_000469.3',
 199,
 1774)

## Run these next two codes instead
### These combine step 1 and step 2 using functions 'identify_unique_transcripts' and 'get_reference_proteins'

In [48]:
run kondrashov

In [ ]:
lociii

['ABCA12',
 'ABCD1',
 'ACAD9',
 'ACADM',
 'ACADVL',
 'ACAT1',
 'ADA',
 'AGL',
 'AGXT',
 'AHI1',
 'AIRE',
 'ALMS1',
 'ALOX12B',
 'ALPL',
 'ANK1',
 'ANO5',
 'APC',
 'AR',
 'ARSA',
 'ARSB',
 'ASL',
 'ASPA',
 'ASPM',
 'ATM',
 'ATP7B',
 'BBS2',
 'BCKDHA',
 'BEST1',
 'BLM',
 'BRIP1',
 'BTD',
 'BTK',
 'CASR',
 'CBS',
 'CC2D2A',
 'CDH23',
 'CEP290',
 'CERKL',
 'CFTR',
 'CHD7',
 'CHEK2',
 'CLN3',
 'CNGB3',
 'CPS1',
 'CRB1',
 'CTNS',
 'CYBB',
 'CYP11B1',
 'CYP17A1',
 'CYP27A1',
 'DCLRE1C',
 'DICER1',
 'DUOX2',
 'EHMT1',
 'ELP1',
 'ERCC6',
 'EVC',
 'EVC2',
 'EXT1',
 'EXT2',
 'EYS',
 'F7',
 'F8',
 'F9',
 'FANCA',
 'FANCI',
 'FBN2',
 'FKRP',
 'FLCN',
 'FRAS1',
 'G6PD',
 'GAA',
 'GALC',
 'GALNS',
 'GALT',
 'GBA1',
 'GBE1',
 'GCDH',
 'GJB1',
 'GLB1',
 'GNE',
 'GNPTAB',
 'HBB',
 'HEXA',
 'HEXB',
 'HGD',
 'HGSNAT',
 'HMBS',
 'HPRT1',
 'HPS3',
 'IL2RG',
 'ITGA2B',
 'IVD',
 'KCNH2',
 'KCNQ1',
 'KRIT1',
 'L1CAM',
 'LDLR',
 'LIPA',
 'LOXHD1',
 'LPL',
 'LRPPRC',
 'LYST',
 'MAN2B1',
 'MCCC1',
 'MCCC2',
 'MED13L',
 'MFN2',
 'MKS1',
 'MMUT',
 'MPZ',
 'MSH2',
 'MTHFR',
 'MUTYH',
 'MYH7',
 'NAGLU',
 'NF1',
 'NF2',
 'NIPBL',
 'NPC1',
 'NSD1',
 'OCA2',
 'OPA1',
 'PAH',
 'PALB2',
 'PAX3',
 'PAX6',
 'PCDH15',
 'PCNT',
 'PKHD1',
 'PMM2',
 'POMGNT1',
 'PRPF31',
 'PYGM',
 'RAD50',
 'RARS2',
 'RECQL4',
 'RHO',
 'RP1',
 'RPGRIP1L',
 'SACS',
 'SATB2',
 'SCN4A',
 'SERPING1',
 'SGSH',
 'SI',
 'SLC12A6',
 'SLC25A13',
 'SLC26A4',
 'SMPD1',
 'SPAST',
 'SPG11',
 'SYNE1',
 'TCIRG1',
 'TMC1',
 'TMEM67',
 'TP53',
 'TPP1',
 'TSC1',
 'TTR',
 'TYR',
 'UNC13D',
 'USH1C',
 'USH2A',
 'VHL',
 'VPS13A',
 'VPS13B',
 'VWF',
 'WFS1',
 'WRN',
 'WT1',
 'XPC',
 'ZEB2',
 'ZFYVE26']

In [ ]:
os.getcwd()
bb= os.listdir("pathogenic_lociii")

In [ ]:
sorted(bb)
len(bb)

904

In [ ]:
# find the position of a gene in locie
print(locie.index("TNNT2"))
vv= locie[842:]
print(vv)

841
['TNXB', 'TP53', 'TP63', 'TPM1', 'TPO', 'TPP1', 'TRIM37', 'TRIO', 'TRIOBP', 'TRMU', 'TRPM1', 'TRPS1', 'TRPV4', 'TSC1', 'TSC2', 'TSHR', 'TTC21B', 'TTC7A', 'TTLL5', 'TTN', 'TTR', 'TUBA1A', 'TUBB2B', 'TUBB3', 'TUBGCP6', 'TULP1', 'TWIST1', 'TWNK', 'TYMP', 'TYR', 'TYRP1', 'UBE3A', 'UBR1', 'UMOD', 'UNC13D', 'UNC80', 'USH1C', 'USH2A', 'USP9X', 'VCP', 'VHL', 'VPS13A', 'VPS13B', 'VPS13C', 'VPS13D', 'VWF', 'WAS', 'WDFY3', 'WDR19', 'WDR45', 'WDR62', 'WFS1', 'WNT10A', 'WRN', 'WT1', 'WWOX', 'XPC', 'ZBTB20', 'ZEB2', 'ZFYVE26', 'ZNF469']

### Step 3

In [ ]:
#loci = ["ALPL", "ABCD1", "CFTR"]    
gene_transcripts = {}

for gene in vv:
    gene_transcripts[gene] = identify_unique_transcripts(gene)
    #print(f"{gene} : {unique_acc}")
    #print(gene_transcripts)

'TNXB': {'NM_001365276.2'},
'TP53': {'NM_000546.6'},
'TP63': {'NM_001114980.2', 'NM_003722.5'},
'TPM1': {'NM_001018005.2'},
'TPO': {'NM_001206744.2'},
'TPP1': {'NM_000391.4'},
'TRIM37': {'NM_001005207.5', 'NM_015294.6'},
'TRIO': {'NM_007118.4'},
'TRIOBP': {'NM_001039141.3'},
'TRMU': {'NM_018006.5'},
'TRPM1': {'NM_001252024.2'},
'TRPS1': {'NM_014112.5'},
'TRPV4': {'NM_021625.5'},
'TSC1': {'NM_000368.5'},
'TSC2': {'NM_000548.5'},
'TSHR': {'NM_000369.5'},
'TTC21B': {'NM_024753.5'},
'TTC7A': {'NM_020458.4'},
'TTLL5': {'NM_015072.5'},
'TTN': {'NM_001267550.1', 'NM_001267550.2'},
'TTR': {'NM_000371.4'},
'TUBA1A': {'NM_006009.4'},
'TUBB2B': {'NM_178012.5'},
'TUBB3': {'NM_006086.4'},
'TUBGCP6': {'NM_020461.4'},
'TULP1': {'NM_003322.6'},
'TWIST1': {'NM_000474.4'},
'TWNK': {'NM_021830.5'},
'TYMP': {'NM_001953.5'},
'TYR': {'NM_000372.5', 'NM_000372.4'},
'TYRP1': {'NM_000550.3'},
'UBE3A': {'NM_130839.5'},
'UBR1': {'NM_174916.3'},
'UMOD': {'NM_003361.4'},
'UNC13D': {'NM_199242.3'},
'UNC80': {'NM_001371986.1'},
'USH1C': {'NM_153676.4', 'NM_005709.4'},
'USH2A': {'NM_206933.4', 'none'},
'USP9X': {'NM_001039591.3'},
'VCP': {'NM_007126.5'},
'VHL': {'NM_000551.4'},
'VPS13A': {'NM_033305.3'},
'VPS13B': {'NM_017890.5', 'NM_152564.5'},
'VPS13C': {'NM_020821.3'},
'VPS13D': {'NM_015378.4'},
'VWF': {'NM_000552.5'},
'WAS': {'NM_000377.3'},
'WDFY3': {'NM_014991.6'},
'WDR19': {'NM_025132.4'},
'WDR45': {'NM_001029896.2'},
'WDR62': {'NM_001083961.2'},
'WFS1': {'NM_006005.3'},
'WNT10A': {'NM_025216.3'},
'WRN': {'NM_000553.6'},
'WT1': {'NM_024426.6'},
'WWOX': {'NM_016373.4'},
'XPC': {'NM_004628.5'},
'ZBTB20': {'NM_001348800.3'},
'ZEB2': {'NM_014795.4'},
'ZFYVE26': {'NM_015346.4'},
'ZNF469': {'NM_001367624.2'},

In [ ]:
gene_transcripts = {'ABCA12': {'NM_173076.3'},
 'ABCD1': {'NM_000033.4'},
 'ACAD9': {'NM_014049.4', 'NM_014049.5'},
 'ACADM': {'NM_000016.6'},
 'ACADVL': {'NM_000018.4'},
 'ACAT1': {'NM_000019.4'},
 'ADA': {'NM_000022.4'},
 'AGL': {'NM_000642.3'},
 'AGXT': {'NM_000030.3'},
 'AHI1': {'NM_001134831.2'},
 'AIRE': {'NM_000383.4'},
 'ALMS1': {'NM_001378454.1'},
 'ALOX12B': {'NM_001139.3'},
 'ALPL': {'NM_000478.6'},
 'ANK1': {'NM_000037.4'},
 'ANO5': {'NM_213599.3'},
 'APC': {'NM_000038.6', 'NM_001127510.3', 'NM_001127511.3'},
 'AR': {'NM_000044.6'},
 'ARSA': {'NM_000487.6'},
 'ARSB': {'NM_000046.5'},
 'ASL': {'NM_000048.4'},
 'ASPA': {'NM_000049.4'},
 'ASPM': {'NM_018136.5'},
 'ATM': {'NM_000051.4'},
 'ATP7B': {'NM_000053.4'},
 'BBS2': {'NM_031885.5'},
 'BCKDHA': {'NM_000709.4'},
 'BEST1': {'NM_004183.4'},
 'BLM': {'NM_000057.4'},
 'BRIP1': {'NM_032043.3'},
 'BTD': {'NM_001370658.1'},
 'BTK': {'NM_000061.3'},
 'CASR': {'NM_000388.4'},
 'CBS': {'NM_000071.3'},
 'CC2D2A': {'NM_001378615.1'},
 'CDH23': {'NM_022124.6'},
 'CEP290': {'NM_025114.4'},
 'CERKL': {'NM_201548.5'},
 'CFTR': {'NM_000492.3', 'NM_000492.4'},
 'CHD7': {'NM_017780.4'},
 'CHEK2': {'NM_007194.4'},
 'CLN3': {'NM_001042432.2'},
 'CNGB3': {'NM_019098.5'},
 'CPS1': {'NM_001875.5'},
 'CRB1': {'NM_201253.3'},
 'CTNS': {'NM_004937.3'},
 'CYBB': {'NM_000397.4'},
 'CYP11B1': {'NM_000497.4'},
 'CYP17A1': {'NM_000102.4'},
 'CYP27A1': {'NM_000784.4'},
 'DCLRE1C': {'NM_001033855.3'},
 'DICER1': {'NM_177438.3'},
 'DUOX2': {'NM_001363711.2'},
 'EHMT1': {'NM_024757.5'},
 'ELP1': {'NM_003640.5'},
 'ERCC6': {'NM_000124.4', 'NM_001277058.2'},
 'EVC': {'NM_153717.3'},
 'EVC2': {'NM_147127.5'},
 'EXT1': {'NM_000127.3'},
 'EXT2': {'NM_207122.2'},
 'EYS': {'NM_001142800.2'},
 'F7': {'NM_000131.4', 'NM_000131.5', 'NM_019616.4'},
 'F8': {'NM_000132.4'},
 'F9': {'NM_000133.4'},
 'FANCA': {'NM_000135.4'},
 'FANCI': {'NM_001113378.2'},
 'FBN2': {'NM_001999.4'},
 'FKRP': {'NM_024301.5'},
 'FLCN': {'NM_144997.7'},
 'FRAS1': {'NM_025074.7'},
 'G6PD': {'NM_000402.4', 'NM_001042351.3', 'NM_001360016.2'},
 'GAA': {'NM_000152.5'},
 'GALC': {'NM_000153.4'},
 'GALNS': {'NM_000512.5'},
 'GALT': {'NM_000155.4'},
 'GBA1': {'NM_000157.4'},
 'GBE1': {'NM_000158.4'},
 'GCDH': {'NM_000159.4'},
 'GJB1': {'NM_000166.6', 'NM_001097642.3'},
 'GLB1': {'NM_000404.4'},
 'GNE': {'NM_001128227.3', 'NM_005476.7'},
 'GNPTAB': {'NM_024312.5'},
 'HBB': {'NM_000518.4', 'NM_000518.5'},
 'HEXA': {'NM_000520.6'},
 'HEXB': {'NM_000521.4'},
 'HGD': {'NM_000187.4'},
 'HGSNAT': {'NM_152419.3'},
 'HMBS': {'NM_000190.4'},
 'HPRT1': {'NM_000194.2', 'NM_000194.3'},
 'HPS3': {'NM_032383.5'},
 'IL2RG': {'NM_000206.3'},
 'ITGA2B': {'NM_000419.5'},
 'IVD': {'NM_002225.5'},
 'KCNH2': {'NM_000238.4'},
 'KCNQ1': {'NM_000218.3'},
 'KRIT1': {'NM_194454.3'},
 'L1CAM': {'NM_001278116.2'},
 'LDLR': {'NM_000527.4', 'NM_000527.5'},
 'LIPA': {'NM_000235.4'},
 'LOXHD1': {'NM_001384474.1'},
 'LPL': {'NM_000237.3'},
 'LRPPRC': {'NM_133259.4'},
 'LYST': {'NM_000081.4'},
 'MAN2B1': {'NM_000528.4'},
 'MCCC1': {'NM_020166.5'},
 'MCCC2': {'NM_022132.5'},
 'MED13L': {'NM_015335.5'},
 'MFN2': {'NM_014874.4'},
 'MKS1': {'NM_017777.4'},
 'MMUT': {'NM_000255.4'},
 'MPZ': {'NM_000530.8'},
 'MSH2': {'NM_000251.3'},
 'MTHFR': {'NM_005957.5'},
 'MUTYH': {'NM_001048174.2', 'NM_001128425.2'},
 'MYH7': {'NM_000257.4'},
 'NAGLU': {'NM_000263.4'},
 'NF1': {'NM_001042492.3'},
 'NF2': {'NM_000268.4'},
 'NIPBL': {'NM_133433.4'},
 'NPC1': {'NM_000271.5'},
 'NSD1': {'NM_022455.5'},
 'OCA2': {'NM_000275.3'},
 'OPA1': {'NM_130837.3'},
 'PAH': {'NM_000277.3'},
 'PALB2': {'NM_024675.4'},
 'PAX3': {'NM_181457.3', 'NM_181458.4'},
 'PAX6': {'NM_000280.6', 'NM_001368894.2'},
 'PCDH15': {'NM_001384140.1', 'NM_033056.4'},
 'PCNT': {'NM_006031.6'},
 'PKHD1': {'NM_138694.4'},
 'PMM2': {'NM_000303.3'},
 'POMGNT1': {'NM_017739.4'},
 'PRPF31': {'NM_015629.4'},
 'PYGM': {'NM_005609.4'},
 'RAD50': {'NM_005732.4'},
 'RARS2': {'NM_020320.5'},
 'RECQL4': {'NM_004260.4'},
 'RHO': {'NM_000539.3'},
 'RP1': {'NM_001375654.1', 'NM_006269.2'},
 'RPGRIP1L': {'NM_015272.5'},
 'SACS': {'NM_014363.6'},
 'SATB2': {'NM_001172509.2', 'NM_001172517.1'},
 'SCN4A': {'NM_000334.4'},
 'SERPING1': {'NM_000062.3'},
 'SGSH': {'NM_000199.5'},
 'SI': {'NM_001041.4'},
 'SLC12A6': {'NM_001365088.1'},
 'SLC25A13': {'NM_014251.3'},
 'SLC26A4': {'NM_000441.2'},
 'SMPD1': {'NM_000543.5'},
 'SPAST': {'NM_014946.4'},
 'SPG11': {'NM_025137.4'},
 'SYNE1': {'NM_001347702.2', 'NM_182961.4'},
 'TCIRG1': {'NM_006019.4'},
 'TMC1': {'NM_138691.3'},
 'TMEM67': {'NM_153704.6'},
 'TP53': {'NM_000546.6'},
 'TPP1': {'NM_000391.4'},
 'TSC1': {'NM_000368.5'},
 'TTR': {'NM_000371.4'},
 'TYR': {'NM_000372.4', 'NM_000372.5'},
 'UNC13D': {'NM_199242.3'},
 'USH1C': {'NM_005709.4', 'NM_153676.4'},
 'USH2A': {'NM_206933.4'},
 'VHL': {'NM_000551.4'},
 'VPS13A': {'NM_033305.3'},
 'VPS13B': {'NM_017890.5', 'NM_152564.5'},
 'VWF': {'NM_000552.5'},
 'WFS1': {'NM_006005.3'},
 'WRN': {'NM_000553.6'},
 'WT1': {'NM_024426.6'},
 'XPC': {'NM_004628.5'},
 'ZEB2': {'NM_014795.4'},
 'ZFYVE26': {'NM_015346.4'}}

In [5]:
gene_transcripts = {'AAAS': {'NM_015665.6'},
'ABCA1': {'NM_005502.4'},
'ABCA12': {'NM_173076.3'},
'ABCA3': {'NM_001089.3'},
'ABCA4': {'NM_000350.3'},
'ABCB11': {'NM_003742.4'},
'ABCB4': {'NM_000443.4'},
'ABCC2': {'NM_000392.5'},
'ABCC6': {'NM_001171.6'},
'ABCC8': {'NM_000352.6'},
'ABCC9': {'NM_020297.4'},
'ABCD1': {'NM_000033.4'},
'ACAD9': {'NM_014049.4', 'NM_014049.5'},
'ACADM': {'NM_000016.6'},
'ACADS': {'NM_000017.4'},
'ACADVL': {'NM_000018.4'},
'ACAN': {'NM_001369268.1'},
'ACAT1': {'NM_000019.4'},
'ACO2': {'NM_001098.3', 'none'},
'ACSF3': {'NM_001243279.3'},
'ACTA1': {'none', 'NM_001100.4'},
'ACTB': {'NM_001101.5'},
'ACTG1': {'NM_001614.5'},
'ACVRL1': {'NM_000020.3'},
'ADA': {'NM_000022.4'},
'ADA2': {'NM_001282225.2'},
'ADAMTS13': {'NM_139027.6'},
'ADAMTS2': {'NM_014244.5'},
'ADAMTSL4': {'NM_019032.6'},
'ADAR': {'NM_001111.5'},
'ADGRG1': {'NM_201525.4'},
'ADGRV1': {'NM_032119.4'},
'ADNP': {'NM_001282531.3'},
'ADSL': {'NM_000026.4'},
'AFG2A': {'NM_145207.3'},
'AFG3L2': {'NM_006796.3'},
'AGA': {'NM_000027.4'},
'AGL': {'none', 'NM_000642.3'},
'AGXT': {'NM_000030.3'},
'AHDC1': {'NM_001371928.1'},
'AHI1': {'NM_001134831.2'},
'AIPL1': {'NM_014336.5'},
'AIRE': {'NM_000383.4'},
'ALDH3A2': {'NM_000382.3'},
'ALDH5A1': {'NM_001080.3'},
'ALDH7A1': {'NM_001182.5'},
'ALDOB': {'NM_000035.4'},
'ALG1': {'NM_019109.5'},
'ALG6': {'NM_013339.4'},
'ALMS1': {'NM_001378454.1'},
'ALOX12B': {'NM_001139.3'},
'ALPK3': {'NM_020778.5'},
'ALPL': {'NM_000478.6'},
'ALS2': {'NM_020919.4', 'NM_020919.3'},
'AMT': {'NM_000481.4'},
'ANK1': {'NM_000037.4'},
'ANK2': {'NM_001148.6'},
'ANKRD11': {'NM_013275.6'},
'ANO5': {'NM_213599.3'},
'ANOS1': {'NM_000216.4'},
'APC': {'NM_001127511.3', 'NM_000038.6', 'NM_001127510.3'},
'APOB': {'NM_000384.3'},
'APRT': {'NM_000485.3'},
'AQP2': {'NM_000486.6'},
'AR': {'NM_000044.6'},
'ARG1': {'NM_000045.4'},
'ARID1A': {'NM_006015.6'},
'ARID1B': {'NM_001374828.1'},
'ARSA': {'NM_000487.6'},
'ARSB': {'NM_000046.5'},
'ARX': {'NM_139058.3'},
'ASAH1': {'NM_177924.5'},
'ASH1L': {'NM_018489.3'},
'ASL': {'NM_000048.4'},
'ASNS': {'NM_001673.5'},
'ASPA': {'NM_000049.4'},
'ASPM': {'NM_018136.5'},
'ASS1': {'NM_054012.4'},
'ASXL1': {'NM_015338.6'},
'ASXL3': {'NM_030632.3'},
'ATL1': {'NM_015915.5'},
'ATM': {'NM_000051.4'},
'ATP1A2': {'NM_000702.4'},
'ATP1A3': {'NM_152296.5'},
'ATP2A2': {'NM_170665.4'},
'ATP6V0A4': {'NM_020632.3'},
'ATP6V1B1': {'NM_001692.4'},
'ATP7A': {'NM_000052.7'},
'ATP7B': {'NM_000053.4'},
'ATP8B1': {'NM_001374385.1'},
'ATR': {'NM_001184.4'},
'ATRX': {'NM_000489.6'},
'AUTS2': {'NM_015570.4'},
'AVPR2': {'NM_000054.7'},
'AXIN2': {'NM_004655.4'},
'BAG3': {'NM_004281.4'},
'BAP1': {'NM_004656.4'},
'BARD1': {'NM_000465.4'},
'BBS1': {'NM_024649.5'},
'BBS10': {'NM_024685.4'},
'BBS12': {'NM_152618.3'},
'BBS2': {'NM_031885.5'},
'BBS4': {'NM_033028.5'},
'BBS7': {'NM_176824.3'},
'BBS9': {'NM_198428.3'},
'BCKDHA': {'NM_000709.4'},
'BCKDHB': {'NM_183050.4'},
'BCS1L': {'NM_001079866.2'},
'BEST1': {'NM_004183.4'},
'BLM': {'NM_000057.4'},
'BMPR1A': {'NM_004329.3'},
'BMPR2': {'NM_001204.7'},
'BRAF': {'NM_004333.6'},
'BRAT1': {'NM_152743.4'},
'BRCA1': {'NM_007294.4'},
'BRCA2': {'none', 'NM_000059.4'},
'BRIP1': {'NM_032043.3'},
'BTD': {'NM_001370658.1'},
'BTK': {'NM_000061.3'},
'C3': {'NM_000064.4'},
'CACNA1A': {'NM_001127221.2', 'NM_001127222.2'},
'CACNA1C': {'NM_000719.7', 'NM_001167623.2'},
'CACNA1F': {'NM_001256789.3', 'NM_005183.4'},
'CACNA1S': {'NM_000069.3'},
'CAD': {'NM_004341.5'},
'CAMTA1': {'NM_015215.4'},
'CAPN3': {'NM_000070.3'},
'CASK': {'NM_001367721.1'},
'CASQ2': {'NM_001232.4'},
'CASR': {'NM_000388.4'},
'CBS': {'NM_000071.3'},
'CC2D2A': {'NM_001378615.1'},
'CCDC39': {'NM_181426.2'},
'CCDC40': {'NM_017950.4'},
'CCDC88C': {'NM_001080414.4'},
'CCM2': {'NM_031443.4'},
'CD40LG': {'NM_000074.3'},
'CDC73': {'NM_024529.5'},
'CDH1': {'NM_004360.5'},
'CDH23': {'NM_022124.6'},
'CDHR1': {'NM_033100.4'},
'CDK13': {'NM_003718.5'},
'CDKL5': {'NM_001323289.2', 'NM_001037343.2'},
'CDKN2A': {'NM_058195.4', 'NM_000077.5'},
'CEP152': {'NM_001194998.2'},
'CEP164': {'NM_014956.5'},
'CEP250': {'NM_007186.6'},
'CEP290': {'NM_025114.4'},
'CERKL': {'NM_201548.5'},
'CFH': {'NM_000186.4'},
'CFI': {'NM_000204.5'},
'CFTR': {'none', 'NM_000492.4', 'NM_000492.3'},
'CHAT': {'NM_020549.5'},
'CHD2': {'NM_001271.4'},
'CHD3': {'NM_001005273.3'},
'CHD4': {'NM_001273.5'},
'CHD7': {'NM_017780.4'},
'CHD8': {'NM_001170629.2'},
'CHEK2': {'NM_007194.4'},
'CHM': {'NM_000390.4'},
'CHRNE': {'NM_000080.4', 'none'},
'CLCN1': {'NM_000083.3'},
'CLCN4': {'NM_001830.4'},
'CLCN5': {'NM_001127898.4'},
'CLCN7': {'NM_001287.6'},
'CLCNKB': {'NM_000085.5'},
'CLN3': {'NM_001042432.2'},
'CLN5': {'NM_006493.2', 'NM_006493.4'},
'CLN6': {'NM_017882.3'},
'CLN8': {'NM_018941.4'},
'CLRN1': {'NM_174878.3', 'NM_052995.2'},
'CLTC': {'NM_004859.4'},
'CNGA3': {'NM_001298.3'},
'CNGB1': {'NM_001297.5'},
'CNGB3': {'NM_019098.5'},
'CNTNAP2': {'NM_014141.6'},
'COL11A1': {'NM_001854.4'},
'COL11A2': {'NM_080680.3'},
'COL12A1': {'NM_004370.6'},
'COL17A1': {'NM_000494.4'},
'COL18A1': {'NM_001379500.1'},
'COL1A1': {'NM_000088.4'},
'COL1A2': {'NM_000089.4'},
'COL27A1': {'NM_032888.4'},
'COL2A1': {'NM_001844.5'},
'COL3A1': {'NM_000090.4'},
'COL4A1': {'NM_001845.6'},
'COL4A2': {'NM_001846.4'},
'COL4A3': {'NM_000091.4', 'NM_000091.5'},
'COL4A4': {'NM_000092.5'},
'COL4A5': {'NM_033380.2', 'NM_033380.3'},
'COL5A1': {'NM_000093.5'},
'COL5A2': {'NM_000393.5'},
'COL6A1': {'NM_001848.3'},
'COL6A2': {'NM_001849.4', 'NM_058174.3'},
'COL6A3': {'NM_004369.4'},
'COL7A1': {'none', 'NM_000094.4', 'NM_000094.3'},
'COL9A1': {'NM_001851.6'},
'COLQ': {'NM_005677.4'},
'COMP': {'NM_000095.3'},
'COQ8A': {'NM_020247.5'},
'CP': {'NM_000096.4'},
'CPLANE1': {'NM_001384732.1'},
'CPS1': {'NM_001875.5'},
'CPT1A': {'NM_001876.4'},
'CPT2': {'NM_000098.3'},
'CRB1': {'NM_201253.3'},
'CREBBP': {'NM_004380.3'},
'CSF1R': {'NM_005211.3', 'NM_001288705.3'},
'CSNK2A1': {'NM_177559.3'},
'CSNK2B': {'NM_001320.7'},
'CSPP1': {'NM_001382391.1'},
'CTC1': {'NM_025099.6'},
'CTCF': {'NM_006565.4'},
'CTNNA1': {'NM_001903.5'},
'CTNNB1': {'NM_001904.4'},
'CTNS': {'none', 'NM_004937.3'},
'CTSC': {'NM_001814.6'},
'CTSK': {'NM_000396.4'},
'CUBN': {'NM_001081.4'},
'CUL3': {'NM_003590.5'},
'CUL7': {'NM_014780.5'},
'CYBB': {'NM_000397.4'},
'CYP11B1': {'NM_000497.4'},
'CYP11B2': {'NM_000498.3'},
'CYP17A1': {'NM_000102.4'},
'CYP19A1': {'NM_000103.4'},
'CYP1B1': {'NM_000104.4'},
'CYP21A2': {'NM_000500.9'},
'CYP27A1': {'NM_000784.4'},
'CYP27B1': {'NM_000785.4'},
'CYP4V2': {'NM_207352.4'},
'DBT': {'NM_001918.5'},
'DCLRE1C': {'NM_001033855.3'},
'DCX': {'NM_001195553.2'},
'DDC': {'NM_001082971.2'},
'DDX3X': {'NM_001356.5'},
'DDX41': {'NM_016222.4'},
'DEAF1': {'NM_021008.4'},
'DEPDC5': {'NM_001242896.3'},
'DES': {'NM_001927.4'},
'DHCR7': {'NM_001360.3'},
'DICER1': {'NM_177438.3'},
'DLD': {'NM_000108.5'},
'DLG4': {'NM_001321075.3'},
'DMD': {'NM_004006.3'},
'DNAH1': {'NM_015512.5'},
'DNAH11': {'NM_001277115.2'},
'DNAH5': {'NM_001369.3'},
'DNAH8': {'NM_001206927.2'},
'DNAH9': {'NM_001372.4'},
'DNAI1': {'NM_012144.4'},
'DNAI2': {'NM_023036.6'},
'DNM1': {'NM_004408.4', 'NM_001288739.2'},
'DNMT3A': {'NM_022552.5'},
'DOCK6': {'NM_020812.4'},
'DOCK8': {'NM_203447.4'},
'DOK7': {'NM_173660.5'},
'DPYD': {'NM_000110.4'},
'DSG2': {'NM_001943.5'},
'DSP': {'NM_004415.4'},
'DST': {'NM_001374736.1', 'NM_001723.7'},
'DUOX2': {'NM_001363711.2'},
'DYNC1H1': {'NM_001376.5'},
'DYNC2H1': {'NM_001377.3', 'NM_001080463.2'},
'DYRK1A': {'NM_001347721.2'},
'DYSF': {'NM_003494.4', 'NM_001130987.2'},
'EBF3': {'NM_001375380.1'},
'EBP': {'NM_006579.3'},
'ECHS1': {'NM_004092.4'},
'EDA': {'NM_001399.5'},
'EDAR': {'NM_022336.4'},
'EFTUD2': {'NM_004247.4'},
'EHMT1': {'NM_024757.5'},
'EIF2AK3': {'NM_004836.7'},
'EIF2B5': {'NM_003907.3'},
'ELAC2': {'NM_018127.7'},
'ELANE': {'NM_001972.4'},
'ELN': {'NM_000501.4'},
'ELP1': {'NM_003640.5'},
'EMC1': {'NM_015047.3'},
'ENG': {'NM_001114753.3'},
'ENPP1': {'NM_006208.3'},
'EP300': {'NM_001429.3', 'NM_001429.4'},
'EPG5': {'NM_020964.3'},
'EPHB4': {'NM_004444.5'},
'ERCC2': {'NM_000400.4'},
'ERCC6': {'NM_001277058.2', 'NM_000124.4'},
'ERCC8': {'NM_000082.4'},
'ESCO2': {'NM_001017420.3'},
'ETFDH': {'NM_004453.4'},
'ETHE1': {'NM_014297.5'},
'EVC': {'NM_153717.3'},
'EVC2': {'NM_147127.5'},
'EXT1': {'NM_000127.3'},
'EXT2': {'NM_207122.2'},
'EYA1': {'NM_000503.6'},
'EYA4': {'NM_004100.5'},
'EYS': {'NM_001142800.2'},
'F11': {'NM_000128.4'},
'F5': {'NM_000130.4', 'NM_000130.5'},
'F7': {'none', 'NM_019616.4', 'NM_000131.4', 'NM_000131.5'},
'F8': {'none', 'NM_000132.4'},
'F9': {'none', 'NM_000133.4'},
'FAH': {'NM_000137.4'},
'FAM161A': {'NM_001201543.2'},
'FANCA': {'NM_000135.4'},
'FANCC': {'NM_000136.3'},
'FANCD2': {'NM_001018115.3'},
'FANCG': {'NM_004629.2'},
'FANCI': {'NM_001113378.2'},
'FANCL': {'NM_018062.4'},
'FANCM': {'NM_020937.4'},
'FAS': {'NM_000043.6'},
'FBN1': {'NM_000138.5'},
'FBN2': {'NM_001999.4'},
'FBXL4': {'NM_001278716.2'},
'FBXO11': {'NM_001190274.2'},
'FECH': {'NM_000140.5', 'none', 'NM_000140.3'},
'FGFR1': {'NM_023110.3'},
'FGFR2': {'NM_000141.5'},
'FGFR3': {'NM_000142.5'},
'FH': {'NM_000143.4'},
'FHL1': {'NM_001159699.2', 'NM_001159702.3'},
'FIG4': {'NM_014845.6'},
'FKRP': {'NM_024301.5'},
'FKTN': {'NM_001079802.2'},
'FLCN': {'NM_144997.7'},
'FLG': {'NM_002016.2'},
'FLNA': {'NM_001110556.2'},
'FLNB': {'NM_001457.4'},
'FLNC': {'NM_001458.5'},
'FLT4': {'NM_182925.5'},
'FMO3': {'NM_001002294.3'},
'FOXC1': {'NM_001453.3'},
'FOXG1': {'NM_005249.5'},
'FOXL2': {'NM_023067.4'},
'FOXP1': {'NM_001349338.3'},
'FRAS1': {'NM_025074.7'},
'FREM2': {'NM_207361.6'},
'FUCA1': {'NM_000147.5'},
'G6PC1': {'NM_000151.4'},
'G6PD': {'none', 'NM_001042351.3', 'NM_001360016.2', 'NM_000402.4'},
'GAA': {'NM_000152.5'},
'GABRA1': {'NM_001127644.2'},
'GABRB2': {'NM_001371727.1'},
'GABRB3': {'NM_021912.5', 'NM_000814.6'},
'GABRG2': {'NM_198904.4'},
'GALC': {'NM_001201402.2', 'NM_000153.4'},
'GALK1': {'NM_000154.2'},
'GALNS': {'NM_000512.5'},
'GALT': {'NM_000155.4'},
'GAMT': {'NM_000156.6'},
'GATA2': {'NM_032638.5'},
'GATAD2B': {'NM_020699.4'},
'GBA1': {'NM_000157.4'},
'GBE1': {'NM_000158.4'},
'GCDH': {'NM_000159.4'},
'GCH1': {'NM_000161.3'},
'GCK': {'NM_000162.5', 'none'},
'GDAP1': {'NM_018972.4'},
'GFAP': {'NM_002055.5'},
'GFM1': {'NM_024996.7'},
'GJA1': {'NM_000165.5'},
'GJB1': {'NM_001097642.3', 'NM_000166.6'},
'GJB2': {'NM_004004.6'},
'GLA': {'NM_000169.3'},
'GLB1': {'NM_000404.4'},
'GLDC': {'NM_000170.3'},
'GLE1': {'NM_001003722.2'},
'GLI3': {'NM_000168.6'},
'GLRA1': {'NM_000171.4'},
'GNAO1': {'NM_020988.3'},
'GNAS': {'NM_016592.5', 'NM_000516.7', 'NM_080425.4'},
'GNB1': {'NM_002074.5'},
'GNE': {'NM_005476.7', 'NM_001128227.3'},
'GNPTAB': {'NM_024312.5'},
'GNPTG': {'NM_032520.5'},
'GPR143': {'NM_000273.3'},
'GRHPR': {'NM_012203.2'},
'GRIN1': {'NM_007327.4'},
'GRIN2A': {'NM_001134407.3'},
'GRIN2B': {'NM_000834.5'},
'GRN': {'NM_002087.4'},
'GUCY2D': {'NM_000180.4'},
'GUSB': {'NM_000181.4'},
'HADHA': {'NM_000182.5'},
'HADHB': {'NM_000183.3'},
'HBA2': {'NM_000517.4', 'NM_000517.6'},
'HBB': {'none', 'NM_000518.4', 'NM_000518.5'},
'HDAC8': {'NM_018486.3'},
'HEXA': {'NM_000520.6'},
'HEXB': {'NM_000521.4'},
'HGD': {'NM_000187.4'},
'HGSNAT': {'NM_152419.3'},
'HLCS': {'NM_001352514.2'},
'HMBS': {'NM_000190.4'},
'HMGCL': {'NM_000191.3'},
'HNF1A': {'NM_000545.5', 'none', 'NM_000545.8'},
'HNF1B': {'NM_000458.4'},
'HNF4A': {'NM_175914.5', 'none'},
'HNRNPU': {'NM_031844.3'},
'HOGA1': {'NM_138413.4'},
'HPRT1': {'NM_000194.3', 'NM_000194.2', 'none'},
'HPS1': {'NM_000195.5'},
'HPS3': {'NM_032383.5'},
'HPS4': {'NM_022081.6'},
'HPS5': {'NM_181507.2'},
'HSD17B3': {'NM_000197.2', 'NM_000197.1'},
'HSD17B4': {'NM_000414.4', 'none'},
'HSD3B2': {'NM_000198.4'},
'HSPG2': {'NM_005529.7'},
'HUWE1': {'NM_031407.7'},
'IDS': {'NM_000202.8'},
'IDUA': {'NM_000203.4', 'NM_000203.5'},
'IFT122': {'NM_052989.3'},
'IFT140': {'NM_014714.4'},
'IFT172': {'NM_015662.3'},
'IGF1R': {'NM_000875.5'},
'IGHMBP2': {'NM_002180.3'},
'IL12RB1': {'NM_005535.3'},
'IL2RG': {'NM_000206.3'},
'IMPG2': {'NM_016247.4'},
'INF2': {'NM_022489.4'},
'INSR': {'NM_000208.4'},
'INVS': {'NM_014425.5'},
'IQCB1': {'NM_001023570.4'},
'IQSEC2': {'NM_001111125.3'},
'IRF6': {'NM_006147.4'},
'ITGA2B': {'NM_000419.5'},
'ITGB2': {'NM_000211.5'},
'ITGB3': {'NM_000212.3'},
'ITGB4': {'NM_000213.5'},
'ITPR1': {'NM_001378452.1'},
'IVD': {'NM_002225.5'},
'JAG1': {'NM_000214.3'},
'JAK3': {'NM_000215.4'},
'KAT6A': {'NM_006766.5'},
'KAT6B': {'NM_012330.4'},
'KCNA2': {'NM_004974.4'},
'KCNB1': {'NM_004975.4'},
'KCNH2': {'NM_000238.4'},
'KCNJ1': {'NM_153766.3'},
'KCNJ11': {'NM_000525.4'},
'KCNJ2': {'NM_000891.3'},
'KCNQ1': {'NM_000218.3'},
'KCNQ2': {'NM_172107.4'},
'KCNT1': {'NM_020822.3'},
'KCNV2': {'NM_133497.4'},
'KDM5B': {'NM_006618.5'},
'KDM5C': {'NM_004187.5'},
'KDM6A': {'NM_001291415.2'},
'KDM6B': {'NM_001348716.2'},
'KIAA0586': {'NM_001329943.3'},
'KIF11': {'NM_004523.4'},
'KIF1A': {'NM_001244008.2'},
'KIF5A': {'NM_004984.4'},
'KIF7': {'NM_198525.3'},
'KIT': {'NM_000222.3'},
'KMT2A': {'NM_001197104.2'},
'KMT2B': {'NM_014727.3'},
'KMT2C': {'NM_170606.3'},
'KMT2D': {'NM_003482.4'},
'KMT2E': {'NM_182931.3'},
'KRAS': {'NM_033360.4', 'NM_004985.5'},
'KRIT1': {'NM_194454.3'},
'KRT14': {'NM_000526.5'},
'KRT5': {'NM_000424.4'},
'L1CAM': {'NM_001278116.2'},
'LAMA1': {'NM_005559.4'},
'LAMA2': {'NM_000426.4'},
'LAMA3': {'NM_198129.4', 'NM_000227.6'},
'LAMB2': {'NM_002292.4'},
'LAMB3': {'NM_000228.3'},
'LAMC2': {'NM_005562.3'},
'LAMC3': {'NM_006059.4'},
'LAMP2': {'NM_002294.3'},
'LCA5': {'NM_001122769.3'},
'LDLR': {'NM_000527.4', 'NM_000527.5', 'NM_001195803.1'},
'LIFR': {'NM_001127671.2'},
'LIPA': {'NM_000235.4'},
'LMNA': {'NM_170707.4'},
'LMX1B': {'NM_001174147.2'},
'LOXHD1': {'NM_001384474.1'},
'LPL': {'NM_000237.3'},
'LRBA': {'NM_001364905.1'},
'LRP2': {'NM_004525.3'},
'LRP5': {'NM_002335.4'},
'LRPPRC': {'NM_133259.4'},
'LRSAM1': {'NM_001005373.4'},
'LYST': {'NM_000081.4'},
'LZTR1': {'NM_006767.4'},
'MAN2B1': {'NM_000528.4'},
'MANBA': {'NM_005908.4'},
'MBD4': {'NM_001276270.2'},
'MBD5': {'NM_001378120.1'},
'MCCC1': {'NM_020166.5'},
'MCCC2': {'NM_022132.5'},
'MCOLN1': {'NM_020533.3'},
'MCPH1': {'NM_024596.5'},
'MECP2': {'NM_001110792.2', 'NM_004992.4'},
'MED12': {'NM_005120.3'},
'MED13L': {'NM_015335.5'},
'MED17': {'NM_004268.5'},
'MEF2C': {'NM_002397.5'},
'MEN1': {'NM_001370259.2'},
'MERTK': {'NM_006343.3'},
'MFN2': {'NM_014874.4'},
'MFSD8': {'NM_001371596.2'},
'MITF': {'NM_000248.4', 'NM_001354604.2'},
'MKKS': {'NM_170784.3'},
'MKS1': {'NM_017777.4'},
'MLC1': {'NM_015166.4', 'NM_001376473.1'},
'MLH1': {'NM_000249.4'},
'MMAA': {'NM_172250.3'},
'MMAB': {'NM_052845.4'},
'MMACHC': {'NM_015506.3'},
'MME': {'NM_007289.4'},
'MMUT': {'NM_000255.4'},
'MPDZ': {'NM_001378778.1'},
'MPI': {'NM_002435.3'},
'MPL': {'NM_005373.3'},
'MPV17': {'NM_002437.5'},
'MPZ': {'NM_000530.8'},
'MRE11': {'NM_005591.4'},
'MSH2': {'NM_000251.3'},
'MSH3': {'NM_002439.5'},
'MSH6': {'NM_000179.3'},
'MTHFR': {'NM_005957.5'},
'MTM1': {'NM_000252.3'},
'MTOR': {'NM_004958.4'},
'MTR': {'NM_000254.3'},
'MTRR': {'NM_002454.3'},
'MTTP': {'NM_001386140.1'},
'MUTYH': {'NM_001128425.2', 'NM_001048174.2'},
'MVK': {'NM_000431.4'},
'MYBPC3': {'NM_000256.3', 'none'},
'MYH11': {'NM_001040113.2', 'NM_002474.3'},
'MYH2': {'NM_017534.6'},
'MYH3': {'NM_002470.4'},
'MYH7': {'NM_000257.4'},
'MYO15A': {'NM_016239.4'},
'MYO18B': {'NM_032608.7'},
'MYO5B': {'NM_001080467.3'},
'MYO6': {'NM_004999.4'},
'MYO7A': {'NM_000260.4'},
'MYT1L': {'NM_001303052.2'},
'NAA15': {'NM_057175.5'},
'NAGLU': {'NM_000263.4'},
'NAGS': {'NM_153006.3', 'none'},
'NALCN': {'NM_052867.4'},
'NBAS': {'NM_015909.4'},
'NBEA': {'NM_001385012.1'},
'NBN': {'NM_002485.5'},
'NDP': {'NM_000266.4'},
'NDUFAF5': {'NM_024120.5'},
'NEB': {'NM_001164508.2', 'NM_001164507.2'},
'NEK1': {'NM_001199397.3'},
'NEU1': {'NM_000434.4'},
'NEXMIF': {'NM_001008537.3'},
'NF1': {'NM_001042492.3'},
'NF2': {'NM_000268.4'},
'NFIX': {'NM_001365902.3'},
'NFKB1': {'NM_003998.4'},
'NGLY1': {'NM_018297.4'},
'NIPBL': {'NM_133433.4'},
'NKX2-1': {'NM_001079668.3'},
'NKX2-5': {'NM_004387.4'},
'NLRP3': {'NM_001243133.2'},
'NMNAT1': {'NM_022787.4'},
'NOTCH1': {'NM_017617.5'},
'NOTCH2': {'NM_024408.4'},
'NOTCH3': {'NM_000435.3'},
'NPC1': {'NM_000271.5'},
'NPHP1': {'NM_001128178.3'},
'NPHP3': {'NM_153240.5'},
'NPHP4': {'NM_015102.5'},
'NPHS1': {'NM_004646.4'},
'NPHS2': {'NM_014625.4'},
'NPR2': {'NM_003995.4'},
'NPRL3': {'NM_001077350.3'},
'NR0B1': {'NM_000475.5'},
'NR2E3': {'NM_014249.4'},
'NR2F1': {'NM_005654.6'},
'NR5A1': {'NM_004959.5'},
'NSD1': {'NM_022455.5'},
'NTHL1': {'NM_002528.7', 'none'},
'NTRK1': {'NM_002529.4'},
'OAT': {'NM_000274.4'},
'OCA2': {'NM_000275.3'},
'OCRL': {'NM_000276.4'},
'OFD1': {'NM_003611.3'},
'OPA1': {'NM_130837.3'},
'OPHN1': {'NM_002547.3'},
'OTC': {'none', 'NM_000531.6'},
'OTOF': {'NM_194248.3', 'NM_194323.3'},
'OTOG': {'NM_001292063.2'},
'OTOGL': {'NM_001378609.3'},
'P3H1': {'NM_022356.4'},
'PAFAH1B1': {'none', 'NM_000430.4'},
'PAH': {'NM_000277.3'},
'PALB2': {'NM_024675.4', 'none'},
'PANK2': {'NM_001386393.1'},
'PARN': {'NM_002582.4'},
'PAX2': {'NM_000278.5'},
'PAX3': {'NM_181458.4', 'NM_181457.3'},
'PAX6': {'NM_000280.6', 'NM_001368894.2'},
'PC': {'NM_001040716.2'},
'PCARE': {'NM_001029883.3'},
'PCCA': {'NM_000282.4'},
'PCCB': {'NM_000532.5'},
'PCDH15': {'NM_033056.4', 'NM_001384140.1'},
'PCDH19': {'NM_001184880.2'},
'PCNT': {'NM_006031.6'},
'PDE6A': {'NM_000440.3'},
'PDE6B': {'NM_000283.4'},
'PDE6C': {'NM_006204.4'},
'PDHA1': {'NM_000284.4'},
'PEPD': {'NM_000285.4'},
'PEX1': {'NM_000466.3'},
'PEX10': {'NM_002617.4'},
'PEX6': {'NM_000287.4'},
'PEX7': {'NM_000288.4'},
'PFKM': {'NM_000289.6'},
'PHEX': {'NM_000444.6'},
'PHGDH': {'NM_006623.4'},
'PHIP': {'NM_017934.7'},
'PHKA2': {'NM_000292.3'},
'PHKB': {'NM_000293.3'},
'PIEZO1': {'NM_001142864.4'},
'PIEZO2': {'NM_001378183.1'},
'PIGN': {'NM_176787.5'},
'PIK3CA': {'NM_006218.4'},
'PKD1': {'NM_001009944.3'},
'PKD2': {'NM_000297.4'},
'PKHD1': {'NM_138694.4'},
'PKLR': {'NM_000298.6', 'none'},
'PKP2': {'NM_001005242.3'},
'PLA2G6': {'NM_003560.4', 'none'},
'PLEC': {'NM_201384.3', 'NM_201378.4'},
'PLOD1': {'NM_000302.4'},
'PLP1': {'NM_000533.5'},
'PMM2': {'none', 'NM_000303.3'},
'PMP22': {'NM_000304.4'},
'PMS2': {'NM_000535.7'},
'PNKP': {'NM_007254.4'},
'PNPLA6': {'NM_001166114.2'},
'PNPT1': {'NM_033109.5'},
'POGZ': {'NM_015100.4'},
'POLE': {'NM_006231.4'},
'POLG': {'NM_002693.3'},
'POLR3A': {'NM_007055.4'},
'POLR3B': {'NM_018082.6'},
'POMGNT1': {'NM_017739.4'},
'POMT1': {'NM_001077365.2'},
'POMT2': {'NM_013382.7'},
'POR': {'NM_001395413.1'},
'POT1': {'NM_015450.3'},
'POU3F4': {'NM_000307.5'},
'PPT1': {'NM_000310.4'},
'PRF1': {'NM_001083116.3'},
'PRKAR1A': {'NM_002734.5', 'NM_001276290.1'},
'PROC': {'NM_000312.4', 'none'},
'PROM1': {'NM_006017.3'},
'PROP1': {'NM_006261.5'},
'PROS1': {'NM_000313.4'},
'PRPF31': {'NM_015629.4'},
'PRPF8': {'NM_006445.4'},
'PRPH2': {'NM_000322.5'},
'PRRT2': {'NM_145239.3'},
'PSAP': {'NM_002778.4'},
'PSEN1': {'NM_000021.4'},
'PTCH1': {'NM_000264.5', 'NM_001083603.3'},
'PTEN': {'NM_000314.8'},
'PTPN11': {'NM_002834.5'},
'PTS': {'NM_000317.3'},
'PUF60': {'NM_078480.3'},
'PURA': {'NM_005859.5'},
'PYGL': {'NM_002863.5'},
'PYGM': {'NM_005609.4'},
'RAD50': {'NM_005732.4'},
'RAD51C': {'NM_058216.3'},
'RAD51D': {'NM_002878.4'},
'RAF1': {'NM_002880.4'},
'RAG1': {'NM_000448.3'},
'RAG2': {'NM_000536.4'},
'RAI1': {'NM_030665.4'},
'RAPSN': {'NM_005055.5'},
'RARS2': {'NM_020320.5'},
'RASA1': {'NM_002890.3'},
'RB1': {'NM_000321.3', 'none'},
'RBM20': {'NM_001134363.3'},
'RDH12': {'NM_152443.3'},
'RECQL4': {'NM_004260.4'},
'REEP1': {'NM_001371279.1'},
'RELN': {'NM_005045.4'},
'RET': {'NM_020975.6'},
'RHO': {'NM_000539.3'},
'RP1': {'NM_006269.2', 'NM_001375654.1'},
'RP2': {'NM_006915.3'},
'RPE65': {'NM_000329.3'},
'RPGR': {'NM_001034853.2', 'none'},
'RPGRIP1': {'NM_020366.4'},
'RPGRIP1L': {'NM_015272.5'},
'RPS19': {'NM_001022.4'},
'RPS6KA3': {'NM_004586.3'},
'RS1': {'NM_000330.4', 'none'},
'RTEL1': {'NM_001283009.2', 'NM_001283009.1'},
'RTTN': {'NM_173630.4'},
'RUNX1': {'NM_001754.4', 'NM_001754.5'},
'RUNX2': {'NM_001024630.4', 'none'},
'RYR1': {'NM_000540.2', 'NM_000540.3'},
'RYR2': {'NM_001035.3'},
'SACS': {'NM_014363.6'},
'SAMHD1': {'NM_015474.4'},
'SATB2': {'NM_001172517.1', 'NM_001172509.2'},
'SBF2': {'NM_030962.4'},
'SCN1A': {'NM_001165963.4'},
'SCN2A': {'NM_001040142.2', 'NM_001371246.1'},
'SCN4A': {'NM_000334.4'},
'SCN5A': {'NM_000335.5', 'NM_001099404.2'},
'SCN8A': {'NM_001330260.2', 'NM_014191.4'},
'SCN9A': {'NM_001365536.1'},
'SDCCAG8': {'NM_006642.5'},
'SDHA': {'NM_004168.4'},
'SDHB': {'NM_003000.3'},
'SDHC': {'NM_003001.5'},
'SDHD': {'NM_003002.4'},
'SEC23B': {'NM_006363.6'},
'SELENON': {'NM_020451.3', 'NM_206926.2', 'NM_020451.2'},
'SEPSECS': {'NM_016955.4'},
'SERPINC1': {'none', 'NM_000488.4'},
'SERPING1': {'none', 'NM_000062.3'},
'SETBP1': {'NM_015559.3'},
'SETD5': {'NM_001080517.3'},
'SETX': {'NM_015046.7'},
'SGCA': {'NM_000023.4'},
'SGCB': {'NM_000232.5'},
'SGCE': {'NM_003919.3'},
'SGCG': {'NM_000231.3'},
'SGSH': {'NM_000199.5'},
'SH3TC2': {'NM_024577.4'},
'SHANK3': {'NM_001372044.2'},
'SHH': {'NM_000193.4', 'none'},
'SHOX': {'NM_000451.4'},
'SI': {'NM_001041.4'},
'SIN3A': {'NM_001145358.2'},
'SKIC2': {'NM_006929.5'},
'SKIC3': {'NM_014639.4'},
'SLC12A1': {'NM_000338.3'},
'SLC12A3': {'NM_001126108.2'},
'SLC12A6': {'NM_001365088.1'},
'SLC16A2': {'NM_006517.5'},
'SLC17A5': {'NM_012434.5'},
'SLC20A2': {'NM_001257180.2'},
'SLC22A5': {'NM_003060.4'},
'SLC25A13': {'NM_014251.3'},
'SLC26A2': {'NM_000112.4'},
'SLC26A3': {'NM_000111.3'},
'SLC26A4': {'NM_000441.2'},
'SLC2A1': {'NM_006516.4'},
'SLC34A3': {'NM_001177316.2'},
'SLC37A4': {'NM_001164277.2'},
'SLC39A4': {'NM_130849.4'},
'SLC3A1': {'NM_000341.4'},
'SLC45A2': {'NM_016180.5'},
'SLC4A1': {'NM_000342.4', 'NM_000342.3'},
'SLC4A11': {'NM_001174089.2'},
'SLC6A1': {'NM_003042.4'},
'SLC6A8': {'NM_005629.4'},
'SLC7A7': {'NM_003982.4'},
'SLC7A9': {'NM_014270.5'},
'SLX4': {'NM_032444.4'},
'SMAD3': {'NM_005902.4'},
'SMAD4': {'NM_005359.6'},
'SMARCA2': {'NM_003070.5'},
'SMARCA4': {'NM_003072.5'},
'SMARCAL1': {'NM_014140.4'},
'SMARCB1': {'NM_003073.5'},
'SMC1A': {'NM_006306.4'},
'SMC3': {'NM_005445.4'},
'SMCHD1': {'NM_015295.3'},
'SMPD1': {'NM_000543.5'},
'SOD1': {'NM_000454.5'},
'SOS1': {'NM_005633.4'},
'SOX10': {'none', 'NM_006941.4'},
'SOX11': {'NM_003108.4'},
'SOX5': {'NM_006940.6'},
'SOX9': {'NM_000346.4'},
'SPAST': {'NM_014946.4'},
'SPG11': {'NM_025137.4'},
'SPG7': {'NM_003119.4'},
'SPINK5': {'NM_006846.4'},
'SPRED1': {'NM_152594.3'},
'SPTA1': {'NM_003126.2', 'NM_003126.4'},
'SPTAN1': {'NM_001130438.3'},
'SPTB': {'NM_001355436.2'},
'SRD5A2': {'NM_000348.4'},
'STAR': {'NM_000349.3'},
'STAT1': {'NM_007315.4'},
'STAT3': {'NM_139276.3'},
'STK11': {'NM_000455.5'},
'STXBP1': {'NM_001032221.6', 'NM_003165.6'},
'STXBP2': {'NM_006949.4'},
'SUFU': {'NM_016169.4'},
'SUMF1': {'NM_182760.4'},
'SURF1': {'NM_003172.4'},
'SYNE1': {'NM_001347702.2', 'NM_182961.4'},
'SYNGAP1': {'NM_006772.3'},
'SZT2': {'NM_001365999.1'},
'TAFAZZIN': {'NM_000116.5'},
'TAOK1': {'NM_020791.4'},
'TBC1D24': {'NM_001199107.2'},
'TBCD': {'NM_005993.5'},
'TBCK': {'NM_001163435.3'},
'TBL1XR1': {'NM_024665.7'},
'TBX5': {'NM_181486.4'},
'TCF12': {'NM_207037.2'},
'TCF20': {'NM_001378418.1'},
'TCF4': {'NM_001243226.3', 'NM_001083962.2'},
'TCIRG1': {'NM_006019.4'},
'TCOF1': {'NM_001371623.1'},
'TECPR2': {'NM_014844.5'},
'TECTA': {'NM_005422.4'},
'TERT': {'NM_198253.3', 'TERT:c.1710G>Y '},
'TET2': {'NM_001127208.3'},
'TFR2': {'NM_003227.4'},
'TG': {'NM_003235.5'},
'TGFB2': {'NM_003238.6'},
'TGFBR1': {'NM_004612.4'},
'TGFBR2': {'NM_003242.6'},
'TGM1': {'NM_000359.3'},
'TH': {'NM_199292.3', 'NM_000360.4', 'none'},
'THRB': {'NM_001354712.2'},
'TJP2': {'NM_004817.4'},
'TK2': {'NM_004614.5'},
'TLK2': {'NM_006852.6'},
'TMC1': {'NM_138691.3'},
'TMEM67': {'NM_153704.6'},
'TMPRSS3': {'NM_001256317.3'},
'TNNI3': {'NM_000363.5'},
'TNNT2': {'NM_001276345.2'},
'TNXB': {'NM_001365276.2'},
'TP53': {'NM_000546.6'},
'TP63': {'NM_001114980.2', 'NM_003722.5'},
'TPM1': {'NM_001018005.2'},
'TPO': {'NM_001206744.2'},
'TPP1': {'NM_000391.4'},
'TRIM37': {'NM_001005207.5', 'NM_015294.6'},
'TRIO': {'NM_007118.4'},
'TRIOBP': {'NM_001039141.3'},
'TRMU': {'NM_018006.5'},
'TRPM1': {'NM_001252024.2'},
'TRPS1': {'NM_014112.5'},
'TRPV4': {'NM_021625.5'},
'TSC1': {'NM_000368.5'},
'TSC2': {'NM_000548.5'},
'TSHR': {'NM_000369.5'},
'TTC21B': {'NM_024753.5'},
'TTC7A': {'NM_020458.4'},
'TTLL5': {'NM_015072.5'},
'TTN': {'NM_001267550.1', 'NM_001267550.2'},
'TTR': {'NM_000371.4'},
'TUBA1A': {'NM_006009.4'},
'TUBB2B': {'NM_178012.5'},
'TUBB3': {'NM_006086.4'},
'TUBGCP6': {'NM_020461.4'},
'TULP1': {'NM_003322.6'},
'TWIST1': {'NM_000474.4'},
'TWNK': {'NM_021830.5'},
'TYMP': {'NM_001953.5'},
'TYR': {'NM_000372.5', 'NM_000372.4'},
'TYRP1': {'NM_000550.3'},
'UBE3A': {'NM_130839.5'},
'UBR1': {'NM_174916.3'},
'UMOD': {'NM_003361.4'},
'UNC13D': {'NM_199242.3'},
'UNC80': {'NM_001371986.1'},
'USH1C': {'NM_153676.4', 'NM_005709.4'},
'USH2A': {'NM_206933.4', 'none'},
'USP9X': {'NM_001039591.3'},
'VCP': {'NM_007126.5'},
'VHL': {'NM_000551.4'},
'VPS13A': {'NM_033305.3'},
'VPS13B': {'NM_017890.5', 'NM_152564.5'},
'VPS13C': {'NM_020821.3'},
'VPS13D': {'NM_015378.4'},
'VWF': {'NM_000552.5'},
'WAS': {'NM_000377.3'},
'WDFY3': {'NM_014991.6'},
'WDR19': {'NM_025132.4'},
'WDR45': {'NM_001029896.2'},
'WDR62': {'NM_001083961.2'},
'WFS1': {'NM_006005.3'},
'WNT10A': {'NM_025216.3'},
'WRN': {'NM_000553.6'},
'WT1': {'NM_024426.6'},
'WWOX': {'NM_016373.4'},
'XPC': {'NM_004628.5'},
'ZBTB20': {'NM_001348800.3'},
'ZEB2': {'NM_014795.4'},
'ZFYVE26': {'NM_015346.4'},
'ZNF469': {'NM_001367624.2'}
}

In [6]:
gene_transcripts.items()
len(gene_transcripts.items())

903

In [7]:
list(gene_transcripts.items())

[('AAAS', {'NM_015665.6'}),
 ('ABCA1', {'NM_005502.4'}),
 ('ABCA12', {'NM_173076.3'}),
 ('ABCA3', {'NM_001089.3'}),
 ('ABCA4', {'NM_000350.3'}),
 ('ABCB11', {'NM_003742.4'}),
 ('ABCB4', {'NM_000443.4'}),
 ('ABCC2', {'NM_000392.5'}),
 ('ABCC6', {'NM_001171.6'}),
 ('ABCC8', {'NM_000352.6'}),
 ('ABCC9', {'NM_020297.4'}),
 ('ABCD1', {'NM_000033.4'}),
 ('ACAD9', {'NM_014049.4', 'NM_014049.5'}),
 ('ACADM', {'NM_000016.6'}),
 ('ACADS', {'NM_000017.4'}),
 ('ACADVL', {'NM_000018.4'}),
 ('ACAN', {'NM_001369268.1'}),
 ('ACAT1', {'NM_000019.4'}),
 ('ACO2', {'NM_001098.3', 'none'}),
 ('ACSF3', {'NM_001243279.3'}),
 ('ACTA1', {'NM_001100.4', 'none'}),
 ('ACTB', {'NM_001101.5'}),
 ('ACTG1', {'NM_001614.5'}),
 ('ACVRL1', {'NM_000020.3'}),
 ('ADA', {'NM_000022.4'}),
 ('ADA2', {'NM_001282225.2'}),
 ('ADAMTS13', {'NM_139027.6'}),
 ('ADAMTS2', {'NM_014244.5'}),
 ('ADAMTSL4', {'NM_019032.6'}),
 ('ADAR', {'NM_001111.5'}),
 ('ADGRG1', {'NM_201525.4'}),
 ('ADGRV1', {'NM_032119.4'}),
 ('ADNP', {'NM_001282531.3'}),
 ('ADSL', {'NM_000026.4'}),
 ('AFG2A', {'NM_145207.3'}),
 ('AFG3L2', {'NM_006796.3'}),
 ('AGA', {'NM_000027.4'}),
 ('AGL', {'NM_000642.3', 'none'}),
 ('AGXT', {'NM_000030.3'}),
 ('AHDC1', {'NM_001371928.1'}),
 ('AHI1', {'NM_001134831.2'}),
 ('AIPL1', {'NM_014336.5'}),
 ('AIRE', {'NM_000383.4'}),
 ('ALDH3A2', {'NM_000382.3'}),
 ('ALDH5A1', {'NM_001080.3'}),
 ('ALDH7A1', {'NM_001182.5'}),
 ('ALDOB', {'NM_000035.4'}),
 ('ALG1', {'NM_019109.5'}),
 ('ALG6', {'NM_013339.4'}),
 ('ALMS1', {'NM_001378454.1'}),
 ('ALOX12B', {'NM_001139.3'}),
 ('ALPK3', {'NM_020778.5'}),
 ('ALPL', {'NM_000478.6'}),
 ('ALS2', {'NM_020919.3', 'NM_020919.4'}),
 ('AMT', {'NM_000481.4'}),
 ('ANK1', {'NM_000037.4'}),
 ('ANK2', {'NM_001148.6'}),
 ('ANKRD11', {'NM_013275.6'}),
 ('ANO5', {'NM_213599.3'}),
 ('ANOS1', {'NM_000216.4'}),
 ('APC', {'NM_000038.6', 'NM_001127510.3', 'NM_001127511.3'}),
 ('APOB', {'NM_000384.3'}),
 ('APRT', {'NM_000485.3'}),
 ('AQP2', {'NM_000486.6'}),
 ('AR', {'NM_000044.6'}),
 ('ARG1', {'NM_000045.4'}),
 ('ARID1A', {'NM_006015.6'}),
 ('ARID1B', {'NM_001374828.1'}),
 ('ARSA', {'NM_000487.6'}),
 ('ARSB', {'NM_000046.5'}),
 ('ARX', {'NM_139058.3'}),
 ('ASAH1', {'NM_177924.5'}),
 ('ASH1L', {'NM_018489.3'}),
 ('ASL', {'NM_000048.4'}),
 ('ASNS', {'NM_001673.5'}),
 ('ASPA', {'NM_000049.4'}),
 ('ASPM', {'NM_018136.5'}),
 ('ASS1', {'NM_054012.4'}),
 ('ASXL1', {'NM_015338.6'}),
 ('ASXL3', {'NM_030632.3'}),
 ('ATL1', {'NM_015915.5'}),
 ('ATM', {'NM_000051.4'}),
 ('ATP1A2', {'NM_000702.4'}),
 ('ATP1A3', {'NM_152296.5'}),
 ('ATP2A2', {'NM_170665.4'}),
 ('ATP6V0A4', {'NM_020632.3'}),
 ('ATP6V1B1', {'NM_001692.4'}),
 ('ATP7A', {'NM_000052.7'}),
 ('ATP7B', {'NM_000053.4'}),
 ('ATP8B1', {'NM_001374385.1'}),
 ('ATR', {'NM_001184.4'}),
 ('ATRX', {'NM_000489.6'}),
 ('AUTS2', {'NM_015570.4'}),
 ('AVPR2', {'NM_000054.7'}),
 ('AXIN2', {'NM_004655.4'}),
 ('BAG3', {'NM_004281.4'}),
 ('BAP1', {'NM_004656.4'}),
 ('BARD1', {'NM_000465.4'}),
 ('BBS1', {'NM_024649.5'}),
 ('BBS10', {'NM_024685.4'}),
 ('BBS12', {'NM_152618.3'}),
 ('BBS2', {'NM_031885.5'}),
 ('BBS4', {'NM_033028.5'}),
 ('BBS7', {'NM_176824.3'}),
 ('BBS9', {'NM_198428.3'}),
 ('BCKDHA', {'NM_000709.4'}),
 ('BCKDHB', {'NM_183050.4'}),
 ('BCS1L', {'NM_001079866.2'}),
 ('BEST1', {'NM_004183.4'}),
 ('BLM', {'NM_000057.4'}),
 ('BMPR1A', {'NM_004329.3'}),
 ('BMPR2', {'NM_001204.7'}),
 ('BRAF', {'NM_004333.6'}),
 ('BRAT1', {'NM_152743.4'}),
 ('BRCA1', {'NM_007294.4'}),
 ('BRCA2', {'NM_000059.4', 'none'}),
 ('BRIP1', {'NM_032043.3'}),
 ('BTD', {'NM_001370658.1'}),
 ('BTK', {'NM_000061.3'}),
 ('C3', {'NM_000064.4'}),
 ('CACNA1A', {'NM_001127221.2', 'NM_001127222.2'}),
 ('CACNA1C', {'NM_000719.7', 'NM_001167623.2'}),
 ('CACNA1F', {'NM_001256789.3', 'NM_005183.4'}),
 ('CACNA1S', {'NM_000069.3'}),
 ('CAD', {'NM_004341.5'}),
 ('CAMTA1', {'NM_015215.4'}),
 ('CAPN3', {'NM_000070.3'}),
 ('CASK', {'NM_001367721.1'}),
 ('CASQ2', {'NM_001232.4'}),
 ('CASR', {'NM_000388.4'}),
 ('CBS', {'NM_000071.3'}),
 ('CC2D2A', {'NM_001378615.1'}),
 ('CCDC39', {'NM_181426.2'}),
 ('CCDC40', {'NM_017950.4'}),
 ('CCDC88C', {'NM_001080414.4'}),
 ('CCM2', {'NM_031443.4'}),
 ('CD40LG', {'NM_000074.3'}),
 ('CDC73', {'NM_024529.5'}),
 ('CDH1', {'NM_004360.5'}),
 ('CDH23', {'NM_022124.6'}),
 ('CDHR1', {'NM_033100.4'}),
 ('CDK13', {'NM_003718.5'}),
 ('CDKL5', {'NM_001037343.2', 'NM_001323289.2'}),
 ('CDKN2A', {'NM_000077.5', 'NM_058195.4'}),
 ('CEP152', {'NM_001194998.2'}),
 ('CEP164', {'NM_014956.5'}),
 ('CEP250', {'NM_007186.6'}),
 ('CEP290', {'NM_025114.4'}),
 ('CERKL', {'NM_201548.5'}),
 ('CFH', {'NM_000186.4'}),
 ('CFI', {'NM_000204.5'}),
 ('CFTR', {'NM_000492.3', 'NM_000492.4', 'none'}),
 ('CHAT', {'NM_020549.5'}),
 ('CHD2', {'NM_001271.4'}),
 ('CHD3', {'NM_001005273.3'}),
 ('CHD4', {'NM_001273.5'}),
 ('CHD7', {'NM_017780.4'}),
 ('CHD8', {'NM_001170629.2'}),
 ('CHEK2', {'NM_007194.4'}),
 ('CHM', {'NM_000390.4'}),
 ('CHRNE', {'NM_000080.4', 'none'}),
 ('CLCN1', {'NM_000083.3'}),
 ('CLCN4', {'NM_001830.4'}),
 ('CLCN5', {'NM_001127898.4'}),
 ('CLCN7', {'NM_001287.6'}),
 ('CLCNKB', {'NM_000085.5'}),
 ('CLN3', {'NM_001042432.2'}),
 ('CLN5', {'NM_006493.2', 'NM_006493.4'}),
 ('CLN6', {'NM_017882.3'}),
 ('CLN8', {'NM_018941.4'}),
 ('CLRN1', {'NM_052995.2', 'NM_174878.3'}),
 ('CLTC', {'NM_004859.4'}),
 ('CNGA3', {'NM_001298.3'}),
 ('CNGB1', {'NM_001297.5'}),
 ('CNGB3', {'NM_019098.5'}),
 ('CNTNAP2', {'NM_014141.6'}),
 ('COL11A1', {'NM_001854.4'}),
 ('COL11A2', {'NM_080680.3'}),
 ('COL12A1', {'NM_004370.6'}),
 ('COL17A1', {'NM_000494.4'}),
 ('COL18A1', {'NM_001379500.1'}),
 ('COL1A1', {'NM_000088.4'}),
 ('COL1A2', {'NM_000089.4'}),
 ('COL27A1', {'NM_032888.4'}),
 ('COL2A1', {'NM_001844.5'}),
 ('COL3A1', {'NM_000090.4'}),
 ('COL4A1', {'NM_001845.6'}),
 ('COL4A2', {'NM_001846.4'}),
 ('COL4A3', {'NM_000091.4', 'NM_000091.5'}),
 ('COL4A4', {'NM_000092.5'}),
 ('COL4A5', {'NM_033380.2', 'NM_033380.3'}),
 ('COL5A1', {'NM_000093.5'}),
 ('COL5A2', {'NM_000393.5'}),
 ('COL6A1', {'NM_001848.3'}),
 ('COL6A2', {'NM_001849.4', 'NM_058174.3'}),
 ('COL6A3', {'NM_004369.4'}),
 ('COL7A1', {'NM_000094.3', 'NM_000094.4', 'none'}),
 ('COL9A1', {'NM_001851.6'}),
 ('COLQ', {'NM_005677.4'}),
 ('COMP', {'NM_000095.3'}),
 ('COQ8A', {'NM_020247.5'}),
 ('CP', {'NM_000096.4'}),
 ('CPLANE1', {'NM_001384732.1'}),
 ('CPS1', {'NM_001875.5'}),
 ('CPT1A', {'NM_001876.4'}),
 ('CPT2', {'NM_000098.3'}),
 ('CRB1', {'NM_201253.3'}),
 ('CREBBP', {'NM_004380.3'}),
 ('CSF1R', {'NM_001288705.3', 'NM_005211.3'}),
 ('CSNK2A1', {'NM_177559.3'}),
 ('CSNK2B', {'NM_001320.7'}),
 ('CSPP1', {'NM_001382391.1'}),
 ('CTC1', {'NM_025099.6'}),
 ('CTCF', {'NM_006565.4'}),
 ('CTNNA1', {'NM_001903.5'}),
 ('CTNNB1', {'NM_001904.4'}),
 ('CTNS', {'NM_004937.3', 'none'}),
 ('CTSC', {'NM_001814.6'}),
 ('CTSK', {'NM_000396.4'}),
 ('CUBN', {'NM_001081.4'}),
 ('CUL3', {'NM_003590.5'}),
 ('CUL7', {'NM_014780.5'}),
 ('CYBB', {'NM_000397.4'}),
 ('CYP11B1', {'NM_000497.4'}),
 ('CYP11B2', {'NM_000498.3'}),
 ('CYP17A1', {'NM_000102.4'}),
 ('CYP19A1', {'NM_000103.4'}),
 ('CYP1B1', {'NM_000104.4'}),
 ('CYP21A2', {'NM_000500.9'}),
 ('CYP27A1', {'NM_000784.4'}),
 ('CYP27B1', {'NM_000785.4'}),
 ('CYP4V2', {'NM_207352.4'}),
 ('DBT', {'NM_001918.5'}),
 ('DCLRE1C', {'NM_001033855.3'}),
 ('DCX', {'NM_001195553.2'}),
 ('DDC', {'NM_001082971.2'}),
 ('DDX3X', {'NM_001356.5'}),
 ('DDX41', {'NM_016222.4'}),
 ('DEAF1', {'NM_021008.4'}),
 ('DEPDC5', {'NM_001242896.3'}),
 ('DES', {'NM_001927.4'}),
 ('DHCR7', {'NM_001360.3'}),
 ('DICER1', {'NM_177438.3'}),
 ('DLD', {'NM_000108.5'}),
 ('DLG4', {'NM_001321075.3'}),
 ('DMD', {'NM_004006.3'}),
 ('DNAH1', {'NM_015512.5'}),
 ('DNAH11', {'NM_001277115.2'}),
 ('DNAH5', {'NM_001369.3'}),
 ('DNAH8', {'NM_001206927.2'}),
 ('DNAH9', {'NM_001372.4'}),
 ('DNAI1', {'NM_012144.4'}),
 ('DNAI2', {'NM_023036.6'}),
 ('DNM1', {'NM_001288739.2', 'NM_004408.4'}),
 ('DNMT3A', {'NM_022552.5'}),
 ('DOCK6', {'NM_020812.4'}),
 ('DOCK8', {'NM_203447.4'}),
 ('DOK7', {'NM_173660.5'}),
 ('DPYD', {'NM_000110.4'}),
 ('DSG2', {'NM_001943.5'}),
 ('DSP', {'NM_004415.4'}),
 ('DST', {'NM_001374736.1', 'NM_001723.7'}),
 ('DUOX2', {'NM_001363711.2'}),
 ('DYNC1H1', {'NM_001376.5'}),
 ('DYNC2H1', {'NM_001080463.2', 'NM_001377.3'}),
 ('DYRK1A', {'NM_001347721.2'}),
 ('DYSF', {'NM_001130987.2', 'NM_003494.4'}),
 ('EBF3', {'NM_001375380.1'}),
 ('EBP', {'NM_006579.3'}),
 ('ECHS1', {'NM_004092.4'}),
 ('EDA', {'NM_001399.5'}),
 ('EDAR', {'NM_022336.4'}),
 ('EFTUD2', {'NM_004247.4'}),
 ('EHMT1', {'NM_024757.5'}),
 ('EIF2AK3', {'NM_004836.7'}),
 ('EIF2B5', {'NM_003907.3'}),
 ('ELAC2', {'NM_018127.7'}),
 ('ELANE', {'NM_001972.4'}),
 ('ELN', {'NM_000501.4'}),
 ('ELP1', {'NM_003640.5'}),
 ('EMC1', {'NM_015047.3'}),
 ('ENG', {'NM_001114753.3'}),
 ('ENPP1', {'NM_006208.3'}),
 ('EP300', {'NM_001429.3', 'NM_001429.4'}),
 ('EPG5', {'NM_020964.3'}),
 ('EPHB4', {'NM_004444.5'}),
 ('ERCC2', {'NM_000400.4'}),
 ('ERCC6', {'NM_000124.4', 'NM_001277058.2'}),
 ('ERCC8', {'NM_000082.4'}),
 ('ESCO2', {'NM_001017420.3'}),
 ('ETFDH', {'NM_004453.4'}),
 ('ETHE1', {'NM_014297.5'}),
 ('EVC', {'NM_153717.3'}),
 ('EVC2', {'NM_147127.5'}),
 ('EXT1', {'NM_000127.3'}),
 ('EXT2', {'NM_207122.2'}),
 ('EYA1', {'NM_000503.6'}),
 ('EYA4', {'NM_004100.5'}),
 ('EYS', {'NM_001142800.2'}),
 ('F11', {'NM_000128.4'}),
 ('F5', {'NM_000130.4', 'NM_000130.5'}),
 ('F7', {'NM_000131.4', 'NM_000131.5', 'NM_019616.4', 'none'}),
 ('F8', {'NM_000132.4', 'none'}),
 ('F9', {'NM_000133.4', 'none'}),
 ('FAH', {'NM_000137.4'}),
 ('FAM161A', {'NM_001201543.2'}),
 ('FANCA', {'NM_000135.4'}),
 ('FANCC', {'NM_000136.3'}),
 ('FANCD2', {'NM_001018115.3'}),
 ('FANCG', {'NM_004629.2'}),
 ('FANCI', {'NM_001113378.2'}),
 ('FANCL', {'NM_018062.4'}),
 ('FANCM', {'NM_020937.4'}),
 ('FAS', {'NM_000043.6'}),
 ('FBN1', {'NM_000138.5'}),
 ('FBN2', {'NM_001999.4'}),
 ('FBXL4', {'NM_001278716.2'}),
 ('FBXO11', {'NM_001190274.2'}),
 ('FECH', {'NM_000140.3', 'NM_000140.5', 'none'}),
 ('FGFR1', {'NM_023110.3'}),
 ('FGFR2', {'NM_000141.5'}),
 ('FGFR3', {'NM_000142.5'}),
 ('FH', {'NM_000143.4'}),
 ('FHL1', {'NM_001159699.2', 'NM_001159702.3'}),
 ('FIG4', {'NM_014845.6'}),
 ('FKRP', {'NM_024301.5'}),
 ('FKTN', {'NM_001079802.2'}),
 ('FLCN', {'NM_144997.7'}),
 ('FLG', {'NM_002016.2'}),
 ('FLNA', {'NM_001110556.2'}),
 ('FLNB', {'NM_001457.4'}),
 ('FLNC', {'NM_001458.5'}),
 ('FLT4', {'NM_182925.5'}),
 ('FMO3', {'NM_001002294.3'}),
 ('FOXC1', {'NM_001453.3'}),
 ('FOXG1', {'NM_005249.5'}),
 ('FOXL2', {'NM_023067.4'}),
 ('FOXP1', {'NM_001349338.3'}),
 ('FRAS1', {'NM_025074.7'}),
 ('FREM2', {'NM_207361.6'}),
 ('FUCA1', {'NM_000147.5'}),
 ('G6PC1', {'NM_000151.4'}),
 ('G6PD', {'NM_000402.4', 'NM_001042351.3', 'NM_001360016.2', 'none'}),
 ('GAA', {'NM_000152.5'}),
 ('GABRA1', {'NM_001127644.2'}),
 ('GABRB2', {'NM_001371727.1'}),
 ('GABRB3', {'NM_000814.6', 'NM_021912.5'}),
 ('GABRG2', {'NM_198904.4'}),
 ('GALC', {'NM_000153.4', 'NM_001201402.2'}),
 ('GALK1', {'NM_000154.2'}),
 ('GALNS', {'NM_000512.5'}),
 ('GALT', {'NM_000155.4'}),
 ('GAMT', {'NM_000156.6'}),
 ('GATA2', {'NM_032638.5'}),
 ('GATAD2B', {'NM_020699.4'}),
 ('GBA1', {'NM_000157.4'}),
 ('GBE1', {'NM_000158.4'}),
 ('GCDH', {'NM_000159.4'}),
 ('GCH1', {'NM_000161.3'}),
 ('GCK', {'NM_000162.5', 'none'}),
 ('GDAP1', {'NM_018972.4'}),
 ('GFAP', {'NM_002055.5'}),
 ('GFM1', {'NM_024996.7'}),
 ('GJA1', {'NM_000165.5'}),
 ('GJB1', {'NM_000166.6', 'NM_001097642.3'}),
 ('GJB2', {'NM_004004.6'}),
 ('GLA', {'NM_000169.3'}),
 ('GLB1', {'NM_000404.4'}),
 ('GLDC', {'NM_000170.3'}),
 ('GLE1', {'NM_001003722.2'}),
 ('GLI3', {'NM_000168.6'}),
 ('GLRA1', {'NM_000171.4'}),
 ('GNAO1', {'NM_020988.3'}),
 ('GNAS', {'NM_000516.7', 'NM_016592.5', 'NM_080425.4'}),
 ('GNB1', {'NM_002074.5'}),
 ('GNE', {'NM_001128227.3', 'NM_005476.7'}),
 ('GNPTAB', {'NM_024312.5'}),
 ('GNPTG', {'NM_032520.5'}),
 ('GPR143', {'NM_000273.3'}),
 ('GRHPR', {'NM_012203.2'}),
 ('GRIN1', {'NM_007327.4'}),
 ('GRIN2A', {'NM_001134407.3'}),
 ('GRIN2B', {'NM_000834.5'}),
 ('GRN', {'NM_002087.4'}),
 ('GUCY2D', {'NM_000180.4'}),
 ('GUSB', {'NM_000181.4'}),
 ('HADHA', {'NM_000182.5'}),
 ('HADHB', {'NM_000183.3'}),
 ('HBA2', {'NM_000517.4', 'NM_000517.6'}),
 ('HBB', {'NM_000518.4', 'NM_000518.5', 'none'}),
 ('HDAC8', {'NM_018486.3'}),
 ('HEXA', {'NM_000520.6'}),
 ('HEXB', {'NM_000521.4'}),
 ('HGD', {'NM_000187.4'}),
 ('HGSNAT', {'NM_152419.3'}),
 ('HLCS', {'NM_001352514.2'}),
 ('HMBS', {'NM_000190.4'}),
 ('HMGCL', {'NM_000191.3'}),
 ('HNF1A', {'NM_000545.5', 'NM_000545.8', 'none'}),
 ('HNF1B', {'NM_000458.4'}),
 ('HNF4A', {'NM_175914.5', 'none'}),
 ('HNRNPU', {'NM_031844.3'}),
 ('HOGA1', {'NM_138413.4'}),
 ('HPRT1', {'NM_000194.2', 'NM_000194.3', 'none'}),
 ('HPS1', {'NM_000195.5'}),
 ('HPS3', {'NM_032383.5'}),
 ('HPS4', {'NM_022081.6'}),
 ('HPS5', {'NM_181507.2'}),
 ('HSD17B3', {'NM_000197.1', 'NM_000197.2'}),
 ('HSD17B4', {'NM_000414.4', 'none'}),
 ('HSD3B2', {'NM_000198.4'}),
 ('HSPG2', {'NM_005529.7'}),
 ('HUWE1', {'NM_031407.7'}),
 ('IDS', {'NM_000202.8'}),
 ('IDUA', {'NM_000203.4', 'NM_000203.5'}),
 ('IFT122', {'NM_052989.3'}),
 ('IFT140', {'NM_014714.4'}),
 ('IFT172', {'NM_015662.3'}),
 ('IGF1R', {'NM_000875.5'}),
 ('IGHMBP2', {'NM_002180.3'}),
 ('IL12RB1', {'NM_005535.3'}),
 ('IL2RG', {'NM_000206.3'}),
 ('IMPG2', {'NM_016247.4'}),
 ('INF2', {'NM_022489.4'}),
 ('INSR', {'NM_000208.4'}),
 ('INVS', {'NM_014425.5'}),
 ('IQCB1', {'NM_001023570.4'}),
 ('IQSEC2', {'NM_001111125.3'}),
 ('IRF6', {'NM_006147.4'}),
 ('ITGA2B', {'NM_000419.5'}),
 ('ITGB2', {'NM_000211.5'}),
 ('ITGB3', {'NM_000212.3'}),
 ('ITGB4', {'NM_000213.5'}),
 ('ITPR1', {'NM_001378452.1'}),
 ('IVD', {'NM_002225.5'}),
 ('JAG1', {'NM_000214.3'}),
 ('JAK3', {'NM_000215.4'}),
 ('KAT6A', {'NM_006766.5'}),
 ('KAT6B', {'NM_012330.4'}),
 ('KCNA2', {'NM_004974.4'}),
 ('KCNB1', {'NM_004975.4'}),
 ('KCNH2', {'NM_000238.4'}),
 ('KCNJ1', {'NM_153766.3'}),
 ('KCNJ11', {'NM_000525.4'}),
 ('KCNJ2', {'NM_000891.3'}),
 ('KCNQ1', {'NM_000218.3'}),
 ('KCNQ2', {'NM_172107.4'}),
 ('KCNT1', {'NM_020822.3'}),
 ('KCNV2', {'NM_133497.4'}),
 ('KDM5B', {'NM_006618.5'}),
 ('KDM5C', {'NM_004187.5'}),
 ('KDM6A', {'NM_001291415.2'}),
 ('KDM6B', {'NM_001348716.2'}),
 ('KIAA0586', {'NM_001329943.3'}),
 ('KIF11', {'NM_004523.4'}),
 ('KIF1A', {'NM_001244008.2'}),
 ('KIF5A', {'NM_004984.4'}),
 ('KIF7', {'NM_198525.3'}),
 ('KIT', {'NM_000222.3'}),
 ('KMT2A', {'NM_001197104.2'}),
 ('KMT2B', {'NM_014727.3'}),
 ('KMT2C', {'NM_170606.3'}),
 ('KMT2D', {'NM_003482.4'}),
 ('KMT2E', {'NM_182931.3'}),
 ('KRAS', {'NM_004985.5', 'NM_033360.4'}),
 ('KRIT1', {'NM_194454.3'}),
 ('KRT14', {'NM_000526.5'}),
 ('KRT5', {'NM_000424.4'}),
 ('L1CAM', {'NM_001278116.2'}),
 ('LAMA1', {'NM_005559.4'}),
 ('LAMA2', {'NM_000426.4'}),
 ('LAMA3', {'NM_000227.6', 'NM_198129.4'}),
 ('LAMB2', {'NM_002292.4'}),
 ('LAMB3', {'NM_000228.3'}),
 ('LAMC2', {'NM_005562.3'}),
 ('LAMC3', {'NM_006059.4'}),
 ('LAMP2', {'NM_002294.3'}),
 ('LCA5', {'NM_001122769.3'}),
 ('LDLR', {'NM_000527.4', 'NM_000527.5', 'NM_001195803.1'}),
 ('LIFR', {'NM_001127671.2'}),
 ('LIPA', {'NM_000235.4'}),
 ('LMNA', {'NM_170707.4'}),
 ('LMX1B', {'NM_001174147.2'}),
 ('LOXHD1', {'NM_001384474.1'}),
 ('LPL', {'NM_000237.3'}),
 ('LRBA', {'NM_001364905.1'}),
 ('LRP2', {'NM_004525.3'}),
 ('LRP5', {'NM_002335.4'}),
 ('LRPPRC', {'NM_133259.4'}),
 ('LRSAM1', {'NM_001005373.4'}),
 ('LYST', {'NM_000081.4'}),
 ('LZTR1', {'NM_006767.4'}),
 ('MAN2B1', {'NM_000528.4'}),
 ('MANBA', {'NM_005908.4'}),
 ('MBD4', {'NM_001276270.2'}),
 ('MBD5', {'NM_001378120.1'}),
 ('MCCC1', {'NM_020166.5'}),
 ('MCCC2', {'NM_022132.5'}),
 ('MCOLN1', {'NM_020533.3'}),
 ('MCPH1', {'NM_024596.5'}),
 ('MECP2', {'NM_001110792.2', 'NM_004992.4'}),
 ('MED12', {'NM_005120.3'}),
 ('MED13L', {'NM_015335.5'}),
 ('MED17', {'NM_004268.5'}),
 ('MEF2C', {'NM_002397.5'}),
 ('MEN1', {'NM_001370259.2'}),
 ('MERTK', {'NM_006343.3'}),
 ('MFN2', {'NM_014874.4'}),
 ('MFSD8', {'NM_001371596.2'}),
 ('MITF', {'NM_000248.4', 'NM_001354604.2'}),
 ('MKKS', {'NM_170784.3'}),
 ('MKS1', {'NM_017777.4'}),
 ('MLC1', {'NM_001376473.1', 'NM_015166.4'}),
 ('MLH1', {'NM_000249.4'}),
 ('MMAA', {'NM_172250.3'}),
 ('MMAB', {'NM_052845.4'}),
 ('MMACHC', {'NM_015506.3'}),
 ('MME', {'NM_007289.4'}),
 ('MMUT', {'NM_000255.4'}),
 ('MPDZ', {'NM_001378778.1'}),
 ('MPI', {'NM_002435.3'}),
 ('MPL', {'NM_005373.3'}),
 ('MPV17', {'NM_002437.5'}),
 ('MPZ', {'NM_000530.8'}),
 ('MRE11', {'NM_005591.4'}),
 ('MSH2', {'NM_000251.3'}),
 ('MSH3', {'NM_002439.5'}),
 ('MSH6', {'NM_000179.3'}),
 ('MTHFR', {'NM_005957.5'}),
 ('MTM1', {'NM_000252.3'}),
 ('MTOR', {'NM_004958.4'}),
 ('MTR', {'NM_000254.3'}),
 ('MTRR', {'NM_002454.3'}),
 ('MTTP', {'NM_001386140.1'}),
 ('MUTYH', {'NM_001048174.2', 'NM_001128425.2'}),
 ('MVK', {'NM_000431.4'}),
 ('MYBPC3', {'NM_000256.3', 'none'}),
 ('MYH11', {'NM_001040113.2', 'NM_002474.3'}),
 ('MYH2', {'NM_017534.6'}),
 ('MYH3', {'NM_002470.4'}),
 ('MYH7', {'NM_000257.4'}),
 ('MYO15A', {'NM_016239.4'}),
 ('MYO18B', {'NM_032608.7'}),
 ('MYO5B', {'NM_001080467.3'}),
 ('MYO6', {'NM_004999.4'}),
 ('MYO7A', {'NM_000260.4'}),
 ('MYT1L', {'NM_001303052.2'}),
 ('NAA15', {'NM_057175.5'}),
 ('NAGLU', {'NM_000263.4'}),
 ('NAGS', {'NM_153006.3', 'none'}),
 ('NALCN', {'NM_052867.4'}),
 ('NBAS', {'NM_015909.4'}),
 ('NBEA', {'NM_001385012.1'}),
 ('NBN', {'NM_002485.5'}),
 ('NDP', {'NM_000266.4'}),
 ('NDUFAF5', {'NM_024120.5'}),
 ('NEB', {'NM_001164507.2', 'NM_001164508.2'}),
 ('NEK1', {'NM_001199397.3'}),
 ('NEU1', {'NM_000434.4'}),
 ('NEXMIF', {'NM_001008537.3'}),
 ('NF1', {'NM_001042492.3'}),
 ('NF2', {'NM_000268.4'}),
 ('NFIX', {'NM_001365902.3'}),
 ('NFKB1', {'NM_003998.4'}),
 ('NGLY1', {'NM_018297.4'}),
 ('NIPBL', {'NM_133433.4'}),
 ('NKX2-1', {'NM_001079668.3'}),
 ('NKX2-5', {'NM_004387.4'}),
 ('NLRP3', {'NM_001243133.2'}),
 ('NMNAT1', {'NM_022787.4'}),
 ('NOTCH1', {'NM_017617.5'}),
 ('NOTCH2', {'NM_024408.4'}),
 ('NOTCH3', {'NM_000435.3'}),
 ('NPC1', {'NM_000271.5'}),
 ('NPHP1', {'NM_001128178.3'}),
 ('NPHP3', {'NM_153240.5'}),
 ('NPHP4', {'NM_015102.5'}),
 ('NPHS1', {'NM_004646.4'}),
 ('NPHS2', {'NM_014625.4'}),
 ('NPR2', {'NM_003995.4'}),
 ('NPRL3', {'NM_001077350.3'}),
 ('NR0B1', {'NM_000475.5'}),
 ('NR2E3', {'NM_014249.4'}),
 ('NR2F1', {'NM_005654.6'}),
 ('NR5A1', {'NM_004959.5'}),
 ('NSD1', {'NM_022455.5'}),
 ('NTHL1', {'NM_002528.7', 'none'}),
 ('NTRK1', {'NM_002529.4'}),
 ('OAT', {'NM_000274.4'}),
 ('OCA2', {'NM_000275.3'}),
 ('OCRL', {'NM_000276.4'}),
 ('OFD1', {'NM_003611.3'}),
 ('OPA1', {'NM_130837.3'}),
 ('OPHN1', {'NM_002547.3'}),
 ('OTC', {'NM_000531.6', 'none'}),
 ('OTOF', {'NM_194248.3', 'NM_194323.3'}),
 ('OTOG', {'NM_001292063.2'}),
 ('OTOGL', {'NM_001378609.3'}),
 ('P3H1', {'NM_022356.4'}),
 ('PAFAH1B1', {'NM_000430.4', 'none'}),
 ('PAH', {'NM_000277.3'}),
 ('PALB2', {'NM_024675.4', 'none'}),
 ('PANK2', {'NM_001386393.1'}),
 ('PARN', {'NM_002582.4'}),
 ('PAX2', {'NM_000278.5'}),
 ('PAX3', {'NM_181457.3', 'NM_181458.4'}),
 ('PAX6', {'NM_000280.6', 'NM_001368894.2'}),
 ('PC', {'NM_001040716.2'}),
 ('PCARE', {'NM_001029883.3'}),
 ('PCCA', {'NM_000282.4'}),
 ('PCCB', {'NM_000532.5'}),
 ('PCDH15', {'NM_001384140.1', 'NM_033056.4'}),
 ('PCDH19', {'NM_001184880.2'}),
 ('PCNT', {'NM_006031.6'}),
 ('PDE6A', {'NM_000440.3'}),
 ('PDE6B', {'NM_000283.4'}),
 ('PDE6C', {'NM_006204.4'}),
 ('PDHA1', {'NM_000284.4'}),
 ('PEPD', {'NM_000285.4'}),
 ('PEX1', {'NM_000466.3'}),
 ('PEX10', {'NM_002617.4'}),
 ('PEX6', {'NM_000287.4'}),
 ('PEX7', {'NM_000288.4'}),
 ('PFKM', {'NM_000289.6'}),
 ('PHEX', {'NM_000444.6'}),
 ('PHGDH', {'NM_006623.4'}),
 ('PHIP', {'NM_017934.7'}),
 ('PHKA2', {'NM_000292.3'}),
 ('PHKB', {'NM_000293.3'}),
 ('PIEZO1', {'NM_001142864.4'}),
 ('PIEZO2', {'NM_001378183.1'}),
 ('PIGN', {'NM_176787.5'}),
 ('PIK3CA', {'NM_006218.4'}),
 ('PKD1', {'NM_001009944.3'}),
 ('PKD2', {'NM_000297.4'}),
 ('PKHD1', {'NM_138694.4'}),
 ('PKLR', {'NM_000298.6', 'none'}),
 ('PKP2', {'NM_001005242.3'}),
 ('PLA2G6', {'NM_003560.4', 'none'}),
 ('PLEC', {'NM_201378.4', 'NM_201384.3'}),
 ('PLOD1', {'NM_000302.4'}),
 ('PLP1', {'NM_000533.5'}),
 ('PMM2', {'NM_000303.3', 'none'}),
 ('PMP22', {'NM_000304.4'}),
 ('PMS2', {'NM_000535.7'}),

### Some variants returned 'none' as transcript in gene_transcripts, let's find out which

In [28]:
for gene, transcripts in gene_transcripts.items():
    #reference_proteins[gene] = []
    for transcript in sorted(transcripts):
        if 'none' in transcript:
            print(gene, transcript)

ACO2 none
ACTA1 none
AGL none
BRCA2 none
CFTR none
CHRNE none
COL7A1 none
CTNS none
F7 none
F8 none
F9 none
FECH none
G6PD none
GCK none
HBB none
HNF1A none
HNF4A none
HPRT1 none
HSD17B4 none
MYBPC3 none
NAGS none
NTHL1 none
OTC none
PAFAH1B1 none
PALB2 none
PKLR none
PLA2G6 none
PMM2 none
PROC none
RB1 none
RPGR none
RS1 none
RUNX2 none
SERPINC1 none
SERPING1 none
SHH none
SOX10 none
TH none
USH2A none

In [ ]:
for gene, transcripts in gene_transcripts.items():
    #reference_proteins[gene] = []
    for transcript in sorted(transcripts):
        if 'NM_' not in transcript:
            print(gene, transcript)

ACO2 none
ACTA1 none
AGL none
BRCA2 none
CFTR none
CHRNE none
COL7A1 none
CTNS none
F7 none
F8 none
F9 none
FECH none
G6PD none
GCK none
HBB none
HNF1A none
HNF4A none
HPRT1 none
HSD17B4 none
MYBPC3 none
NAGS none
NTHL1 none
OTC none
PAFAH1B1 none
PALB2 none
PKLR none
PLA2G6 none
PMM2 none
PROC none
RB1 none
RPGR none
RS1 none
RUNX2 none
SERPINC1 none
SERPING1 none
SHH none
SOX10 none
TERT TERT:c.1710G>Y
TH none
USH2A none

### Step 4

In [8]:
reference_proteins = {}

for gene, transcripts in gene_transcripts.items():
    reference_proteins[gene] = []
    for transcript in sorted(transcripts):
        if 'NM_' in transcript:
            prot = get_reference_proteins(gene, transcript)
            reference_proteins[gene].append(prot)
            print(gene, prot)

AAAS [{'transcript': 'NM_015665.6', 'protein_id': 'NP_056480.1', 'protein_seq': Seq('MCSLGLFPPPPPRGQVTLYEHNNELVTGSSYESPPPDFRGQWINLPVLQLTKDP...SHL'), 'cds_seq': Seq('atgtgctctctggggttgttccctcctccaccgcctcggggtcaagtcacccta...taa'), 'cds_start': 145, 'cds_end': 1786}]
ABCA1 [{'transcript': 'NM_005502.4', 'protein_id': 'NP_005493.2', 'protein_seq': Seq('MACWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILISVRLSYPPYEQHEC...SYV'), 'cds_seq': Seq('atggcttgttggcctcagctgaggttgctgctgtggaagaacctcactttcaga...tga'), 'cds_start': 313, 'cds_end': 7099}]
ABCA12 [{'transcript': 'NM_173076.3', 'protein_id': 'NP_775099.2', 'protein_seq': Seq('MASLFHQLQILVWKNWLGVKRQPLWTLVLILWPVIIFIILAITRTKFPPTAKPT...MES'), 'cds_seq': Seq('atggcttccctgtttcatcagcttcagatcctggtctggaaaaattggctaggt...taa'), 'cds_start': 418, 'cds_end': 8206}]
ABCA3 [{'transcript': 'NM_001089.3', 'protein_id': 'NP_001080.2', 'protein_seq': Seq('MAVLRQLALLLWKNYTLQKRKVLVTVLELFLPLLFSGILIWLRLKIQSENVPNA...EGR'), 'cds_seq': Seq('atggctgtgctcaggcagctggcgctcctcctctggaagaactacaccctgcag...tga'), 'cds_start': 694, 'cds_end': 5809}]
ABCA4 [{'transcript': 'NM_000350.3', 'protein_id': 'NP_000341.2', 'protein_seq': Seq('MGFVRQIQLLLWKNWTLRKRQKIRFVVELVWPLSLFLVLIWLRNANPLYSHHEC...AQD'), 'cds_seq': Seq('atgggcttcgtgagacagatacagcttttgctctggaagaactggaccctgcgg...tga'), 'cds_start': 103, 'cds_end': 6925}]
ABCB11 [{'transcript': 'NM_003742.4', 'protein_id': 'NP_003733.2', 'protein_seq': Seq('MSDSVILRSIKKFGEENDGFESDKSYNNDKKSRLQDEKKGDGVRVGFFQLFRFS...PIS'), 'cds_seq': Seq('atgtctgactcagtaattcttcgaagtataaagaaatttggagaggagaatgat...tga'), 'cds_start': 127, 'cds_end': 4093}]
ABCB4 [{'transcript': 'NM_000443.4', 'protein_id': 'NP_000434.1', 'protein_seq': Seq('MDLEAAKNGTAWRPTSAEGDFELGISSKQKRKKTKTVKMIGVLTLFRYSDWQDK...QNL'), 'cds_seq': Seq('atggatcttgaggcggcaaagaacggaacagcctggcgccccacgagcgcggag...tga'), 'cds_start': 53, 'cds_end': 3893}]
ABCC2 [{'transcript': 'NM_000392.5', 'protein_id': 'NP_000383.2', 'protein_seq': Seq('MLEKFCNSTFWNSSFLDSPEADLPLCFEQTVLVWIPLGYLWLLAPWQLLHVYKS...TKF'), 'cds_seq': Seq('atgctggagaagttctgcaactctactttttggaattcctcattcctggacagt...tag'), 'cds_start': 205, 'cds_end': 4843}]
ABCC6 [{'transcript': 'NM_001171.6', 'protein_id': 'NP_001162.5', 'protein_seq': Seq('MAAPAEPCAGQGVWNQTEPEPAATSLLSLCFLRTAGVWVPPMYLWVLGPIYLLF...GLV'), 'cds_seq': Seq('atggccgcgcctgctgagccctgcgcggggcagggggtctggaaccagacagag...tga'), 'cds_start': 60, 'cds_end': 4572}]
ABCC8 [{'transcript': 'NM_000352.6', 'protein_id': 'NP_000343.2', 'protein_seq': Seq('MPLAFCGSENHSAAYRVDQGVLNNGCFVDALNVVPHVFLLFITFPILFIGWGSQ...ADK'), 'cds_seq': Seq('atgcccctggccttctgcggcagcgagaaccactcggccgcctaccgggtggac...tga'), 'cds_start': 69, 'cds_end': 4815}]
ABCC9 [{'transcript': 'NM_020297.4', 'protein_id': 'NP_064693.2', 'protein_seq': Seq('MSLSFCGNNISSYNINDGVLQNSCFVDALNLVPHVFLLFITFPILFIGWGSQSS...ADM'), 'cds_seq': Seq('atgagcctttcattttgtggtaacaacatttcttcatataatatcaacgatggt...tga'), 'cds_start': 363, 'cds_end': 5013}]
ABCD1 [{'transcript': 'NM_000033.4', 'protein_id': 'NP_000024.2', 'protein_seq': Seq('MPVLSRPRPWRGNTLKRTAVLLALAAYGAHKVYPLVRQCLAPARGLQAPAGEPT...AST'), 'cds_seq': Seq('atgccggtgctctccaggccccggccctggcgggggaacacgctgaagcgcacg...tga'), 'cds_start': 411, 'cds_end': 2649}]
ACAD9 [{'transcript': 'NM_014049.4', 'protein_id': 'NP_054768.2', 'protein_seq': Seq('MSGCGLFLRTTAAARACRGLVVSTANRRLLRTSPPVRAFAKELFLGKIKKKEVF...RTC'), 'cds_seq': Seq('atgagcggctgcgggctcttcctgcgcaccacggctgcggctcgtgcctgccgg...tga'), 'cds_start': 202, 'cds_end': 2068}]
ACAD9 [{'transcript': 'NM_014049.5', 'protein_id': 'NP_054768.2', 'protein_seq': Seq('MSGCGLFLRTTAAARACRGLVVSTANRRLLRTSPPVRAFAKELFLGKIKKKEVF...RTC'), 'cds_seq': Seq('atgagcggctgcgggctcttcctgcgcaccacggctgcggctcgtgcctgccgg...tga'), 'cds_start': 72, 'cds_end': 1938}]
ACADM [{'transcript': 'NM_000016.6', 'protein_id': 'NP_000007.1', 'protein_seq': Seq('MAAGFGRCCRVLRSISRFHWRSQHTKANRQREPGLGFSFEFTEQQKEFQATARK...YKN'), 'cds_seq': Seq('atggcagcggggttcgggcgatgctgcagggtcctgagaagtatttctcgtttt...taa'), 'cds_start': 79, 'cds_end': 1345}]
ACADS [{'transcript': 'NM_000017.4', 'protein_id': 'NP_000008.1', 'protein_seq': Seq('MAAALLARASGPARRALCPRAWRQLHTIYQSVELPETHQMLLQTCRDFAEKELF...YRS'), 'cds_seq': Seq('atggccgccgcgctgctcgcccgggcctcgggccctgcccgcagagctctctgt...tga'), 'cds_start': 60, 'cds_end': 1299}]
ACADVL [{'transcript': 'NM_000018.4', 'protein_id': 'NP_000009.1', 'protein_seq': Seq('MQAARMAASLGRQLLRLGGGSSRLTALLGQPRPGPARRPYAGGAAQLALDKSDS...LGF'), 'cds_seq': Seq('atgcaggcggctcggatggccgcgagcttggggcggcagctgctgaggctcggg...tga'), 'cds_start': 47, 'cds_end': 2015}]
ACAN [{'transcript': 'NM_001369268.1', 'protein_id': 'NP_001356197.1', 'protein_seq': Seq('MTTLLWVFVTLRVITAAVTVETSDHDNSLSVSIPQPSPLRVLLGTSLTIPCYFI...TAH'), 'cds_seq': Seq('atgaccactttactctgggttttcgtgactctgagggtcatcactgcagctgtc...tga'), 'cds_start': 381, 'cds_end': 8088}]
ACAT1 [{'transcript': 'NM_000019.4', 'protein_id': 'NP_000010.1', 'protein_seq': Seq('MAVLAALLRSGARSRSPLLRRLVQEIRYVERSYVSKPTLKEVVIVSATRTPIGS...QKL'), 'cds_seq': Seq('atggctgtgctggcggcacttctgcgcagcggcgcccgcagccgcagccccctg...tag'), 'cds_start': 40, 'cds_end': 1324}]
ACO2 [{'transcript': 'NM_001098.3', 'protein_id': 'NP_001089.1', 'protein_seq': Seq('MAPYSLLVTRLQKALGVRQYHVASVLCQRAKVAMSHFEPNEYIHYDLLEKNINI...LQQ'), 'cds_seq': Seq('atggcgccctacagcctactggtgactcggctgcagaaagctctgggtgtgcgg...tga'), 'cds_start': 30, 'cds_end': 2373}]
ACSF3 [{'transcript': 'NM_001243279.3', 'protein_id': 'NP_001230208.1', 'protein_seq': Seq('MLPHVVLTFRRLGCALASCRLAPARHRGSGLLHTAPVARSDRSAPVFTRALAFG...HPS'), 'cds_seq': Seq('atgctgccccatgtggtgctcaccttccggcgcctgggctgcgccttggcgtcc...tga'), 'cds_start': 338, 'cds_end': 2069}]
ACTA1 [{'transcript': 'NM_001100.4', 'protein_id': 'NP_001091.1', 'protein_seq': Seq('MCDEDETTALVCDNGSGLVKAGFAGDDAPRAVFPSIVGRPRHQGVMVGMGQKDS...KCF'), 'cds_seq': Seq('atgtgcgacgaagacgagaccaccgccctcgtgtgcgacaatggctccggcctg...tag'), 'cds_start': 103, 'cds_end': 1237}]
ACTB [{'transcript': 'NM_001101.5', 'protein_id': 'NP_001092.1', 'protein_seq': Seq('MDDDIAALVVDNGSGMCKAGFAGDDAPRAVFPSIVGRPRHQGVMVGMGQKDSYV...KCF'), 'cds_seq': Seq('atggatgatgatatcgccgcgctcgtcgtcgacaacggctccggcatgtgcaag...tag'), 'cds_start': 84, 'cds_end': 1212}]
ACTG1 [{'transcript': 'NM_001614.5', 'protein_id': 'NP_001605.1', 'protein_seq': Seq('MEEEIAALVIDNGSGMCKAGFAGDDAPRAVFPSIVGRPRHQGVMVGMGQKDSYV...KCF'), 'cds_seq': Seq('atggaagaagagatcgccgcgctggtcattgacaatggctccggcatgtgcaaa...taa'), 'cds_start': 72, 'cds_end': 1200}]
ACVRL1 [{'transcript': 'NM_000020.3', 'protein_id': 'NP_000011.2', 'protein_seq': Seq('MTLGSPRKGLLMLLMALVTQGDPVKPSRGPLVTCTCESPHCKGPTCRGAWCTVV...VIQ'), 'cds_seq': Seq('atgaccttgggctcccccaggaaaggccttctgatgctgctgatggccttggtg...tag'), 'cds_start': 197, 'cds_end': 1709}]
ADA [{'transcript': 'NM_000022.4', 'protein_id': 'NP_000013.2', 'protein_seq': Seq('MAQTPAFDKPKVELHVHLDGSIKPETILYYGRRRGIALPANTAEGLLNVIGMDK...QNL'), 'cds_seq': Seq('atggcccagacgcccgccttcgacaagcccaaagtggaactgcatgtccaccta...tga'), 'cds_start': 92, 'cds_end': 1184}]
ADA2 [{'transcript': 'NM_001282225.2', 'protein_id': 'NP_001269154.1', 'protein_seq': Seq('MLVDGPSERPALCFLLLAVAMSFFGSALSIDETRAHLLLKEKMMRLGGRLVLNT...ATK'), 'cds_seq': Seq('atgttggtggatggcccatctgagcggccagccctgtgcttcttgctgttggct...tga'), 'cds_start': 126, 'cds_end': 1662}]
ADAMTS13 [{'transcript': 'NM_139027.6', 'protein_id': 'NP_620596.2', 'protein_seq': Seq('MHQRHPRARCPPLCVAGILACGFLLGCWGPSHFQQSCLQALEPQAVSSYLSPGA...EGT'), 'cds_seq': Seq('atgcaccagcgtcacccccgggcaagatgccctcccctctgtgtggccggaatc...tga'), 'cds_start': 77, 'cds_end': 4193}]
ADAMTS2 [{'transcript': 'NM_014244.5', 'protein_id': 'NP_055059.2', 'protein_seq': Seq('MDPPAGAARRLLCPALLLLLLLLPPPLLPPPPPPANARLAAAADPPGGPLGHGA...GKF'), 'cds_seq': Seq('atggatccgccggcgggagccgctcgccgcctgctctgccccgcgctgctgctg...taa'), 'cds_start': 133, 'cds_end': 3769}]
ADAMTSL4 [{'transcript': 'NM_019032.6', 'protein_id': 'NP_061905.2', 'protein_seq': Seq('MENWTGRPWLYLLLLLSLPQLCLDQEVLSGHSLQTPTEEGQGPEGVWGPWVQWA...DPS'), 'cds_seq': Seq('atggagaactggactggcaggccctggctgtatctgctgctgcttctgtccctc...tga'), 'cds_start': 250, 'cds_end': 3475}]
ADAR [{'transcript': 'NM_001111.5', 'protein_id': 'NP_001102.3', 'protein_seq': Seq('MNPRQGYSLSGYYTHPFQGYEHRQLRYQQPGPGSSPSSFLLKQIEFLKGQLPEA...CPV'), 'cds_seq': Seq('atgaatccgcggcaggggtattccctcagcggatactacacccatccatttcaa...tag'), 'cds_start': 180, 'cds_end': 3861}]
ADGRG1 [{'transcript': 'NM_201525.4', 'protein_id': 'NP_958933.1', 'protein_seq': Seq('MTPQSLLQTTLFLLSLLFLVQGAHGRGHREDFRFCSQRNQTHRSSLHYKPTPDL...SRI'), 'cds_seq': Seq('atgactccccagtcgctgctgcagacgacactgttcctgctgagtctgctcttc...tag'), 'cds_start': 208, 'cds_end': 2272}]
ADGRV1 [{'transcript': 'NM_032119.4', 'protein_id': 'NP_115495.3', 'protein_seq': Seq('MSVFLGPGMPSASLLVNLLSALLILFVFGETEIRFTGQTEFVVNETSTTVIRLI...THL'), 'cds_seq': Seq('atgtcggtgttcctggggccagggatgccctctgcatctttattagtaaatctt...tag'), 'cds_start': 99, 'cds_end': 19020}]
ADNP [{'transcript': 'NM_001282531.3', 'protein_id': 'NP_001269460.1', 'protein_seq': Seq('MFQLPVNNLGSLRKARKTVKKILSDIGLEYCKEHIEDFKQFEPNDFYLKNTTWE...QQA'), 'cds_seq': Seq('atgttccaacttcctgtcaacaatcttggcagtttaagaaaagcccggaaaact...taa'), 'cds_start': 876, 'cds_end': 4185}]
ADSL [{'transcript': 'NM_000026.4', 'protein_id': 'NP_000017.1', 'protein_seq': Seq('MAAGGDHGSPDSYRSPLASRYASPEMCFVFSDRYKFRTWRQLWLWLAEAEQTLG...LCL'), 'cds_seq': Seq('atggcggctggaggcgatcatggttcgcccgacagctaccgctcacctcttgcc...tag'), 'cds_start': 59, 'cds_end': 1514}]
AFG2A [{'transcript': 'NM_145207.3', 'protein_id': 'NP_660208.2', 'protein_seq': Seq('MSSKKNRKRLNQSAENGSSLPSAASSCAEARAPSAGSDFAATSGTLTVTNLLEK...HTL'), 'cds_seq': Seq('atgtcttccaagaagaatagaaagcggttgaaccaaagcgcggaaaatggttcg...tga'), 'cds_start': 65, 'cds_end': 2747}]
AFG3L2 [{'transcript': 'NM_006796.3', 'protein_id': 'NP_006787.2', 'protein_seq': Seq('MAHRCLRLWGRGGCWPRGLQQLLVPGGVGPGEQPCLRTLYRFVTTQARASRNSL...VAN'), 'cds_seq': Seq('atggcgcaccgctgtttgcggctgtggggccggggcggctgctggccccgcggc...tag'), 'cds_start': 145, 'cds_end': 2539}]
AGA [{'transcript': 'NM_000027.4', 'protein_id': 'NP_000018.2', 'protein_seq': Seq('MARKSNLPVLLVPFLLCQALVRCSSPLPLVVNTWPFKNATEAAWRALASGGSAL...DCI'), 'cds_seq': Seq('atggcgcggaagtcgaacttgcctgtgcttctcgtgccgtttctgctctgccag...taa'), 'cds_start': 62, 'cds_end': 1103}]
AGL [{'transcript': 'NM_000642.3', 'protein_id': 'NP_000633.2', 'protein_seq': Seq('MGHSKQIRILLLNEMEKLEKTLFRLEQGYELQFRLGPTLQGKAVTVYTNYPFPG...YDL'), 'cds_seq': Seq('atgggacacagtaaacagattcgaattttacttctgaacgaaatggagaaactg...tag'), 'cds_start': 123, 'cds_end': 4722}]
AGXT [{'transcript': 'NM_000030.3', 'protein_id': 'NP_000021.1', 'protein_seq': Seq('MASHKLLVTPPKALLKPLSIPNQLLLGPGPSNLPPRIMAAGGLQMIGSMSKDMY...KKL'), 'cds_seq': Seq('atggcctctcacaagctgctggtgaccccccccaaggccctgctcaagcccctc...tga'), 'cds_start': 42, 'cds_end': 1221}]
AHDC1 [{'transcript': 'NM_001371928.1', 'protein_id': 'NP_001358857.1', 'protein_seq': Seq('MRVKPQGLVVTSSAVCSSPDYLREPKYYPGGPPTPRPLLPTRPPASPPDKAFST...TSL'), 'cds_seq': Seq('atgcgtgtgaagccccagggcctggtggtgacttccagtgccgtgtgcagctct...tag'), 'cds_start': 901, 'cds_end': 5713}]
AHI1 [{'transcript': 'NM_001134831.2', 'protein_id': 'NP_001128303.1', 'protein_seq': Seq('MPTAESEAKVKTKVRFEELLKTHSDLMREKKKLKKKLVRSEENISPDTIRSNLH...LIE'), 'cds_seq': Seq('atgcctacagctgagagtgaagcaaaagtaaaaaccaaagttcgctttgaagaa...taa'), 'cds_start': 359, 'cds_end': 3950}]
AIPL1 [{'transcript': 'NM_014336.5', 'protein_id': 'NP_055151.3', 'protein_seq': Seq('MDAALLLNVEGVKKTILHGGTGELPNFITGSRVIFHFRTMKCDEERTVIDDSRQ...LQH'), 'cds_seq': Seq('atggatgccgctctgctcctgaacgtggaaggggtcaagaaaaccattctgcac...tga'), 'cds_start': 17, 'cds_end': 1172}]
AIRE [{'transcript': 'NM_000383.4', 'protein_id': 'NP_000374.1', 'protein_seq': Seq('MATDAALRRLLRLHRTEIAVAVDSAFPLLHALADHDVVPEDKFQETLHLKEKEG...FPS'), 'cds_seq': Seq('atggcgacggacgcggcgctacgccggcttctgaggctgcaccgcacggagatc...tga'), 'cds_start': 131, 'cds_end': 1769}]
ALDH3A2 [{'transcript': 'NM_000382.3', 'protein_id': 'NP_000373.1', 'protein_seq': Seq('MELEVRRVRQAFLSGRSRPLRFRLQQLEALRRMVQEREKDILTAIAADLCKSEF...EYY'), 'cds_seq': Seq('atggagctcgaagtccggcgggtccgacaggcgttcctgtccggccggtcgcga...tga'), 'cds_start': 221, 'cds_end': 1679}]
ALDH5A1 [{'transcript': 'NM_001080.3', 'protein_id': 'NP_001071.1', 'protein_seq': Seq('MATCIWLRSCGARRLGSTFPGCRLRPRAGGLVPASGPAPGPAQLRCYAGRLAGL...GGL'), 'cds_seq': Seq('atggcgacctgcatttggctgcggagctgtggggcccggcgcctcgggtcgacg...tag'), 'cds_start': 28, 'cds_end': 1636}]
ALDH7A1 [{'transcript': 'NM_001182.5', 'protein_id': 'NP_001173.2', 'protein_seq': Seq('MWRLPRALCVHAAKTSKLSGPWSRPAAFMSTLLINQPQYAWLKELGLREENEGV...KFQ'), 'cds_seq': Seq('atgtggcgccttcctcgcgcgctgtgtgtgcacgctgcaaagaccagcaagctc...taa'), 'cds_start': 21, 'cds_end': 1641}]
ALDOB [{'transcript': 'NM_000035.4', 'protein_id': 'NP_000026.2', 'protein_seq': Seq('MAHRFPALTQEQKKELSEIAQSIVANGKGILAADESVGTMGNRLQRIKVENTEE...YTY'), 'cds_seq': Seq('atggcccaccgatttccagccctcacccaggagcagaagaaggagctctcagaa...tag'), 'cds_start': 76, 'cds_end': 1171}]
ALG1 [{'transcript': 'NM_019109.5', 'protein_id': 'NP_061982.3', 'protein_seq': Seq('MAASCLVLLALCLLLPLLLLGGWKRWRRGRAARHVVAVVLGDVGRSPRMQYHAL...MDT'), 'cds_seq': Seq('atggcggcctcatgcttggtcctgctggcgctgtgtctgctgctgccgctgctg...taa'), 'cds_start': 7, 'cds_end': 1402}]
ALG6 [{'transcript': 'NM_013339.4', 'protein_id': 'NP_037471.2', 'protein_seq': Seq('MEKWYLMTVVVLIGLTVRWTVSLNSYSGAGKPPMFGDYEAQRHWQEITFNLPVK...KIS'), 'cds_seq': Seq('atggagaaatggtacttgatgacagtagtggttttaataggactaacagtacga...tag'), 'cds_start': 268, 'cds_end': 1792}]
ALMS1 [{'transcript': 'NM_001378454.1', 'protein_id': 'NP_001365383.1', 'protein_seq': Seq('MEPEDLPWPGELEEEEEEEEEEEEEEEEAAAAAAANVDDVVVVEEVEEEAGREL...PWD'), 'cds_seq': Seq('atggagcccgaggatctgccatggccgggcgagctggaggaggaggaggaggag...tga'), 'cds_start': 33, 'cds_end': 12540}]
ALOX12B [{'transcript': 'NM_001139.3', 'protein_id': 'NP_001130.1', 'protein_seq': Seq('MATYKVRVATGTDLLSGTRDSISLTIVGTQGESHKQLLNHFGRDFATGAVGQYT...ISI'), 'cds_seq': Seq('atggccacctacaaagtcagggtggccacaggcaccgacctcttgtcgggaaca...tag'), 'cds_start': 274, 'cds_end': 2380}]
ALPK3 [{'transcript': 'NM_020778.5', 'protein_id': 'NP_065829.4', 'protein_seq': Seq('MGSRRAPSRGWGAGGRSGAGGDGEDDGPVWIPSPASRSYLLSVRPETSLSSNRL...GMR'), 'cds_seq': Seq('atggggtcgcggagggcccccagccggggctggggcgcgggtgggcggtcgggg...tag'), 'cds_start': 97, 'cds_end': 5215}]
ALPL [{'transcript': 'NM_000478.6', 'protein_id': 'NP_000469.3', 'protein_seq': Seq('MISPFLVLAIGTCLTNSLVPEKEKDPKYWRDQAQETLKYALELQKLNTNVAKNV...VLF'), 'cds_seq': Seq('atgatttcaccattcttagtactggccattggcacctgccttactaactcctta...tga'), 'cds_start': 199, 'cds_end': 1774}]
ALS2 [{'transcript': 'NM_020919.3', 'protein_id': 'NP_065970.2', 'protein_seq': Seq('MDSKKRSSTEAEGSKERGLVHIWQAGSFPITPERLPGWGGKTVLQAALGVKHGV...KLN'), 'cds_seq': Seq('atggactcaaagaagagaagctcaacagaggcagaaggatccaaggaaagaggc...tag'), 'cds_start': 356, 'cds_end': 5330}]
ALS2 [{'transcript': 'NM_020919.4', 'protein_id': 'NP_065970.2', 'protein_seq': Seq('MDSKKRSSTEAEGSKERGLVHIWQAGSFPITPERLPGWGGKTVLQAALGVKHGV...KLN'), 'cds_seq': Seq('atggactcaaagaagagaagctcaacagaggcagaaggatccaaggaaagaggc...tag'), 'cds_start': 117, 'cds_end': 5091}]
AMT [{'transcript': 'NM_000481.4', 'protein_id': 'NP_000472.2', 'protein_seq': Seq('MQRAVSVVARLGFRLQAFPPALCRPLSCAQEVLRRTPLYDFHLAHGGKMVAFAG...TLK'), 'cds_seq': Seq('atgcagagggctgtaagtgtggtggcccgtctgggctttcgcctgcaggcattc...tga'), 'cds_start': 23, 'cds_end': 1235}]
ANK1 [{'transcript': 'NM_000037.4', 'protein_id': 'NP_000028.3', 'protein_seq': Seq('MPYSVGFREADAATSFLRAARSGNLDKALDHLRNGVDINTCNQNGLNGLHLASK...GKQ'), 'cds_seq': Seq('atgccctattctgtgggcttccgcgaagccgatgctgctaccagctttctgaga...tga'), 'cds_start': 84, 'cds_end': 5727}]
ANK2 [{'transcript': 'NM_001148.6', 'protein_id': 'NP_001139.3', 'protein_seq': Seq('MMNEDAAQKSDSGEKFNGSSQRRKRPKKSDSNASFLRAARAGNLDKVVEYLKGG...NNE'), 'cds_seq': Seq('atgatgaacgaagatgcagctcagaaaagcgacagtggagagaagttcaacggc...taa'), 'cds_start': 76, 'cds_end': 11950}]
ANKRD11 [{'transcript': 'NM_013275.6', 'protein_id': 'NP_037407.4', 'protein_seq': Seq('MPKGGCPKAPQQEELPLSSDMVEKQTGKKDKDKVSLTKTPKLERGDGGKEVRER...LPA'), 'cds_seq': Seq('atgcccaagggtgggtgccctaaagcaccacagcaggaagagcttcccctcagc...tga'), 'cds_start': 461, 'cds_end': 8453}]
ANO5 [{'transcript': 'NM_213599.3', 'protein_id': 'NP_998764.1', 'protein_seq': Seq('MGDPDLLEVLAEEGEKVNKHIDYSFQMSEQSLSSRETSFLINEETMPAKRFNLF...STL'), 'cds_seq': Seq('atgggcgacccggatctcctggaagtgttggcggaggaaggggaaaaagtcaat...taa'), 'cds_start': 408, 'cds_end': 3150}]
ANOS1 [{'transcript': 'NM_000216.4', 'protein_id': 'NP_000207.2', 'protein_seq': Seq('MVPGVPGAVLTLCLWLAASSGCLAAGPGAAAARRLDESLSAGSVQRARCASRCL...ERY'), 'cds_seq': Seq('atggtgcccggggtgcccggcgcggtcctgaccctctgcctctggctggcggcc...taa'), 'cds_start': 101, 'cds_end': 2144}]
APC [{'transcript': 'NM_000038.6', 'protein_id': 'NP_000029.2', 'protein_seq': Seq('MAAASYDQLLKQVEALKMENSNLRQELEDNSNHLTKLETEASNMKEVLKQLQGS...TSV'), 'cds_seq': Seq('atggctgcagcttcatatgatcagttgttaaagcaagttgaggcactgaagatg...taa'), 'cds_start': 59, 'cds_end': 8591}]
APC [{'transcript': 'NM_001127510.3', 'protein_id': 'NP_001120982.1', 'protein_seq': Seq('MAAASYDQLLKQVEALKMENSNLRQELEDNSNHLTKLETEASNMKEVLKQLQGS...TSV'), 'cds_seq': Seq('atggctgcagcttcatatgatcagttgttaaagcaagttgaggcactgaagatg...taa'), 'cds_start': 167, 'cds_end': 8699}]
APC [{'transcript': 'NM_001127511.3', 'protein_id': 'NP_001120983.2', 'protein_seq': Seq('MYASLGSGPVAPLPASVPPSVLGSWSTGGSRSCVRQETKSPGGARTSGHWASVW...TSV'), 'cds_seq': Seq('atgtacgcctccctgggctcgggtccggtcgcccctttgcccgcttctgtacca...taa'), 'cds_start': 220, 'cds_end': 8698}]
APOB [{'transcript': 'NM_000384.3', 'protein_id': 'NP_000375.3', 'protein_seq': Seq('MDPPRPALLALLALPALLLLLLAGARAEEEMLENVSLVCPKDATRFKHLRKYTY...IIL'), 'cds_seq': Seq('atggacccgccgaggcccgcgctgctggcgctgctggcgctgcctgcgctgctg...taa'), 'cds_start': 128, 'cds_end': 13820}]
APRT [{'transcript': 'NM_000485.3', 'protein_id': 'NP_000476.1', 'protein_seq': Seq('MADSELQLVEQRIRSFPDFPTPGVVFRDISPVLKDPASFRAAIGLLARHLKATH...QYE'), 'cds_seq': Seq('atggccgactccgagctgcagctggttgagcagcggatccgcagcttccccgac...tga'), 'cds_start': 29, 'cds_end': 572}]
AQP2 [{'transcript': 'NM_000486.6', 'protein_id': 'NP_000477.1', 'protein_seq': Seq('MWELRSIAFSRAVFAEFLATLLFVFFGLGSALNWPQALPSVLQIAMAFGLGIGT...TKA'), 'cds_seq': Seq('atgtgggagctccgctccatagccttctccagggctgtgttcgcagagttcctg...tga'), 'cds_start': 94, 'cds_end': 910}]
AR [{'transcript': 'NM_000044.6', 'protein_id': 'NP_000035.2', 'protein_seq': Seq('MEVQLGLGRVYPRPPSKTYRGAFQNLFQSVREVIQNPGPRHPEAASAAPPGASL...HTQ'), 'cds_seq': Seq('atggaagtgcagttagggctgggaagggtctaccctcggccgccgtccaagacc...tga'), 'cds_start': 1126, 'cds_end': 3889}]
ARG1 [{'transcript': 'NM_000045.4', 'protein_id': 'NP_000036.2', 'protein_seq': Seq('MSAKSRTIGIIGAPFSKGQPRGGVEEGPTVLRKAGLLEKLKEQECDVKDYGDLP...PPK'), 'cds_seq': Seq('atgagcgccaagtccagaaccatagggattattggagctcctttctcaaaggga...taa'), 'cds_start': 57, 'cds_end': 1026}]
ARID1A [{'transcript': 'NM_006015.6', 'protein_id': 'NP_006006.3', 'protein_seq': Seq('MAAQVAPAAASSLGNPPPPPPSELKKAEQQQREEAGGEAAAAAAAERGEMKAAA...GQS'), 'cds_seq': Seq('atggccgcgcaggtcgcccccgccgccgccagcagcctgggcaacccgccgccg...tga'), 'cds_start': 389, 'cds_end': 7247}]
ARID1B [{'transcript': 'NM_001374828.1', 'protein_id': 'NP_001361757.1', 'protein_seq': Seq('MAARAAAAAAAAAARARARAGSGERRAPPGPRPAPGARDLEAGARGAAAAAAAP...GQL'), 'cds_seq': Seq('atggccgcgcgggcagcagcggcggcggcggcggcggcggcgcgggcgcgggcg...tga'), 'cds_start': 303, 'cds_end': 7422}]
ARSA [{'transcript': 'NM_000487.6', 'protein_id': 'NP_000478.3', 'protein_seq': Seq('MSMGAPRSLLLALAAGLAVARPPNIVLIFADDLGYGDLGCYGHPSSTTPNLDQL...PHA'), 'cds_seq': Seq('atgtccatgggggcaccgcggtccctcctcctggccctggctgctggcctggcc...tga'), 'cds_start': 373, 'cds_end': 1903}]
ARSB [{'transcript': 'NM_000046.5', 'protein_id': 'NP_000037.2', 'protein_seq': Seq('MGPRGAASLPRGPGPRRLLLPVVLPLLLLLLLAPPGSGAGASRPPHLVFLLADD...PWM'), 'cds_seq': Seq('atgggtccgcgcggcgcggcgagcttgccccgaggccccggacctcggcggctg...tag'), 'cds_start': 62, 'cds_end': 1664}]
ARX [{'transcript': 'NM_139058.3', 'protein_id': 'NP_620689.1', 'protein_seq': Seq('MSNQYQEEGCSERPECKSKSPTLLSSYCIDSILGRRSPCKMRLLGAAQSLPAPL...EVC'), 'cds_seq': Seq('atgagcaatcagtaccaggaggagggctgctccgagaggcccgagtgcaaaagt...taa'), 'cds_start': 228, 'cds_end': 1917}]

In [9]:
reference_proteins

{'AAAS': [[{'transcript': 'NM_015665.6',
    'protein_id': 'NP_056480.1',
    'protein_seq': Seq('MCSLGLFPPPPPRGQVTLYEHNNELVTGSSYESPPPDFRGQWINLPVLQLTKDP...SHL'),
    'cds_seq': Seq('atgtgctctctggggttgttccctcctccaccgcctcggggtcaagtcacccta...taa'),
    'cds_start': 145,
    'cds_end': 1786}]],
 'ABCA1': [[{'transcript': 'NM_005502.4',
    'protein_id': 'NP_005493.2',
    'protein_seq': Seq('MACWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILISVRLSYPPYEQHEC...SYV'),
    'cds_seq': Seq('atggcttgttggcctcagctgaggttgctgctgtggaagaacctcactttcaga...tga'),
    'cds_start': 313,
    'cds_end': 7099}]],
 'ABCA12': [[{'transcript': 'NM_173076.3',
    'protein_id': 'NP_775099.2',
    'protein_seq': Seq('MASLFHQLQILVWKNWLGVKRQPLWTLVLILWPVIIFIILAITRTKFPPTAKPT...MES'),
    'cds_seq': Seq('atggcttccctgtttcatcagcttcagatcctggtctggaaaaattggctaggt...taa'),
    'cds_start': 418,
    'cds_end': 8206}]],
 'ABCA3': [[{'transcript': 'NM_001089.3',
    'protein_id': 'NP_001080.2',
    'protein_seq': Seq('MAVLRQLALLLWKNYTLQKRKVLVTVLELFLPLLFSGILIWLRLKIQSENVPNA...EGR'),
    'cds_seq': Seq('atggctgtgctcaggcagctggcgctcctcctctggaagaactacaccctgcag...tga'),
    'cds_start': 694,
    'cds_end': 5809}]],
 'ABCA4': [[{'transcript': 'NM_000350.3',
    'protein_id': 'NP_000341.2',
    'protein_seq': Seq('MGFVRQIQLLLWKNWTLRKRQKIRFVVELVWPLSLFLVLIWLRNANPLYSHHEC...AQD'),
    'cds_seq': Seq('atgggcttcgtgagacagatacagcttttgctctggaagaactggaccctgcgg...tga'),
    'cds_start': 103,
    'cds_end': 6925}]],
 'ABCB11': [[{'transcript': 'NM_003742.4',
    'protein_id': 'NP_003733.2',
    'protein_seq': Seq('MSDSVILRSIKKFGEENDGFESDKSYNNDKKSRLQDEKKGDGVRVGFFQLFRFS...PIS'),
    'cds_seq': Seq('atgtctgactcagtaattcttcgaagtataaagaaatttggagaggagaatgat...tga'),
    'cds_start': 127,
    'cds_end': 4093}]],
 'ABCB4': [[{'transcript': 'NM_000443.4',
    'protein_id': 'NP_000434.1',
    'protein_seq': Seq('MDLEAAKNGTAWRPTSAEGDFELGISSKQKRKKTKTVKMIGVLTLFRYSDWQDK...QNL'),
    'cds_seq': Seq('atggatcttgaggcggcaaagaacggaacagcctggcgccccacgagcgcggag...tga'),
    'cds_start': 53,
    'cds_end': 3893}]],
 'ABCC2': [[{'transcript': 'NM_000392.5',
    'protein_id': 'NP_000383.2',
    'protein_seq': Seq('MLEKFCNSTFWNSSFLDSPEADLPLCFEQTVLVWIPLGYLWLLAPWQLLHVYKS...TKF'),
    'cds_seq': Seq('atgctggagaagttctgcaactctactttttggaattcctcattcctggacagt...tag'),
    'cds_start': 205,
    'cds_end': 4843}]],
 'ABCC6': [[{'transcript': 'NM_001171.6',
    'protein_id': 'NP_001162.5',
    'protein_seq': Seq('MAAPAEPCAGQGVWNQTEPEPAATSLLSLCFLRTAGVWVPPMYLWVLGPIYLLF...GLV'),
    'cds_seq': Seq('atggccgcgcctgctgagccctgcgcggggcagggggtctggaaccagacagag...tga'),
    'cds_start': 60,
    'cds_end': 4572}]],
 'ABCC8': [[{'transcript': 'NM_000352.6',
    'protein_id': 'NP_000343.2',
    'protein_seq': Seq('MPLAFCGSENHSAAYRVDQGVLNNGCFVDALNVVPHVFLLFITFPILFIGWGSQ...ADK'),
    'cds_seq': Seq('atgcccctggccttctgcggcagcgagaaccactcggccgcctaccgggtggac...tga'),
    'cds_start': 69,
    'cds_end': 4815}]],
 'ABCC9': [[{'transcript': 'NM_020297.4',
    'protein_id': 'NP_064693.2',
    'protein_seq': Seq('MSLSFCGNNISSYNINDGVLQNSCFVDALNLVPHVFLLFITFPILFIGWGSQSS...ADM'),
    'cds_seq': Seq('atgagcctttcattttgtggtaacaacatttcttcatataatatcaacgatggt...tga'),
    'cds_start': 363,
    'cds_end': 5013}]],
 'ABCD1': [[{'transcript': 'NM_000033.4',
    'protein_id': 'NP_000024.2',
    'protein_seq': Seq('MPVLSRPRPWRGNTLKRTAVLLALAAYGAHKVYPLVRQCLAPARGLQAPAGEPT...AST'),
    'cds_seq': Seq('atgccggtgctctccaggccccggccctggcgggggaacacgctgaagcgcacg...tga'),
    'cds_start': 411,
    'cds_end': 2649}]],
 'ACAD9': [[{'transcript': 'NM_014049.4',
    'protein_id': 'NP_054768.2',
    'protein_seq': Seq('MSGCGLFLRTTAAARACRGLVVSTANRRLLRTSPPVRAFAKELFLGKIKKKEVF...RTC'),
    'cds_seq': Seq('atgagcggctgcgggctcttcctgcgcaccacggctgcggctcgtgcctgccgg...tga'),
    'cds_start': 202,
    'cds_end': 2068}],
  [{'transcript': 'NM_014049.5',
    'protein_id': 'NP_054768.2',
    'protein_seq': Seq('MSGCGLFLRTTAAARACRGLVVSTANRRLLRTSPPVRAFAKELFLGKIKKKEVF...RTC'),
    'cds_seq': Seq('atgagcggctgcgggctcttcctgcgcaccacggctgcggctcgtgcctgccgg...tga'),
    'cds_start': 72,
    'cds_end': 1938}]],
 'ACADM': [[{'transcript': 'NM_000016.6',
    'protein_id': 'NP_000007.1',
    'protein_seq': Seq('MAAGFGRCCRVLRSISRFHWRSQHTKANRQREPGLGFSFEFTEQQKEFQATARK...YKN'),
    'cds_seq': Seq('atggcagcggggttcgggcgatgctgcagggtcctgagaagtatttctcgtttt...taa'),
    'cds_start': 79,
    'cds_end': 1345}]],
 'ACADS': [[{'transcript': 'NM_000017.4',
    'protein_id': 'NP_000008.1',
    'protein_seq': Seq('MAAALLARASGPARRALCPRAWRQLHTIYQSVELPETHQMLLQTCRDFAEKELF...YRS'),
    'cds_seq': Seq('atggccgccgcgctgctcgcccgggcctcgggccctgcccgcagagctctctgt...tga'),
    'cds_start': 60,
    'cds_end': 1299}]],
 'ACADVL': [[{'transcript': 'NM_000018.4',
    'protein_id': 'NP_000009.1',
    'protein_seq': Seq('MQAARMAASLGRQLLRLGGGSSRLTALLGQPRPGPARRPYAGGAAQLALDKSDS...LGF'),
    'cds_seq': Seq('atgcaggcggctcggatggccgcgagcttggggcggcagctgctgaggctcggg...tga'),
    'cds_start': 47,
    'cds_end': 2015}]],
 'ACAN': [[{'transcript': 'NM_001369268.1',
    'protein_id': 'NP_001356197.1',
    'protein_seq': Seq('MTTLLWVFVTLRVITAAVTVETSDHDNSLSVSIPQPSPLRVLLGTSLTIPCYFI...TAH'),
    'cds_seq': Seq('atgaccactttactctgggttttcgtgactctgagggtcatcactgcagctgtc...tga'),
    'cds_start': 381,
    'cds_end': 8088}]],
 'ACAT1': [[{'transcript': 'NM_000019.4',
    'protein_id': 'NP_000010.1',
    'protein_seq': Seq('MAVLAALLRSGARSRSPLLRRLVQEIRYVERSYVSKPTLKEVVIVSATRTPIGS...QKL'),
    'cds_seq': Seq('atggctgtgctggcggcacttctgcgcagcggcgcccgcagccgcagccccctg...tag'),
    'cds_start': 40,
    'cds_end': 1324}]],
 'ACO2': [[{'transcript': 'NM_001098.3',
    'protein_id': 'NP_001089.1',
    'protein_seq': Seq('MAPYSLLVTRLQKALGVRQYHVASVLCQRAKVAMSHFEPNEYIHYDLLEKNINI...LQQ'),
    'cds_seq': Seq('atggcgccctacagcctactggtgactcggctgcagaaagctctgggtgtgcgg...tga'),
    'cds_start': 30,
    'cds_end': 2373}]],
 'ACSF3': [[{'transcript': 'NM_001243279.3',
    'protein_id': 'NP_001230208.1',
    'protein_seq': Seq('MLPHVVLTFRRLGCALASCRLAPARHRGSGLLHTAPVARSDRSAPVFTRALAFG...HPS'),
    'cds_seq': Seq('atgctgccccatgtggtgctcaccttccggcgcctgggctgcgccttggcgtcc...tga'),
    'cds_start': 338,
    'cds_end': 2069}]],
 'ACTA1': [[{'transcript': 'NM_001100.4',
    'protein_id': 'NP_001091.1',
    'protein_seq': Seq('MCDEDETTALVCDNGSGLVKAGFAGDDAPRAVFPSIVGRPRHQGVMVGMGQKDS...KCF'),
    'cds_seq': Seq('atgtgcgacgaagacgagaccaccgccctcgtgtgcgacaatggctccggcctg...tag'),
    'cds_start': 103,
    'cds_end': 1237}]],
 'ACTB': [[{'transcript': 'NM_001101.5',
    'protein_id': 'NP_001092.1',
    'protein_seq': Seq('MDDDIAALVVDNGSGMCKAGFAGDDAPRAVFPSIVGRPRHQGVMVGMGQKDSYV...KCF'),
    'cds_seq': Seq('atggatgatgatatcgccgcgctcgtcgtcgacaacggctccggcatgtgcaag...tag'),
    'cds_start': 84,
    'cds_end': 1212}]],
 'ACTG1': [[{'transcript': 'NM_001614.5',
    'protein_id': 'NP_001605.1',
    'protein_seq': Seq('MEEEIAALVIDNGSGMCKAGFAGDDAPRAVFPSIVGRPRHQGVMVGMGQKDSYV...KCF'),
    'cds_seq': Seq('atggaagaagagatcgccgcgctggtcattgacaatggctccggcatgtgcaaa...taa'),
    'cds_start': 72,
    'cds_end': 1200}]],
 'ACVRL1': [[{'transcript': 'NM_000020.3',
    'protein_id': 'NP_000011.2',
    'protein_seq': Seq('MTLGSPRKGLLMLLMALVTQGDPVKPSRGPLVTCTCESPHCKGPTCRGAWCTVV...VIQ'),
    'cds_seq': Seq('atgaccttgggctcccccaggaaaggccttctgatgctgctgatggccttggtg...tag'),
    'cds_start': 197,
    'cds_end': 1709}]],
 'ADA': [[{'transcript': 'NM_000022.4',
    'protein_id': 'NP_000013.2',
    'protein_seq': Seq('MAQTPAFDKPKVELHVHLDGSIKPETILYYGRRRGIALPANTAEGLLNVIGMDK...QNL'),
    'cds_seq': Seq('atggcccagacgcccgccttcgacaagcccaaagtggaactgcatgtccaccta...tga'),
    'cds_start': 92,
    'cds_end': 1184}]],
 'ADA2': [[{'transcript': 'NM_001282225.2',
    'protein_id': 'NP_001269154.1',
    'protein_seq': Seq('MLVDGPSERPALCFLLLAVAMSFFGSALSIDETRAHLLLKEKMMRLGGRLVLNT...ATK'),
    'cds_seq': Seq('atgttggtggatggcccatctgagcggccagccctgtgcttcttgctgttggct...tga'),
    'cds_start': 126,
    'cds_end': 1662}]],
 'ADAMTS13': [[{'transcript': 'NM_139027.6',
    'protein_id': 'NP_620596.2',
    'protein_seq': Seq('MHQRHPRARCPPLCVAGILACGFLLGCWGPSHFQQSCLQALEPQAVSSYLSPGA...EGT'),
    'cds_seq': Seq('atgcaccagcgtcacccccgggcaagatgccctcccctctgtgtggccggaatc...tga'),
    'cds_start': 77,
    'cds_end': 4193}]],
 'ADAMTS2': [[{'transcript': 'NM_014244.5',
    'protein_id': 'NP_055059.2',
    'protein_seq': Seq('MDPPAGAARRLLCPALLLLLLLLPPPLLPPPPPPANARLAAAADPPGGPLGHGA...GKF'),
    'cds_seq': Seq('atggatccgccggcgggagccgctcgccgcctgctctgccccgcgctgctgctg...taa'),
    'cds_start': 133,
    'cds_end': 3769}]],
 'ADAMTSL4': [[{'transcript': 'NM_019032.6',
    'protein_id': 'NP_061905.2',
    'protein_seq': Seq('MENWTGRPWLYLLLLLSLPQLCLDQEVLSGHSLQTPTEEGQGPEGVWGPWVQWA...DPS'),
    'cds_seq': Seq('atggagaactggactggcaggccctggctgtatctgctgctgcttctgtccctc...tga'),
    'cds_start': 250,
    'cds_end': 3475}]],
 'ADAR': [[{'transcript': 'NM_001111.5',
    'protein_id': 'NP_001102.3',
    'protein_seq': Seq('MNPRQGYSLSGYYTHPFQGYEHRQLRYQQPGPGSSPSSFLLKQIEFLKGQLPEA...CPV'),
    'cds_seq': Seq('atgaatccgcggcaggggtattccctcagcggatactacacccatccatttcaa...tag'),
    'cds_start': 180,
    'cds_end': 3861}]],
 'ADGRG1': [[{'transcript': 'NM_201525.4',
    'protein_id': 'NP_958933.1',
    'protein_seq': Seq('MTPQSLLQTTLFLLSLLFLVQGAHGRGHREDFRFCSQRNQTHRSSLHYKPTPDL...SRI'),
    'cds_seq': Seq('atgactccccagtcgctgctgcagacgacactgttcctgctgagtctgctcttc...tag'),
    'cds_start': 208,
    'cds_end': 2272}]],
 'ADGRV1': [[{'transcript': 'NM_032119.4',
    'protein_id': 'NP_115495.3',
    'protein_seq': Seq('MSVFLGPGMPSASLLVNLLSALLILFVFGETEIRFTGQTEFVVNETSTTVIRLI...THL'),
    'cds_seq': Seq('atgtcggtgttcctggggccagggatgccctctgcatctttattagtaaatctt...tag'),
    'cds_start': 99,
    'cds_end': 19020}]],
 'ADNP': [[{'transcript': 'NM_001282531.3',
    'protein_id': 'NP_001269460.1',
    'protein_seq': Seq('MFQLPVNNLGSLRKARKTVKKILSDIGLEYCKEHIEDFKQFEPNDFYLKNTTWE...QQA'),
    'cds_seq': Seq('atgttccaacttcctgtcaacaatcttggcagtttaagaaaagcccggaaaact...taa'),
    'cds_start': 876,
    'cds_end': 4185}]],
 'ADSL': [[{'transcript': 'NM_000026.4',
    'protein_id': 'NP_000017.1',
    'protein_seq': Seq('MAAGGDHGSPDSYRSPLASRYASPEMCFVFSDRYKFRTWRQLWLWLAEAEQTLG...LCL'),
    'cds_seq': Seq('atggcggctggaggcgatcatggttcgcccgacagctaccgctcacctcttgcc...tag'),
    'cds_start': 59,
    'cds_end': 1514}]],
 'AFG2A': [[{'transcript': 'NM_145207.3',
    'protein_id': 'NP_660208.2',
    'protein_seq': Seq('MSSKKNRKRLNQSAENGSSLPSAASSCAEARAPSAGSDFAATSGTLTVTNLLEK...HTL'),
    'cds_seq': Seq('atgtcttccaagaagaatagaaagcggttgaaccaaagcgcggaaaatggttcg...tga'),
    'cds_start': 65,
    'cds_end': 2747}]],
 'AFG3L2': [[{'transcript': 'NM_006796.3',
    'protein_id': 'NP_006787.2',
    'protein_seq': Seq('MAHRCLRLWGRGGCWPRGLQQLLVPGGVGPGEQPCLRTLYRFVTTQARASRNSL...VAN'),
    'cds_seq': Seq('atggcgcaccgctgtttgcggctgtggggccggggcggctgctggccccgcggc...tag'),
    'cds_start': 145,
    'cds_end': 2539}]],
 'AGA': [[{'transcript': 'NM_000027.4',
    'protein_id': 'NP_000018.2',
    'protein_seq': Seq('MARKSNLPVLLVPFLLCQALVRCSSPLPLVVNTWPFKNATEAAWRALASGGSAL...DCI'),
    'cds_seq': Seq('atggcgcggaagtcgaacttgcctgtgcttctcgtgccgtttctgctctgccag...taa'),
    'cds_start': 62,
    'cds_end': 1103}]],
 'AGL': [[{'transcript': 'NM_000642.3',
    'protein_id': 'NP_000633.2',
    'protein_seq': Seq('MGHSKQIRILLLNEMEKLEKTLFRLEQGYELQFRLGPTLQGKAVTVYTNYPFPG...YDL'),
    'cds_seq': Seq('atgggacacagtaaacagattcgaattttacttctgaacgaaatggagaaactg...tag'),
    'cds_start': 123,
    'cds_end': 4722}]],
 'AGXT': [[{'transcript': 'NM_000030.3',
    'protein_id': 'NP_000021.1',
    'protein_seq': Seq('MASHKLLVTPPKALLKPLSIPNQLLLGPGPSNLPPRIMAAGGLQMIGSMSKDMY...KKL'),
    'cds_seq': Seq('atggcctctcacaagctgctggtgaccccccccaaggccctgctcaagcccctc...tga'),
    'cds_start': 42,
    'cds_end': 1221}]],
 'AHDC1': [[{'transcript': 'NM_001371928.1',
    'protein_id': 'NP_001358857.1',
    'protein_seq': Seq('MRVKPQGLVVTSSAVCSSPDYLREPKYYPGGPPTPRPLLPTRPPASPPDKAFST...TSL'),
    'cds_seq': Seq('atgcgtgtgaagccccagggcctggtggtgacttccagtgccgtgtgcagctct...tag'),
    'cds_start': 901,
    'cds_end': 5713}]],
 'AHI1': [[{'transcript': 'NM_001134831.2',
    'protein_id': 'NP_001128303.1',
    'protein_seq': Seq('MPTAESEAKVKTKVRFEELLKTHSDLMREKKKLKKKLVRSEENISPDTIRSNLH...LIE'),
    'cds_seq': Seq('atgcctacagctgagagtgaagcaaaagtaaaaaccaaagttcgctttgaagaa...taa'),
    'cds_start': 359,
    'cds_end': 3950}]],
 'AIPL1': [[{'transcript': 'NM_014336.5',
    'protein_id': 'NP_055151.3',
    'protein_seq': Seq('MDAALLLNVEGVKKTILHGGTGELPNFITGSRVIFHFRTMKCDEERTVIDDSRQ...LQH'),
    'cds_seq': Seq('atggatgccgctctgctcctgaacgtggaaggggtcaagaaaaccattctgcac...tga'),
    'cds_start': 17,
    'cds_end': 1172}]],
 'AIRE': [[{'transcript': 'NM_000383.4',
    'protein_id': 'NP_000374.1',
    'protein_seq': Seq('MATDAALRRLLRLHRTEIAVAVDSAFPLLHALADHDVVPEDKFQETLHLKEKEG...FPS'),
    'cds_seq': Seq('atggcgacggacgcggcgctacgccggcttctgaggctgcaccgcacggagatc...tga'),
    'cds_start': 131,
    'cds_end': 1769}]],
 'ALDH3A2': [[{'transcript': 'NM_000382.3',
    'protein_id': 'NP_000373.1',
    'protein_seq': Seq('MELEVRRVRQAFLSGRSRPLRFRLQQLEALRRMVQEREKDILTAIAADLCKSEF...EYY'),
    'cds_seq': Seq('atggagctcgaagtccggcgggtccgacaggcgttcctgtccggccggtcgcga...tga'),
    'cds_start': 221,
    'cds_end': 1679}]],
 'ALDH5A1': [[{'transcript': 'NM_001080.3',
    'protein_id': 'NP_001071.1',
    'protein_seq': Seq('MATCIWLRSCGARRLGSTFPGCRLRPRAGGLVPASGPAPGPAQLRCYAGRLAGL...GGL'),
    'cds_seq': Seq('atggcgacctgcatttggctgcggagctgtggggcccggcgcctcgggtcgacg...tag'),
    'cds_start': 28,
    'cds_end': 1636}]],
 'ALDH7A1': [[{'transcript': 'NM_001182.5',
    'protein_id': 'NP_001173.2',
    'protein_seq': Seq('MWRLPRALCVHAAKTSKLSGPWSRPAAFMSTLLINQPQYAWLKELGLREENEGV...KFQ'),
    'cds_seq': Seq('atgtggcgccttcctcgcgcgctgtgtgtgcacgctgcaaagaccagcaagctc...taa'),
    'cds_start': 21,
    'cds_end': 1641}]],
 'ALDOB': [[{'transcript': 'NM_000035.4',
    'protein_id': 'NP_000026.2',
    'protein_seq': Seq('MAHRFPALTQEQKKELSEIAQSIVANGKGILAADESVGTMGNRLQRIKVENTEE...YTY'),
    'cds_seq': Seq('atggcccaccgatttccagccctcacccaggagcagaagaaggagctctcagaa...tag'),
    'cds_start': 76,
    'cds_end': 1171}]],
 'ALG1': [[{'transcript': 'NM_019109.5',
    'protein_id': 'NP_061982.3',
    'protein_seq': Seq('MAASCLVLLALCLLLPLLLLGGWKRWRRGRAARHVVAVVLGDVGRSPRMQYHAL...MDT'),
    'cds_seq': Seq('atggcggcctcatgcttggtcctgctggcgctgtgtctgctgctgccgctgctg...taa'),
    'cds_start': 7,
    'cds_end': 1402}]],
 'ALG6': [[{'transcript': 'NM_013339.4',
    'protein_id': 'NP_037471.2',
    'protein_seq': Seq('MEKWYLMTVVVLIGLTVRWTVSLNSYSGAGKPPMFGDYEAQRHWQEITFNLPVK...KIS'),
    'cds_seq': Seq('atggagaaatggtacttgatgacagtagtggttttaataggactaacagtacga...tag'),
    'cds_start': 268,
    'cds_end': 1792}]],
 'ALMS1': [[{'transcript': 'NM_001378454.1',
    'protein_id': 'NP_001365383.1',
    'protein_seq': Seq('MEPEDLPWPGELEEEEEEEEEEEEEEEEAAAAAAANVDDVVVVEEVEEEAGREL...PWD'),
    'cds_seq': Seq('atggagcccgaggatctgccatggccgggcgagctggaggaggaggaggaggag...tga'),
    'cds_start': 33,
    'cds_end': 12540}]],
 'ALOX12B': [[{'transcript': 'NM_001139.3',
    'protein_id': 'NP_001130.1',
    'protein_seq': Seq('MATYKVRVATGTDLLSGTRDSISLTIVGTQGESHKQLLNHFGRDFATGAVGQYT...ISI'),
    'cds_seq': Seq('atggccacctacaaagtcagggtggccacaggcaccgacctcttgtcgggaaca...tag'),
    'cds_start': 274,
    'cds_end': 2380}]],
 'ALPK3': [[{'transcript': 'NM_020778.5',
    'protein_id': 'NP_065829.4',
    'protein_seq': Seq('MGSRRAPSRGWGAGGRSGAGGDGEDDGPVWIPSPASRSYLLSVRPETSLSSNRL...GMR'),
    'cds_seq': Seq('atggggtcgcggagggcccccagccggggctggggcgcgggtgggcggtcgggg...tag'),
    'cds_start': 97,
    'cds_end': 5215}]],
 'ALPL': [[{'transcript': 'NM_000478.6',
    'protein_id': 'NP_000469.3',
    'protein_seq': Seq('MISPFLVLAIGTCLTNSLVPEKEKDPKYWRDQAQETLKYALELQKLNTNVAKNV...VLF'),
    'cds_seq': Seq('atgatttcaccattcttagtactggccattggcacctgccttactaactcctta...tga'),
    'cds_start': 199,
    'cds_end': 1774}]],
 'ALS2': [[{'transcript': 'NM_020919.3',
    'protein_id': 'NP_065970.2',
    'protein_seq': Seq('MDSKKRSSTEAEGSKERGLVHIWQAGSFPITPERLPGWGGKTVLQAALGVKHGV...KLN'),
    'cds_seq': Seq('atggactcaaagaagagaagctcaacagaggcagaaggatccaaggaaagaggc...tag'),
    'cds_start': 356,
    'cds_end': 5330}],
  [{'transcript': 'NM_020919.4',
    'protein_id': 'NP_065970.2',
    'protein_seq': Seq('MDSKKRSSTEAEGSKERGLVHIWQAGSFPITPERLPGWGGKTVLQAALGVKHGV...KLN'),
    'cds_seq': Seq('atggactcaaagaagagaagctcaacagaggcagaaggatccaaggaaagaggc...tag'),
    'cds_start': 117,
    'cds_end': 5091}]],
 'AMT': [[{'transcript': 'NM_000481.4',
    'protein_id': 'NP_000472.2',
    'protein_seq': Seq('MQRAVSVVARLGFRLQAFPPALCRPLSCAQEVLRRTPLYDFHLAHGGKMVAFAG...TLK'),
    'cds_seq': Seq('atgcagagggctgtaagtgtggtggcccgtctgggctttcgcctgcaggcattc...tga'),
    'cds_start': 23,
    'cds_end': 1235}]],
 'ANK1': [[{'transcript': 'NM_000037.4',
    'protein_id': 'NP_000028.3',
    'protein_seq': Seq('MPYSVGFREADAATSFLRAARSGNLDKALDHLRNGVDINTCNQNGLNGLHLASK...GKQ'),
    'cds_seq': Seq('atgccctattctgtgggcttccgcgaagccgatgctgctaccagctttctgaga...tga'),
    'cds_start': 84,
    'cds_end': 5727}]],
 'ANK2': [[{'transcript': 'NM_001148.6',
    'protein_id': 'NP_001139.3',
    'protein_seq': Seq('MMNEDAAQKSDSGEKFNGSSQRRKRPKKSDSNASFLRAARAGNLDKVVEYLKGG...NNE'),
    'cds_seq': Seq('atgatgaacgaagatgcagctcagaaaagcgacagtggagagaagttcaacggc...taa'),
    'cds_start': 76,
    'cds_end': 11950}]],
 'ANKRD11': [[{'transcript': 'NM_013275.6',
    'protein_id': 'NP_037407.4',
    'protein_seq': Seq('MPKGGCPKAPQQEELPLSSDMVEKQTGKKDKDKVSLTKTPKLERGDGGKEVRER...LPA'),
    'cds_seq': Seq('atgcccaagggtgggtgccctaaagcaccacagcaggaagagcttcccctcagc...tga'),
    'cds_start': 461,
    'cds_end': 8453}]],
 'ANO5': [[{'transcript': 'NM_213599.3',
    'protein_id': 'NP_998764.1',
    'protein_seq': Seq('MGDPDLLEVLAEEGEKVNKHIDYSFQMSEQSLSSRETSFLINEETMPAKRFNLF...STL'),
    'cds_seq': Seq('atgggcgacccggatctcctggaagtgttggcggaggaaggggaaaaagtcaat...taa'),
    'cds_start': 408,
    'cds_end': 3150}]],
 'ANOS1': [[{'transcript': 'NM_000216.4',
    'protein_id': 'NP_000207.2',
    'protein_seq': Seq('MVPGVPGAVLTLCLWLAASSGCLAAGPGAAAARRLDESLSAGSVQRARCASRCL...ERY'),
    'cds_seq': Seq('atggtgcccggggtgcccggcgcggtcctgaccctctgcctctggctggcggcc...taa'),
    'cds_start': 101,
    'cds_end': 2144}]],
 'APC': [[{'transcript': 'NM_000038.6',
    'protein_id': 'NP_000029.2',
    'protein_seq': Seq('MAAASYDQLLKQVEALKMENSNLRQELEDNSNHLTKLETEASNMKEVLKQLQGS...TSV'),
    'cds_seq': Seq('atggctgcagcttcatatgatcagttgttaaagcaagttgaggcactgaagatg...taa'),
    'cds_start': 59,
    'cds_end': 8591}],
  [{'transcript': 'NM_001127510.3',
    'protein_id': 'NP_001120982.1',
    'protein_seq': Seq('MAAASYDQLLKQVEALKMENSNLRQELEDNSNHLTKLETEASNMKEVLKQLQGS...TSV'),
    'cds_seq': Seq('atggctgcagcttcatatgatcagttgttaaagcaagttgaggcactgaagatg...taa'),
    'cds_start': 167,
    'cds_end': 8699}],
  [{'transcript': 'NM_001127511.3',
    'protein_id': 'NP_001120983.2',
    'protein_seq': Seq('MYASLGSGPVAPLPASVPPSVLGSWSTGGSRSCVRQETKSPGGARTSGHWASVW...TSV'),
    'cds_seq': Seq('atgtacgcctccctgggctcgggtccggtcgcccctttgcccgcttctgtacca...taa'),
    'cds_start': 220,
    'cds_end': 8698}]],
 'APOB': [[{'transcript': 'NM_000384.3',
    'protein_id': 'NP_000375.3',
    'protein_seq': Seq('MDPPRPALLALLALPALLLLLLAGARAEEEMLENVSLVCPKDATRFKHLRKYTY...IIL'),
    'cds_seq': Seq('atggacccgccgaggcccgcgctgctggcgctgctggcgctgcctgcgctgctg...taa'),
    'cds_start': 128,
    'cds_end': 13820}]],
 'APRT': [[{'transcript': 'NM_000485.3',
    'protein_id': 'NP_000476.1',
    'protein_seq': Seq('MADSELQLVEQRIRSFPDFPTPGVVFRDISPVLKDPASFRAAIGLLARHLKATH...QYE'),
    'cds_seq': Seq('atggccgactccgagctgcagctggttgagcagcggatccgcagcttccccgac...tga'),
    'cds_start': 29,
    'cds_end': 572}]],
 'AQP2': [[{'transcript': 'NM_000486.6',
    'protein_id': 'NP_000477.1',
    'protein_seq': Seq('MWELRSIAFSRAVFAEFLATLLFVFFGLGSALNWPQALPSVLQIAMAFGLGIGT...TKA'),
    'cds_seq': Seq('atgtgggagctccgctccatagccttctccagggctgtgttcgcagagttcctg...tga'),
    'cds_start': 94,
    'cds_end': 910}]],
 'AR': [[{'transcript': 'NM_000044.6',
    'protein_id': 'NP_000035.2',

In [ ]:

## ignore
loci = ["ALPL", "ABCD1", "CFTR"]
for gene in loci:
    for transcript in gene_transcripts[gene]:
        #print(transcript)
        prot = get_reference_proteins(gene, transcript)
        print(gene, prot)

ALPL [{'transcript': 'NM_000478.6', 'protein_id': 'NP_000469.3', 'protein_seq': Seq('MISPFLVLAIGTCLTNSLVPEKEKDPKYWRDQAQETLKYALELQKLNTNVAKNV...VLF'), 'cds_seq': Seq('atgatttcaccattcttagtactggccattggcacctgccttactaactcctta...tga'), 'cds_start': 199, 'cds_end': 1774}]
ABCD1 [{'transcript': 'NM_000033.4', 'protein_id': 'NP_000024.2', 'protein_seq': Seq('MPVLSRPRPWRGNTLKRTAVLLALAAYGAHKVYPLVRQCLAPARGLQAPAGEPT...AST'), 'cds_seq': Seq('atgccggtgctctccaggccccggccctggcgggggaacacgctgaagcgcacg...tga'), 'cds_start': 411, 'cds_end': 2649}]
CFTR [{'transcript': 'NM_000492.3', 'protein_id': 'NP_000483.3', 'protein_seq': Seq('MQRSPLEKASVVSKLFFSWTRPILRKGYRQRLELSDIYQIPSVDSADNLSEKLE...TRL'), 'cds_seq': Seq('atgcagaggtcgcctctggaaaaggccagcgttgtctccaaactttttttcagc...tag'), 'cds_start': 132, 'cds_end': 4575}]
CFTR [{'transcript': 'NM_000492.4', 'protein_id': 'NP_000483.3', 'protein_seq': Seq('MQRSPLEKASVVSKLFFSWTRPILRKGYRQRLELSDIYQIPSVDSADNLSEKLE...TRL'), 'cds_seq': Seq('atgcagaggtcgcctctggaaaaggccagcgttgtctccaaactttttttcagc...tag'), 'cds_start': 70, 'cds_end': 4513}]

### STEP 3   Finding the most similar *species* sequence to the reference human sequence

The following defines a pairwise aligner object using the Needleman-Wunsch
algorithm using the default `blastp` scoring scheme and substitution matrix.

In [10]:
from Bio import SeqIO, Align
from Bio.Seq import Seq

In [11]:
aligner = Align.PairwiseAligner(scoring="blastp")
print(aligner)

Pairwise sequence aligner with parameters
  substitution_matrix: <Array object at 0x16f603d90>
  open_internal_insertion_score: -12.000000
  extend_internal_insertion_score: -1.000000
  open_left_insertion_score: -12.000000
  extend_left_insertion_score: -1.000000
  open_right_insertion_score: -12.000000
  extend_right_insertion_score: -1.000000
  open_internal_deletion_score: -12.000000
  extend_internal_deletion_score: -1.000000
  open_left_deletion_score: -12.000000
  extend_left_deletion_score: -1.000000
  open_right_deletion_score: -12.000000
  extend_right_deletion_score: -1.000000
  mode: global

In [13]:
print(aligner.substitution_matrix[:, :])

     A    B    C    D    E    F    G    H    I    J    K    L    M    N    O    P    Q    R    S    T    U    V    W    X    Y    Z    *
A  4.0 -2.0  0.0 -2.0 -1.0 -2.0  0.0 -2.0 -1.0 -1.0 -1.0 -1.0 -1.0 -2.0 -1.0 -1.0 -1.0 -1.0  1.0  0.0  0.0  0.0 -3.0 -1.0 -2.0 -1.0 -4.0
B -2.0  4.0 -3.0  4.0  1.0 -3.0 -1.0  0.0 -3.0 -3.0  0.0 -4.0 -3.0  4.0 -1.0 -2.0  0.0 -1.0  0.0 -1.0 -3.0 -3.0 -4.0 -1.0 -3.0  0.0 -4.0
C  0.0 -3.0  9.0 -3.0 -4.0 -2.0 -3.0 -3.0 -1.0 -1.0 -3.0 -1.0 -1.0 -3.0 -1.0 -3.0 -3.0 -3.0 -1.0 -1.0  9.0 -1.0 -2.0 -1.0 -2.0 -3.0 -4.0
D -2.0  4.0 -3.0  6.0  2.0 -3.0 -1.0 -1.0 -3.0 -3.0 -1.0 -4.0 -3.0  1.0 -1.0 -1.0  0.0 -2.0  0.0 -1.0 -3.0 -3.0 -4.0 -1.0 -3.0  1.0 -4.0
E -1.0  1.0 -4.0  2.0  5.0 -3.0 -2.0  0.0 -3.0 -3.0  1.0 -3.0 -2.0  0.0 -1.0 -1.0  2.0  0.0  0.0 -1.0 -4.0 -2.0 -3.0 -1.0 -2.0  4.0 -4.0
F -2.0 -3.0 -2.0 -3.0 -3.0  6.0 -3.0 -1.0  0.0  0.0 -3.0  0.0  0.0 -3.0 -1.0 -4.0 -3.0 -3.0 -2.0 -2.0 -2.0 -1.0  1.0 -1.0  3.0 -3.0 -4.0
G  0.0 -1.0 -3.0 -1.0 -2.0 -3.0  6.0 -2.0 -4.0 -4.0 -2.0 -4.0 -3.0  0.0 -1.0 -2.0 -2.0 -2.0  0.0 -2.0 -3.0 -3.0 -2.0 -1.0 -3.0 -2.0 -4.0
H -2.0  0.0 -3.0 -1.0  0.0 -1.0 -2.0  8.0 -3.0 -3.0 -1.0 -3.0 -2.0  1.0 -1.0 -2.0  0.0  0.0 -1.0 -2.0 -3.0 -3.0 -2.0 -1.0  2.0  0.0 -4.0
I -1.0 -3.0 -1.0 -3.0 -3.0  0.0 -4.0 -3.0  4.0  3.0 -3.0  2.0  1.0 -3.0 -1.0 -3.0 -3.0 -3.0 -2.0 -1.0 -1.0  3.0 -3.0 -1.0 -1.0 -3.0 -4.0
J -1.0 -3.0 -1.0 -3.0 -3.0  0.0 -4.0 -3.0  3.0  3.0 -3.0  3.0  2.0 -3.0 -1.0 -3.0 -2.0 -2.0 -2.0 -1.0 -1.0  2.0 -2.0 -1.0 -1.0 -3.0 -4.0
K -1.0  0.0 -3.0 -1.0  1.0 -3.0 -2.0 -1.0 -3.0 -3.0  5.0 -2.0 -1.0  0.0 -1.0 -1.0  1.0  2.0  0.0 -1.0 -3.0 -2.0 -3.0 -1.0 -2.0  1.0 -4.0
L -1.0 -4.0 -1.0 -4.0 -3.0  0.0 -4.0 -3.0  2.0  3.0 -2.0  4.0  2.0 -3.0 -1.0 -3.0 -2.0 -2.0 -2.0 -1.0 -1.0  1.0 -2.0 -1.0 -1.0 -3.0 -4.0
M -1.0 -3.0 -1.0 -3.0 -2.0  0.0 -3.0 -2.0  1.0  2.0 -1.0  2.0  5.0 -2.0 -1.0 -2.0  0.0 -1.0 -1.0 -1.0 -1.0  1.0 -1.0 -1.0 -1.0 -1.0 -4.0
N -2.0  4.0 -3.0  1.0  0.0 -3.0  0.0  1.0 -3.0 -3.0  0.0 -3.0 -2.0  6.0 -1.0 -2.0  0.0  0.0  1.0  0.0 -3.0 -3.0 -4.0 -1.0 -2.0  0.0 -4.0
O -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -4.0
P -1.0 -2.0 -3.0 -1.0 -1.0 -4.0 -2.0 -2.0 -3.0 -3.0 -1.0 -3.0 -2.0 -2.0 -1.0  7.0 -1.0 -2.0 -1.0 -1.0 -3.0 -2.0 -4.0 -1.0 -3.0 -1.0 -4.0
Q -1.0  0.0 -3.0  0.0  2.0 -3.0 -2.0  0.0 -3.0 -2.0  1.0 -2.0  0.0  0.0 -1.0 -1.0  5.0  1.0  0.0 -1.0 -3.0 -2.0 -2.0 -1.0 -1.0  4.0 -4.0
R -1.0 -1.0 -3.0 -2.0  0.0 -3.0 -2.0  0.0 -3.0 -2.0  2.0 -2.0 -1.0  0.0 -1.0 -2.0  1.0  5.0 -1.0 -1.0 -3.0 -3.0 -3.0 -1.0 -2.0  0.0 -4.0
S  1.0  0.0 -1.0  0.0  0.0 -2.0  0.0 -1.0 -2.0 -2.0  0.0 -2.0 -1.0  1.0 -1.0 -1.0  0.0 -1.0  4.0  1.0 -1.0 -2.0 -3.0 -1.0 -2.0  0.0 -4.0
T  0.0 -1.0 -1.0 -1.0 -1.0 -2.0 -2.0 -2.0 -1.0 -1.0 -1.0 -1.0 -1.0  0.0 -1.0 -1.0 -1.0 -1.0  1.0  5.0 -1.0  0.0 -2.0 -1.0 -2.0 -1.0 -4.0
U  0.0 -3.0  9.0 -3.0 -4.0 -2.0 -3.0 -3.0 -1.0 -1.0 -3.0 -1.0 -1.0 -3.0 -1.0 -3.0 -3.0 -3.0 -1.0 -1.0  9.0 -1.0 -2.0 -1.0 -2.0 -3.0 -4.0
V  0.0 -3.0 -1.0 -3.0 -2.0 -1.0 -3.0 -3.0  3.0  2.0 -2.0  1.0  1.0 -3.0 -1.0 -2.0 -2.0 -3.0 -2.0  0.0 -1.0  4.0 -3.0 -1.0 -1.0 -2.0 -4.0
W -3.0 -4.0 -2.0 -4.0 -3.0  1.0 -2.0 -2.0 -3.0 -2.0 -3.0 -2.0 -1.0 -4.0 -1.0 -4.0 -2.0 -3.0 -3.0 -2.0 -2.0 -3.0 11.0 -1.0  2.0 -2.0 -4.0
X -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -4.0
Y -2.0 -3.0 -2.0 -3.0 -2.0  3.0 -3.0  2.0 -1.0 -1.0 -2.0 -1.0 -1.0 -2.0 -1.0 -3.0 -1.0 -2.0 -2.0 -2.0 -2.0 -1.0  2.0 -1.0  7.0 -2.0 -4.0
Z -1.0  0.0 -3.0  1.0  4.0 -3.0 -2.0  0.0 -3.0 -3.0  1.0 -3.0 -1.0  0.0 -1.0 -1.0  4.0  0.0  0.0 -1.0 -3.0 -2.0 -2.0 -1.0 -2.0  4.0 -4.0
* -4.0 -4.0 -4.0 -4.0 -4.0 -4.0 -4.0 -4.0 -4.0 -4.0 -4.0 -4.0 -4.0 -4.0 -4.0 -4.0 -4.0 -4.0 -4.0 -4.0 -4.0 -4.0 -4.0 -4.0 -4.0 -4.0  1.0

### The function 'write_best_species_matches' extracts the highest-scoring sequence per unique species from the fasta file (fasta/{gene}.fasta) and writes a new file (fasta/{gene}_match.fasta)

In [9]:
run kondrashov

In [ ]:
len(lociii)

174

In [24]:
# trial run
best = write_best_species_matches(gene="AAAS", reference_seq= 'NP_056480.1', aligner=aligner, outfile=f"XXX_match.fasta")

ValueError: sequence contains letters not in the alphabet

### Some some transcripts encode protein that are identical but have different accession id, this could be because they exist at different coding regions 
#### e.g G6PD  NM_001042351.3 → NP_001035810.1; NM_001360016.2 → NP_001346945.1 different accession ids, identical protein sequence

#### I'll delete 'G6PD_NP_001346945.1_match.fasta' because the reference seq (i.e No. 1) is replaced with its identical protein 'NP_001035810.1'

In [ ]:
# compare the protein sequences directly
prot1 = reference_proteins["G6PD"][1][0]["protein_seq"]
prot2 = reference_proteins["G6PD"][2][0]["protein_seq"]

print(prot1 == prot2)

True

In [ ]:
# compare the coding sequences
cds1 = reference_proteins["G6PD"][1][0]["cds_seq"]
cds2 = reference_proteins["G6PD"][2][0]["cds_seq"]

print(cds1 == cds2)

True

In [ ]:
lociii

['ABCA12',
 'ABCD1',
 'ACAD9',
 'ACADM',
 'ACADVL',
 'ACAT1',
 'ADA',
 'AGL',
 'AGXT',
 'AHI1',
 'AIRE',
 'ALMS1',
 'ALOX12B',
 'ALPL',
 'ANK1',
 'ANO5',
 'APC',
 'AR',
 'ARSA',
 'ARSB',
 'ASL',
 'ASPA',
 'ASPM',
 'ATM',
 'ATP7B',
 'BBS2',
 'BCKDHA',
 'BEST1',
 'BLM',
 'BRIP1',
 'BTD',
 'BTK',
 'CASR',
 'CBS',
 'CC2D2A',
 'CDH23',
 'CEP290',
 'CERKL',
 'CFTR',
 'CHD7',
 'CHEK2',
 'CLN3',
 'CNGB3',
 'CPS1',
 'CRB1',
 'CTNS',
 'CYBB',
 'CYP11B1',
 'CYP17A1',
 'CYP27A1',
 'DCLRE1C',
 'DICER1',
 'DUOX2',
 'EHMT1',
 'ELP1',
 'ERCC6',
 'EVC',
 'EVC2',
 'EXT1',
 'EXT2',
 'EYS',
 'F7',
 'F8',
 'F9',
 'FANCA',
 'FANCI',
 'FBN2',
 'FKRP',
 'FLCN',
 'FRAS1',
 'G6PD',
 'GAA',
 'GALC',
 'GALNS',
 'GALT',
 'GBA1',
 'GBE1',
 'GCDH',
 'GJB1',
 'GLB1',
 'GNE',
 'GNPTAB',
 'HBB',
 'HEXA',
 'HEXB',
 'HGD',
 'HGSNAT',
 'HMBS',
 'HPRT1',
 'HPS3',
 'IL2RG',
 'ITGA2B',
 'IVD',
 'KCNH2',
 'KCNQ1',
 'KRIT1',
 'L1CAM',
 'LDLR',
 'LIPA',
 'LOXHD1',
 'LPL',
 'LRPPRC',
 'LYST',
 'MAN2B1',
 'MCCC1',
 'MCCC2',
 'MED13L',
 'MFN2',
 'MKS1',
 'MMUT',
 'MPZ',
 'MSH2',
 'MTHFR',
 'MUTYH',
 'MYH7',
 'NAGLU',
 'NF1',
 'NF2',
 'NIPBL',
 'NPC1',
 'NSD1',
 'OCA2',
 'OPA1',
 'PAH',
 'PALB2',
 'PAX3',
 'PAX6',
 'PCDH15',
 'PCNT',
 'PKHD1',
 'PMM2',
 'POMGNT1',
 'PRPF31',
 'PYGM',
 'RAD50',
 'RARS2',
 'RECQL4',
 'RHO',
 'RP1',
 'RPGRIP1L',
 'SACS',
 'SATB2',
 'SCN4A',
 'SERPING1',
 'SGSH',
 'SI',
 'SLC12A6',
 'SLC25A13',
 'SLC26A4',
 'SMPD1',
 'SPAST',
 'SPG11',
 'SYNE1',
 'TCIRG1',
 'TMC1',
 'TMEM67',
 'TP53',
 'TPP1',
 'TSC1',
 'TTR',
 'TYR',
 'UNC13D',
 'USH1C',
 'USH2A',
 'VHL',
 'VPS13A',
 'VPS13B',
 'VWF',
 'WFS1',
 'WRN',
 'WT1',
 'XPC',
 'ZEB2',
 'ZFYVE26']

## Run this

In [ ]:
reference_proteins["ABCD1"]
#reference_proteins
#reference_proteins["ABCD1"][0][0]["protein_seq"]
len(reference_proteins["ABCD1"][0][0]["protein_seq"])
#reference_proteins["ABCD1"][0][0]["cds_seq"]
#len(reference_proteins["ABCD1"][0][]["cds_seq"])

745

In [19]:
reference_proteins= {'AAAS': [[{'transcript': 'NM_015665.6',
    'protein_id': 'NP_056480.1',
    'protein_seq': Seq('MCSLGLFPPPPPRGQVTLYEHNNELVTGSSYESPPPDFRGQWINLPVLQLTKDP...SHL'),
    'cds_seq': Seq('atgtgctctctggggttgttccctcctccaccgcctcggggtcaagtcacccta...taa'),
    'cds_start': 145,
    'cds_end': 1786}]],
 'ABCA1': [[{'transcript': 'NM_005502.4',
    'protein_id': 'NP_005493.2',
    'protein_seq': Seq('MACWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILISVRLSYPPYEQHEC...SYV'),
    'cds_seq': Seq('atggcttgttggcctcagctgaggttgctgctgtggaagaacctcactttcaga...tga'),
    'cds_start': 313,
    'cds_end': 7099}]],
 'ABCA12': [[{'transcript': 'NM_173076.3',
    'protein_id': 'NP_775099.2',
    'protein_seq': Seq('MASLFHQLQILVWKNWLGVKRQPLWTLVLILWPVIIFIILAITRTKFPPTAKPT...MES'),
    'cds_seq': Seq('atggcttccctgtttcatcagcttcagatcctggtctggaaaaattggctaggt...taa'),
    'cds_start': 418,
    'cds_end': 8206}]],
 'ABCA3': [[{'transcript': 'NM_001089.3',
    'protein_id': 'NP_001080.2',
    'protein_seq': Seq('MAVLRQLALLLWKNYTLQKRKVLVTVLELFLPLLFSGILIWLRLKIQSENVPNA...EGR'),
    'cds_seq': Seq('atggctgtgctcaggcagctggcgctcctcctctggaagaactacaccctgcag...tga'),
    'cds_start': 694,
    'cds_end': 5809}]],
 'ABCA4': [[{'transcript': 'NM_000350.3',
    'protein_id': 'NP_000341.2',
    'protein_seq': Seq('MGFVRQIQLLLWKNWTLRKRQKIRFVVELVWPLSLFLVLIWLRNANPLYSHHEC...AQD'),
    'cds_seq': Seq('atgggcttcgtgagacagatacagcttttgctctggaagaactggaccctgcgg...tga'),
    'cds_start': 103,
    'cds_end': 6925}]],
 'ABCB11': [[{'transcript': 'NM_003742.4',
    'protein_id': 'NP_003733.2',
    'protein_seq': Seq('MSDSVILRSIKKFGEENDGFESDKSYNNDKKSRLQDEKKGDGVRVGFFQLFRFS...PIS'),
    'cds_seq': Seq('atgtctgactcagtaattcttcgaagtataaagaaatttggagaggagaatgat...tga'),
    'cds_start': 127,
    'cds_end': 4093}]],
 'ABCB4': [[{'transcript': 'NM_000443.4',
    'protein_id': 'NP_000434.1',
    'protein_seq': Seq('MDLEAAKNGTAWRPTSAEGDFELGISSKQKRKKTKTVKMIGVLTLFRYSDWQDK...QNL'),
    'cds_seq': Seq('atggatcttgaggcggcaaagaacggaacagcctggcgccccacgagcgcggag...tga'),
    'cds_start': 53,
    'cds_end': 3893}]],
 'ABCC2': [[{'transcript': 'NM_000392.5',
    'protein_id': 'NP_000383.2',
    'protein_seq': Seq('MLEKFCNSTFWNSSFLDSPEADLPLCFEQTVLVWIPLGYLWLLAPWQLLHVYKS...TKF'),
    'cds_seq': Seq('atgctggagaagttctgcaactctactttttggaattcctcattcctggacagt...tag'),
    'cds_start': 205,
    'cds_end': 4843}]],
 'ABCC6': [[{'transcript': 'NM_001171.6',
    'protein_id': 'NP_001162.5',
    'protein_seq': Seq('MAAPAEPCAGQGVWNQTEPEPAATSLLSLCFLRTAGVWVPPMYLWVLGPIYLLF...GLV'),
    'cds_seq': Seq('atggccgcgcctgctgagccctgcgcggggcagggggtctggaaccagacagag...tga'),
    'cds_start': 60,
    'cds_end': 4572}]],
 'ABCC8': [[{'transcript': 'NM_000352.6',
    'protein_id': 'NP_000343.2',
    'protein_seq': Seq('MPLAFCGSENHSAAYRVDQGVLNNGCFVDALNVVPHVFLLFITFPILFIGWGSQ...ADK'),
    'cds_seq': Seq('atgcccctggccttctgcggcagcgagaaccactcggccgcctaccgggtggac...tga'),
    'cds_start': 69,
    'cds_end': 4815}]],
 'ABCC9': [[{'transcript': 'NM_020297.4',
    'protein_id': 'NP_064693.2',
    'protein_seq': Seq('MSLSFCGNNISSYNINDGVLQNSCFVDALNLVPHVFLLFITFPILFIGWGSQSS...ADM'),
    'cds_seq': Seq('atgagcctttcattttgtggtaacaacatttcttcatataatatcaacgatggt...tga'),
    'cds_start': 363,
    'cds_end': 5013}]],
 'ABCD1': [[{'transcript': 'NM_000033.4',
    'protein_id': 'NP_000024.2',
    'protein_seq': Seq('MPVLSRPRPWRGNTLKRTAVLLALAAYGAHKVYPLVRQCLAPARGLQAPAGEPT...AST'),
    'cds_seq': Seq('atgccggtgctctccaggccccggccctggcgggggaacacgctgaagcgcacg...tga'),
    'cds_start': 411,
    'cds_end': 2649}]],
 'ACAD9': [[{'transcript': 'NM_014049.4',
    'protein_id': 'NP_054768.2',
    'protein_seq': Seq('MSGCGLFLRTTAAARACRGLVVSTANRRLLRTSPPVRAFAKELFLGKIKKKEVF...RTC'),
    'cds_seq': Seq('atgagcggctgcgggctcttcctgcgcaccacggctgcggctcgtgcctgccgg...tga'),
    'cds_start': 202,
    'cds_end': 2068}],
  [{'transcript': 'NM_014049.5',
    'protein_id': 'NP_054768.2',
    'protein_seq': Seq('MSGCGLFLRTTAAARACRGLVVSTANRRLLRTSPPVRAFAKELFLGKIKKKEVF...RTC'),
    'cds_seq': Seq('atgagcggctgcgggctcttcctgcgcaccacggctgcggctcgtgcctgccgg...tga'),
    'cds_start': 72,
    'cds_end': 1938}]],
 'ACADM': [[{'transcript': 'NM_000016.6',
    'protein_id': 'NP_000007.1',
    'protein_seq': Seq('MAAGFGRCCRVLRSISRFHWRSQHTKANRQREPGLGFSFEFTEQQKEFQATARK...YKN'),
    'cds_seq': Seq('atggcagcggggttcgggcgatgctgcagggtcctgagaagtatttctcgtttt...taa'),
    'cds_start': 79,
    'cds_end': 1345}]],
 'ACADS': [[{'transcript': 'NM_000017.4',
    'protein_id': 'NP_000008.1',
    'protein_seq': Seq('MAAALLARASGPARRALCPRAWRQLHTIYQSVELPETHQMLLQTCRDFAEKELF...YRS'),
    'cds_seq': Seq('atggccgccgcgctgctcgcccgggcctcgggccctgcccgcagagctctctgt...tga'),
    'cds_start': 60,
    'cds_end': 1299}]],
 'ACADVL': [[{'transcript': 'NM_000018.4',
    'protein_id': 'NP_000009.1',
    'protein_seq': Seq('MQAARMAASLGRQLLRLGGGSSRLTALLGQPRPGPARRPYAGGAAQLALDKSDS...LGF'),
    'cds_seq': Seq('atgcaggcggctcggatggccgcgagcttggggcggcagctgctgaggctcggg...tga'),
    'cds_start': 47,
    'cds_end': 2015}]],
 'ACAN': [[{'transcript': 'NM_001369268.1',
    'protein_id': 'NP_001356197.1',
    'protein_seq': Seq('MTTLLWVFVTLRVITAAVTVETSDHDNSLSVSIPQPSPLRVLLGTSLTIPCYFI...TAH'),
    'cds_seq': Seq('atgaccactttactctgggttttcgtgactctgagggtcatcactgcagctgtc...tga'),
    'cds_start': 381,
    'cds_end': 8088}]],
 'ACAT1': [[{'transcript': 'NM_000019.4',
    'protein_id': 'NP_000010.1',
    'protein_seq': Seq('MAVLAALLRSGARSRSPLLRRLVQEIRYVERSYVSKPTLKEVVIVSATRTPIGS...QKL'),
    'cds_seq': Seq('atggctgtgctggcggcacttctgcgcagcggcgcccgcagccgcagccccctg...tag'),
    'cds_start': 40,
    'cds_end': 1324}]],
 'ACO2': [[{'transcript': 'NM_001098.3',
    'protein_id': 'NP_001089.1',
    'protein_seq': Seq('MAPYSLLVTRLQKALGVRQYHVASVLCQRAKVAMSHFEPNEYIHYDLLEKNINI...LQQ'),
    'cds_seq': Seq('atggcgccctacagcctactggtgactcggctgcagaaagctctgggtgtgcgg...tga'),
    'cds_start': 30,
    'cds_end': 2373}]],
 'ACSF3': [[{'transcript': 'NM_001243279.3',
    'protein_id': 'NP_001230208.1',
    'protein_seq': Seq('MLPHVVLTFRRLGCALASCRLAPARHRGSGLLHTAPVARSDRSAPVFTRALAFG...HPS'),
    'cds_seq': Seq('atgctgccccatgtggtgctcaccttccggcgcctgggctgcgccttggcgtcc...tga'),
    'cds_start': 338,
    'cds_end': 2069}]],
 'ACTA1': [[{'transcript': 'NM_001100.4',
    'protein_id': 'NP_001091.1',
    'protein_seq': Seq('MCDEDETTALVCDNGSGLVKAGFAGDDAPRAVFPSIVGRPRHQGVMVGMGQKDS...KCF'),
    'cds_seq': Seq('atgtgcgacgaagacgagaccaccgccctcgtgtgcgacaatggctccggcctg...tag'),
    'cds_start': 103,
    'cds_end': 1237}]],
 'ACTB': [[{'transcript': 'NM_001101.5',
    'protein_id': 'NP_001092.1',
    'protein_seq': Seq('MDDDIAALVVDNGSGMCKAGFAGDDAPRAVFPSIVGRPRHQGVMVGMGQKDSYV...KCF'),
    'cds_seq': Seq('atggatgatgatatcgccgcgctcgtcgtcgacaacggctccggcatgtgcaag...tag'),
    'cds_start': 84,
    'cds_end': 1212}]],
 'ACTG1': [[{'transcript': 'NM_001614.5',
    'protein_id': 'NP_001605.1',
    'protein_seq': Seq('MEEEIAALVIDNGSGMCKAGFAGDDAPRAVFPSIVGRPRHQGVMVGMGQKDSYV...KCF'),
    'cds_seq': Seq('atggaagaagagatcgccgcgctggtcattgacaatggctccggcatgtgcaaa...taa'),
    'cds_start': 72,
    'cds_end': 1200}]],
 'ACVRL1': [[{'transcript': 'NM_000020.3',
    'protein_id': 'NP_000011.2',
    'protein_seq': Seq('MTLGSPRKGLLMLLMALVTQGDPVKPSRGPLVTCTCESPHCKGPTCRGAWCTVV...VIQ'),
    'cds_seq': Seq('atgaccttgggctcccccaggaaaggccttctgatgctgctgatggccttggtg...tag'),
    'cds_start': 197,
    'cds_end': 1709}]],
 'ADA': [[{'transcript': 'NM_000022.4',
    'protein_id': 'NP_000013.2',
    'protein_seq': Seq('MAQTPAFDKPKVELHVHLDGSIKPETILYYGRRRGIALPANTAEGLLNVIGMDK...QNL'),
    'cds_seq': Seq('atggcccagacgcccgccttcgacaagcccaaagtggaactgcatgtccaccta...tga'),
    'cds_start': 92,
    'cds_end': 1184}]],
 'ADA2': [[{'transcript': 'NM_001282225.2',
    'protein_id': 'NP_001269154.1',
    'protein_seq': Seq('MLVDGPSERPALCFLLLAVAMSFFGSALSIDETRAHLLLKEKMMRLGGRLVLNT...ATK'),
    'cds_seq': Seq('atgttggtggatggcccatctgagcggccagccctgtgcttcttgctgttggct...tga'),
    'cds_start': 126,
    'cds_end': 1662}]],
 'ADAMTS13': [[{'transcript': 'NM_139027.6',
    'protein_id': 'NP_620596.2',
    'protein_seq': Seq('MHQRHPRARCPPLCVAGILACGFLLGCWGPSHFQQSCLQALEPQAVSSYLSPGA...EGT'),
    'cds_seq': Seq('atgcaccagcgtcacccccgggcaagatgccctcccctctgtgtggccggaatc...tga'),
    'cds_start': 77,
    'cds_end': 4193}]],
 'ADAMTS2': [[{'transcript': 'NM_014244.5',
    'protein_id': 'NP_055059.2',
    'protein_seq': Seq('MDPPAGAARRLLCPALLLLLLLLPPPLLPPPPPPANARLAAAADPPGGPLGHGA...GKF'),
    'cds_seq': Seq('atggatccgccggcgggagccgctcgccgcctgctctgccccgcgctgctgctg...taa'),
    'cds_start': 133,
    'cds_end': 3769}]],
 'ADAMTSL4': [[{'transcript': 'NM_019032.6',
    'protein_id': 'NP_061905.2',
    'protein_seq': Seq('MENWTGRPWLYLLLLLSLPQLCLDQEVLSGHSLQTPTEEGQGPEGVWGPWVQWA...DPS'),
    'cds_seq': Seq('atggagaactggactggcaggccctggctgtatctgctgctgcttctgtccctc...tga'),
    'cds_start': 250,
    'cds_end': 3475}]],
 'ADAR': [[{'transcript': 'NM_001111.5',
    'protein_id': 'NP_001102.3',
    'protein_seq': Seq('MNPRQGYSLSGYYTHPFQGYEHRQLRYQQPGPGSSPSSFLLKQIEFLKGQLPEA...CPV'),
    'cds_seq': Seq('atgaatccgcggcaggggtattccctcagcggatactacacccatccatttcaa...tag'),
    'cds_start': 180,
    'cds_end': 3861}]],
 'ADGRG1': [[{'transcript': 'NM_201525.4',
    'protein_id': 'NP_958933.1',
    'protein_seq': Seq('MTPQSLLQTTLFLLSLLFLVQGAHGRGHREDFRFCSQRNQTHRSSLHYKPTPDL...SRI'),
    'cds_seq': Seq('atgactccccagtcgctgctgcagacgacactgttcctgctgagtctgctcttc...tag'),
    'cds_start': 208,
    'cds_end': 2272}]],
 'ADGRV1': [[{'transcript': 'NM_032119.4',
    'protein_id': 'NP_115495.3',
    'protein_seq': Seq('MSVFLGPGMPSASLLVNLLSALLILFVFGETEIRFTGQTEFVVNETSTTVIRLI...THL'),
    'cds_seq': Seq('atgtcggtgttcctggggccagggatgccctctgcatctttattagtaaatctt...tag'),
    'cds_start': 99,
    'cds_end': 19020}]],
 'ADNP': [[{'transcript': 'NM_001282531.3',
    'protein_id': 'NP_001269460.1',
    'protein_seq': Seq('MFQLPVNNLGSLRKARKTVKKILSDIGLEYCKEHIEDFKQFEPNDFYLKNTTWE...QQA'),
    'cds_seq': Seq('atgttccaacttcctgtcaacaatcttggcagtttaagaaaagcccggaaaact...taa'),
    'cds_start': 876,
    'cds_end': 4185}]],
 'ADSL': [[{'transcript': 'NM_000026.4',
    'protein_id': 'NP_000017.1',
    'protein_seq': Seq('MAAGGDHGSPDSYRSPLASRYASPEMCFVFSDRYKFRTWRQLWLWLAEAEQTLG...LCL'),
    'cds_seq': Seq('atggcggctggaggcgatcatggttcgcccgacagctaccgctcacctcttgcc...tag'),
    'cds_start': 59,
    'cds_end': 1514}]],
 'AFG2A': [[{'transcript': 'NM_145207.3',
    'protein_id': 'NP_660208.2',
    'protein_seq': Seq('MSSKKNRKRLNQSAENGSSLPSAASSCAEARAPSAGSDFAATSGTLTVTNLLEK...HTL'),
    'cds_seq': Seq('atgtcttccaagaagaatagaaagcggttgaaccaaagcgcggaaaatggttcg...tga'),
    'cds_start': 65,
    'cds_end': 2747}]],
 'AFG3L2': [[{'transcript': 'NM_006796.3',
    'protein_id': 'NP_006787.2',
    'protein_seq': Seq('MAHRCLRLWGRGGCWPRGLQQLLVPGGVGPGEQPCLRTLYRFVTTQARASRNSL...VAN'),
    'cds_seq': Seq('atggcgcaccgctgtttgcggctgtggggccggggcggctgctggccccgcggc...tag'),
    'cds_start': 145,
    'cds_end': 2539}]],
 'AGA': [[{'transcript': 'NM_000027.4',
    'protein_id': 'NP_000018.2',
    'protein_seq': Seq('MARKSNLPVLLVPFLLCQALVRCSSPLPLVVNTWPFKNATEAAWRALASGGSAL...DCI'),
    'cds_seq': Seq('atggcgcggaagtcgaacttgcctgtgcttctcgtgccgtttctgctctgccag...taa'),
    'cds_start': 62,
    'cds_end': 1103}]],
 'AGL': [[{'transcript': 'NM_000642.3',
    'protein_id': 'NP_000633.2',
    'protein_seq': Seq('MGHSKQIRILLLNEMEKLEKTLFRLEQGYELQFRLGPTLQGKAVTVYTNYPFPG...YDL'),
    'cds_seq': Seq('atgggacacagtaaacagattcgaattttacttctgaacgaaatggagaaactg...tag'),
    'cds_start': 123,
    'cds_end': 4722}]],
 'AGXT': [[{'transcript': 'NM_000030.3',
    'protein_id': 'NP_000021.1',
    'protein_seq': Seq('MASHKLLVTPPKALLKPLSIPNQLLLGPGPSNLPPRIMAAGGLQMIGSMSKDMY...KKL'),
    'cds_seq': Seq('atggcctctcacaagctgctggtgaccccccccaaggccctgctcaagcccctc...tga'),
    'cds_start': 42,
    'cds_end': 1221}]],
 'AHDC1': [[{'transcript': 'NM_001371928.1',
    'protein_id': 'NP_001358857.1',
    'protein_seq': Seq('MRVKPQGLVVTSSAVCSSPDYLREPKYYPGGPPTPRPLLPTRPPASPPDKAFST...TSL'),
    'cds_seq': Seq('atgcgtgtgaagccccagggcctggtggtgacttccagtgccgtgtgcagctct...tag'),
    'cds_start': 901,
    'cds_end': 5713}]],
 'AHI1': [[{'transcript': 'NM_001134831.2',
    'protein_id': 'NP_001128303.1',
    'protein_seq': Seq('MPTAESEAKVKTKVRFEELLKTHSDLMREKKKLKKKLVRSEENISPDTIRSNLH...LIE'),
    'cds_seq': Seq('atgcctacagctgagagtgaagcaaaagtaaaaaccaaagttcgctttgaagaa...taa'),
    'cds_start': 359,
    'cds_end': 3950}]],
 'AIPL1': [[{'transcript': 'NM_014336.5',
    'protein_id': 'NP_055151.3',
    'protein_seq': Seq('MDAALLLNVEGVKKTILHGGTGELPNFITGSRVIFHFRTMKCDEERTVIDDSRQ...LQH'),
    'cds_seq': Seq('atggatgccgctctgctcctgaacgtggaaggggtcaagaaaaccattctgcac...tga'),
    'cds_start': 17,
    'cds_end': 1172}]],
 'AIRE': [[{'transcript': 'NM_000383.4',
    'protein_id': 'NP_000374.1',
    'protein_seq': Seq('MATDAALRRLLRLHRTEIAVAVDSAFPLLHALADHDVVPEDKFQETLHLKEKEG...FPS'),
    'cds_seq': Seq('atggcgacggacgcggcgctacgccggcttctgaggctgcaccgcacggagatc...tga'),
    'cds_start': 131,
    'cds_end': 1769}]],
 'ALDH3A2': [[{'transcript': 'NM_000382.3',
    'protein_id': 'NP_000373.1',
    'protein_seq': Seq('MELEVRRVRQAFLSGRSRPLRFRLQQLEALRRMVQEREKDILTAIAADLCKSEF...EYY'),
    'cds_seq': Seq('atggagctcgaagtccggcgggtccgacaggcgttcctgtccggccggtcgcga...tga'),
    'cds_start': 221,
    'cds_end': 1679}]],
 'ALDH5A1': [[{'transcript': 'NM_001080.3',
    'protein_id': 'NP_001071.1',
    'protein_seq': Seq('MATCIWLRSCGARRLGSTFPGCRLRPRAGGLVPASGPAPGPAQLRCYAGRLAGL...GGL'),
    'cds_seq': Seq('atggcgacctgcatttggctgcggagctgtggggcccggcgcctcgggtcgacg...tag'),
    'cds_start': 28,
    'cds_end': 1636}]],
 'ALDH7A1': [[{'transcript': 'NM_001182.5',
    'protein_id': 'NP_001173.2',
    'protein_seq': Seq('MWRLPRALCVHAAKTSKLSGPWSRPAAFMSTLLINQPQYAWLKELGLREENEGV...KFQ'),
    'cds_seq': Seq('atgtggcgccttcctcgcgcgctgtgtgtgcacgctgcaaagaccagcaagctc...taa'),
    'cds_start': 21,
    'cds_end': 1641}]],
 'ALDOB': [[{'transcript': 'NM_000035.4',
    'protein_id': 'NP_000026.2',
    'protein_seq': Seq('MAHRFPALTQEQKKELSEIAQSIVANGKGILAADESVGTMGNRLQRIKVENTEE...YTY'),
    'cds_seq': Seq('atggcccaccgatttccagccctcacccaggagcagaagaaggagctctcagaa...tag'),
    'cds_start': 76,
    'cds_end': 1171}]],
 'ALG1': [[{'transcript': 'NM_019109.5',
    'protein_id': 'NP_061982.3',
    'protein_seq': Seq('MAASCLVLLALCLLLPLLLLGGWKRWRRGRAARHVVAVVLGDVGRSPRMQYHAL...MDT'),
    'cds_seq': Seq('atggcggcctcatgcttggtcctgctggcgctgtgtctgctgctgccgctgctg...taa'),
    'cds_start': 7,
    'cds_end': 1402}]],
 'ALG6': [[{'transcript': 'NM_013339.4',
    'protein_id': 'NP_037471.2',
    'protein_seq': Seq('MEKWYLMTVVVLIGLTVRWTVSLNSYSGAGKPPMFGDYEAQRHWQEITFNLPVK...KIS'),
    'cds_seq': Seq('atggagaaatggtacttgatgacagtagtggttttaataggactaacagtacga...tag'),
    'cds_start': 268,
    'cds_end': 1792}]],
 'ALMS1': [[{'transcript': 'NM_001378454.1',
    'protein_id': 'NP_001365383.1',
    'protein_seq': Seq('MEPEDLPWPGELEEEEEEEEEEEEEEEEAAAAAAANVDDVVVVEEVEEEAGREL...PWD'),
    'cds_seq': Seq('atggagcccgaggatctgccatggccgggcgagctggaggaggaggaggaggag...tga'),
    'cds_start': 33,
    'cds_end': 12540}]],
 'ALOX12B': [[{'transcript': 'NM_001139.3',
    'protein_id': 'NP_001130.1',
    'protein_seq': Seq('MATYKVRVATGTDLLSGTRDSISLTIVGTQGESHKQLLNHFGRDFATGAVGQYT...ISI'),
    'cds_seq': Seq('atggccacctacaaagtcagggtggccacaggcaccgacctcttgtcgggaaca...tag'),
    'cds_start': 274,
    'cds_end': 2380}]],
 'ALPK3': [[{'transcript': 'NM_020778.5',
    'protein_id': 'NP_065829.4',
    'protein_seq': Seq('MGSRRAPSRGWGAGGRSGAGGDGEDDGPVWIPSPASRSYLLSVRPETSLSSNRL...GMR'),
    'cds_seq': Seq('atggggtcgcggagggcccccagccggggctggggcgcgggtgggcggtcgggg...tag'),
    'cds_start': 97,
    'cds_end': 5215}]],
 'ALPL': [[{'transcript': 'NM_000478.6',
    'protein_id': 'NP_000469.3',
    'protein_seq': Seq('MISPFLVLAIGTCLTNSLVPEKEKDPKYWRDQAQETLKYALELQKLNTNVAKNV...VLF'),
    'cds_seq': Seq('atgatttcaccattcttagtactggccattggcacctgccttactaactcctta...tga'),
    'cds_start': 199,
    'cds_end': 1774}]],
 'ALS2': [[{'transcript': 'NM_020919.3',
    'protein_id': 'NP_065970.2',
    'protein_seq': Seq('MDSKKRSSTEAEGSKERGLVHIWQAGSFPITPERLPGWGGKTVLQAALGVKHGV...KLN'),
    'cds_seq': Seq('atggactcaaagaagagaagctcaacagaggcagaaggatccaaggaaagaggc...tag'),
    'cds_start': 356,
    'cds_end': 5330}],
  [{'transcript': 'NM_020919.4',
    'protein_id': 'NP_065970.2',
    'protein_seq': Seq('MDSKKRSSTEAEGSKERGLVHIWQAGSFPITPERLPGWGGKTVLQAALGVKHGV...KLN'),
    'cds_seq': Seq('atggactcaaagaagagaagctcaacagaggcagaaggatccaaggaaagaggc...tag'),
    'cds_start': 117,
    'cds_end': 5091}]],
 'AMT': [[{'transcript': 'NM_000481.4',
    'protein_id': 'NP_000472.2',
    'protein_seq': Seq('MQRAVSVVARLGFRLQAFPPALCRPLSCAQEVLRRTPLYDFHLAHGGKMVAFAG...TLK'),
    'cds_seq': Seq('atgcagagggctgtaagtgtggtggcccgtctgggctttcgcctgcaggcattc...tga'),
    'cds_start': 23,
    'cds_end': 1235}]],
 'ANK1': [[{'transcript': 'NM_000037.4',
    'protein_id': 'NP_000028.3',
    'protein_seq': Seq('MPYSVGFREADAATSFLRAARSGNLDKALDHLRNGVDINTCNQNGLNGLHLASK...GKQ'),
    'cds_seq': Seq('atgccctattctgtgggcttccgcgaagccgatgctgctaccagctttctgaga...tga'),
    'cds_start': 84,
    'cds_end': 5727}]],
 'ANK2': [[{'transcript': 'NM_001148.6',
    'protein_id': 'NP_001139.3',
    'protein_seq': Seq('MMNEDAAQKSDSGEKFNGSSQRRKRPKKSDSNASFLRAARAGNLDKVVEYLKGG...NNE'),
    'cds_seq': Seq('atgatgaacgaagatgcagctcagaaaagcgacagtggagagaagttcaacggc...taa'),
    'cds_start': 76,
    'cds_end': 11950}]],
 'ANKRD11': [[{'transcript': 'NM_013275.6',
    'protein_id': 'NP_037407.4',
    'protein_seq': Seq('MPKGGCPKAPQQEELPLSSDMVEKQTGKKDKDKVSLTKTPKLERGDGGKEVRER...LPA'),
    'cds_seq': Seq('atgcccaagggtgggtgccctaaagcaccacagcaggaagagcttcccctcagc...tga'),
    'cds_start': 461,
    'cds_end': 8453}]],
 'ANO5': [[{'transcript': 'NM_213599.3',
    'protein_id': 'NP_998764.1',
    'protein_seq': Seq('MGDPDLLEVLAEEGEKVNKHIDYSFQMSEQSLSSRETSFLINEETMPAKRFNLF...STL'),
    'cds_seq': Seq('atgggcgacccggatctcctggaagtgttggcggaggaaggggaaaaagtcaat...taa'),
    'cds_start': 408,
    'cds_end': 3150}]],
 'ANOS1': [[{'transcript': 'NM_000216.4',
    'protein_id': 'NP_000207.2',
    'protein_seq': Seq('MVPGVPGAVLTLCLWLAASSGCLAAGPGAAAARRLDESLSAGSVQRARCASRCL...ERY'),
    'cds_seq': Seq('atggtgcccggggtgcccggcgcggtcctgaccctctgcctctggctggcggcc...taa'),
    'cds_start': 101,
    'cds_end': 2144}]],
 'APC': [[{'transcript': 'NM_000038.6',
    'protein_id': 'NP_000029.2',
    'protein_seq': Seq('MAAASYDQLLKQVEALKMENSNLRQELEDNSNHLTKLETEASNMKEVLKQLQGS...TSV'),
    'cds_seq': Seq('atggctgcagcttcatatgatcagttgttaaagcaagttgaggcactgaagatg...taa'),
    'cds_start': 59,
    'cds_end': 8591}],
  [{'transcript': 'NM_001127510.3',
    'protein_id': 'NP_001120982.1',
    'protein_seq': Seq('MAAASYDQLLKQVEALKMENSNLRQELEDNSNHLTKLETEASNMKEVLKQLQGS...TSV'),
    'cds_seq': Seq('atggctgcagcttcatatgatcagttgttaaagcaagttgaggcactgaagatg...taa'),
    'cds_start': 167,
    'cds_end': 8699}],
  [{'transcript': 'NM_001127511.3',
    'protein_id': 'NP_001120983.2',
    'protein_seq': Seq('MYASLGSGPVAPLPASVPPSVLGSWSTGGSRSCVRQETKSPGGARTSGHWASVW...TSV'),
    'cds_seq': Seq('atgtacgcctccctgggctcgggtccggtcgcccctttgcccgcttctgtacca...taa'),
    'cds_start': 220,
    'cds_end': 8698}]],
 'APOB': [[{'transcript': 'NM_000384.3',
    'protein_id': 'NP_000375.3',
    'protein_seq': Seq('MDPPRPALLALLALPALLLLLLAGARAEEEMLENVSLVCPKDATRFKHLRKYTY...IIL'),
    'cds_seq': Seq('atggacccgccgaggcccgcgctgctggcgctgctggcgctgcctgcgctgctg...taa'),
    'cds_start': 128,
    'cds_end': 13820}]],
 'APRT': [[{'transcript': 'NM_000485.3',
    'protein_id': 'NP_000476.1',
    'protein_seq': Seq('MADSELQLVEQRIRSFPDFPTPGVVFRDISPVLKDPASFRAAIGLLARHLKATH...QYE'),
    'cds_seq': Seq('atggccgactccgagctgcagctggttgagcagcggatccgcagcttccccgac...tga'),
    'cds_start': 29,
    'cds_end': 572}]],
 'AQP2': [[{'transcript': 'NM_000486.6',
    'protein_id': 'NP_000477.1',
    'protein_seq': Seq('MWELRSIAFSRAVFAEFLATLLFVFFGLGSALNWPQALPSVLQIAMAFGLGIGT...TKA'),
    'cds_seq': Seq('atgtgggagctccgctccatagccttctccagggctgtgttcgcagagttcctg...tga'),
    'cds_start': 94,
    'cds_end': 910}]],
 'AR': [[{'transcript': 'NM_000044.6',
    'protein_id': 'NP_000035.2',
    'protein_seq': Seq('MEVQLGLGRVYPRPPSKTYRGAFQNLFQSVREVIQNPGPRHPEAASAAPPGASL...HTQ'),
    'cds_seq': Seq('atggaagtgcagttagggctgggaagggtctaccctcggccgccgtccaagacc...tga'),
    'cds_start': 1126,
    'cds_end': 3889}]],
 'ARG1': [[{'transcript': 'NM_000045.4',
    'protein_id': 'NP_000036.2',
    'protein_seq': Seq('MSAKSRTIGIIGAPFSKGQPRGGVEEGPTVLRKAGLLEKLKEQECDVKDYGDLP...PPK'),
    'cds_seq': Seq('atgagcgccaagtccagaaccatagggattattggagctcctttctcaaaggga...taa'),
    'cds_start': 57,
    'cds_end': 1026}]],
 'ARID1A': [[{'transcript': 'NM_006015.6',
    'protein_id': 'NP_006006.3',
    'protein_seq': Seq('MAAQVAPAAASSLGNPPPPPPSELKKAEQQQREEAGGEAAAAAAAERGEMKAAA...GQS'),
    'cds_seq': Seq('atggccgcgcaggtcgcccccgccgccgccagcagcctgggcaacccgccgccg...tga'),
    'cds_start': 389,
    'cds_end': 7247}]],
 'ARID1B': [[{'transcript': 'NM_001374828.1',
    'protein_id': 'NP_001361757.1',
    'protein_seq': Seq('MAARAAAAAAAAAARARARAGSGERRAPPGPRPAPGARDLEAGARGAAAAAAAP...GQL'),
    'cds_seq': Seq('atggccgcgcgggcagcagcggcggcggcggcggcggcggcgcgggcgcgggcg...tga'),
    'cds_start': 303,
    'cds_end': 7422}]],
 'ARSA': [[{'transcript': 'NM_000487.6',
    'protein_id': 'NP_000478.3',
    'protein_seq': Seq('MSMGAPRSLLLALAAGLAVARPPNIVLIFADDLGYGDLGCYGHPSSTTPNLDQL...PHA'),
    'cds_seq': Seq('atgtccatgggggcaccgcggtccctcctcctggccctggctgctggcctggcc...tga'),
    'cds_start': 373,
    'cds_end': 1903}]],
 'ARSB': [[{'transcript': 'NM_000046.5',
    'protein_id': 'NP_000037.2',
    'protein_seq': Seq('MGPRGAASLPRGPGPRRLLLPVVLPLLLLLLLAPPGSGAGASRPPHLVFLLADD...PWM'),
    'cds_seq': Seq('atgggtccgcgcggcgcggcgagcttgccccgaggccccggacctcggcggctg...tag'),
    'cds_start': 62,
    'cds_end': 1664}]],
 'ARX': [[{'transcript': 'NM_139058.3',
    'protein_id': 'NP_620689.1',
    'protein_seq': Seq('MSNQYQEEGCSERPECKSKSPTLLSSYCIDSILGRRSPCKMRLLGAAQSLPAPL...EVC'),
    'cds_seq': Seq('atgagcaatcagtaccaggaggagggctgctccgagaggcccgagtgcaaaagt...taa'),
    'cds_start': 228,
    'cds_end': 1917}]],
 'ASAH1': [[{'transcript': 'NM_177924.5',
    'protein_id': 'NP_808592.2',
    'protein_seq': Seq('MPGRSCVALVLLAAAVSCAVAQHAPPWTEDCRKSTYPPSGPTYRGAVPWYTINL...IGW'),
    'cds_seq': Seq('atgccgggccggagttgcgtcgccttagtcctcctggctgccgccgtcagctgt...tga'),
    'cds_start': 49,
    'cds_end': 1237}]],
 'ASH1L': [[{'transcript': 'NM_018489.3',
    'protein_id': 'NP_060959.2',
    'protein_seq': Seq('MDPRNTAMLGLGSDSEGFSRKSPSAISTGTLVSKREVELEKNTKEEEDLRKRNR...FRK'),
    'cds_seq': Seq('atggaccctagaaatactgctatgttaggattgggttctgattccgaaggtttt...tga'),
    'cds_start': 750,
    'cds_end': 9645}]],
 'ASL': [[{'transcript': 'NM_000048.4',
    'protein_id': 'NP_000039.2',
    'protein_seq': Seq('MASESGKLWGGRFVGAVDPIMEKFNASIAYDRHLWEVDVQGSKAYSRGLEKAGL...QQA'),
    'cds_seq': Seq('atggcctcggagagtgggaagctttggggtggccggtttgtgggtgcagtggac...tag'),
    'cds_start': 81,
    'cds_end': 1476}]],
 'ASNS': [[{'transcript': 'NM_001673.5',
    'protein_id': 'NP_001664.3',
    'protein_seq': Seq('MCGIWALFGSDDCLSVQCLSAMKIAHRGPDAFRFENVNGYTNCCFGFHRLAVVD...VKA'),
    'cds_seq': Seq('atgtgtggcatttgggcgctgtttggcagtgatgattgcctttctgttcagtgt...tag'),
    'cds_start': 117,
    'cds_end': 1803}]],
 'ASPA': [[{'transcript': 'NM_000049.4',
    'protein_id': 'NP_000040.1',
    'protein_seq': Seq('MTSCHIAEEHIQKVAIFGGTHGNELTGVFLVKHWLENGAEIQRTGLEVKPFITN...CLH'),
    'cds_seq': Seq('atgacttcttgtcacattgctgaagaacatatacaaaaggttgctatctttgga...tag'),
    'cds_start': 163,
    'cds_end': 1105}]],
 'ASPM': [[{'transcript': 'NM_018136.5',
    'protein_id': 'NP_060606.3',
    'protein_seq': Seq('MANRRVGRGCWEVSPTERRPPAGLRGPAAEEEASSPPVLSLSHFCRSPFLCFGD...IPY'),
    'cds_seq': Seq('atggcgaaccggcgagtggggcgaggctgctgggaagtgagcccgaccgagcgg...tag'),
    'cds_start': 232,
    'cds_end': 10666}]],
 'ASS1': [[{'transcript': 'NM_054012.4',
    'protein_id': 'NP_446464.1',
    'protein_seq': Seq('MSSKGSVVLAYSGGLDTSCILVWLKEQGYDVIAYLANIGQKEDFEEARKKALKL...TAK'),
    'cds_seq': Seq('atgtccagcaaaggctccgtggttctggcctacagtggcggcctggacacctcg...tag'),
    'cds_start': 40,
    'cds_end': 1279}]],
 'ASXL1': [[{'transcript': 'NM_015338.6',
    'protein_id': 'NP_056153.2',
    'protein_seq': Seq('MKDKQKKKKERTWAEAARLVLENYSDAPMTPKQILQVIEAEGLKEMRSGTSPLA...VVR'),
    'cds_seq': Seq('atgaaggacaaacagaagaagaagaaggagcgcacgtgggccgaggccgcgcgc...taa'),
    'cds_start': 445,
    'cds_end': 5071}]],
 'ASXL3': [[{'transcript': 'NM_030632.3',
    'protein_id': 'NP_085135.1',
    'protein_seq': Seq('MKDKRKKKDRTWAEAARLALEKHPNSPMTAKQILEVIQKEGLKETSGTSPLACL...VVR'),
    'cds_seq': Seq('atgaaagacaagaggaagaagaaggaccgcacctgggccgaggctgcccgcctg...taa'),
    'cds_start': 413,
    'cds_end': 7160}]],
 'ATL1': [[{'transcript': 'NM_015915.5',
    'protein_id': 'NP_056999.2',
    'protein_seq': Seq('MAKNRRDRNSWGGFSEKTYEWSSEEEEPVKKAGPVQVLIVKDDHSFELDETALN...KKM'),
    'cds_seq': Seq('atggccaagaaccgcagggacagaaacagttggggtggattttcggaaaagaca...taa'),
    'cds_start': 121,
    'cds_end': 1798}]],
 'ATM': [[{'transcript': 'NM_000051.4',
    'protein_id': 'NP_000042.3',
    'protein_seq': Seq('MSLVLNDLLICCRQLEHDRATERKKEVEKFKRLIRDPETIKHLDRHSDSKQGKY...AWV'),
    'cds_seq': Seq('atgagtctagtacttaatgatctgcttatctgctgccgtcaactagaacatgat...tga'),
    'cds_start': 150,
    'cds_end': 9321}]],
 'ATP1A2': [[{'transcript': 'NM_000702.4',
    'protein_id': 'NP_000693.1',
    'protein_seq': Seq('MGRGAGREYSPAATTAENGGGKKKQKEKELDELKKEVAMDDHKLSLDELGRKYQ...TYY'),
    'cds_seq': Seq('atgggccgtggggctggccgtgagtactcacctgccgccaccacggcagagaat...tga'),
    'cds_start': 103,
    'cds_end': 3166}]],
 'ATP1A3': [[{'transcript': 'NM_152296.5',
    'protein_id': 'NP_689509.1',
    'protein_seq': Seq('MGDKKDDKDSPKKNKGKERRDLDDLKKEVAMTEHKMSVEEVCRKYNTDCVQGLT...TYY'),
    'cds_seq': Seq('atgggggacaagaaagatgacaaggactcacccaagaagaacaagggcaaggag...tga'),
    'cds_start': 154,
    'cds_end': 3196}]],
 'ATP2A2': [[{'transcript': 'NM_170665.4',
    'protein_id': 'NP_733765.1',
    'protein_seq': Seq('MENAHTKTVEEVLGHFGVNESTGLSLEQVKKLKERWGSNELPAEEGKTLLELVI...FWS'),
    'cds_seq': Seq('atggagaacgcgcacaccaagacggtggaggaggtgctgggccacttcggcgtc...tga'),
    'cds_start': 543,
    'cds_end': 3672}]],
 'ATP6V0A4': [[{'transcript': 'NM_020632.3',
    'protein_id': 'NP_065683.2',
    'protein_seq': Seq('MVSVFRSEEMCLSQLFLQVEAAYCCVAELGELGLVQFKDLNMNVNSFQRKFVNE...AEE'),
    'cds_seq': Seq('atggtgtctgtgtttcgaagcgaggagatgtgtttgtcacaactgtttctccag...tag'),
    'cds_start': 283,
    'cds_end': 2806}]],
 'ATP6V1B1': [[{'transcript': 'NM_001692.4',
    'protein_id': 'NP_001683.2',
    'protein_seq': Seq('MAMEIDSRPGGLPGSSCNLGAAREHMQAVTRNYITHPRVTYRTVCSVNGPLVVL...TAL'),
    'cds_seq': Seq('atggccatggagatagacagcaggcctggggggctccccggcagtagctgcaac...tag'),
    'cds_start': 55,
    'cds_end': 1597}]],
 'ATP7A': [[{'transcript': 'NM_000052.7',
    'protein_id': 'NP_000043.4',
    'protein_seq': Seq('MDPSMGVNSVTISVEGMTCNSCVWTIEQQIGKVNGVHHIKVSLEEKNATIIYDP...TAL'),
    'cds_seq': Seq('atggatccaagtatgggtgtgaattctgttaccatttctgttgagggtatgact...taa'),
    'cds_start': 164,
    'cds_end': 4667}]],
 'ATP7B': [[{'transcript': 'NM_000053.4',
    'protein_id': 'NP_000044.2',
    'protein_seq': Seq('MPEQERQITAREGASRKILSKLSLPTRAWEPAMKKSFAFDNVGYEGGLDGLGPS...QYI'),
    'cds_seq': Seq('atgcctgagcaggagagacagatcacagccagagaaggggccagtcggaaaatc...tga'),
    'cds_start': 113,
    'cds_end': 4511}]],
 'ATP8B1': [[{'transcript': 'NM_001374385.1',
    'protein_id': 'NP_001361314.1',
    'protein_seq': Seq('MSTERDSETTFDEDSQPNDEVVPYSDDETEDELDDQGSAVEPEQNRVNREAEEN...GDS'),
    'cds_seq': Seq('atgagtacagaaagagactcagaaacgacatttgacgaggattctcagcctaat...tga'),
    'cds_start': 343,
    'cds_end': 4099}]],
 'ATR': [[{'transcript': 'NM_001184.4',
    'protein_id': 'NP_001175.2',
    'protein_seq': Seq('MGEHGLELASMIPALRELGSATPEEYNTVVQKPRQILCQFIDRILTDVNVVAVE...PYM'),
    'cds_seq': Seq('atgggggaacatggcctggagctggcttccatgatccccgccctgcgggagctg...tga'),
    'cds_start': 29,
    'cds_end': 7964}]],
 'ATRX': [[{'transcript': 'NM_000489.6',
    'protein_id': 'NP_000480.3',
    'protein_seq': Seq('MTAEPMSESKLNTLVQKLHDFLAHSSEESEETSSPPRLAMNQNTDKISGSGSNS...KSM'),
    'cds_seq': Seq('atgaccgctgagcccatgagtgaaagcaagttgaatacattggtgcagaagctt...tga'),
    'cds_start': 215,
    'cds_end': 7694}]],
 'AUTS2': [[{'transcript': 'NM_015570.4',
    'protein_id': 'NP_056385.1',
    'protein_seq': Seq('MDGPTRGHGLRKKRRSRSQRDRERRSRGGLGAGAAGGGGAGRTRALSLASSSGS...EAR'),
    'cds_seq': Seq('atggatggcccgacgcggggccatggactccgcaaaaagcggcggtcgcggtcg...taa'),
    'cds_start': 1179,
    'cds_end': 4959}]],
 'AVPR2': [[{'transcript': 'NM_000054.7',
    'protein_id': 'NP_000045.1',
    'protein_seq': Seq('MLMASTTSAVPGHPSLPSLPSNSSQERPLDTRDPLLARAELALLSIVFVAVALS...TSS'),
    'cds_seq': Seq('atgctcatggcgtccaccacttccgctgtgcctgggcatccctctctgcccagc...tga'),
    'cds_start': 271,
    'cds_end': 1387}]],
 'AXIN2': [[{'transcript': 'NM_004655.4',
    'protein_id': 'NP_004646.3',
    'protein_seq': Seq('MSSAMLVTCLPDPSSSFREDAPRPPVPGEEGETPPCQPGVGKGQVTKPMPVSSN...RID'),
    'cds_seq': Seq('atgagtagcgctatgttggtgacttgcctcccggaccccagcagcagcttccgt...tga'),
    'cds_start': 315,
    'cds_end': 2847}]],
 'BAG3': [[{'transcript': 'NM_004281.4',
    'protein_id': 'NP_004272.2',
    'protein_seq': Seq('MSAATHSPMMQVASGNGDRDPLPPGWEIKIDPQTGWPFFVDHNSRTTTWNDPRV...AAP'),
    'cds_seq': Seq('atgagcgccgccacccactcgcccatgatgcaggtggcgtccggcaacggtgac...tag'),
    'cds_start': 296,
    'cds_end': 2024}]],
 'BAP1': [[{'transcript': 'NM_004656.4',
    'protein_id': 'NP_004647.1',
    'protein_seq': Seq('MNKGWLELESDPGLFTLLVEDFGVKGVQVEEIYDLQSKCQGPVYGFIFLFKWIE...KRQ'),
    'cds_seq': Seq('atgaataagggctggctggagctggagagcgacccaggcctcttcaccctgctc...tga'),
    'cds_start': 130,
    'cds_end': 2320}]],
 'BARD1': [[{'transcript': 'NM_000465.4',
    'protein_id': 'NP_000456.2',
    'protein_seq': Seq('MPDNRQPRNRQPRIRSGNEPRSAPAMEPDGRGAWAHSRAALDRLEKLLRCSRCT...LDS'),
    'cds_seq': Seq('atgccggataatcggcagccgaggaaccggcagccgaggatccgctccgggaac...tga'),
    'cds_start': 114,
    'cds_end': 2448}]],
 'BBS1': [[{'transcript': 'NM_024649.5',
    'protein_id': 'NP_078925.3',
    'protein_seq': Seq('MAAASSSDSDACGAESNEANSKWLDAHYDPMANIHTFSACLALADLHGDGEYKL...AAA'),
    'cds_seq': Seq('atggccgctgcgtcctcatcggattccgacgcctgcggagctgagagcaatgag...tga'),
    'cds_start': 25,
    'cds_end': 1807}]],
 'BBS10': [[{'transcript': 'NM_024685.4',
    'protein_id': 'NP_078961.3',
    'protein_seq': Seq('MLSSMAAAGSVKAALQVAEVLEAIVSCCVGPEGRQVLCTKPTGEVLLSRNGGRL...DEL'),
    'cds_seq': Seq('atgttaagttctatggccgctgcagggtctgtgaaggcggcgttgcaggtggcc...taa'),
    'cds_start': 57,
    'cds_end': 2229}]],
 'BBS12': [[{'transcript': 'NM_152618.3',
    'protein_id': 'NP_689831.2',
    'protein_seq': Seq('MVMACRVVNKRRHMGLQQLSSFAETGRTFLGPLKSSKFIIDEECHESVLISSTV...LFL'),
    'cds_seq': Seq('atggtgatggcttgcagagtcgtaaacaaaagaagacacatgggacttcaacaa...tag'),
    'cds_start': 191,
    'cds_end': 2324}]],
 'BBS2': [[{'transcript': 'NM_031885.5',
    'protein_id': 'NP_114091.4',
    'protein_seq': Seq('MLLPVFTLKLRHKISPRMVAIGRYDGTHPCLAAATQTGKVFIHNPHTRNQHVSA...ASS'),
    'cds_seq': Seq('atgctgctgcctgtgttcaccctgaaactgcgccacaaaatcagcccccgaatg...tag'),
    'cds_start': 162,
    'cds_end': 2328}]],
 'BBS4': [[{'transcript': 'NM_033028.5',
    'protein_id': 'NP_149017.2',
    'protein_seq': Seq('MAEERVATRTQFPVSTESQKPRQKKAPEFPILEKQNWLIHLHYIRKDYEACKAV...REK'),
    'cds_seq': Seq('atggctgaggagagagtcgcgacgagaactcaatttcctgtatctactgagtct...taa'),
    'cds_start': 21,
    'cds_end': 1581}]],
 'BBS7': [[{'transcript': 'NM_176824.3',
    'protein_id': 'NP_789794.1',
    'protein_seq': Seq('MDLILNRMDYLQVGVTSQKTMKLIPASRHRATQKVVIGDHDGVVMCFGMKKGEA...DAA'),
    'cds_seq': Seq('atggatctgattttaaaccgaatggattatctgcaggtgggagtaacatctcag...tga'),
    'cds_start': 161,
    'cds_end': 2309}]],
 'BBS9': [[{'transcript': 'NM_198428.3',
    'protein_id': 'NP_940820.1',
    'protein_seq': Seq('MSLFKARDWWSTILGDKEEFDQGCLCLANVDNSGNGQDKIIVGSFMGYLRIFSP...VSE'),
    'cds_seq': Seq('atgtctttatttaaagcccgtgattggtggtctactattctgggagataaagaa...taa'),
    'cds_start': 489,
    'cds_end': 3153}]],
 'BCKDHA': [[{'transcript': 'NM_000709.4',
    'protein_id': 'NP_000700.1',
    'protein_seq': Seq('MAVAIAAARVWRLNRGLSQAALLLLRQPGARGLARSHPPRQQQQFSSLDDKPQF...FDK'),
    'cds_seq': Seq('atggcggtagcgatcgctgcagcgagggtctggcggctaaaccgtggtttgagc...tga'),
    'cds_start': 10,
    'cds_end': 1348}]],
 'BCKDHB': [[{'transcript': 'NM_183050.4',
    'protein_id': 'NP_898871.1',
    'protein_seq': Seq('MAVVAAAAGWLLRLRAAGAEGHWRRLPGAGLARGFLHPAATVEDAAQRRQVAHF...INY'),
    'cds_seq': Seq('atggcggttgtagcggcggctgccggctggctactcaggctcagggcggcaggg...tga'),
    'cds_start': 23,
    'cds_end': 1202}]],
 'BCS1L': [[{'transcript': 'NM_001079866.2',
    'protein_id': 'NP_001073335.1',
    'protein_seq': Seq('MPLSDFILALKDNPYFGAGFGLVGVGTALALARKGVQLGLVAFRRHYMITLEVP...LRR'),
    'cds_seq': Seq('atgccactttcagactttattctggctctgaaggacaatccctactttggggct...tga'),
    'cds_start': 110,
    'cds_end': 1370}]],
 'BEST1': [[{'transcript': 'NM_004183.4',
    'protein_id': 'NP_004174.1',
    'protein_seq': Seq('MTITYTSQVANARLGSFSRLLLCWRGSIYKLLYGEFLIFLLCYYIIRFIYRLAL...AHS'),
    'cds_seq': Seq('atgaccatcacttacacaagccaagtggctaatgcccgcttaggctccttctcc...taa'),
    'cds_start': 113,
    'cds_end': 1871}]],
 'BLM': [[{'transcript': 'NM_000057.4',
    'protein_id': 'NP_000048.1',
    'protein_seq': Seq('MAAVPQNNLQEQLERHSARTLNNKLSLSKPKFSGFTFKKKTSSDNNVSVTNVSV...AFS'),
    'cds_seq': Seq('atggctgctgttcctcaaaataatctacaggagcaactagaacgtcactcagcc...taa'),
    'cds_start': 99,
    'cds_end': 4353}]],
 'BMPR1A': [[{'transcript': 'NM_004329.3',
    'protein_id': 'NP_004320.2',
    'protein_seq': Seq('MPQLYIYIRLLGAYLFIISRVQGQNLDSMLHGTGMKSDSDQKKSENGVTLAPED...VKI'),
    'cds_seq': Seq('atgcctcagctatacatttacatcagattattgggagcctatttgttcatcatt...tga'),
    'cds_start': 568,
    'cds_end': 2167}]],
 'BMPR2': [[{'transcript': 'NM_001204.7',
    'protein_id': 'NP_001195.2',
    'protein_seq': Seq('MTSSLQRPWRVPWLPWTILLVSTAAASQNQERLCAFKDPYQQDLGIGESRISHE...NCL'),
    'cds_seq': Seq('atgacttcctcgctgcagcggccctggcgggtgccctggctaccatggaccatc...tga'),
    'cds_start': 1148,
    'cds_end': 4265}]],
 'BRAF': [[{'transcript': 'NM_004333.6',
    'protein_id': 'NP_004324.2',
    'protein_seq': Seq('MAALSGGGGGGAEPGQALFNGDMEPEAGAGAGAAASSAADPAIPEEVWNIKQMI...PVH'),
    'cds_seq': Seq('atggcggcgctgagcggtggcggtggtggcggcgcggagccgggccaggctctg...tga'),
    'cds_start': 226,
    'cds_end': 2527}]],
 'BRAT1': [[{'transcript': 'NM_152743.4',
    'protein_id': 'NP_689956.2',
    'protein_seq': Seq('MDPECAQLLPALCAVLVDPRQPVADDTCLEKLLDWFKTVTEGESSVVLLQEHPC...DCY'),
    'cds_seq': Seq('atggacccagaatgcgcccagctgctcccggctctctgtgctgttctggtagat...tga'),
    'cds_start': 54,
    'cds_end': 2520}]],
 'BRCA1': [[{'transcript': 'NM_007294.4',
    'protein_id': 'NP_009225.1',
    'protein_seq': Seq('MDLSALRVEEVQNVINAMQKILECPICLELIKEPVSTKCDHIFCKFCMLKLLNQ...SHY'),
    'cds_seq': Seq('atggatttatctgctcttcgcgttgaagaagtacaaaatgtcattaatgctatg...tga'),
    'cds_start': 113,
    'cds_end': 5705}]],
 'BRCA2': [[{'transcript': 'NM_000059.4',
    'protein_id': 'NP_000050.3',
    'protein_seq': Seq('MPIGSKERPTFFEIFKTRCNKADLGPISLNWFEELSSEAPPYNSEPAEESEHKN...KYI'),
    'cds_seq': Seq('atgcctattggatccaaagagaggccaacattttttgaaatttttaagacacgc...taa'),
    'cds_start': 199,
    'cds_end': 10456}]],
 'BRIP1': [[{'transcript': 'NM_032043.3',
    'protein_id': 'NP_114432.2',
    'protein_seq': Seq('MSSMWSEYTIGGVKIYFPYKAYPSQLAMMNSILRGLNSKQHCLLESPTGSGKSL...GFK'),
    'cds_seq': Seq('atgtcttcaatgtggtctgaatatacaattggtggggtgaagatttactttcct...taa'),
    'cds_start': 275,
    'cds_end': 4025}]],
 'BTD': [[{'transcript': 'NM_001370658.1',
    'protein_id': 'NP_001357587.1',
    'protein_seq': Seq('MSGARSKLALFLCGCYVVALGAHTGEESVADHHEAEYYVAAVYEHPSILSLNPL...ERD'),
    'cds_seq': Seq('atgtctggagccagaagtaagcttgctcttttcctctgcggctgttacgtggtt...tag'),
    'cds_start': 166,
    'cds_end': 1738}]],
 'BTK': [[{'transcript': 'NM_000061.3',
    'protein_id': 'NP_000052.1',
    'protein_seq': Seq('MAAVILESIFLKRSQQKKKTSPLNFKKRLFLLTVHKLSYYEYDFERGRRGSKKG...EES'),
    'cds_seq': Seq('atggccgcagtgattctggagagcatctttctgaagcgatcccaacagaaaaag...tga'),
    'cds_start': 160,
    'cds_end': 2140}]],
 'C3': [[{'transcript': 'NM_000064.4',
    'protein_id': 'NP_000055.2',
    'protein_seq': Seq('MGPTSGPSLLLLLLTHLPLALGSPMYSIITPNILRLESEETMVLEAHDAQGDVP...CPN'),
    'cds_seq': Seq('atgggacccacctcaggtcccagcctgctgctcctgctactaacccacctcccc...tga'),
    'cds_start': 61,
    'cds_end': 5053}]],
 'CACNA1A': [[{'transcript': 'NM_001127221.2',
    'protein_id': 'NP_001120693.1',
    'protein_seq': Seq('MARFGDEMPARYGGGGSGAAAGVVVGSGGGRGAGGSRQGGQPGAQRMYKQSMAQ...HRQ'),
    'cds_seq': Seq('atggcccgcttcggagacgagatgccggcccgctacgggggaggaggctccggg...tag'),
    'cds_start': 255,
    'cds_end': 7041}],
  [{'transcript': 'NM_001127222.2',
    'protein_id': 'NP_001120694.1',
    'protein_seq': Seq('MARFGDEMPARYGGGGSGAAAGVVVGSGGGRGAGGSRQGGQPGAQRMYKQSMAQ...DWC'),
    'cds_seq': Seq('atggcccgcttcggagacgagatgccggcccgctacgggggaggaggctccggg...taa'),
    'cds_start': 255,
    'cds_end': 7776}]],
 'CACNA1C': [[{'transcript': 'NM_000719.7',
    'protein_id': 'NP_000710.5',
    'protein_seq': Seq('MVNENTRMYIPEENHQGSNYGSPRPAHANMNANAAAGLAPEHIPTPGAALSWQA...SSL'),
    'cds_seq': Seq('atggtcaatgagaatacgaggatgtacattccagaggaaaaccaccaaggttcc...tag'),
    'cds_start': 576,
    'cds_end': 6993}],
  [{'transcript': 'NM_001167623.2',
    'protein_id': 'NP_001161095.1',
    'protein_seq': Seq('MVNENTRMYIPEENHQGSNYGSPRPAHANMNANAAAGLAPEHIPTPGAALSWQA...SSL'),
    'cds_seq': Seq('atggtcaatgagaatacgaggatgtacattccagaggaaaaccaccaaggttcc...tag'),
    'cds_start': 576,
    'cds_end': 6993}]],
 'CACNA1F': [[{'transcript': 'NM_001256789.3',
    'protein_id': 'NP_001243718.1',
    'protein_seq': Seq('MSESEGGKDTTPEPSPANGAGPGPEWGLCPGPPAVEGESSGASGLGTPKRRNQH...HAL'),
    'cds_seq': Seq('atgtcggaatctgaaggcgggaaagacaccaccccagagcccagtccagccaat...tga'),
    'cds_start': 31,
    'cds_end': 5932}],
  [{'transcript': 'NM_005183.4',
    'protein_id': 'NP_005174.2',
    'protein_seq': Seq('MSESEGGKDTTPEPSPANGAGPGPEWGLCPGPPAVEGESSGASGLGTPKRRNQH...HAL'),
    'cds_seq': Seq('atgtcggaatctgaaggcgggaaagacaccaccccagagcccagtccagccaat...tga'),
    'cds_start': 31,
    'cds_end': 5965}]],
 'CACNA1S': [[{'transcript': 'NM_000069.3',
    'protein_id': 'NP_000060.2',
    'protein_seq': Seq('MEPSSPQDEGLRKKQPKKPVPEILPRPPRALFCLTLENPLRKACISIVEWKPFE...PRL'),
    'cds_seq': Seq('atggagccatcctcaccccaggatgaaggcctgaggaagaaacagcccaagaag...tga'),
    'cds_start': 87,
    'cds_end': 5709}]],
 'CAD': [[{'transcript': 'NM_004341.5',
    'protein_id': 'NP_004332.2',
    'protein_seq': Seq('MAALVLEDGSVLRGQPFGAAVSTAGEVVFQTGMVGYPEALTDPSYKAQILVLTY...GRF'),
    'cds_seq': Seq('atggcggccctagtgttggaggacgggtcggtcctgcggggccagccctttggg...tag'),
    'cds_start': 183,
    'cds_end': 6861}]],
 'CAMTA1': [[{'transcript': 'NM_015215.4',
    'protein_id': 'NP_056030.1',
    'protein_seq': Seq('MWRAEGKWLPKTSRKSVSQSVFCGTSTYCVLNTVPPIEDDHGNSNSSHVKIFLP...QGT'),
    'cds_seq': Seq('atgtggcgcgcggaggggaaatggctgccgaaaacaagccggaagagcgtttcc...tga'),
    'cds_start': 77,
    'cds_end': 5099}]],
 'CAPN3': [[{'transcript': 'NM_000070.3',
    'protein_id': 'NP_000061.1',
    'protein_seq': Seq('MPTVISASVAPRTAAEPRSPGPVPHPAQSKATEAGGGNPSGIYSAIISRNFPII...MYA'),
    'cds_seq': Seq('atgccgaccgtcattagcgcatctgtggctccaaggacagcggctgagccccgg...tga'),
    'cds_start': 305,
    'cds_end': 2771}]],
 'CASK': [[{'transcript': 'NM_001367721.1',
    'protein_id': 'NP_001354650.1',
    'protein_seq': Seq('MADDDVLFEDVYELCEVIGKGPFSVVRRCINRETGQQFAVKIVDVAKFTSSPGL...WVY'),
    'cds_seq': Seq('atggccgacgacgacgtgctgttcgaggatgtgtacgagctgtgcgaggtgatc...tag'),
    'cds_start': 566,
    'cds_end': 3347}]],
 'CASQ2': [[{'transcript': 'NM_001232.4',
    'protein_id': 'NP_001223.2',
    'protein_seq': Seq('MKRTHLFIVGIYFLSSCRAEEGLNFPTYDGKDRVVSLSEKNFKQVLKKYDLLCL...DDE'),
    'cds_seq': Seq('atgaagagaactcacttgtttattgtggggatttattttctgtcctcttgcagg...tag'),
    'cds_start': 173,
    'cds_end': 1373}]],
 'CASR': [[{'transcript': 'NM_000388.4',
    'protein_id': 'NP_000379.3',
    'protein_seq': Seq('MAFYSCCWVLLALTWHTSAYGPDQRAQKKGDIILGGLFPIHFGVAAKDQDLKSR...VNS'),
    'cds_seq': Seq('atggcattttatagctgctgctgggtcctcttggcactcacctggcacacctct...taa'),
    'cds_start': 387,
    'cds_end': 3624}]],
 'CBS': [[{'transcript': 'NM_000071.3',
    'protein_id': 'NP_000062.1',
    'protein_seq': Seq('MPSETPQAEVGPTGCPHRSGPHSAKGSLEKGSPEDKEAKEPLWIRPDAPSRCTW...DQK'),
    'cds_seq': Seq('atgccttctgagaccccccaggcagaagtggggcccacaggctgcccccaccgc...tga'),
    'cds_start': 150,
    'cds_end': 1806}]],
 'CC2D2A': [[{'transcript': 'NM_001378615.1',
    'protein_id': 'NP_001365544.1',
    'protein_seq': Seq('MNPREEKVKIITEEFIENDEDADMGRQNKNSKVRRQPRKKQPPTAVPKEMVSEK...RNR'),
    'cds_seq': Seq('atgaatcccagggaagaaaaagtaaaaataattacagaggagttcattgaaaat...taa'),
    'cds_start': 194,
    'cds_end': 5057}]],
 'CCDC39': [[{'transcript': 'NM_181426.2',
    'protein_id': 'NP_852091.1',
    'protein_seq': Seq('MSSEFLAELHWEDGFAIPVANEENKLLEDQLSKLKDERASLQDELREYEERINS...SSK'),
    'cds_seq': Seq('atgagtagcgaattcctggctgagctgcactgggaggatgggttcgccatcccg...taa'),
    'cds_start': 109,
    'cds_end': 2935}]],
 'CCDC40': [[{'transcript': 'NM_017950.4',
    'protein_id': 'NP_060420.2',
    'protein_seq': Seq('MAEPGGAAGRSHPEDGSASEGEKEGNNESHMVSPPEKDDGQKGEEAVGSTEHPE...GPS'),
    'cds_seq': Seq('atggcggaaccgggcggcgcggcgggccggtcccatccggaagatggatcggct...tag'),
    'cds_start': 21,
    'cds_end': 3450}]],
 'CCDC88C': [[{'transcript': 'NM_001080414.4',
    'protein_id': 'NP_001073883.2',
    'protein_seq': Seq('MDVTVSELLELFLQSPLVTWVKTFGPFGSGSQDNLTMYMDLVDGIFLNQIMLQI...GCV'),
    'cds_seq': Seq('atggacgtgacagtctcggagctcctggagctcttcctgcagagcccgctggtg...tga'),
    'cds_start': 130,
    'cds_end': 6217}]],
 'CCM2': [[{'transcript': 'NM_031443.4',
    'protein_id': 'NP_113631.1',
    'protein_seq': Seq('MEEEGKKGKKPGIVSPFKRVFLKGEKSRDKKAHEKVTERRPLHTVVLSLPERVE...DSA'),
    'cds_seq': Seq('atggaagaggagggcaagaagggcaagaagcctggaattgtctcgccatttaaa...tga'),
    'cds_start': 133,
    'cds_end': 1468}]],
 'CD40LG': [[{'transcript': 'NM_000074.3',
    'protein_id': 'NP_000065.1',
    'protein_seq': Seq('MIETYNQTSPRSAATGLPISMKIFMYLLTVFLITQMIGSALFAVYLHRRLDKIE...LKL'),
    'cds_seq': Seq('atgatcgaaacatacaaccaaacttctccccgatctgcggccactggactgccc...tga'),
    'cds_start': 91,
    'cds_end': 877}]],
 'CDC73': [[{'transcript': 'NM_024529.5',
    'protein_id': 'NP_078805.3',
    'protein_seq': Seq('MADVLSVLRQYNIQKKEIVVKGDEVIFGEFSWPKNVKTNYVVWGTGKEGQPREY...LRF'),
    'cds_seq': Seq('atggcggacgtgcttagcgtcctgcgacagtacaacatccagaagaaggagatt...tga'),
    'cds_start': 170,
    'cds_end': 1766}]],
 'CDH1': [[{'transcript': 'NM_004360.5',
    'protein_id': 'NP_004351.1',
    'protein_seq': Seq('MGPWSRSLSALLLLLQVSSWLCQEPEPCHPGFDAESYTFTVPRRHLERGRVLGR...EDD'),
    'cds_seq': Seq('atgggcccttggagccgcagcctctcggcgctgctgctgctgctgcaggtctcc...tag'),
    'cds_start': 124,
    'cds_end': 2773}]],
 'CDH23': [[{'transcript': 'NM_022124.6',
    'protein_id': 'NP_071407.4',
    'protein_seq': Seq('MGRHVATSCHVAWLLVLISGCWGQVNRLPFFTNHFFDTYLLISEDTPVGSSVTQ...TEL'),
    'cds_seq': Seq('atggggcgccatgttgccaccagctgccacgtggcctggcttttggtgctgatc...tga'),
    'cds_start': 404,
    'cds_end': 10469}]],
 'CDHR1': [[{'transcript': 'NM_033100.4',
    'protein_id': 'NP_149091.1',
    'protein_seq': Seq('MRRCRWAALALGLLRLCLAQANFAPHFFDNGVGSTNGNMALFSLPEDTPVGSHV...AYF'),
    'cds_seq': Seq('atgaggcgctgccggtgggccgccctggccctggggctgctgcgcctctgcttg...tag'),
    'cds_start': 224,
    'cds_end': 2804}]],
 'CDK13': [[{'transcript': 'NM_003718.5',
    'protein_id': 'NP_003709.3',
    'protein_seq': Seq('MPSSSDTALGGGGGLSWAEKKLEERRKRRRFLSPQQPPLLLPLLQPQLLQPPPP...LPY'),
    'cds_seq': Seq('atgccgagcagctcggacacggcgctggggggaggcgggggcctgagctgggcg...tga'),
    'cds_start': 386,
    'cds_end': 4925}]],
 'CDKL5': [[{'transcript': 'NM_001037343.2',
    'protein_id': 'NP_001032420.1',
    'protein_seq': Seq('MKIPNIGNVMNKFEILGVVGEGAYGVVLKCRHKETHEIVAIKKFKDSEENEEVK...TGK'),
    'cds_seq': Seq('atgaagattcctaacattggtaatgtgatgaataaatttgagatccttggggtt...tga'),
    'cds_start': 249,
    'cds_end': 3342}],
  [{'transcript': 'NM_001323289.2',
    'protein_id': 'NP_001310218.1',
    'protein_seq': Seq('MKIPNIGNVMNKFEILGVVGEGAYGVVLKCRHKETHEIVAIKKFKDSEENEEVK...TAL'),
    'cds_seq': Seq('atgaagattcctaacattggtaatgtgatgaataaatttgagatccttggggtt...taa'),
    'cds_start': 250,
    'cds_end': 3133}]],
 'CDKN2A': [[{'transcript': 'NM_000077.5',
    'protein_id': 'NP_000068.1',
    'protein_seq': Seq('MEPAAGSSMEPSADWLATAAARGRVEEVRALLEAGALPNAPNSYGRRPIQVMMM...IPD'),
    'cds_seq': Seq('atggagccggcggcggggagcagcatggagccttcggctgactggctggccacg...tga'),
    'cds_start': 30,
    'cds_end': 501}],
  [{'transcript': 'NM_058195.4',
    'protein_id': 'NP_478102.2',
    'protein_seq': Seq('MVRRFLVTLRIRRACGPPRVRVFVVHIPRLTGEWAAPGAPAAVALVLMLLRSQR...GPG'),
    'cds_seq': Seq('atggtgcgcaggttcttggtgaccctccggattcggcgcgcgtgcggcccgccg...tga'),
    'cds_start': 61,
    'cds_end': 460}]],
 'CEP152': [[{'transcript': 'NM_001194998.2',
    'protein_id': 'NP_001181927.1',
    'protein_seq': Seq('MSLDFGSVALPVQNEDEEYDEEDYEREKELQQLLTDLPHDMLDDDLSSPELQYS...NLD'),
    'cds_seq': Seq('atgtcattagactttggcagtgtggcactaccagtgcaaaatgaagatgaagag...taa'),
    'cds_start': 116,
    'cds_end': 5249}]],
 'CEP164': [[{'transcript': 'NM_014956.5',
    'protein_id': 'NP_055771.4',
    'protein_seq': Seq('MAGRPLRIGDQLVLEEDYDETYIPSEQEILEFAREIGIDPIKEPELMWLAREGI...YRF'),
    'cds_seq': Seq('atggctggacgacccctccgcataggagatcagctggttctggaagaagattat...tga'),
    'cds_start': 148,
    'cds_end': 4531}]],
 'CEP250': [[{'transcript': 'NM_007186.6',
    'protein_id': 'NP_009117.2',
    'protein_seq': Seq('METRSPGLNNMKPQSLQLVLEEQVLALQQQMAENQAASWRKLKNSQEAQQRQAT...ASR'),
    'cds_seq': Seq('atggagacaagaagccctgggttgaacaacatgaagccccagtcactgcagctg...tag'),
    'cds_start': 451,
    'cds_end': 7780}]],
 'CEP290': [[{'transcript': 'NM_025114.4',
    'protein_id': 'NP_079390.3',
    'protein_seq': Seq('MPPNINWKEIMKVDPDDLPRQEELADNLLISLSKVEVNELKSEKQENVIHLFRI...PIY'),
    'cds_seq': Seq('atgccacctaatataaactggaaagaaataatgaaagttgacccagatgacctg...taa'),
    'cds_start': 216,
    'cds_end': 7656}]],
 'CERKL': [[{'transcript': 'NM_201548.5',
    'protein_id': 'NP_963842.1',
    'protein_seq': Seq('MPWRRRRNRVSALEGGREEEAPPEAAAVPPALLTSPQQTEAAAERILLRGIFEI...IPK'),
    'cds_seq': Seq('atgccctggaggaggcgcaggaaccgggtgagtgccctggagggcggccgggag...taa'),
    'cds_start': 99,
    'cds_end': 1698}]],
 'CFH': [[{'transcript': 'NM_000186.4',
    'protein_id': 'NP_000177.2',
    'protein_seq': Seq('MRLLAKIICLMLWAICVAEDCNELPPRRNTEILTGSWSDQTYPEGTQAIYKCRP...AKR'),
    'cds_seq': Seq('atgagacttctagcaaagattatttgccttatgttatgggctatttgtgtagca...tag'),
    'cds_start': 75,
    'cds_end': 3771}]],
 'CFI': [[{'transcript': 'NM_000204.5',
    'protein_id': 'NP_000195.3',
    'protein_seq': Seq('MKLLHVFLLFLCFHLRFCKVTYTSQEDLVEKKCLAKKYTHLSCDKVFCQPWQRC...YNV'),
    'cds_seq': Seq('atgaagcttcttcatgttttcctgttatttctgtgcttccacttaaggttttgc...taa'),
    'cds_start': 28,
    'cds_end': 1780}]],
 'CFTR': [[{'transcript': 'NM_000492.3',
    'protein_id': 'NP_000483.3',
    'protein_seq': Seq('MQRSPLEKASVVSKLFFSWTRPILRKGYRQRLELSDIYQIPSVDSADNLSEKLE...TRL'),
    'cds_seq': Seq('atgcagaggtcgcctctggaaaaggccagcgttgtctccaaactttttttcagc...tag'),
    'cds_start': 132,
    'cds_end': 4575}],
  [{'transcript': 'NM_000492.4',
    'protein_id': 'NP_000483.3',
    'protein_seq': Seq('MQRSPLEKASVVSKLFFSWTRPILRKGYRQRLELSDIYQIPSVDSADNLSEKLE...TRL'),
    'cds_seq': Seq('atgcagaggtcgcctctggaaaaggccagcgttgtctccaaactttttttcagc...tag'),
    'cds_start': 70,
    'cds_end': 4513}]],
 'CHAT': [[{'transcript': 'NM_020549.5',
    'protein_id': 'NP_065574.4',
    'protein_seq': Seq('MGLRTAKKRGLGGGGKWKREEGGGTRGRREVRPACFLQSGGRGDPGDVGGPAGN...HQP'),
    'cds_seq': Seq('atggggctgaggacagcgaagaagagggggcttgggggaggggggaaatggaag...tga'),
    'cds_start': 153,
    'cds_end': 2400}]],
 'CHD2': [[{'transcript': 'NM_001271.4',
    'protein_id': 'NP_001262.3',
    'protein_seq': Seq('MMRNKDKSQEEDSSLHSNASSHSASEEASGSDSGSQSESEQGSDPGSGHGSESN...RKT'),
    'cds_seq': Seq('atgatgagaaataaggacaaaagccaagaggaggacagttcgctacacagcaat...taa'),
    'cds_start': 572,
    'cds_end': 6059}]],
 'CHD3': [[{'transcript': 'NM_001005273.3',
    'protein_id': 'NP_001005273.1',
    'protein_seq': Seq('MKAADTVILWARSKNDQLRISFPPGLCWGDRMPDKDDIRLLPSALGVKKRKRGP...IDD'),
    'cds_seq': Seq('atgaaggcggcagacactgtgatcctgtgggcaagaagtaaaaatgaccagctg...tga'),
    'cds_start': 212,
    'cds_end': 6215}]],
 'CHD4': [[{'transcript': 'NM_001273.5',
    'protein_id': 'NP_001264.2',
    'protein_seq': Seq('MASGLGSPSPCSAGSEEEDMDALLNNSLPPPHPENEEDPEEDLSETETPKLKKK...QQQ'),
    'cds_seq': Seq('atggcgtcgggcctgggctccccgtccccctgctcggcgggcagtgaggaggag...tga'),
    'cds_start': 158,
    'cds_end': 5897}]],
 'CHD7': [[{'transcript': 'NM_017780.4',
    'protein_id': 'NP_060250.2',
    'protein_seq': Seq('MADPGMMSLFGEDGNIFSEGLEGLGECGYPENPVNPMGQQMPIDQGFASLQPSL...NDE'),
    'cds_seq': Seq('atggcagatccaggaatgatgagtctttttggcgaggatgggaatattttcagt...taa'),
    'cds_start': 517,
    'cds_end': 9511}]],
 'CHD8': [[{'transcript': 'NM_001170629.2',
    'protein_id': 'NP_001164100.1',
    'protein_seq': Seq('MADPIMDLFDDPNLFGLDSLTDDSFNQVTQDPIEEALGLPSSLDSLDQMNQDGG...ADD'),
    'cds_seq': Seq('atggcagaccccatcatggatctgttcgatgacccaaatttatttggcctggac...tga'),
    'cds_start': 307,
    'cds_end': 8053}]],
 'CHEK2': [[{'transcript': 'NM_007194.4',
    'protein_id': 'NP_009125.1',
    'protein_seq': Seq('MSRESDVEAQQSHGSSACSQPHGSVTQSQGSSSQSQGISSSSTSTMPNSSQSSH...AVL'),
    'cds_seq': Seq('atgtctcgggagtcggatgttgaggctcagcagtctcatggcagcagtgcctgt...tga'),
    'cds_start': 58,
    'cds_end': 1690}]],
 'CHM': [[{'transcript': 'NM_000390.4',
    'protein_id': 'NP_000381.1',
    'protein_seq': Seq('MADTLPSEFDVIVIGTGLPESIIAAACSRSGRRVLHVDSRSYYGGNWASFSFSG...SSE'),
    'cds_seq': Seq('atggcggatactctcccttcggagtttgatgtgatcgtaatagggacgggtttg...taa'),
    'cds_start': 26,
    'cds_end': 1988}]],
 'CHRNE': [[{'transcript': 'NM_000080.4',
    'protein_id': 'NP_000071.1',
    'protein_seq': Seq('MARAPLGVLLLLGLLGRGVGKNEELRLYHHLFNNYDPGSRPVREPEDTVTISLK...IQP'),
    'cds_seq': Seq('atggcaagggctccgcttggggtcctgctcctcttggggcttctcggcaggggt...tag'),
    'cds_start': 35,
    'cds_end': 1517}]],
 'CLCN1': [[{'transcript': 'NM_000083.3',
    'protein_id': 'NP_000074.3',
    'protein_seq': Seq('MEQSRSQQRGGEQSWWGSDPQYQYMPFEHCTSYGLPSENGGLQHRLRKDAGPRH...LIL'),
    'cds_seq': Seq('atggagcaatcccggtcacagcagcgtgggggtgaacaaagctggtggggtagt...tga'),
    'cds_start': 102,
    'cds_end': 3069}]],
 'CLCN4': [[{'transcript': 'NM_001830.4',
    'protein_id': 'NP_001821.2',
    'protein_seq': Seq('MVNAGAMSGSGNLMDFLDEPFPDVGTYEDFHTIDWLREKSRDTDRHRKITSKSK...MFN'),
    'cds_seq': Seq('atggtcaatgcgggagcgatgagtggctctggaaacctgatggatttcctcgat...tag'),
    'cds_start': 400,
    'cds_end': 2683}]],
 'CLCN5': [[{'transcript': 'NM_001127898.4',
    'protein_id': 'NP_001121370.1',
    'protein_seq': Seq('MAMWQGAMDNRGFQQGSFSSFQNSSSDEDLMDIPATAMDFSMRDDVPPLDREVG...LFN'),
    'cds_seq': Seq('atggccatgtggcagggtgccatggataacagaggctttcagcaggggagtttt...tag'),
    'cds_start': 401,
    'cds_end': 2852}]],
 'CLCN7': [[{'transcript': 'NM_001287.6',
    'protein_id': 'NP_001278.1',
    'protein_seq': Seq('MANVSKKVSWSGRDRDDEEAAPLLRRTARPGGGTPLLNGAGPGAARQSPRSALF...AQT'),
    'cds_seq': Seq('atggccaacgtctctaagaaggtgtcctggtccggccgggaccgggacgacgag...tga'),
    'cds_start': 54,
    'cds_end': 2472}]],
 'CLCNKB': [[{'transcript': 'NM_000085.5',
    'protein_id': 'NP_000076.2',
    'protein_seq': Seq('MEEFVGLREGSSGNPVTLQELWGPCPRIRRGIRGGLEWLKQKLFRLGEDWYFLM...APK'),
    'cds_seq': Seq('atggaggagtttgtggggctgcgtgaaggctcctcagggaaccctgtgactctg...tga'),
    'cds_start': 106,
    'cds_end': 2170}]],
 'CLN3': [[{'transcript': 'NM_001042432.2',
    'protein_id': 'NP_001035897.1',
    'protein_seq': Seq('MGGCAGSRRRFSDSEGEETVPEPRLPLLDHQGAHWKNAVGFWLLGLCNNFSYVV...QLS'),
    'cds_seq': Seq('atgggaggctgtgcaggctcgcggcggcgcttttcggattccgagggggaggag...tga'),
    'cds_start': 131,
    'cds_end': 1448}]],
 'CLN5': [[{'transcript': 'NM_006493.2',
    'protein_id': 'NP_006484.1',
    'protein_seq': Seq('MRRNLRLGPSSGADAQGQGAPRPGLAAPRMLLPPASQASRGSGSTGCSLMAQEV...SGL'),
    'cds_seq': Seq('atgcgccggaacctgcgcttggggccaagctctggagctgacgcgcaggggcaa...taa'),
    'cds_start': 28,
    'cds_end': 1252}],
  [{'transcript': 'NM_006493.4',
    'protein_id': 'NP_006484.2',
    'protein_seq': Seq('MAQEVDTAQGAEMRRGAGAARGRASWCWALALLWLAVVPGWSRVSGIPSRRHWP...SGL'),
    'cds_seq': Seq('atggcgcaggaggtagacacggcacagggcgccgagatgcggcggggcgcgggc...taa'),
    'cds_start': 18,
    'cds_end': 1095}]],
 'CLN6': [[{'transcript': 'NM_017882.3',
    'protein_id': 'NP_060352.1',
    'protein_seq': Seq('MEATRRRQHLGATGGPGAQLGASFLQARHGSVSADEAARTAPFHLDLWFYFTLQ...SRH'),
    'cds_seq': Seq('atggaggcgacgcggaggcggcagcacctgggagcgacgggcggcccaggcgcg...tga'),
    'cds_start': 144,
    'cds_end': 1080}]],
 'CLN8': [[{'transcript': 'NM_018941.4',
    'protein_id': 'NP_061764.2',
    'protein_seq': Seq('MNPASDGGTSESIFDLDYASWGIRSTLMVAGFVFYLGVFVVCHQLSSSLNATYR...KRP'),
    'cds_seq': Seq('atgaatcctgcgagcgatgggggcacatcagagagcatttttgacctggactat...tag'),
    'cds_start': 220,
    'cds_end': 1081}]],
 'CLRN1': [[{'transcript': 'NM_052995.2',
    'protein_id': 'NP_443721.1',
    'protein_seq': Seq('MQALQQQPVFPDLLKAIPVSIHVNVILFSAILIVLTMVGTAFFMYNAFGKPFET...GHS'),
    'cds_seq': Seq('atgcaggccctgcagcagcaaccagtttttccagatttgctcaaagcaatccca...tga'),
    'cds_start': 392,
    'cds_end': 755}],
  [{'transcript': 'NM_174878.3',
    'protein_id': 'NP_777367.1',
    'protein_seq': Seq('MPSQQKKIIFCMAGVFSFACALGVVTALGTPLWIKATVLCKTGALLVNASGQEL...LMY'),
    'cds_seq': Seq('atgccaagccaacagaagaaaatcattttttgcatggccggagtgttcagtttt...tga'),
    'cds_start': 19,
    'cds_end': 718}]],
 'CLTC': [[{'transcript': 'NM_004859.4',
    'protein_id': 'NP_004850.1',
    'protein_seq': Seq('MAQILPIRFQEHLQLQNLGINPANIGFSTLTMESDKFICIREKVGEQAQVVIID...YSM'),
    'cds_seq': Seq('atggcccagattctgccaattcgttttcaggagcatctccagctccagaacctg...tga'),
    'cds_start': 237,
    'cds_end': 5265}]],
 'CNGA3': [[{'transcript': 'NM_001298.3',
    'protein_id': 'NP_001289.1',
    'protein_seq': Seq('MAKINTQYSHPSRTHLKVKTSDRDLNRAENGLSRAHSSSEETSSVLQPGIAMET...KQQ'),
    'cds_seq': Seq('atggccaagatcaacacccaatactcccacccctccaggacccacctcaaggta...tga'),
    'cds_start': 116,
    'cds_end': 2201}]],
 'CNGB1': [[{'transcript': 'NM_001297.5',
    'protein_id': 'NP_001288.3',
    'protein_seq': Seq('MLGWVQRVLPQPPGTPRKTKMQEEEEVEPEPEMEAEVEPEPNPEEAETESESMP...KAE'),
    'cds_seq': Seq('atgttgggctgggtccagagggtgctgcctcagcccccagggacccctcggaag...taa'),
    'cds_start': 77,
    'cds_end': 3833}]],
 'CNGB3': [[{'transcript': 'NM_019098.5',
    'protein_id': 'NP_061971.3',
    'protein_seq': Seq('MFKSLTKVNKVKPIGENNENEQSSRRNEEGSHPSNQSQQTTAQEENKGEEKSLK...AKQ'),
    'cds_seq': Seq('atgtttaaatcgctgacaaaagtcaacaaggtgaagcctataggagagaacaat...taa'),
    'cds_start': 7,
    'cds_end': 2437}]],
 'CNTNAP2': [[{'transcript': 'NM_014141.6',
    'protein_id': 'NP_054860.1',
    'protein_seq': Seq('MQAAPRAGCGAALLLWIVSSCLCRAWTAPSTSQKCDEPLVSGLPHVAFSSSSSI...WLI'),
    'cds_seq': Seq('atgcaggcggctccgcgcgccggctgcggggcagcgctcctgctgtggattgtc...tga'),
    'cds_start': 76,
    'cds_end': 4072}]],
 'COL11A1': [[{'transcript': 'NM_001854.4',
    'protein_id': 'NP_001845.3',
    'protein_seq': Seq('MEPWSSRWKTKRWLWDFTVTTLALTFLFQAREVRGAAPVDVLKALDFHNSPEGI...FLG'),
    'cds_seq': Seq('atggagccgtggtcctctaggtggaaaacgaaacggtggctctgggatttcacc...taa'),
    'cds_start': 344,
    'cds_end': 5765}]],
 'COL11A2': [[{'transcript': 'NM_080680.3',
    'protein_id': 'NP_542411.2',
    'protein_seq': Seq('MERCSRCHRLLLLLPLVLGLSAAPGWAGAPPVDVLRALRFPSLPDGVRRAKGIC...FMG'),
    'cds_seq': Seq('atggagcggtgcagccgctgccatcgcctcctcctcctcctacctctggtgctg...tag'),
    'cds_start': 227,
    'cds_end': 5438}]],
 'COL12A1': [[{'transcript': 'NM_004370.6',
    'protein_id': 'NP_004361.3',
    'protein_seq': Seq('MRSRLPPALAALGAALLLSSIEAEVDPPSDLNFKIIDENTVHMSWAKPVDPIVG...GSG'),
    'cds_seq': Seq('atgcggagtaggcttcccccagcgcttgccgccctgggcgcggccctgctcctg...taa'),
    'cds_start': 312,
    'cds_end': 9504}]],
 'COL17A1': [[{'transcript': 'NM_000494.4',
    'protein_id': 'NP_000485.3',
    'protein_seq': Seq('MDVTKKNKRDGTEVTERIVTETVTTRLTSLPPKGGTSNGYAKTASLGGGSRLEK...VKP'),
    'cds_seq': Seq('atggatgtaaccaagaaaaacaaacgagatggaactgaagtcactgagagaatt...tga'),
    'cds_start': 169,
    'cds_end': 4663}]],
 'COL18A1': [[{'transcript': 'NM_001379500.1',
    'protein_id': 'NP_001366429.1',
    'protein_seq': Seq('MAPRCPWPWPRRRRLLDVLAPLVLLLGVRAASAEPERISEEVGLLQLLGDPPPQ...ASK'),
    'cds_seq': Seq('atggcgccgaggtgcccctggccatggccgcggcggcggcgcctcctggacgtg...tag'),
    'cds_start': 66,
    'cds_end': 4086}]],
 'COL1A1': [[{'transcript': 'NM_000088.4',
    'protein_id': 'NP_000079.2',
    'protein_seq': Seq('MFSFVDLRLLLLLAATALLTHGQEEGQVEGQDEDIPPITCVQNGLRYHDRDVWK...CFL'),
    'cds_seq': Seq('atgttcagctttgtggacctccggctcctgctcctcttagcggccaccgccctc...taa'),
    'cds_start': 118,
    'cds_end': 4513}]],
 'COL1A2': [[{'transcript': 'NM_000089.4',
    'protein_id': 'NP_000080.2',
    'protein_seq': Seq('MLSFVDTRTLLLLAVTLCLATCQSLQEETVRKGPAGDRGPRGERGPPGPPGRDG...CFK'),
    'cds_seq': Seq('atgctcagctttgtggatacgcggactttgttgctgcttgcagtaaccttatgc...taa'),
    'cds_start': 137,
    'cds_end': 4238}]],
 'COL27A1': [[{'transcript': 'NM_032888.4',
    'protein_id': 'NP_116277.2',
    'protein_seq': Seq('MGAGSARGARGTAAAAAARGGGFLFSWILVSFACHLASTQGAPEDVDILQRLGL...CFL'),
    'cds_seq': Seq('atgggagcgggatcggcgcggggggcccgaggcacagcggcggcggcggcggcg...tga'),
    'cds_start': 414,
    'cds_end': 5997}]],
 'COL2A1': [[{'transcript': 'NM_001844.5',
    'protein_id': 'NP_001835.3',
    'protein_seq': Seq('MIRLGAPQTLVLLTLLVAAVLRCQGQDVQEAGSCVQDGQRYNDKDVWKPEPCRI...CFL'),
    'cds_seq': Seq('atgattcgcctcggggctccccagacgctggtgctgctgacgctgctcgtcgcc...taa'),
    'cds_start': 155,
    'cds_end': 4619}]],
 'COL3A1': [[{'transcript': 'NM_000090.4',
    'protein_id': 'NP_000081.2',
    'protein_seq': Seq('MMSFVQKGSWLLLALLHPTIILAQQEAVEGGCSHLGQSYADRDVWKPEPCQICV...CFL'),
    'cds_seq': Seq('atgatgagctttgtgcaaaaggggagctggctacttctcgctctgcttcatccc...taa'),
    'cds_start': 117,
    'cds_end': 4518}]],
 'COL4A1': [[{'transcript': 'NM_001845.6',
    'protein_id': 'NP_001836.3',
    'protein_seq': Seq('MGPRLSVWLLLLPAALLLHEEHSRAAAKGGCAGSGCGKCDCHGVKGQKGERGLP...RRT'),
    'cds_seq': Seq('atggggccccggctcagcgtctggctgctgctgctgcccgccgcccttctgctc...taa'),
    'cds_start': 130,
    'cds_end': 5140}]],
 'COL4A2': [[{'transcript': 'NM_001846.4',
    'protein_id': 'NP_001837.2',
    'protein_seq': Seq('MGRDQRAVAGPALRRWLLLGTVTVGFLAQSVLAGVKKFDVPCGGRDCSGGCQCY...KNL'),
    'cds_seq': Seq('atggggagagaccagcgcgcggtggccggccctgccctacggcggtggctgctg...tga'),
    'cds_start': 289,
    'cds_end': 5428}]],
 'COL4A3': [[{'transcript': 'NM_000091.4',
    'protein_id': 'NP_000082.2',
    'protein_seq': Seq('MSARTAPRPQVLLLPLLLVLLAAAPAASKGCVCKDKGQCFCDGAKGEKGEKGFP...KRH'),
    'cds_seq': Seq('atgagcgcccggaccgcccccaggccgcaggtgctcctgctgccgctcctgctg...tga'),
    'cds_start': 162,
    'cds_end': 5175}],
  [{'transcript': 'NM_000091.5',
    'protein_id': 'NP_000082.2',
    'protein_seq': Seq('MSARTAPRPQVLLLPLLLVLLAAAPAASKGCVCKDKGQCFCDGAKGEKGEKGFP...KRH'),
    'cds_seq': Seq('atgagcgcccggaccgcccccaggccgcaggtgctcctgctgccgctcctgctg...tga'),
    'cds_start': 103,
    'cds_end': 5116}]],
 'COL4A4': [[{'transcript': 'NM_000092.5',
    'protein_id': 'NP_000083.3',
    'protein_seq': Seq('MWSLHIVLMRCSFRLTKSLATGPWSLILILFSVQYVYGSGKKYIGPCGGRDCSV...KYS'),
    'cds_seq': Seq('atgtggtctctgcacatagtactaatgaggtgctccttcagattgaccaagtcc...tag'),
    'cds_start': 300,
    'cds_end': 5373}]],
 'COL4A5': [[{'transcript': 'NM_033380.2',
    'protein_id': 'NP_203699.1',
    'protein_seq': Seq('MKLRGVSLAAGLFLLALSLWGQPAEAAACYGCSPGSKCDCSGIKGEKGERGFPG...KRT'),
    'cds_seq': Seq('atgaaactgcgtggagtcagcctggctgccggcttgttcttactggccctgagt...taa'),
    'cds_start': 282,
    'cds_end': 5358}],
  [{'transcript': 'NM_033380.3',
    'protein_id': 'NP_203699.1',
    'protein_seq': Seq('MKLRGVSLAAGLFLLALSLWGQPAEAAACYGCSPGSKCDCSGIKGEKGERGFPG...KRT'),
    'cds_seq': Seq('atgaaactgcgtggagtcagcctggctgccggcttgttcttactggccctgagt...taa'),
    'cds_start': 288,
    'cds_end': 5364}]],
 'COL5A1': [[{'transcript': 'NM_000093.5',
    'protein_id': 'NP_000084.3',
    'protein_seq': Seq('MDVHTRWKARSALRPGAPLLPPLLLLLLWAPPPSRAAQPADLLKVLDFHNLPDG...FMG'),
    'cds_seq': Seq('atggacgtccatacccgctggaaagcgcgcagcgcgctccgcccgggcgccccg...tag'),
    'cds_start': 385,
    'cds_end': 5902}]],
 'COL5A2': [[{'transcript': 'NM_000393.5',
    'protein_id': 'NP_000384.2',
    'protein_seq': Seq('MMANWAEARPLLILIVLLGQFVSIKAQEEDEDEGYGEEIACTQNGQMYLNRDIW...CFV'),
    'cds_seq': Seq('atgatggcaaactgggcggaagcaagacctctcctcattcttattgttttatta...taa'),
    'cds_start': 157,
    'cds_end': 4657}]],
 'COL6A1': [[{'transcript': 'NM_001848.3',
    'protein_id': 'NP_001839.2',
    'protein_seq': Seq('MRAARALLPLLLQACWTAAQDEPETPRAVAFQDCPVDLFFVLDTSESVALRLKP...ALG'),
    'cds_seq': Seq('atgagggcggcccgtgctctgctgcccctgctgctgcaggcctgctggacagcc...tag'),
    'cds_start': 81,
    'cds_end': 3168}]],
 'COL6A2': [[{'transcript': 'NM_001849.4',
    'protein_id': 'NP_001840.3',
    'protein_seq': Seq('MLQGTCSVLLLWGILGAIQAQQQEVISPDTTERNNNCPEKTDCPIHVYFVLDTS...WIC'),
    'cds_seq': Seq('atgctccagggcacctgctccgtgctcctgctctggggaatcctgggggccatc...tag'),
    'cds_start': 89,
    'cds_end': 3149}],
  [{'transcript': 'NM_058174.3',
    'protein_id': 'NP_478054.2',
    'protein_seq': Seq('MLQGTCSVLLLWGILGAIQAQQQEVISPDTTERNNNCPEKTDCPIHVYFVLDTS...ALC'),
    'cds_seq': Seq('atgctccagggcacctgctccgtgctcctgctctggggaatcctgggggccatc...taa'),
    'cds_start': 89,
    'cds_end': 2846}]],
 'COL6A3': [[{'transcript': 'NM_004369.4',
    'protein_id': 'NP_004360.2',
    'protein_seq': Seq('MRKHRHLPLVAVFCLFLSGFPTTHAQQQQADVKNGAAADIIFLVDSSWTIGEEH...MGT'),
    'cds_seq': Seq('atgaggaaacatcggcacttgcccttagtggccgtcttttgcctctttctctca...taa'),
    'cds_start': 242,
    'cds_end': 9776}]],
 'COL7A1': [[{'transcript': 'NM_000094.3',
    'protein_id': 'NP_000085.1',
    'protein_seq': Seq('MTLRLLVAALCAGILAEAPRVRAQHRERVTCTRLYAADIVFLLDGSSSIGRSNF...AQD'),
    'cds_seq': Seq('atgacgctgcggcttctggtggccgcgctctgcgccgggatcctggcagaggcg...tga'),
    'cds_start': 1,
    'cds_end': 8836}],
  [{'transcript': 'NM_000094.4',
    'protein_id': 'NP_000085.1',
    'protein_seq': Seq('MTLRLLVAALCAGILAEAPRVRAQHRERVTCTRLYAADIVFLLDGSSSIGRSNF...AQD'),
    'cds_seq': Seq('atgacgctgcggcttctggtggccgcgctctgcgccgggatcctggcagaggcg...tga'),
    'cds_start': 63,
    'cds_end': 8898}]],
 'COL9A1': [[{'transcript': 'NM_001851.6',
    'protein_id': 'NP_001842.3',
    'protein_seq': Seq('MKTCWKIPVFFFVCSFLEPWASAAVKRRPRFPVNSNSNGGNELCPKIRIGQDDL...PDP'),
    'cds_seq': Seq('atgaagacctgctggaaaattccagttttcttctttgtgtgcagtttcctggaa...tga'),
    'cds_start': 160,
    'cds_end': 2926}]],
 'COLQ': [[{'transcript': 'NM_005677.4',
    'protein_id': 'NP_005668.2',
    'protein_seq': Seq('MVVLNPMTLGIYLQLFFLSIVSQPTFINSVLPISAALPSLDQKKRGGHKACCLL...YFT'),
    'cds_seq': Seq('atggttgtcctgaatccaatgactttgggaatttatcttcagcttttcttcctc...tga'),
    'cds_start': 81,
    'cds_end': 1449}]],
 'COMP': [[{'transcript': 'NM_000095.3',
    'protein_id': 'NP_000086.2',
    'protein_seq': Seq('MVPDTACVLLLTLAALGASGQGQSPLGSDLGPQMLRELQETNAALQDVRELLRQ...RQA'),
    'cds_seq': Seq('atggtccccgacaccgcctgcgttcttctgctcaccctggctgccctcggcgcg...tag'),
    'cds_start': 36,
    'cds_end': 2310}]],
 'COQ8A': [[{'transcript': 'NM_020247.5',
    'protein_id': 'NP_064632.2',
    'protein_seq': Seq('MAAILGDTIMVAKGLVKLTQAAVETHLQHLGIGGELIMAARALQSTAVEQIGMF...AQQ'),
    'cds_seq': Seq('atggctgccatattgggagacaccatcatggtggctaaaggccttgtcaagctg...tag'),
    'cds_start': 115,
    'cds_end': 2059}]],
 'CP': [[{'transcript': 'NM_000096.4',
    'protein_id': 'NP_000087.2',
    'protein_seq': Seq('MKILILGIFLFLCSTPAWAKEKHYYIGIIETTWDYASDHGEKKLISVDTEHSNI...KSG'),
    'cds_seq': Seq('atgaagattttgatacttggtatttttctgtttttatgtagtaccccagcctgg...tga'),
    'cds_start': 37,
    'cds_end': 3235}]],
 'CPLANE1': [[{'transcript': 'NM_001384732.1',
    'protein_id': 'NP_001371661.1',
    'protein_seq': Seq('MEIRLEILTSTGIKQKKPWPRVSWLGKEKEAVFLLDDKFINEINLLSGKIKKKI...LDL'),
    'cds_seq': Seq('atggagataagattagaaatcttgacatcaacaggtattaagcagaaaaaacca...taa'),
    'cds_start': 179,
    'cds_end': 9935}]],
 'CPS1': [[{'transcript': 'NM_001875.5',
    'protein_id': 'NP_001866.2',
    'protein_seq': Seq('MTRILTAFKVVRTLKTGFGFTNVTAHQKWKFSRPGIRLLSVKAQTAHIVLEDGT...KAA'),
    'cds_seq': Seq('atgacgaggattttgacagctttcaaagtggtgaggacactgaagactggtttt...tag'),
    'cds_start': 135,
    'cds_end': 4638}]],
 'CPT1A': [[{'transcript': 'NM_001876.4',
    'protein_id': 'NP_001867.2',
    'protein_seq': Seq('MAEAHQAVAFQFTVTPDGIDLRLSHEALRQIYLSGLHSWKKKFIRFKNGIITGV...SKK'),
    'cds_seq': Seq('atggcagaagctcaccaagctgtggcctttcagttcacggtcactccggacggg...taa'),
    'cds_start': 155,
    'cds_end': 2477}]],
 'CPT2': [[{'transcript': 'NM_000098.3',
    'protein_id': 'NP_000089.1',
    'protein_seq': Seq('MVPRLLLRAWPRGPAVGPGAPSRPLSAGSGPGQYLQRSIVPTMHYQDSLPRLPI...IKS'),
    'cds_seq': Seq('atggtgccccgcctgctgctgcgcgcctggccccggggccccgcggttggtccg...taa'),
    'cds_start': 120,
    'cds_end': 2097}]],
 'CRB1': [[{'transcript': 'NM_201253.3',
    'protein_id': 'NP_957705.1',
    'protein_seq': Seq('MALKNINYLLIFYLSFSLLIYIKNSFCNKNNTRCLSNSCQNNSTCKDFSKDNDC...RLI'),
    'cds_seq': Seq('atggcacttaagaacattaactaccttctcatcttctacctcagtttctcactg...tag'),
    'cds_start': 161,
    'cds_end': 4382}]],
 'CREBBP': [[{'transcript': 'NM_004380.3',
    'protein_id': 'NP_004371.2',
    'protein_seq': Seq('MAENLLDGPPNPKRAKLSSPGFSANDSTDFGSLFDLENDLPDELIPNGGELGLL...EGL'),
    'cds_seq': Seq('atggctgagaacttgctggacggaccgcccaaccccaaaagagccaaactcagc...tag'),
    'cds_start': 797,
    'cds_end': 8126}]],
 'CSF1R': [[{'transcript': 'NM_001288705.3',
    'protein_id': 'NP_001275634.1',
    'protein_seq': Seq('MGPGVLLLLLVATAWHGQGIPVIEPSVPELVVKPGATVTLRCVGNGSVEWDGPP...QFC'),
    'cds_seq': Seq('atgggcccaggagttctgctgctcctgctggtggccacagcttggcatggtcag...tga'),
    'cds_start': 127,
    'cds_end': 3046}],
  [{'transcript': 'NM_005211.3',
    'protein_id': 'NP_005202.2',
    'protein_seq': Seq('MGPGVLLLLLVATAWHGQGIPVIEPSVPELVVKPGATVTLRCVGNGSVEWDGPP...QFC'),
    'cds_seq': Seq('atgggcccaggagttctgctgctcctgctggtggccacagcttggcatggtcag...tga'),
    'cds_start': 292,
    'cds_end': 3211}]],
 'CSNK2A1': [[{'transcript': 'NM_177559.3',
    'protein_id': 'NP_808227.1',
    'protein_seq': Seq('MSGPVPSRARVYTDVNTHRPREYWDYESHVVEWGNQDDYQLVRKLGRGKYSEVF...AQQ'),
    'cds_seq': Seq('atgtcgggacccgtgccaagcagggccagagtttacacagatgttaatacacac...taa'),
    'cds_start': 345,
    'cds_end': 1521}]],
 'CSNK2B': [[{'transcript': 'NM_001320.7',
    'protein_id': 'NP_001311.3',
    'protein_seq': Seq('MSSSEEVSWISWFCGLRGNEFFCEVDEDYIQDKFNLTGLNEQVPHYRQALDMIL...TIR'),
    'cds_seq': Seq('atgagcagctcagaggaggtgtcctggatttcctggttctgtgggctccgtggc...tga'),
    'cds_start': 140,
    'cds_end': 788}]],
 'CSPP1': [[{'transcript': 'NM_001382391.1',
    'protein_id': 'NP_001369320.1',
    'protein_seq': Seq('MADNLDEFIEEQKARLAEDKAELESDPPYMEMKGKLSAKLSENSKILISMAKEN...AHG'),
    'cds_seq': Seq('atggctgataatttggatgaatttattgaagagcaaaaagccagattggccgaa...taa'),
    'cds_start': 157,
    'cds_end': 3838}]],
 'CTC1': [[{'transcript': 'NM_025099.6',
    'protein_id': 'NP_079375.3',
    'protein_seq': Seq('MAAGRAQVPSSEQAWLEDAQVFIQKTLCPAVKEPNVQLTPLVIDCVKTVWLSQG...SSC'),
    'cds_seq': Seq('atggcggctggccgggcccaggtcccttcctccgaacaagcctggcttgaggat...taa'),
    'cds_start': 20,
    'cds_end': 3674}]],
 'CTCF': [[{'transcript': 'NM_006565.4',
    'protein_id': 'NP_006556.1',
    'protein_seq': Seq('MEGDAVEAIVEESETFIKGKERKTYQRRREGGQEEDACHLPQNQTDGGEVVQDV...MDR'),
    'cds_seq': Seq('atggaaggtgatgcagtcgaagccattgtggaggagtccgaaacttttattaaa...tga'),
    'cds_start': 325,
    'cds_end': 2509}]],
 'CTNNA1': [[{'transcript': 'NM_001903.5',
    'protein_id': 'NP_001894.2',
    'protein_seq': Seq('MTAVHAGNINFKWDPKSLEIRTLAVERLLEPLVTQVTTLVNTNSKGPSNKKRGR...DSI'),
    'cds_seq': Seq('atgactgctgtccatgcaggcaacataaacttcaagtgggatcctaaaagtcta...taa'),
    'cds_start': 88,
    'cds_end': 2809}]],
 'CTNNB1': [[{'transcript': 'NM_001904.4',
    'protein_id': 'NP_001895.1',
    'protein_seq': Seq('MATQADLMELDMAMEPDRKAAVSHWQQQSYLDSGIHSGATTTAPSLSGKGNPEE...TDL'),
    'cds_seq': Seq('atggctactcaagctgatttgatggagttggacatggccatggaaccagacaga...taa'),
    'cds_start': 214,
    'cds_end': 2560}]],
 'CTNS': [[{'transcript': 'NM_004937.3',
    'protein_id': 'NP_004928.2',
    'protein_seq': Seq('MIRNWLTIFILFPLKLVEKCESSVSLTVPPVVKLENGSSTNVSLTLRPPLNATL...QLN'),
    'cds_seq': Seq('atgataaggaattggctgactatttttatcctttttcccctgaagctcgtagag...tag'),
    'cds_start': 301,
    'cds_end': 1405}]],
 'CTSC': [[{'transcript': 'NM_001814.6',
    'protein_id': 'NP_001805.4',
    'protein_seq': Seq('MGAGPSLLLAALLLLLSGDGAVRCDTPANCTYLDLLGTWVFQVGSSGSQRDVNC...PKL'),
    'cds_seq': Seq('atgggtgctgggccctccttgctgctcgccgccctcctgctgcttctctccggc...tag'),
    'cds_start': 64,
    'cds_end': 1456}]],
 'CTSK': [[{'transcript': 'NM_000396.4',
    'protein_id': 'NP_000387.1',
    'protein_seq': Seq('MWGLKVLLLPVVSFALYPEEILDTHWELWKKTHRKQYNNKVDEISRRLIWEKNL...PKM'),
    'cds_seq': Seq('atgtgggggctcaaggttctgctgctacctgtggtgagctttgctctgtaccct...tga'),
    'cds_start': 48,
    'cds_end': 1038}]],
 'CUBN': [[{'transcript': 'NM_001081.4',
    'protein_id': 'NP_001072.2',
    'protein_seq': Seq('MMNMSLPFLWSLLTLLIFAEVNGEAGELELQRQKRSINLQQPRMATERGNLVFL...WDS'),
    'cds_seq': Seq('atgatgaacatgtctttaccttttctttggagtttgcttaccttattaatattt...taa'),
    'cds_start': 46,
    'cds_end': 10918}]],
 'CUL3': [[{'transcript': 'NM_003590.5',
    'protein_id': 'NP_003581.1',
    'protein_seq': Seq('MSNLSKGTGSRKDTKMRIRAFPMTMDEKYVNSIWDLLKNAIQEIQRKNNSGLSF...YVA'),
    'cds_seq': Seq('atgtcgaatctgagcaaaggcacgggcagccggaaggacaccaagatgcggatc...taa'),
    'cds_start': 354,
    'cds_end': 2661}]],
 'CUL7': [[{'transcript': 'NM_014780.5',
    'protein_id': 'NP_055595.2',
    'protein_seq': Seq('MVGELRYREFRVPLGPGLHAYPDELIRQRVGHDGHPEYQIRWLILRRGDEGDGG...TFR'),
    'cds_seq': Seq('atggtgggagaactccgctacagggaattcagggtgcccctggggcccggctta...tag'),
    'cds_start': 238,
    'cds_end': 5335}]],
 'CYBB': [[{'transcript': 'NM_000397.4',
    'protein_id': 'NP_000388.2',
    'protein_seq': Seq('MGNWAVNEGLSIFVILVWLGLNVFLFVWYYRVYDIPPKFFYTRKLLGSALALAR...ENF'),
    'cds_seq': Seq('atggggaactgggctgtgaatgaggggctctccatttttgtcattctggtttgg...taa'),
    'cds_start': 19,
    'cds_end': 1732}]],
 'CYP11B1': [[{'transcript': 'NM_000497.4',
    'protein_id': 'NP_000488.3',
    'protein_seq': Seq('MALRAKAEVCMAVPWLSLQRAQALGTRAARVPRTVLPFEAMPRRPGNRWLRLLQ...AIN'),
    'cds_seq': Seq('atggcactcagggcaaaggcagaggtgtgcatggcagtgccctggctgtccctg...taa'),
    'cds_start': 12,
    'cds_end': 1524}]],
 'CYP11B2': [[{'transcript': 'NM_000498.3',
    'protein_id': 'NP_000489.3',
    'protein_seq': Seq('MALRAKAEVCVAAPWLSLQRARALGTRAARAPRTVLPFEAMPQHPGNRWLRLLQ...AIN'),
    'cds_seq': Seq('atggcactcagggcaaaggcagaggtgtgcgtggcagcgccctggctgtccctg...tag'),
    'cds_start': 3,
    'cds_end': 1515}]],
 'CYP17A1': [[{'transcript': 'NM_000102.4',
    'protein_id': 'NP_000093.1',
    'protein_seq': Seq('MWELVALLLLTLAYLFWPKRRCPGAKYPKSLLSLPLVGSLPFLPRHGHMHNNFF...GST'),
    'cds_seq': Seq('atgtgggagctcgtggctctcttgctgcttaccctagcttatttgttttggccc...taa'),
    'cds_start': 52,
    'cds_end': 1579}]],
 'CYP19A1': [[{'transcript': 'NM_000103.4',
    'protein_id': 'NP_000094.2',
    'protein_seq': Seq('MVLEMLNPIHYNITSIVPEAMPAATMPVLLLTGLFLLVWNYEGTSSIPGPGYCM...LEH'),
    'cds_seq': Seq('atggttttggaaatgctgaacccgatacattataacatcaccagcatcgtgcct...tag'),
    'cds_start': 140,
    'cds_end': 1652}]],
 'CYP1B1': [[{'transcript': 'NM_000104.4',
    'protein_id': 'NP_000095.2',
    'protein_seq': Seq('MGTSLSPNDPWPLNPLSIQQTTLLLLLSVLATVHVGQRLLRQRRRQLRSAPPGP...TCQ'),
    'cds_seq': Seq('atgggcaccagcctcagcccgaacgacccttggccgctaaacccgctgtccatc...taa'),
    'cds_start': 373,
    'cds_end': 2005}]],
 'CYP21A2': [[{'transcript': 'NM_000500.9',
    'protein_id': 'NP_000491.4',
    'protein_seq': Seq('MLLLGLLLLLPLLAGARLLWNWWKLRSLHLPPLAPGFLHLLQPDLPIYLLGLTQ...QSQ'),
    'cds_seq': Seq('atgctgctcctgggcctgctgctgctgctgcccctgctggctggcgcccgcctg...tga'),
    'cds_start': 8,
    'cds_end': 1496}]],
 'CYP27A1': [[{'transcript': 'NM_000784.4',
    'protein_id': 'NP_000775.1',
    'protein_seq': Seq('MAALGCARLRWALRGAGRGLCPHGARAKAAIPAALPSDKATGAPGAGPGVRRRQ...RQC'),
    'cds_seq': Seq('atggctgcgctgggctgcgcgaggctgaggtgggcgctgcgaggggccggccgt...tga'),
    'cds_start': 36,
    'cds_end': 1632}]],
 'CYP27B1': [[{'transcript': 'NM_000785.4',
    'protein_id': 'NP_000776.1',
    'protein_seq': Seq('MTQTLKYASRVFHRVRWAPELGASLGYREYHSARRSLADIPGPSTPSFLAELFC...LDR'),
    'cds_seq': Seq('atgacccagaccctcaagtacgcctccagagtgttccatcgcgtccgctgggcg...tag'),
    'cds_start': 37,
    'cds_end': 1564}]],
 'CYP4V2': [[{'transcript': 'NM_207352.4',
    'protein_id': 'NP_997235.3',
    'protein_seq': Seq('MAGLWLGLVWQKLLLWGAASALSLAGASLVLSLLQRVASYARKWQQMRPIPTVA...DER'),
    'cds_seq': Seq('atggcggggctctggctggggctcgtgtggcagaagctgctgctgtggggcgcg...taa'),
    'cds_start': 257,
    'cds_end': 1835}]],
 'DBT': [[{'transcript': 'NM_001918.5',
    'protein_id': 'NP_001909.4',
    'protein_seq': Seq('MAAVRMLRTWSRNAGKLICVRYFQTCGNVHVLKPNYVCFFGYPSFKYSHPHHFL...DLK'),
    'cds_seq': Seq('atggctgcagtccgtatgctgagaacctggagcaggaatgcggggaagctgatt...tga'),
    'cds_start': 14,
    'cds_end': 1463}]],
 'DCLRE1C': [[{'transcript': 'NM_001033855.3',
    'protein_id': 'NP_001029027.1',
    'protein_seq': Seq('MSSFEGQMAEYPTISIDRFDRENLRARAYFLSHCHKDHMKGLRAPTLKRRLECS...LDT'),
    'cds_seq': Seq('atgagttctttcgaggggcagatggccgagtatccaactatctccatagaccgc...taa'),
    'cds_start': 86,
    'cds_end': 2165}]],
 'DCX': [[{'transcript': 'NM_001195553.2',
    'protein_id': 'NP_001182482.1',
    'protein_seq': Seq('MELDFGHFDERDKTSRNMRGSRMNGLPSPTHSAHCSFYRTRTLQALSNEKKAKK...DSM'),
    'cds_seq': Seq('atggaacttgattttggacactttgacgaaagagataagacatccaggaacatg...taa'),
    'cds_start': 77,
    'cds_end': 1178}]],
 'DDC': [[{'transcript': 'NM_001082971.2',
    'protein_id': 'NP_001076440.2',
    'protein_seq': Seq('MNASEFRRRGKEMVDYMANYMEGIEGRQVYPDVEPGYLRPLIPAAAPQEPDTFE...ERE'),
    'cds_seq': Seq('atgaacgcaagtgaattccgaaggagagggaaggagatggtggattacatggcc...tag'),
    'cds_start': 149,
    'cds_end': 1592}]],
 'DDX3X': [[{'transcript': 'NM_001356.5',
    'protein_id': 'NP_001347.3',
    'protein_seq': Seq('MSHVAVENALGLDQQFAGLDLNSSDNQSGGSTASKGRYIPPHLRNREATKGFYD...WGN'),
    'cds_seq': Seq('atgagtcatgtggcagtggaaaatgcgctcgggctggaccagcagtttgctggc...tga'),
    'cds_start': 91,
    'cds_end': 2080}]],
 'DDX41': [[{'transcript': 'NM_016222.4',
    'protein_id': 'NP_057306.2',
    'protein_seq': Seq('MEESEPERKRARTDEVPAGGSRSEAEDEDDEDYVPYVPLRQRRQLLLQKLLQRR...MDF'),
    'cds_seq': Seq('atggaggagtcggaacccgaacggaagcgggctcgcaccgacgaggtgcctgcc...tga'),
    'cds_start': 16,
    'cds_end': 1885}]],
 'DEAF1': [[{'transcript': 'NM_021008.4',
    'protein_id': 'NP_066288.2',
    'protein_seq': Seq('MEDSDSAAKQLGLAEAAAVAAAAAVAAAAAAAAGGEAEEPVLSRDEDSEEDADS...VTV'),
    'cds_seq': Seq('atggaggactcggactcggcggcaaagcagctgggcctggctgaggcggcggcg...tga'),
    'cds_start': 175,
    'cds_end': 1873}]],
 'DEPDC5': [[{'transcript': 'NM_001242896.3',
    'protein_id': 'NP_001229825.1',
    'protein_seq': Seq('MRTTKVYKLVIHKKGFGGSDDELVVNPKVFPHIKLGDIVEIAHPNDEYSPLLLQ...SAP'),
    'cds_seq': Seq('atgagaacaacaaaggtctacaaactcgtcatccacaagaagggctttgggggc...tga'),
    'cds_start': 206,
    'cds_end': 5018}]],
 'DES': [[{'transcript': 'NM_001927.4',
    'protein_id': 'NP_001918.3',
    'protein_seq': Seq('MSQAYSSSQRVSSYRRTFGGAPGFPLGSPLSSPVFPRAGFGSKGSSSSVTSRVY...EVL'),
    'cds_seq': Seq('atgagccaggcctactcgtccagccagcgcgtgtcctcctaccgccgcaccttc...taa'),
    'cds_start': 86,
    'cds_end': 1499}]],
 'DHCR7': [[{'transcript': 'NM_001360.3',
    'protein_id': 'NP_001351.2',
    'protein_seq': Seq('MAAKSQPNIPKAKSLDGVTNDRTASQGQWGRAWEVDWFSLASVIFLLLFAPFIV...GIF'),
    'cds_seq': Seq('atggctgcaaaatcgcaacccaacattcccaaagccaagagtctagatggcgtc...taa'),
    'cds_start': 235,
    'cds_end': 1663}]],
 'DICER1': [[{'transcript': 'NM_177438.3',
    'protein_id': 'NP_803187.1',
    'protein_seq': Seq('MKSPALQPLSMAGLQLMTPASSPMGPFFGLPWQQEAIHDNIYTPRKYQVELLEA...PNS'),
    'cds_seq': Seq('atgaaaagccctgctttgcaacccctcagcatggcaggcctgcagctcatgacc...tga'),
    'cds_start': 345,
    'cds_end': 6114}]],
 'DLD': [[{'transcript': 'NM_000108.5',
    'protein_id': 'NP_000099.2',
    'protein_seq': Seq('MQSWSRVYCSLAKRGHFNRISHGLQGLSAVPLRTYADQPIDADVTVIGSGPGGY...INF'),
    'cds_seq': Seq('atgcagagctggagtcgtgtgtactgctccttggccaagagaggccatttcaat...tga'),
    'cds_start': 68,
    'cds_end': 1598}]],
 'DLG4': [[{'transcript': 'NM_001321075.3',
    'protein_id': 'NP_001308004.1',
    'protein_seq': Seq('MDCLCIVTTKKYRYQDEDTPPLEHSPAHLPNQANSPPVIVNTDTLEAPGYELQV...ERL'),
    'cds_seq': Seq('atggactgtctctgtatagtgacaaccaagaaataccgctaccaagatgaagac...tga'),
    'cds_start': 480,
    'cds_end': 2655}]],
 'DMD': [[{'transcript': 'NM_004006.3',
    'protein_id': 'NP_003997.2',
    'protein_seq': Seq('MLWWEEVEDCYEREDVQKKTFTKWVNAQFSKFGKQHIENLFSDLQDGRRLLDLL...DTM'),
    'cds_seq': Seq('atgctttggtgggaagaagtagaggactgttatgaaagagaagatgttcaaaag...tag'),
    'cds_start': 237,
    'cds_end': 11295}]],
 'DNAH1': [[{'transcript': 'NM_015512.5',
    'protein_id': 'NP_056327.4',
    'protein_seq': Seq('MEQPNSKGYSLGRTPQGPECSSAPAVQVGTHRGLEYNPGKILPGSDYGLGNPPA...LDY'),
    'cds_seq': Seq('atggagcagcctaacagtaaaggctatagcctgggaaggacccctcagggccca...tag'),
    'cds_start': 261,
    'cds_end': 13059}]],
 'DNAH11': [[{'transcript': 'NM_001277115.2',
    'protein_id': 'NP_001264044.1',
    'protein_seq': Seq('MAAQVAAREARDFREAPTLRLTSGAGLEAVGAVELEEEEENEEEAAARRARSFA...LEA'),
    'cds_seq': Seq('atggcagcccaggtggcagcccgggaggcgcgagacttcagagaagccccgacc...taa'),
    'cds_start': 207,
    'cds_end': 13758}]],
 'DNAH5': [[{'transcript': 'NM_001369.3',
    'protein_id': 'NP_001360.1',
    'protein_seq': Seq('MFRIGRRQLWKHSVTRVLTQRLKGEKEAKRALLDARHNYLFAIVASCLDLNKTE...DVK'),
    'cds_seq': Seq('atgtttaggattgggaggagacagctctggaagcatagcgtcactcgagtttta...taa'),
    'cds_start': 250,
    'cds_end': 14125}]],
 'DNAH8': [[{'transcript': 'NM_001206927.2',
    'protein_id': 'NP_001193856.1',
    'protein_seq': Seq('MEKDAEDGAPSEGAEAPPSTEEAAPPRSEEEEAPRPPTVEAPAEDGFSPSAEDA...DIK'),
    'cds_seq': Seq('atggagaaggatgctgaagatggcgccccttctgagggagcagaggctcctccc...taa'),
    'cds_start': 139,
    'cds_end': 14263}]],
 'DNAH9': [[{'transcript': 'NM_001372.4',
    'protein_id': 'NP_001363.2',
    'protein_seq': Seq('MRLAEERAALAAENADGEPGADRRLRLLGTYVAMSLRPAAGAWERCAGSAEAEQ...LQI'),
    'cds_seq': Seq('atgcggctcgcggaggagcgggccgcgctcgcggcggagaacgcggatggggaa...tag'),
    'cds_start': 29,
    'cds_end': 13490}]],
 'DNAI1': [[{'transcript': 'NM_012144.4',
    'protein_id': 'NP_036276.1',
    'protein_seq': Seq('MIPASAKAPHKQPHKQSISIGRGTRKRDEDSGTEVGEGTDEWAQSKATVRPPDQ...IKT'),
    'cds_seq': Seq('atgattcctgcttctgcgaaggctccccataaacagcctcataagcagagcatc...tga'),
    'cds_start': 201,
    'cds_end': 2301}]],
 'DNAI2': [[{'transcript': 'NM_023036.6',
    'protein_id': 'NP_075462.3',
    'protein_seq': Seq('MEIVYVYVKKRSEFGKQCNFSDRQAELNIDIMPNPELAEQFVERNPVDTGIQCS...DLA'),
    'cds_seq': Seq('atggagattgtgtacgtgtacgtcaagaagcgcagcgagttcgggaagcagtgc...tag'),
    'cds_start': 123,
    'cds_end': 1941}]],
 'DNM1': [[{'transcript': 'NM_001288739.2',
    'protein_id': 'NP_001275668.1',
    'protein_seq': Seq('MGNRGMEDLIPLVNRLQDAFSAIGQNADLDLPQIAVVGGQSAGKSSVLENFVGR...FDL'),
    'cds_seq': Seq('atgggcaaccgcggcatggaagatctcatcccgctggtcaaccggctgcaagac...taa'),
    'cds_start': 92,
    'cds_end': 2687}],
  [{'transcript': 'NM_004408.4',
    'protein_id': 'NP_004399.2',
    'protein_seq': Seq('MGNRGMEDLIPLVNRLQDAFSAIGQNADLDLPQIAVVGGQSAGKSSVLENFVGR...FDL'),
    'cds_seq': Seq('atgggcaaccgcggcatggaagatctcatcccgctggtcaaccggctgcaagac...taa'),
    'cds_start': 92,
    'cds_end': 2687}]],
 'DNMT3A': [[{'transcript': 'NM_022552.5',
    'protein_id': 'NP_072046.2',
    'protein_seq': Seq('MPAMPSSGPGDTSSSAAEREEDRKDGEEQEEPRGKEERQEPSTTARKVGRPGRK...ACV'),
    'cds_seq': Seq('atgcccgccatgccctccagcggccccggggacaccagcagctctgctgcggag...taa'),
    'cds_start': 277,
    'cds_end': 3016}]],
 'DOCK6': [[{'transcript': 'NM_020812.4',
    'protein_id': 'NP_065863.2',
    'protein_seq': Seq('MAASERRAFAHKINRTVAAEVRKQVSRERSGSPHSSRRCSSSLGVPLTEVVEPL...ADL'),
    'cds_seq': Seq('atggctgcctccgagcgccgcgccttcgcgcacaagatcaacaggacggtggcc...tga'),
    'cds_start': 84,
    'cds_end': 6228}]],
 'DOCK8': [[{'transcript': 'NM_203447.4',
    'protein_id': 'NP_982272.2',
    'protein_seq': Seq('MATLPSAERRAFALKINRYSSAEIRKQFTLPPNLGQYHRQSISTSGFPSLQLPQ...QGS'),
    'cds_seq': Seq('atggccactctgccgagcgcagagcgccgcgcgttcgcgctcaagatcaacagg...taa'),
    'cds_start': 112,
    'cds_end': 6412}]],
 'DOK7': [[{'transcript': 'NM_173660.5',
    'protein_id': 'NP_775931.3',
    'protein_seq': Seq('MTEAALVEGQVKLRDGKKWKSRWLVLRKPSPVADCLLMLVYKDKSERIKGLRER...PPP'),
    'cds_seq': Seq('atgaccgaggcggcgctggtggagggccaggtcaagctgcgggacggcaagaag...tga'),
    'cds_start': 70,
    'cds_end': 1585}]],
 'DPYD': [[{'transcript': 'NM_000110.4',
    'protein_id': 'NP_000101.2',
    'protein_seq': Seq('MAPVLSKDSADIESILALNPRTQTHATLCSTSAKKLDKKHWKRNPDKNCFNCEK...PVC'),
    'cds_seq': Seq('atggcccctgtgctcagtaaggactcggcggacatcgagagtatcctggcttta...taa'),
    'cds_start': 112,
    'cds_end': 3190}]],
 'DSG2': [[{'transcript': 'NM_001943.5',
    'protein_id': 'NP_001934.2',
    'protein_seq': Seq('MARSPGRAYALLLLLICFNVGSGLHLQVLSTRNENKLLPKHPHLVRQKRAWITA...SYS'),
    'cds_seq': Seq('atggcgcggagcccgggacgcgcgtacgccctgctgcttctcctgatctgcttt...taa'),
    'cds_start': 75,
    'cds_end': 3432}]],
 'DSP': [[{'transcript': 'NM_004415.4',
    'protein_id': 'NP_004406.2',
    'protein_seq': Seq('MSCNGGSHPRINTLGRMIRAESGPDLRYEVTSGGGGTSRMYYSRRGVITDQNSD...IGH'),
    'cds_seq': Seq('atgagctgcaacggaggctcccacccgcggatcaacactctgggccgcatgatc...tag'),
    'cds_start': 245,
    'cds_end': 8861}]],
 'DST': [[{'transcript': 'NM_001374736.1',
    'protein_id': 'NP_001361665.1',
    'protein_seq': Seq('MIAAAFLVLLRPYSIQCALFLLLLLLGTIATIVFFCCWHRKLQKGRHPMKSVFS...SKR'),
    'cds_seq': Seq('atgatcgccgcggctttcctcgtcttgctgagaccctacagcatccaatgtgcc...tag'),
    'cds_start': 243,
    'cds_end': 23700}],
  [{'transcript': 'NM_001723.7',
    'protein_id': 'NP_001714.1',
    'protein_seq': Seq('MHSSSYSYRSSDSVFSNTTSTRTSLDSNENLLLVHCGPTLINSCISFGSESFDG...YSS'),
    'cds_seq': Seq('atgcacagtagtagttatagttaccgtagcagtgattctgtgtttagtaacact...taa'),
    'cds_start': 101,
    'cds_end': 8051}]],
 'DUOX2': [[{'transcript': 'NM_001363711.2',
    'protein_id': 'NP_001350640.1',
    'protein_seq': Seq('MLRARPEALMLLGALLTGSLGPSGSQDALSLPWEVQRYDGWFNNLRHHERGAVG...ENF'),
    'cds_seq': Seq('atgctccgtgcaagaccagaggcactgatgctcctgggagctcttctgactgga...tga'),
    'cds_start': 214,
    'cds_end': 4861}]],
 'DYNC1H1': [[{'transcript': 'NM_001376.5',
    'protein_id': 'NP_001367.2',
    'protein_seq': Seq('MSEPGGGGGEDGSAGLEVSAVQNVADVSVLQKHLRKLVPLLLEDGGEAPAALEA...CTE'),
    'cds_seq': Seq('atgtcggagcccgggggcggcggcggcgaggacggctcggccggattggaagtg...taa'),
    'cds_start': 119,
    'cds_end': 14060}]],
 'DYNC2H1': [[{'transcript': 'NM_001080463.2',
    'protein_id': 'NP_001073932.1',
    'protein_seq': Seq('MANGTADVRKLFIFTTTQNYFGLMSELWDQPLLCNCLEINNFLDDGNQMLLRVQ...KNQ'),
    'cds_seq': Seq('atggcgaacgggactgcggacgttcggaagctcttcatcttcactactacccag...tag'),
    'cds_start': 149,
    'cds_end': 13094}],
  [{'transcript': 'NM_001377.3',
    'protein_id': 'NP_001368.2',
    'protein_seq': Seq('MANGTADVRKLFIFTTTQNYFGLMSELWDQPLLCNCLEINNFLDDGNQMLLRVQ...KNQ'),
    'cds_seq': Seq('atggcgaacgggactgcggacgttcggaagctcttcatcttcactactacccag...tag'),
    'cds_start': 149,
    'cds_end': 13073}]],
 'DYRK1A': [[{'transcript': 'NM_001347721.2',
    'protein_id': 'NP_001334650.1',
    'protein_seq': Seq('MHTGGETSACKPSSVRLAPSFSFHAAGLQMAGQMPHSHQYSDRRQPNISDQQVS...ASS'),
    'cds_seq': Seq('atgcatacaggaggagagacttcagcatgcaaaccttcatctgttcggcttgca...tga'),
    'cds_start': 932,
    'cds_end': 3197}]],
 'DYSF': [[{'transcript': 'NM_001130987.2',
    'protein_id': 'NP_001124459.1',
    'protein_seq': Seq('MLCCLLVRASNLPSAKKDRRSDPVASLTFRGVKKRTKVIKNSVNPVWNEGFEWD...PFS'),
    'cds_seq': Seq('atgctgtgctgcctgctggtgagggccagcaacctccccagtgcgaagaaggac...tga'),
    'cds_start': 144,
    'cds_end': 6504}],
  [{'transcript': 'NM_003494.4',
    'protein_id': 'NP_003485.1',
    'protein_seq': Seq('MLRVFILYAENVHTPDTDISDAYCSAVFAGVKKRTKVIKNSVNPVWNEGFEWDL...PFS'),
    'cds_seq': Seq('atgctgagggtcttcatcctctatgccgagaacgtccacacacccgacaccgac...tga'),
    'cds_start': 438,
    'cds_end': 6681}]],
 'EBF3': [[{'transcript': 'NM_001375380.1',
    'protein_id': 'NP_001362309.1',
    'protein_seq': Seq('MFGIQENIPRGGTTMKEEPLGSGMNPVRSWMHTAGVVDANTAAQSGVGLARAHF...LGW'),
    'cds_seq': Seq('atgtttgggattcaggagaatattccgcgcggggggacgaccatgaaggaggag...tag'),
    'cds_start': 506,
    'cds_end': 2396}]],
 'EBP': [[{'transcript': 'NM_006579.3',
    'protein_id': 'NP_006570.1',
    'protein_seq': Seq('MTTNAGPLHPYWPQHLRLDNFVPNDRPTWHILAGLFSVTGVLVVTTWLLSGRAA...KKN'),
    'cds_seq': Seq('atgactaccaacgcgggccccttgcacccatactggcctcagcacctaagactg...tga'),
    'cds_start': 173,
    'cds_end': 866}]],
 'ECHS1': [[{'transcript': 'NM_004092.4',
    'protein_id': 'NP_004083.3',
    'protein_seq': Seq('MAALRVLLSCVRGPLRPPVRCPAWRPFASGANFEYIIAEKRGKNNTVGLIQLNR...KDQ'),
    'cds_seq': Seq('atggccgccctgcgtgtcctgctgtcctgcgtccgcggcccgctgaggcccccg...tga'),
    'cds_start': 21,
    'cds_end': 894}]],
 'EDA': [[{'transcript': 'NM_001399.5',
    'protein_id': 'NP_001390.1',
    'protein_seq': Seq('MGYPEVERRELLPAAAPRERGSQGCGCGGAPARAGEGNSCLLFLGFFGLSLALH...PAS'),
    'cds_seq': Seq('atgggctacccggaggtggagcgcagggaactcctgcctgcagcagcgccgcgg...tag'),
    'cds_start': 196,
    'cds_end': 1372}]],
 'EDAR': [[{'transcript': 'NM_022336.4',
    'protein_id': 'NP_071731.1',
    'protein_seq': Seq('MAHVGDCTQTPWLPVLVVSLMCSARAEYSNCGENEYYNQTTGLCQECPPCGPGE...AAS'),
    'cds_seq': Seq('atggcccatgtgggggactgcacgcagacgccctggctccccgtcctggtggtg...tga'),
    'cds_start': 279,
    'cds_end': 1626}]],
 'EFTUD2': [[{'transcript': 'NM_004247.4',
    'protein_id': 'NP_004238.3',
    'protein_seq': Seq('MDTDLYDEFGNYIGPELDSDEDDDELGRETKDLDEMDDDDDDDDVGDHDDDHPG...YPM'),
    'cds_seq': Seq('atggataccgacttatatgatgagtttgggaattatattggaccagagcttgat...tga'),
    'cds_start': 81,
    'cds_end': 3000}]],
 'EHMT1': [[{'transcript': 'NM_024757.5',
    'protein_id': 'NP_079033.4',
    'protein_seq': Seq('MAAADAEAVPARGEPQQDCCVKTELLGEETPMAADEGSAEKQAGEAHMAADGET...DPL'),
    'cds_seq': Seq('atggccgccgccgatgccgaggcagttccggcgaggggggagcctcagcaggat...tga'),
    'cds_start': 24,
    'cds_end': 3921}]],
 'EIF2AK3': [[{'transcript': 'NM_004836.7',
    'protein_id': 'NP_004827.4',
    'protein_seq': Seq('MERAISPGLLVRALLLLLLLLGLAARTVAAGRARGLPAPTAEAAFGLGAAAAPT...PSN'),
    'cds_seq': Seq('atggagcgcgccatcagcccggggctgctggtacgggcgctgctgctgctgctg...tag'),
    'cds_start': 190,
    'cds_end': 3541}]],
 'EIF2B5': [[{'transcript': 'NM_003907.3',
    'protein_id': 'NP_003898.2',
    'protein_seq': Seq('MAAPVVAPPGVVVSRANKRSGAGPGGSGGGGARGAEEEPPPPLQAVLVADSFDR...EDD'),
    'cds_seq': Seq('atggcggcccctgtagtggcgccgcctggtgtggtggttagtcgggctaacaag...tga'),
    'cds_start': 28,
    'cds_end': 2194}]],
 'ELAC2': [[{'transcript': 'NM_018127.7',
    'protein_id': 'NP_060597.4',
    'protein_seq': Seq('MWALCSLLRSAAGRTMSQGRTISQAPARRERPRKDPLRHLRTREKRGPSGCSGG...RAQ'),
    'cds_seq': Seq('atgtgggcgctttgctcgctgctgcggtccgcggccggacgcaccatgtcgcag...tga'),
    'cds_start': 80,
    'cds_end': 2561}]],
 'ELANE': [[{'transcript': 'NM_001972.4',
    'protein_id': 'NP_001963.1',
    'protein_seq': Seq('MTLGRRLACLFLACVLPALLLGGTALASEIVGGRRARPHAWPFMVSLQLRGGHF...RTH'),
    'cds_seq': Seq('atgaccctcggccgccgactcgcgtgtcttttcctcgcctgtgtcctgccggcc...tga'),
    'cds_start': 26,
    'cds_end': 830}]],
 'ELN': [[{'transcript': 'NM_000501.4',
    'protein_id': 'NP_000492.2',
    'protein_seq': Seq('MAGLTAAAPRPGVLLLLLSILHPSRPGGVPGAIPGGVPGGVFYPGAGLGALGGG...KRK'),
    'cds_seq': Seq('atggcgggtctgacggcggcggccccgcggcccggagtcctcctgctcctgctg...tga'),
    'cds_start': 15,
    'cds_end': 2190}]],
 'ELP1': [[{'transcript': 'NM_003640.5',
    'protein_id': 'NP_003631.2',
    'protein_seq': Seq('MRNLKLFRTLEFRDIQGPGNPQCFSLRTEQGTVLIGSEHGLIEVDPVSREVKNE...LLD'),
    'cds_seq': Seq('atgcgaaatctgaaattatttcggaccctggagttcagggatattcaaggtcca...tga'),
    'cds_start': 316,
    'cds_end': 4315}]],
 'EMC1': [[{'transcript': 'NM_015047.3',
    'protein_id': 'NP_055862.1',
    'protein_seq': Seq('MAAEWASRFWLWATLLIPAAAVYEDQVGKFDWRQQYVGKVKFASLEFSPGSKKL...AWR'),
    'cds_seq': Seq('atggcggctgagtgggcttctcgtttctggctttgggctacgctgctgattcct...taa'),
    'cds_start': 15,
    'cds_end': 2997}]],
 'ENG': [[{'transcript': 'NM_001114753.3',
    'protein_id': 'NP_001108225.1',
    'protein_seq': Seq('MDRGTLPLAVALLLASCSLSPTSLAETVHCDLQPVGPERGEVTYTTSQVSKGCV...SMA'),
    'cds_seq': Seq('atggaccgcggcacgctccctctggctgttgccctgctgctggccagctgcagc...tag'),
    'cds_start': 303,
    'cds_end': 2280}]],
 'ENPP1': [[{'transcript': 'NM_006208.3',
    'protein_id': 'NP_006199.2',
    'protein_seq': Seq('MERDGCAGGGSRGGEGGRAPREGPAGNGRDRGRSHAAEAPGDPQAAASLLAPMD...QED'),
    'cds_seq': Seq('atggagcgcgacggctgcgcggggggcgggagccgcggcggcgagggcgggcgc...tga'),
    'cds_start': 16,
    'cds_end': 2794}]],
 'EP300': [[{'transcript': 'NM_001429.3',
    'protein_id': 'NP_001420.2',
    'protein_seq': Seq('MAENVVEPGPPSAKRPKLSSPALSASASDGTDFGSLFDLEHDLPDELINSTELG...DIH'),
    'cds_seq': Seq('atggccgagaatgtggtggaaccggggccgccttcagccaagcggcctaaactc...tag'),
    'cds_start': 395,
    'cds_end': 7640}],
  [{'transcript': 'NM_001429.4',
    'protein_id': 'NP_001420.2',
    'protein_seq': Seq('MAENVVEPGPPSAKRPKLSSPALSASASDGTDFGSLFDLEHDLPDELINSTELG...DIH'),
    'cds_seq': Seq('atggccgagaatgtggtggaaccggggccgccttcagccaagcggcctaaactc...tag'),
    'cds_start': 413,
    'cds_end': 7658}]],
 'EPG5': [[{'transcript': 'NM_020964.3',
    'protein_id': 'NP_066015.2',
    'protein_seq': Seq('MAEAVKPQRRAKAKASRTKTKEKKKYETPQREESSEVSLPKTSREQEIPSLACE...HIR'),
    'cds_seq': Seq('atggccgaggcggtgaagccccagcgccgggccaaggccaaggccagccggact...tag'),
    'cds_start': 90,
    'cds_end': 7830}]],
 'EPHB4': [[{'transcript': 'NM_004444.5',
    'protein_id': 'NP_004435.3',
    'protein_seq': Seq('MELRVLLCWASLAAALEETLLNTKLETADLKWVTFPQVDGQWEELSGLDEEQHS...PQY'),
    'cds_seq': Seq('atggagctccgggtgctgctctgctgggcttcgttggccgcagctttggaagag...tga'),
    'cds_start': 493,
    'cds_end': 3457}]],
 'ERCC2': [[{'transcript': 'NM_000400.4',
    'protein_id': 'NP_000391.1',
    'protein_seq': Seq('MKLNVDGLLVYFPYDYIYPEQFSYMRELKRTLDAKGHGVLEMPSGTGKTVSLLA...QQL'),
    'cds_seq': Seq('atgaagctcaacgtggacgggctcctggtctacttcccgtacgactacatctac...tga'),
    'cds_start': 33,
    'cds_end': 2316}]],
 'ERCC6': [[{'transcript': 'NM_000124.4',
    'protein_id': 'NP_000115.1',
    'protein_seq': Seq('MPNEGIPHSSQTQEQDCLQSQPVSNNEEMAIKQESGGDGEVEEYLSFRSVGDGL...EYC'),
    'cds_seq': Seq('atgccaaatgagggaatcccccactcaagtcaaactcaggagcaagactgttta...taa'),
    'cds_start': 174,
    'cds_end': 4656}],
  [{'transcript': 'NM_001277058.2',
    'protein_id': 'NP_001263987.1',
    'protein_seq': Seq('MPNEGIPHSSQTQEQDCLQSQPVSNNEEMAIKQESGGDGEVEEYLSFRSVGDGL...HTE'),
    'cds_seq': Seq('atgccaaatgagggaatcccccactcaagtcaaactcaggagcaagactgttta...tag'),
    'cds_start': 174,
    'cds_end': 3360}]],
 'ERCC8': [[{'transcript': 'NM_000082.4',
    'protein_id': 'NP_000073.1',
    'protein_seq': Seq('MLGFLSARQTGLEDPLRLRRAESTRRVLGLELNKDRDVERIHGGGINTLDIEPV...EEG'),
    'cds_seq': Seq('atgctggggtttttgtccgcacgccaaacgggtttggaggaccctcttcgcctt...tga'),
    'cds_start': 62,
    'cds_end': 1253}]],
 'ESCO2': [[{'transcript': 'NM_001017420.3',
    'protein_id': 'NP_001017420.1',
    'protein_seq': Seq('MAALTPRKRKQDSLKCDSLLHFTENLFPSPNKKHCFYQNSDKNEENLHCSQQEH...FNS'),
    'cds_seq': Seq('atggcagctcttactccaaggaagaggaagcaggattctttgaagtgtgacagc...taa'),
    'cds_start': 70,
    'cds_end': 1876}]],
 'ETFDH': [[{'transcript': 'NM_004453.4',
    'protein_id': 'NP_004444.2',
    'protein_seq': Seq('MLVPLAKLSCLAYQCFHALKIKKNYLPLCATRWSSTSTVPRITTHYTIYPRDKD...NGM'),
    'cds_seq': Seq('atgctggtgccgctagccaagctgtcctgcctggcatatcagtgctttcatgcc...taa'),
    'cds_start': 161,
    'cds_end': 2015}]],
 'ETHE1': [[{'transcript': 'NM_014297.5',
    'protein_id': 'NP_055112.2',
    'protein_seq': Seq('MAEAVLRVARRQLSQRGGSGAPILLRQMFEPVSCTFTYLLGDRESREAVLIDPV...PTA'),
    'cds_seq': Seq('atggcggaggctgtactgagggtcgcccggcggcagctgagccagcgcggcggg...tga'),
    'cds_start': 24,
    'cds_end': 789}]],
 'EVC': [[{'transcript': 'NM_153717.3',
    'protein_id': 'NP_714928.1',
    'protein_seq': Seq('MARGGAACKSDARLLLGRDALRPAPALLAPAVLLGAALGLGLGLWLGCRAGRQR...SNL'),
    'cds_seq': Seq('atggcccgcggcggggcggcctgcaagagcgacgcgcggctgctgctggggcgg...tag'),
    'cds_start': 180,
    'cds_end': 3159}]],
 'EVC2': [[{'transcript': 'NM_147127.5',
    'protein_id': 'NP_667338.3',
    'protein_seq': Seq('MDPSGSRGRPTWVLAGGLLAVALALGGRGCLGASSRPRWRPLGAQPPRDPQVAP...GMD'),
    'cds_seq': Seq('atggacccctcgggctcccgggggcgccccacgtgggtgctggccgggggtctc...tag'),
    'cds_start': 46,
    'cds_end': 3973}]],
 'EXT1': [[{'transcript': 'NM_000127.3',
    'protein_id': 'NP_000118.2',
    'protein_seq': Seq('MQAKKRYFILLSAGSCLALLFYFGGLQFRASRSHSRREEHSGRNGLHHPSPDHF...ERL'),
    'cds_seq': Seq('atgcaggccaaaaaacgctatttcatcctgctctcagctggctcttgtctcgcc...tga'),
    'cds_start': 780,
    'cds_end': 3021}]],
 'EXT2': [[{'transcript': 'NM_207122.2',
    'protein_id': 'NP_997005.1',
    'protein_seq': Seq('MCASVKYNIRGPALIPRMKTKHRIYYITLFSIVLLGLIATGMFQFWPHSIESSN...GSL'),
    'cds_seq': Seq('atgtgtgcgtcggtcaagtataatatccggggtcctgccctcatcccaagaatg...tga'),
    'cds_start': 205,
    'cds_end': 2362}]],
 'EYA1': [[{'transcript': 'NM_000503.6',
    'protein_id': 'NP_000494.2',
    'protein_seq': Seq('MEMQDLTSPHSRLSGSSESPSGPKLGNSHINSNSMTPNGTEVKTEPMSSSETAS...EYL'),
    'cds_seq': Seq('atggaaatgcaggatctaaccagcccgcatagccgtctgagtggtagtagtgaa...taa'),
    'cds_start': 477,
    'cds_end': 2256}]],
 'EYA4': [[{'transcript': 'NM_004100.5',
    'protein_id': 'NP_004091.3',
    'protein_seq': Seq('MEDSQDLNEQSVKKTCTESDVSQSQNSRSMEMQDLASPHTLVGGGDTPGSSKLE...EYL'),
    'cds_seq': Seq('atggaagactcccaggatttaaatgaacaatcagtaaagaaaacgtgcacagaa...taa'),
    'cds_start': 458,
    'cds_end': 2378}]],
 'EYS': [[{'transcript': 'NM_001142800.2',
    'protein_id': 'NP_001136272.1',
    'protein_seq': Seq('MTDKSIVILSLMVFHSSFINGKTCRRQLVEEWHPQPSSYVVNWTLTENICLDFY...EVT'),
    'cds_seq': Seq('atgactgacaaatcaatcgtcattctgagcctgatggtttttcacagctctttc...taa'),
    'cds_start': 539,
    'cds_end': 9974}]],
 'F11': [[{'transcript': 'NM_000128.4',
    'protein_id': 'NP_000119.1',
    'protein_seq': Seq('MIFLYQVVHFILFTSVSGECVTQLLKDTCFEGGDITTVFTPSAKYCQVVCTYHP...QAV'),
    'cds_seq': Seq('atgattttcttatatcaagtggtacatttcattttatttacttcagtttctggt...tga'),
    'cds_start': 108,
    'cds_end': 1986}]],
 'F5': [[{'transcript': 'NM_000130.4',
    'protein_id': 'NP_000121.2',
    'protein_seq': Seq('MFPGCPRLWVLVVLGTSWVGWGSQGTEAAQLRQFYVAAQGISWSYRPEPTNSSL...DIY'),
    'cds_seq': Seq('atgttcccaggctgcccacgcctctgggtcctggtggtcttgggcaccagctgg...tag'),
    'cds_start': 145,
    'cds_end': 6820}],
  [{'transcript': 'NM_000130.5',
    'protein_id': 'NP_000121.2',
    'protein_seq': Seq('MFPGCPRLWVLVVLGTSWVGWGSQGTEAAQLRQFYVAAQGISWSYRPEPTNSSL...DIY'),
    'cds_seq': Seq('atgttcccaggctgcccacgcctctgggtcctggtggtcttgggcaccagctgg...tag'),
    'cds_start': 95,
    'cds_end': 6770}]],
 'F7': [[{'transcript': 'NM_000131.4',
    'protein_id': 'NP_000122.1',
    'protein_seq': Seq('MVSQALRLLCLLLGLQGCLAAGGVAKASGGETRDMPWKPGPHRVFVTQEEAHGV...PFP'),
    'cds_seq': Seq('atggtctcccaggccctcaggctcctctgccttctgcttgggcttcagggctgc...tag'),
    'cds_start': 54,
    'cds_end': 1455}],
  [{'transcript': 'NM_000131.5',
    'protein_id': 'NP_000122.1',
    'protein_seq': Seq('MVSQALRLLCLLLGLQGCLAAGGVAKASGGETRDMPWKPGPHRVFVTQEEAHGV...PFP'),
    'cds_seq': Seq('atggtctcccaggccctcaggctcctctgccttctgcttgggcttcagggctgc...tag'),
    'cds_start': 51,
    'cds_end': 1452}],
  [{'transcript': 'NM_019616.4',
    'protein_id': 'NP_062562.1',
    'protein_seq': Seq('MVSQALRLLCLLLGLQGCLAAVFVTQEEAHGVLHRRRRANAFLEELRPGSLERE...PFP'),
    'cds_seq': Seq('atggtctcccaggccctcaggctcctctgccttctgcttgggcttcagggctgc...tag'),
    'cds_start': 51,
    'cds_end': 1386}]],
 'F8': [[{'transcript': 'NM_000132.4',
    'protein_id': 'NP_000123.1',
    'protein_seq': Seq('MQIELSTCFFLCLLRFCFSATRRYYLGAVELSWDYMQSDLGELPVDARFPPRVP...DLY'),
    'cds_seq': Seq('atgcaaatagagctctccacctgcttctttctgtgccttttgcgattctgcttt...tga'),
    'cds_start': 171,
    'cds_end': 7227}]],
 'F9': [[{'transcript': 'NM_000133.4',
    'protein_id': 'NP_000124.1',
    'protein_seq': Seq('MQRVNMIMAESPGLITICLLGYLLSAECTVFLDHENANKILNRPKRYNSGKLEE...KLT'),
    'cds_seq': Seq('atgcagcgcgtgaacatgatcatggcagaatcaccaggcctcatcaccatctgc...taa'),
    'cds_start': 26,
    'cds_end': 1412}]],
 'FAH': [[{'transcript': 'NM_000137.4',
    'protein_id': 'NP_000128.1',
    'protein_seq': Seq('MSFIPVAEDSDFPIHNLPYGVFSTRGDPRPRIGVAIGDQILDLSIIKHLFTGPV...LPS'),
    'cds_seq': Seq('atgtccttcatcccggtggccgaggattccgacttccccatccacaacctgccc...tga'),
    'cds_start': 56,
    'cds_end': 1316}]],
 'FAM161A': [[{'transcript': 'NM_001201543.2',
    'protein_id': 'NP_001188472.1',
    'protein_seq': Seq('MATSHRVAKLVASSLQTPVNPITGARVAQYEREDPLKALAAAEAILEDEEEEKV...ESH'),
    'cds_seq': Seq('atggccacctcccaccgagtggcgaagctggtggcctccagtctccagaccccg...tga'),
    'cds_start': 19,
    'cds_end': 2170}]],
 'FANCA': [[{'transcript': 'NM_000135.4',
    'protein_id': 'NP_000126.2',
    'protein_seq': Seq('MSDSWVPNSASGQDPGGRRRAWAELLAGRVKREKYNPERAQKLKESAVRLLRSH...HLF'),
    'cds_seq': Seq('atgtccgactcgtgggtcccgaactccgcctcgggccaggacccagggggccgc...tga'),
    'cds_start': 32,
    'cds_end': 4400}]],
 'FANCC': [[{'transcript': 'NM_000136.3',
    'protein_id': 'NP_000127.2',
    'protein_seq': Seq('MAQDSVDLSCDYQFWMQKLSVWDQASTLETQQDTCLHVAQFQEFLRKMYEALKE...TQV'),
    'cds_seq': Seq('atggctcaagattcagtagatctttcttgtgattatcagttttggatgcagaag...tag'),
    'cds_start': 262,
    'cds_end': 1939}]],
 'FANCD2': [[{'transcript': 'NM_001018115.3',
    'protein_id': 'NP_001018125.1',
    'protein_seq': Seq('MVSKRRLSKSEDKESLTEDASKTRKQPLSKKTKKSHIANEVEENDSIFVKLLKI...DSD'),
    'cds_seq': Seq('atggtttccaaaagaagactgtcaaaatctgaggataaagagagcctgacagaa...tag'),
    'cds_start': 70,
    'cds_end': 4426}]],
 'FANCG': [[{'transcript': 'NM_004629.2',
    'protein_id': 'NP_004620.1',
    'protein_seq': Seq('MSRQTTSVGSSCLDLWREKNDRLVRQAKVAQNSGLTLRRQQLAQDALEGLRGLL...CDL'),
    'cds_seq': Seq('atgtcccgccagaccacctctgtgggctccagctgcctggacctgtggagggaa...tag'),
    'cds_start': 418,
    'cds_end': 2287}]],
 'FANCI': [[{'transcript': 'NM_001113378.2',
    'protein_id': 'NP_001106849.1',
    'protein_seq': Seq('MDQKILSLAAEKTADKLQEFLQTLREGDLTNLLQNQAVKGKVAGALLRAIFKGS...RKK'),
    'cds_seq': Seq('atggaccagaagattttatctctagcagcagaaaaaacagcagacaaactgcaa...taa'),
    'cds_start': 74,
    'cds_end': 4061}]],
 'FANCL': [[{'transcript': 'NM_018062.4',
    'protein_id': 'NP_060532.2',
    'protein_seq': Seq('MAVTEASLLRQCPLLLPQNRSKTVYEGFISAQGRDFHLRIVLPEDLQLKNARLL...RKH'),
    'cds_seq': Seq('atggcggtgacggaagcgagcctgttgcgccagtgccccctgcttctgccccag...tga'),
    'cds_start': 12,
    'cds_end': 1140}]],
 'FANCM': [[{'transcript': 'NM_020937.4',
    'protein_id': 'NP_065988.1',
    'protein_seq': Seq('MSGRQRTLFQTWGSSISRSSGTPGCSSGTERPQSPGSSKAPLPAAAEAQLESDD...SDI'),
    'cds_seq': Seq('atgagcggacggcaaagaacgctttttcagacgtggggctcaagtatctcccga...taa'),
    'cds_start': 102,
    'cds_end': 6249}]],
 'FAS': [[{'transcript': 'NM_000043.6',
    'protein_id': 'NP_000034.1',
    'protein_seq': Seq('MLGIWTLLPLVLTSVARLSSKSVNAQVTDINSKGLELRKTVTTVETQNLEGLHH...SLV'),
    'cds_seq': Seq('atgctgggcatctggaccctcctacctctggttcttacgtctgttgctagatta...tag'),
    'cds_start': 79,
    'cds_end': 1087}]],
 'FBN1': [[{'transcript': 'NM_000138.5',
    'protein_id': 'NP_000129.3',
    'protein_seq': Seq('MRRGRLLEIALGFTVLLASYTSHGADANLEAGNVKETRASRAKRRGGGGHDALK...LLH'),
    'cds_seq': Seq('atgcgtcgagggcgtctgctggagatcgccctgggatttaccgtgcttttagcg...taa'),
    'cds_start': 316,
    'cds_end': 8932}]],
 'FBN2': [[{'transcript': 'NM_001999.4',
    'protein_id': 'NP_001990.2',
    'protein_seq': Seq('MGRRRRLCLQLYFLWLGCVVLWAQGTAGQPQPPPPKPPRPQPPPQQVRSATAGS...QLY'),
    'cds_seq': Seq('atggggagaagacggaggctgtgtctccagctctacttcctgtggctgggctgt...taa'),
    'cds_start': 642,
    'cds_end': 9381}]],
 'FBXL4': [[{'transcript': 'NM_001278716.2',
    'protein_id': 'NP_001265645.1',
    'protein_seq': Seq('MSPVFPMLTVLTMFYYICLRRRARTATRGEMMNTHRAIESNSQTSPLNAEVVQY...FTQ'),
    'cds_seq': Seq('atgtcaccggtctttcccatgttaacagttctgaccatgttttattatatatgc...tga'),
    'cds_start': 449,
    'cds_end': 2315}]],
 'FBXO11': [[{'transcript': 'NM_001190274.2',
    'protein_id': 'NP_001177203.1',
    'protein_seq': Seq('MNSVRAANRRPRRVSRPRPVQQQQQQPPQQPPPQPPQQQPPQQQPPPPPQQQQQ...QHN'),
    'cds_seq': Seq('atgaactccgtccgagccgccaaccggagacccaggcgagtgtcgcggccgcgc...tga'),
    'cds_start': 778,
    'cds_end': 3562}]],
 'FECH': [[{'transcript': 'NM_000140.3',
    'protein_id': 'NP_000131.2',
    'protein_seq': Seq('MRSLGANMAAALRAAGVLLRDPLASSSWRVCQPWRWKSGAAAAAVTTETAQHAQ...QQL'),
    'cds_seq': Seq('atgcgttcactcggcgcaaacatggctgcggccctgcgcgccgcgggcgtcctg...tga'),
    'cds_start': 117,
    'cds_end': 1389}],
  [{'transcript': 'NM_000140.5',
    'protein_id': 'NP_000131.2',
    'protein_seq': Seq('MRSLGANMAAALRAAGVLLRDPLASSSWRVCQPWRWKSGAAAAAVTTETAQHAQ...QQL'),
    'cds_seq': Seq('atgcgttcactcggcgcaaacatggctgcggccctgcgcgccgcgggcgtcctg...tga'),
    'cds_start': 82,
    'cds_end': 1354}]],
 'FGFR1': [[{'transcript': 'NM_023110.3',
    'protein_id': 'NP_075598.2',
    'protein_seq': Seq('MWSWKCLLFWAVLVTATLCTARPSPTLPEQAQPWGAPVEVESFLVHPGDLLQLR...KRR'),
    'cds_seq': Seq('atgtggagctggaagtgcctcctcttctgggctgtgctggtcacagccacactc...tga'),
    'cds_start': 743,
    'cds_end': 3212}]],
 'FGFR2': [[{'transcript': 'NM_000141.5',
    'protein_id': 'NP_000132.3',
    'protein_seq': Seq('MVSWGRFICLVVVTMATLSLARPSFSLVEDTTLEPEEPPTKYQISQPEVYVAAP...VKT'),
    'cds_seq': Seq('atggtcagctggggtcgtttcatctgcctggtcgtggtcaccatggcaaccttg...tga'),
    'cds_start': 633,
    'cds_end': 3099}]],
 'FGFR3': [[{'transcript': 'NM_000142.5',
    'protein_id': 'NP_000133.1',
    'protein_seq': Seq('MGAPACALALCVAVAIVAGASSESLGTEQRVVGRAAEVPGPEPGQQEQLVFGSG...SRT'),
    'cds_seq': Seq('atgggcgcccctgcctgcgccctcgcgctctgcgtggccgtggccatcgtggcc...tga'),
    'cds_start': 275,
    'cds_end': 2696}]],
 'FH': [[{'transcript': 'NM_000143.4',
    'protein_id': 'NP_000134.2',
    'protein_seq': Seq('MYRALRLLARSRPLVRAPAAALASAPGLGGAAVPSFWPPNAARMASQNSFRIEY...GPK'),
    'cds_seq': Seq('atgtaccgagcacttcggctcctcgcgcgctcgcgtcccctcgtgcgggctcca...tga'),
    'cds_start': 33,
    'cds_end': 1566}]],
 'FHL1': [[{'transcript': 'NM_001159699.2',
    'protein_id': 'NP_001153171.1',
    'protein_seq': Seq('MASHRHSGPSSYKVGTMAEKFDCHYCRDPLQGKKYVQKDGHHCCLKCFDKFCAN...KKL'),
    'cds_seq': Seq('atggcttcccatagacactcaggtccctccagctacaaggtgggcaccatggcg...taa'),
    'cds_start': 66,
    'cds_end': 957}],
  [{'transcript': 'NM_001159702.3',
    'protein_id': 'NP_001153174.1',
    'protein_seq': Seq('MAEKFDCHYCRDPLQGKKYVQKDGHHCCLKCFDKFCANTCVECRKPIGADSKEV...NAP'),
    'cds_seq': Seq('atggcggagaagtttgactgccactactgcagggatcccttgcaggggaagaag...tga'),
    'cds_start': 196,
    'cds_end': 1168}]],
 'FIG4': [[{'transcript': 'NM_014845.6',
    'protein_id': 'NP_055660.1',
    'protein_seq': Seq('MPTAAAPIISSVQKLVLYETRARYFLVGSNNAETKYRVLKIDRTEPKDLVIIDD...RYL'),
    'cds_seq': Seq('atgcccacggccgccgcccccatcatcagctcggtccagaagctggttctgtat...tga'),
    'cds_start': 140,
    'cds_end': 2864}]],
 'FKRP': [[{'transcript': 'NM_024301.5',
    'protein_id': 'NP_077277.1',
    'protein_seq': Seq('MRLTRCQAALAAAITLNLLVLFYVSWLQHQPRNSRARGPRRASAAGPRVTVLVR...GSG'),
    'cds_seq': Seq('atgcggctcacccgctgccaggctgccctggcggccgccatcaccctcaacctt...tga'),
    'cds_start': 286,
    'cds_end': 1774}]],
 'FKTN': [[{'transcript': 'NM_001079802.2',
    'protein_id': 'NP_001073270.1',
    'protein_seq': Seq('MSRINKNVVLALLTLTSSAFLLFQLYYYKHYLSTKNGAGLSKSKGSRIGFDSTQ...QLY'),
    'cds_seq': Seq('atgagtagaatcaataagaacgtggttttggcccttttaacgctgacaagttct...tga'),
    'cds_start': 215,
    'cds_end': 1601}]],
 'FLCN': [[{'transcript': 'NM_144997.7',
    'protein_id': 'NP_659434.2',
    'protein_seq': Seq('MNAIVALCHFCELHGPRTLFCTEVLHAPLPQGDGNEDSPGQGEQAEEEEGGIQM...SRN'),
    'cds_seq': Seq('atgaatgccatcgtggctctctgccacttctgcgagctccacggcccccgcact...tga'),
    'cds_start': 484,
    'cds_end': 2224}]],
 'FLG': [[{'transcript': 'NM_002016.2',
    'protein_id': 'NP_002007.1',
    'protein_seq': Seq('MSTLLENIFAIINLFKQYSKKDKNTDTLSKKELKELLEKEFRQILKNPDDPDMV...YYE'),
    'cds_seq': Seq('atgtctactctcctggaaaacatctttgccataattaatcttttcaagcaatat...taa'),
    'cds_start': 72,
    'cds_end': 12258}]],
 'FLNA': [[{'transcript': 'NM_001110556.2',
    'protein_id': 'NP_001104026.1',
    'protein_seq': Seq('MSSSHSRAGQSAAGAAPGGGVDTRDAEMPATEKDLAEDAPWKKIQQNTFTRWCN...VVP'),
    'cds_seq': Seq('atgagtagctcccactctcgggcgggccagagcgcagcaggcgcggctccgggc...tga'),
    'cds_start': 245,
    'cds_end': 8189}]],
 'FLNB': [[{'transcript': 'NM_001457.4',
    'protein_id': 'NP_001448.2',
    'protein_seq': Seq('MPVTEKDLAEDAPWKKIQQNTFTRWCNEHLKCVNKRIGNLQTDLSDGLRLIALL...TVP'),
    'cds_seq': Seq('atgccggtaaccgagaaggatctagctgaggacgcgccttggaagaagatccag...taa'),
    'cds_start': 143,
    'cds_end': 7952}]],
 'FLNC': [[{'transcript': 'NM_001458.5',
    'protein_id': 'NP_001449.3',
    'protein_seq': Seq('MMNNSGYSDAGLGLGDETDEMPSTEKDLAEDAPWKKIQQNTFTRWCNEHLKCVG...KVP'),
    'cds_seq': Seq('atgatgaacaacagcggctactcagacgccggcctcggcctgggcgatgagaca...tga'),
    'cds_start': 232,
    'cds_end': 8410}]],
 'FLT4': [[{'transcript': 'NM_182925.5',
    'protein_id': 'NP_891555.2',
    'protein_seq': Seq('MQRGAALCLRLWLCLGLLDGLVSGYSMTPPTLNITEESHVIDTGDSLSISCRGQ...NSY'),
    'cds_seq': Seq('atgcagcggggcgccgcgctgtgcctgcgactgtggctctgcctgggactcctg...taa'),
    'cds_start': 55,
    'cds_end': 4147}]],
 'FMO3': [[{'transcript': 'NM_001002294.3',
    'protein_id': 'NP_001002294.1',
    'protein_seq': Seq('MGKKVAIIGAGVSGLASIRSCLEEGLEPTCFEKSNDIGGLWKFSDHAEEGRASI...VLT'),
    'cds_seq': Seq('atggggaagaaagtggccatcattggagctggtgtgagtggcttggcctccatc...taa'),
    'cds_start': 83,
    'cds_end': 1682}]],
 'FOXC1': [[{'transcript': 'NM_001453.3',
    'protein_id': 'NP_001444.2',
    'protein_seq': Seq('MQARYSVSSPNSLGVVPYLGGEQSYYRAAAAAAGGGYTAMPAPMSVYSHPAHAE...SKF'),
    'cds_seq': Seq('atgcaggcgcgctactccgtgtccagccccaactccctgggagtggtgccctac...tga'),
    'cds_start': 531,
    'cds_end': 2193}]],
 'FOXG1': [[{'transcript': 'NM_005249.5',
    'protein_id': 'NP_005240.3',
    'protein_seq': Seq('MLDMGDRKEVKMIPKSSFSINSLVPEAVQNDNHHASHGHHNSHHPQHHHHHHHH...LIH'),
    'cds_seq': Seq('atgctggacatgggagataggaaagaggtgaaaatgatccccaagtcctcgttc...taa'),
    'cds_start': 493,
    'cds_end': 1963}]],
 'FOXL2': [[{'transcript': 'NM_023067.4',
    'protein_id': 'NP_075555.1',
    'protein_seq': Seq('MMASYPEPEDAAGALLAPETGRTVKEPEGPPPSPGKGGGGGGGTAPEKPDPAQK...LDL'),
    'cds_seq': Seq('atgatggccagctaccccgagcccgaggacgcggcgggggccctgctggcccca...tga'),
    'cds_start': 415,
    'cds_end': 1546}]],
 'FOXP1': [[{'transcript': 'NM_001349338.3',
    'protein_id': 'NP_001336267.1',
    'protein_seq': Seq('MMQESGTETKSNGSAIQNGSGGSNHLLECGGLREGRSNGETPAVDIGAADLAHA...DME'),
    'cds_seq': Seq('atgatgcaagaatctgggactgagacaaaaagtaacggttcagccatccagaat...tga'),
    'cds_start': 604,
    'cds_end': 2638}]],
 'FRAS1': [[{'transcript': 'NM_025074.7',
    'protein_id': 'NP_079350.5',
    'protein_seq': Seq('MGVLKVWLGLALALAEFAVLPHHSEGACVYQDSLLADATIWKPDSCQSCRCHGD...TEV'),
    'cds_seq': Seq('atgggtgtcctcaaagtgtggctcgggctggccctagcgttggcggaatttgca...taa'),
    'cds_start': 687,
    'cds_end': 12726}]],
 'FREM2': [[{'transcript': 'NM_207361.6',
    'protein_id': 'NP_997244.4',
    'protein_seq': Seq('MHSAGTPGLSSRRTGNSTSFQPGPPPPPRLLLLLLLLLSLVSRVPAQPAAFGRA...SEV'),
    'cds_seq': Seq('atgcactcagccgggactcccgggttatcctcgcgccggacaggcaactccacc...tga'),
    'cds_start': 268,
    'cds_end': 9778}]],
 'FUCA1': [[{'transcript': 'NM_000147.5',
    'protein_id': 'NP_000138.2',
    'protein_seq': Seq('MRAPGMRSRPAGPALLLLLLFLGAAESVRRAQPPRRYTPDWPSLDSRPLPAWFD...GVK'),
    'cds_seq': Seq('atgcgggctccggggatgaggtcgcggccggcgggtcccgcgctgttgctgctg...taa'),
    'cds_start': 4,
    'cds_end': 1405}]],
 'G6PC1': [[{'transcript': 'NM_000151.4',
    'protein_id': 'NP_000142.2',
    'protein_seq': Seq('MEEGMNVLHDFGIQSTHYLQVNYQDSQDWFILVSVIADLRNAFYVLFPIWFHLQ...KSL'),
    'cds_seq': Seq('atggaggaaggaatgaatgttctccatgactttgggatccagtcaacacattac...taa'),
    'cds_start': 78,
    'cds_end': 1152}]],
 'G6PD': [[{'transcript': 'NM_000402.4',
    'protein_id': 'NP_000393.4',
    'protein_seq': Seq('MGRRGSAPGNGRTLRGCERGGRRRRSADSVMAEQVALSRTQVCGILREELFQGD...HKL'),
    'cds_seq': Seq('atgggccggcggggctcagcccccggaaacggtcgtacacttcggggctgcgag...tga'),
    'cds_start': 148,
    'cds_end': 1786}],
  [{'transcript': 'NM_001042351.3',
    'protein_id': 'NP_001035810.1',
    'protein_seq': Seq('MAEQVALSRTQVCGILREELFQGDAFHQSDTHIFIIMGASGDLAKKKIYPTIWW...HKL'),
    'cds_seq': Seq('atggcagagcaggtggccctgagccggacccaggtgtgcgggatcctgcgggaa...tga'),
    'cds_start': 110,
    'cds_end': 1658}],
  [{'transcript': 'NM_001360016.2',
    'protein_id': 'NP_001346945.1',
    'protein_seq': Seq('MAEQVALSRTQVCGILREELFQGDAFHQSDTHIFIIMGASGDLAKKKIYPTIWW...HKL'),
    'cds_seq': Seq('atggcagagcaggtggccctgagccggacccaggtgtgcgggatcctgcgggaa...tga'),
    'cds_start': 66,
    'cds_end': 1614}]],
 'GAA': [[{'transcript': 'NM_000152.5',
    'protein_id': 'NP_000143.2',
    'protein_seq': Seq('MGVRHPPCSHRLLAVCALVSLATAALLGHILLHDFLLVPRELSGSSPVLEETHP...SWC'),
    'cds_seq': Seq('atgggagtgaggcacccgccctgctcccaccggctcctggccgtctgcgccctc...tag'),
    'cds_start': 342,
    'cds_end': 3201}]],
 'GABRA1': [[{'transcript': 'NM_001127644.2',
    'protein_id': 'NP_001121116.1',
    'protein_seq': Seq('MRKSPGLSDCLWAWILLLSTLTGRSYGQPSLQDELKDNTTVFTRILDRLLDGYD...PHQ'),
    'cds_seq': Seq('atgaggaaaagtccaggtctgtctgactgtctttgggcctggatcctccttctg...tag'),
    'cds_start': 318,
    'cds_end': 1689}]],
 'GABRB2': [[{'transcript': 'NM_001371727.1',
    'protein_id': 'NP_001358656.1',
    'protein_seq': Seq('MWRVRKRGYFGIWSFPLIIAAVCAQSVNDPSNMSLVKETVDRLLKGYDIRLRPD...YVN'),
    'cds_seq': Seq('atgtggagagtgcggaaaaggggctactttgggatttggtccttccccttaata...taa'),
    'cds_start': 82,
    'cds_end': 1621}]],
 'GABRB3': [[{'transcript': 'NM_000814.6',
    'protein_id': 'NP_000805.1',
    'protein_seq': Seq('MWGLAGGRLFGIFSAPVLVAVVCCAQSVNDPGNMSFVKETVDKLLKGYDIRLRP...YVN'),
    'cds_seq': Seq('atgtggggccttgcgggaggaaggcttttcggcatcttctcggccccggtgctg...tga'),
    'cds_start': 104,
    'cds_end': 1526}],
  [{'transcript': 'NM_021912.5',
    'protein_id': 'NP_068712.1',
    'protein_seq': Seq('MCSGLLELLLPIWLSWTLGTRGSEPRSVNDPGNMSFVKETVDKLLKGYDIRLRP...YVN'),
    'cds_seq': Seq('atgtgctccgggctcctggagctcctgctgcccatctggctctcctggaccctg...tga'),
    'cds_start': 39,
    'cds_end': 1461}]],
 'GABRG2': [[{'transcript': 'NM_198904.4',
    'protein_id': 'NP_944494.1',
    'protein_seq': Seq('MSSPNIWSTGSSVYSTPVFSQKMTVWILLLLSLYPGFTSQKSDDDYEDYASNKT...LYL'),
    'cds_seq': Seq('atgagttcgccaaatatatggagcacaggaagctcagtctactcgactcctgta...tga'),
    'cds_start': 227,
    'cds_end': 1655}]],
 'GALC': [[{'transcript': 'NM_000153.4',
    'protein_id': 'NP_000144.2',
    'protein_seq': Seq('MAEWLLSASWQRRAKAMTAAAGSAGRAAVPLLLCALLAPGGAYVLDDSDGLGRE...ATR'),
    'cds_seq': Seq('atggctgagtggctactctcggcttcctggcaacgccgagcgaaagctatgact...taa'),
    'cds_start': 18,
    'cds_end': 2076}],
  [{'transcript': 'NM_001201402.2',
    'protein_id': 'NP_001188331.1',
    'protein_seq': Seq('MLGKSHGRATHGPLPLADLGIHLPCVKVLHQVTPEEKPAATSRLLVNYPEPYRS...ATR'),
    'cds_seq': Seq('atgctggggaagagccatggtagggccactcatggccctcttcctttggcggac...taa'),
    'cds_start': 166,
    'cds_end': 2146}]],
 'GALK1': [[{'transcript': 'NM_000154.2',
    'protein_id': 'NP_000145.1',
    'protein_seq': Seq('MAALRQPQVAELLAEARRAFREEFGAEPELAVSAPGRVNLIGEHTDYNQGLVLP...LCL'),
    'cds_seq': Seq('atggctgctttgagacagccccaggtcgcggagctgctggccgaggcccggcga...tga'),
    'cds_start': 56,
    'cds_end': 1235}]],
 'GALNS': [[{'transcript': 'NM_000512.5',
    'protein_id': 'NP_000503.1',
    'protein_seq': Seq('MAAVVAATRWWQLLLVLSAAGMGASGAPQPPNILLLLMDDMGWGDLGVYGEPSR...WSH'),
    'cds_seq': Seq('atggcggcggttgtcgcggcgacgaggtggtggcagctgttgctggtgctcagc...tag'),
    'cds_start': 70,
    'cds_end': 1639}]],
 'GALT': [[{'transcript': 'NM_000155.4',
    'protein_id': 'NP_000146.2',
    'protein_seq': Seq('MSRSGTDPQQRQQASEADAAAATFRANDHQHIRYNPLQDEWVLVSAHRMKRPWQ...TIA'),
    'cds_seq': Seq('atgtcgcgcagtggaaccgatcctcagcaacgccagcaggcgtcagaggcggac...tga'),
    'cds_start': 30,
    'cds_end': 1170}]],
 'GAMT': [[{'transcript': 'NM_000156.6',
    'protein_id': 'NP_000147.1',
    'protein_seq': Seq('MSAPSATPIFAPGENCSPAWGAAPAAYDAADTHLRILGKPVMERWETPYMHALA...TKG'),
    'cds_seq': Seq('atgagcgcccccagcgcgacccccatcttcgcgcccggcgagaactgcagcccc...tga'),
    'cds_start': 66,
    'cds_end': 777}]],
 'GATA2': [[{'transcript': 'NM_032638.5',
    'protein_id': 'NP_116027.2',
    'protein_seq': Seq('MEVAPEQPRWMAHPAVLNAQHPDSHHPGLAHNYMEPAQLLPPDEVDVFFNHLDS...AMG'),
    'cds_seq': Seq('atggaggtggcgcccgagcagccgcgctggatggcgcacccggccgtgctgaat...tag'),
    'cds_start': 348,
    'cds_end': 1791}]],
 'GATAD2B': [[{'transcript': 'NM_020699.4',
    'protein_id': 'NP_065750.1',
    'protein_seq': Seq('MDRMTEDALRLNLLKRSLDPADERDDVLAKRLKMEGHEAMERLKMLALLKRKDL...GQK'),
    'cds_seq': Seq('atggatagaatgacagaagatgctcttcgcttgaatctgttgaagcggagcttg...taa'),
    'cds_start': 241,
    'cds_end': 2023}]],
 'GBA1': [[{'transcript': 'NM_000157.4',
    'protein_id': 'NP_000148.2',
    'protein_seq': Seq('MEFSSPSREECPKPLSRVSIMAGSLTGLLLLQAVSWASGARPCIPKSFGYSSVV...RRQ'),
    'cds_seq': Seq('atggagttttcaagtccttccagagaggaatgtcccaagcctttgagtagggta...tga'),
    'cds_start': 137,
    'cds_end': 1748}]],
 'GBE1': [[{'transcript': 'NM_000158.4',
    'protein_id': 'NP_000149.4',
    'protein_seq': Seq('MAAPMTPAARPEDYEAALNAALADVPELARLLEIDPYLKPYAVDFQRRYKQFSQ...LPN'),
    'cds_seq': Seq('atggcggctccgatgactcccgcggctcggcccgaggactacgaggcggcgctc...tga'),
    'cds_start': 128,
    'cds_end': 2237}]],
 'GCDH': [[{'transcript': 'NM_000159.4',
    'protein_id': 'NP_000150.1',
    'protein_seq': Seq('MALRGVSVRLLSRGPGLHVLRTWVSSAAQTEKGGRTQSQLAKSSRPEFDWQDPL...ASK'),
    'cds_seq': Seq('atggccctgagaggcgtctccgtgcggctgctgagccgcggacccggcctgcac...tga'),
    'cds_start': 77,
    'cds_end': 1394}]],
 'GCH1': [[{'transcript': 'NM_000161.3',
    'protein_id': 'NP_000152.1',
    'protein_seq': Seq('MEKGPVRAPAEKPRGARCSNGFPERDPPRPGPSRPAEKPPRPEAKSAQPADGWK...IRS'),
    'cds_seq': Seq('atggagaagggccctgtgcgggcaccggcggagaagccgcggggcgccaggtgc...tga'),
    'cds_start': 163,
    'cds_end': 916}]],
 'GCK': [[{'transcript': 'NM_000162.5',
    'protein_id': 'NP_000153.1',
    'protein_seq': Seq('MLDDRARMEAAKKEKVEQILAEFQLQEEDLKKVMRRMQKEMDRGLRLETHEEAS...LGQ'),
    'cds_seq': Seq('atgctggacgacagagccaggatggaggccgccaagaaggagaaggtagagcag...tga'),
    'cds_start': 486,
    'cds_end': 1884}]],
 'GDAP1': [[{'transcript': 'NM_018972.4',
    'protein_id': 'NP_061845.2',
    'protein_seq': Seq('MAERQEEQRGSPPLRAEGKADAEVKLILYHWTHSFSSQKVRLVIAEKALKCEEH...NYF'),
    'cds_seq': Seq('atggctgagaggcaggaagagcagagagggagcccgcccttgagggcggaaggc...tag'),
    'cds_start': 59,
    'cds_end': 1136}]],
 'GFAP': [[{'transcript': 'NM_002055.5',
    'protein_id': 'NP_002046.1',
    'protein_seq': Seq('MERRRITSAARRSYVSSGEMMVGGLAPGRRLGPGTRLSLARMPPPLPTRVDFSL...DVM'),
    'cds_seq': Seq('atggagaggagacgcatcacctccgctgctcgccgctcctacgtctcctcaggg...tga'),
    'cds_start': 14,
    'cds_end': 1313}]],
 'GFM1': [[{'transcript': 'NM_024996.7',
    'protein_id': 'NP_079272.4',
    'protein_seq': Seq('MRLLGAAAVAALGRGRAPASLGWQRKQVNWKACRWSSSGVIPNEKIRNIGISAH...AKN'),
    'cds_seq': Seq('atgagactcctgggagctgcagccgtcgcggctctggggcgcggaagggccccc...taa'),
    'cds_start': 108,
    'cds_end': 2364}]],
 'GJA1': [[{'transcript': 'NM_000165.5',
    'protein_id': 'NP_000156.1',
    'protein_seq': Seq('MGDWSALGKLLDKVQAYSTAGGKVWLSVLFIFRILLLGTAVESAWGDEQSAFRC...LEI'),
    'cds_seq': Seq('atgggtgactggagcgccttaggcaaactccttgacaaggttcaagcctactca...tag'),
    'cds_start': 203,
    'cds_end': 1352}]],
 'GJB1': [[{'transcript': 'NM_000166.6',
    'protein_id': 'NP_000157.1',
    'protein_seq': Seq('MNWTGLYTLLSGVNRHSTAIGRVWLSVIFIFRIMVLVVAAESVWGDEKSSFICN...SAC'),
    'cds_seq': Seq('atgaactggacaggtttgtacaccttgctcagtggcgtgaaccggcattctact...tga'),
    'cds_start': 128,
    'cds_end': 980}],
  [{'transcript': 'NM_001097642.3',
    'protein_id': 'NP_001091111.1',
    'protein_seq': Seq('MNWTGLYTLLSGVNRHSTAIGRVWLSVIFIFRIMVLVVAAESVWGDEKSSFICN...SAC'),
    'cds_seq': Seq('atgaactggacaggtttgtacaccttgctcagtggcgtgaaccggcattctact...tga'),
    'cds_start': 68,
    'cds_end': 920}]],
 'GJB2': [[{'transcript': 'NM_004004.6',
    'protein_id': 'NP_003995.2',
    'protein_seq': Seq('MDWGTLQTILGGVNKHSTSIGKIWLTVLFIFRIMILVVAAKEVWGDEQADFVCN...KPV'),
    'cds_seq': Seq('atggattggggcacgctgcagacgatcctggggggtgtgaacaaacactccacc...taa'),
    'cds_start': 178,
    'cds_end': 859}]],
 'GLA': [[{'transcript': 'NM_000169.3',
    'protein_id': 'NP_000160.1',
    'protein_seq': Seq('MQLRNPELHLGCALALRFLALVSWDIPGARALDNGLARTPTMGWLHWERFMCNL...DLL'),
    'cds_seq': Seq('atgcagctgaggaacccagaactacatctgggctgcgcgcttgcgcttcgcttc...taa'),
    'cds_start': 22,
    'cds_end': 1312}]],
 'GLB1': [[{'transcript': 'NM_000404.4',
    'protein_id': 'NP_000395.3',
    'protein_seq': Seq('MPGFLVRILPLLLVLLLLGPTRGLRNATQRMFEIDYSRDSFLKDGQPFRYISGS...DHV'),
    'cds_seq': Seq('atgccggggttcctggttcgcatcctccctctgttgctggttctgctgcttctg...tga'),
    'cds_start': 61,
    'cds_end': 2095}]],
 'GLDC': [[{'transcript': 'NM_000170.3',
    'protein_id': 'NP_000161.2',
    'protein_seq': Seq('MQSCARAWGLRLGRGVGGGRRLAGGSGPCWAPRSRDSSSGGGDSAAAGASRLLE...ASS'),
    'cds_seq': Seq('atgcagtcctgtgccagggcgtgggggctgcgcctgggccgcggggtcgggggc...tag'),
    'cds_start': 230,
    'cds_end': 3293}]],
 'GLE1': [[{'transcript': 'NM_001003722.2',
    'protein_id': 'NP_001003722.1',
    'protein_seq': Seq('MPSEGRCWETLKALRSSDKGRLCYYRDWLLRREDVLEECMSLPKLSSYSGWVVE...WRS'),
    'cds_seq': Seq('atgccgtctgagggtcgctgctgggagaccttgaaggccctacgcagttccgac...tga'),
    'cds_start': 87,
    'cds_end': 2184}]],
 'GLI3': [[{'transcript': 'NM_000168.6',
    'protein_id': 'NP_000159.3',
    'protein_seq': Seq('MEAQSHSSTTTEKKKVENSIVKCSTRTDVSEKAVASSTTSNEDESPGQTYHRER...VMQ'),
    'cds_seq': Seq('atggaggcccagtcccacagctccacgaccactgaaaagaaaaaagttgagaat...tag'),
    'cds_start': 281,
    'cds_end': 5024}]],
 'GLRA1': [[{'transcript': 'NM_000171.4',
    'protein_id': 'NP_000162.2',
    'protein_seq': Seq('MYSFNTLRLYLWETIVFFSLAASKEAEAARSAPKPMSPSDFLDKLMGRTSGYDA...HNQ'),
    'cds_seq': Seq('atgtacagcttcaatactcttcgactctacctttgggagaccattgtattcttc...tga'),
    'cds_start': 302,
    'cds_end': 1652}]],
 'GNAO1': [[{'transcript': 'NM_020988.3',
    'protein_id': 'NP_066268.1',
    'protein_seq': Seq('MGCTLSAEERAALERSKAIEKNLKEDGISAAKDVKLLLLGAGESGKSTIVKQMK...GLY'),
    'cds_seq': Seq('atgggatgtactctgagcgcagaggagagagccgccctcgagcggagcaaggcg...tga'),
    'cds_start': 747,
    'cds_end': 1812}]],
 'GNAS': [[{'transcript': 'NM_000516.7',
    'protein_id': 'NP_000507.1',
    'protein_seq': Seq('MGCLGNSKTEDQRNEEKAQREANKKIEKQLQKDKQVYRATHRLLLLGAGESGKS...ELL'),
    'cds_seq': Seq('atgggctgcctcgggaacagtaagaccgaggaccagcgcaacgaggagaaggcg...taa'),
    'cds_start': 306,
    'cds_end': 1491}],
  [{'transcript': 'NM_016592.5',
    'protein_id': 'NP_057676.1',
    'protein_seq': Seq('MDRRSRAQQWRRARHNYNDLCPPIGRRAATALLWLSCSIALLRALATSNARAQQ...RRH'),
    'cds_seq': Seq('atggatcggaggtcccgggctcagcagtggcgccgagctcgccataattacaac...taa'),
    'cds_start': 359,
    'cds_end': 1097}],
  [{'transcript': 'NM_080425.4',
    'protein_id': 'NP_536350.2',
    'protein_seq': Seq('MGVRNCLYGNNMSGQRDIPPEIGEQPEQPPLEAPGAAAPGAGPSPAEEMETEPP...ELL'),
    'cds_seq': Seq('atgggcgtgcgcaactgcctctacggcaataatatgtcaggacaacgcgatatc...taa'),
    'cds_start': 550,
    'cds_end': 3664}]],
 'GNB1': [[{'transcript': 'NM_002074.5',
    'protein_id': 'NP_002065.1',
    'protein_seq': Seq('MSELDQLRQEAEQLKNQIRDARKACADATLSQITNNIDPVGRIQMRTRRTLRGH...IWN'),
    'cds_seq': Seq('atgagtgagcttgaccagttacggcaggaggccgagcaacttaagaaccagatt...taa'),
    'cds_start': 363,
    'cds_end': 1386}]],
 'GNE': [[{'transcript': 'NM_001128227.3',
    'protein_id': 'NP_001121699.1',
    'protein_seq': Seq('METYGYLQRESCFQGPHELYFKNLSKRNKQIMEKNGNNRKLRVCVATCNRADYS...RIY'),
    'cds_seq': Seq('atggaaacctatggttatctgcagagggagtcatgctttcaaggacctcatgaa...tag'),
    'cds_start': 34,
    'cds_end': 2296}],
  [{'transcript': 'NM_005476.7',
    'protein_id': 'NP_005467.1',
    'protein_seq': Seq('MEKNGNNRKLRVCVATCNRADYSKLAPIMFGIKTEPEFFELDVVVLGSHLIDDY...RIY'),
    'cds_seq': Seq('atggagaagaatggaaataaccgaaagctgcgggtttgtgttgctacttgtaac...tag'),
    'cds_start': 170,
    'cds_end': 2339}]],
 'GNPTAB': [[{'transcript': 'NM_024312.5',
    'protein_id': 'NP_077288.2',
    'protein_seq': Seq('MLFKLLQRQTYTCLSHRYGLYVCFLGVVVTIVSAFQFGEVVLEWSRDQYHVLFD...IRV'),
    'cds_seq': Seq('atgctgttcaagctcctgcagagacagacctatacctgcctgtcccacaggtat...tag'),
    'cds_start': 284,
    'cds_end': 4055}]],
 'GNPTG': [[{'transcript': 'NM_032520.5',
    'protein_id': 'NP_115909.1',
    'protein_seq': Seq('MAAGLARLLLLLGLSAGGPAPAGAAKMKVVEEPNAFGVNNPFLPQASRLQAKRD...GSL'),
    'cds_seq': Seq('atggcggcggggctggcgcggctcctgttgctcctcgggctctcggccggcggg...tga'),
    'cds_start': 35,
    'cds_end': 953}]],
 'GPR143': [[{'transcript': 'NM_000273.3',
    'protein_id': 'NP_000264.2',
    'protein_seq': Seq('MASPRLGTFCCPTRDAATQLVLSFQPRAFHALCLGSGGLRLALGLLQLLPGRRP...GDL'),
    'cds_seq': Seq('atggcctccccgcgcctagggaccttctgctgccccacgcgggacgcagccacg...tga'),
    'cds_start': 30,
    'cds_end': 1245}]],
 'GRHPR': [[{'transcript': 'NM_012203.2',
    'protein_id': 'NP_036335.1',
    'protein_seq': Seq('MRPVRLMKVFVTRRIPAEGRVALARAADCEVEQWDSDEPIPAKELERGVAGAHG...LKL'),
    'cds_seq': Seq('atgagaccggtgcgactcatgaaggtgttcgtcacccgcaggatacccgccgag...tag'),
    'cds_start': 55,
    'cds_end': 1042}]],
 'GRIN1': [[{'transcript': 'NM_007327.4',
    'protein_id': 'NP_015566.1',
    'protein_seq': Seq('MSTMRLLTLALLFSCSVARAACDPKIVNIGAVLSTRKHEQMFREAVNQANKRHG...RES'),
    'cds_seq': Seq('atgagcaccatgcgcctgctgacgctcgccctgctgttctcctgctccgtcgcc...tga'),
    'cds_start': 333,
    'cds_end': 3150}]],
 'GRIN2A': [[{'transcript': 'NM_001134407.3',
    'protein_id': 'NP_001127879.1',
    'protein_seq': Seq('MGRVGYWTLLVLPALLVWRGPAPSAAAEKGPPALNIAVMLGHSHDVTERELRTL...SDV'),
    'cds_seq': Seq('atgggcagagtgggctattggaccctgctggtgctgccggcccttctggtctgg...taa'),
    'cds_start': 570,
    'cds_end': 4965}]],
 'GRIN2B': [[{'transcript': 'NM_000834.5',
    'protein_id': 'NP_000825.2',
    'protein_seq': Seq('MKPRAECCSPKFWLVLAVLAVSGSRARSQKSPPSIGIAVILVGTSDEVAIKDAH...SDV'),
    'cds_seq': Seq('atgaagcccagagcggagtgctgttctcccaagttctggttggtgttggccgtc...tga'),
    'cds_start': 708,
    'cds_end': 5163}]],
 'GRN': [[{'transcript': 'NM_002087.4',
    'protein_id': 'NP_002078.1',
    'protein_seq': Seq('MWTLVSWVALTAGLVAGTRCPDGQFCPVACCLDPGGASYSCCRPLLDKWPTTLS...QLL'),
    'cds_seq': Seq('atgtggaccctggtgagctgggtggccttaacagcagggctggtggctggaacg...tga'),
    'cds_start': 40,
    'cds_end': 1822}]],
 'GUCY2D': [[{'transcript': 'NM_000180.4',
    'protein_id': 'NP_000171.1',
    'protein_seq': Seq('MTACARRAGGLPDPGLCGPAWWAPSLPRLPRALPRLPLLLLLLLLQPPALSAVF...QFS'),
    'cds_seq': Seq('atgaccgcctgcgcccgccgagcgggtgggcttccggaccccgggctctgcggt...tga'),
    'cds_start': 129,
    'cds_end': 3441}]],
 'GUSB': [[{'transcript': 'NM_000181.4',
    'protein_id': 'NP_000172.2',
    'protein_seq': Seq('MARGSAVAWAALGPLLWGCALGLQGGMLYPQESPSRECKELDGLWSFRADFSDN...LFT'),
    'cds_seq': Seq('atggcccgggggtcggcggttgcctgggcggcgctcgggccgttgttgtggggc...tga'),
    'cds_start': 30,
    'cds_end': 1986}]],
 'HADHA': [[{'transcript': 'NM_000182.5',
    'protein_id': 'NP_000173.2',
    'protein_seq': Seq('MVACRAIGILSRFSAFRILRSRGYICRNFTGSSALLTRTHINYGVKGDVAVVRI...FYQ'),
    'cds_seq': Seq('atggtggcctgccgggcgattggcatcctcagccgcttttctgccttcaggatc...tga'),
    'cds_start': 36,
    'cds_end': 2328}]],
 'HADHB': [[{'transcript': 'NM_000183.3',
    'protein_id': 'NP_000174.1',
    'protein_seq': Seq('MTILTYPFKNLPTASKWALRFSIRPLSCSSQLRAAPAVQTKTKKTLAKPNIRNV...YPK'),
    'cds_seq': Seq('atgactatcttgacttacccctttaaaaatcttcccactgcatcaaaatgggcc...taa'),
    'cds_start': 60,
    'cds_end': 1485}]],
 'HBA2': [[{'transcript': 'NM_000517.4',
    'protein_id': 'NP_000508.1',
    'protein_seq': Seq('MVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSA...KYR'),
    'cds_seq': Seq('atggtgctgtctcctgccgacaagaccaacgtcaaggccgcctggggtaaggtc...taa'),
    'cds_start': 66,
    'cds_end': 495}],
  [{'transcript': 'NM_000517.6',
    'protein_id': 'NP_000508.1',
    'protein_seq': Seq('MVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSA...KYR'),
    'cds_seq': Seq('atggtgctgtctcctgccgacaagaccaacgtcaaggccgcctggggtaaggtc...taa'),
    'cds_start': 37,
    'cds_end': 466}]],
 'HBB': [[{'transcript': 'NM_000518.4',
    'protein_id': 'NP_000509.1',
    'protein_seq': Seq('MVHLTPEEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDA...KYH'),
    'cds_seq': Seq('atggtgcatctgactcctgaggagaagtctgccgttactgccctgtggggcaag...taa'),
    'cds_start': 50,
    'cds_end': 494}],
  [{'transcript': 'NM_000518.5',
    'protein_id': 'NP_000509.1',
    'protein_seq': Seq('MVHLTPEEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDA...KYH'),
    'cds_seq': Seq('atggtgcatctgactcctgaggagaagtctgccgttactgccctgtggggcaag...taa'),
    'cds_start': 50,
    'cds_end': 494}]],
 'HDAC8': [[{'transcript': 'NM_018486.3',
    'protein_id': 'NP_060956.1',
    'protein_seq': Seq('MEEPEEPADSGQSLVPVYIYSPEYVSMCDSLAKIPKRASMVHSLIEAYALHKQM...HVV'),
    'cds_seq': Seq('atggaggagccggaggaaccggcggacagtgggcagtcgctggtcccggtttat...tag'),
    'cds_start': 82,
    'cds_end': 1216}]],
 'HEXA': [[{'transcript': 'NM_000520.6',
    'protein_id': 'NP_000511.2',
    'protein_seq': Seq('MTSSRLWFSLLLAAAFAGRATALWPWPQNFQTSDQRYVLYPNNFQFQYDVSSAA...EQT'),
    'cds_seq': Seq('atgacaagctccaggctttggttttcgctgctgctggcggcagcgttcgcagga...tga'),
    'cds_start': 42,
    'cds_end': 1632}]],
 'HEXB': [[{'transcript': 'NM_000521.4',
    'protein_id': 'NP_000512.2',
    'protein_seq': Seq('MELCGLGLPRPPMLLALLLATLLAAMLALLTQVALVVQVAEAARAPSVSAKPGP...ENM'),
    'cds_seq': Seq('atggagctgtgcgggctggggctgccccggccgcccatgctgctggcgctgctg...taa'),
    'cds_start': 28,
    'cds_end': 1699}]],
 'HGD': [[{'transcript': 'NM_000187.4',
    'protein_id': 'NP_000178.2',
    'protein_seq': Seq('MAELKYISGFGNECSSEDPRCPGSLPEGQNNPQVCPYNLYAEQLSGSAFTCPRS...EPN'),
    'cds_seq': Seq('atggctgagttaaagtacatttctggatttgggaatgagtgttcttcagaggat...tga'),
    'cds_start': 128,
    'cds_end': 1466}]],
 'HGSNAT': [[{'transcript': 'NM_152419.3',
    'protein_id': 'NP_689632.2',
    'protein_seq': Seq('MSGAGRALAALLLAASVLSAALLAPGGSSGRDAQAAPPRDLDKKRHAELKMDQA...WKI'),
    'cds_seq': Seq('atgagcggggcgggcagggcgctggccgcgctgctgctggccgcgtccgtgctg...tga'),
    'cds_start': 33,
    'cds_end': 1941}]],
 'HLCS': [[{'transcript': 'NM_001352514.2',
    'protein_id': 'NP_001339443.1',
    'protein_seq': Seq('MLITLCYLYLWARWGRRPAELVRATVRRLRASRCSFTFCGAAAQPPGARVCLSR...KRR'),
    'cds_seq': Seq('atgctcatcacgctgtgctacctgtacctgtgggcgcgctggggtcgccggccg...taa'),
    'cds_start': 31,
    'cds_end': 2653}]],
 'HMBS': [[{'transcript': 'NM_000190.4',
    'protein_id': 'NP_000181.2',
    'protein_seq': Seq('MSGNGNAAATAEENSPKMRVIRVGTRKSQLARIQTDSVVATLKASYPGLQFEII...DAH'),
    'cds_seq': Seq('atgtctggtaacggcaatgcggctgcaacggcggaagaaaacagcccaaagatg...taa'),
    'cds_start': 153,
    'cds_end': 1239}]],
 'HMGCL': [[{'transcript': 'NM_000191.3',
    'protein_id': 'NP_000182.2',
    'protein_seq': Seq('MAAMRKALPRRLVGLASLRAVSTSSMGTLPKRVKIVEVGPRDGLQNEKNIVSTP...CKL'),
    'cds_seq': Seq('atggcagcaatgaggaaggcgcttccgcggcgactggtgggcttggcgtccctc...tga'),
    'cds_start': 14,
    'cds_end': 992}]],
 'HNF1A': [[{'transcript': 'NM_000545.5',
    'protein_id': 'NP_000536.5',
    'protein_seq': Seq('MVSKLSQLQTELLAALLESGLSKEALIQALGEPGPYLLAGEGPLDKGESCGGGR...SSQ'),
    'cds_seq': Seq('atggtttctaaactgagccagctgcagacggagctcctggcggccctgctcgag...taa'),
    'cds_start': 23,
    'cds_end': 1919}],
  [{'transcript': 'NM_000545.8',
    'protein_id': 'NP_000536.6',
    'protein_seq': Seq('MVSKLSQLQTELLAALLESGLSKEALIQALGEPGPYLLAGEGPLDKGESCGGGR...SSQ'),
    'cds_seq': Seq('atggtttctaaactgagccagctgcagacggagctcctggcggccctgctcgag...taa'),
    'cds_start': 226,
    'cds_end': 2122}]],
 'HNF1B': [[{'transcript': 'NM_000458.4',
    'protein_id': 'NP_000449.1',
    'protein_seq': Seq('MVSKLTSLQQELLSALLSSGVTKEVLVQALEELLPSPNFGVKLETLPLSPGSGA...QAW'),
    'cds_seq': Seq('atggtgtccaagctcacgtcgctccagcaagaactcctgagcgccctgctgagc...tga'),
    'cds_start': 175,
    'cds_end': 1849}]],
 'HNF4A': [[{'transcript': 'NM_175914.5',
    'protein_id': 'NP_787110.2',
    'protein_seq': Seq('MVSVNAPLGAPVESSYDTSPSEGTNLNAPNSLGVSALCAICGDRATGKHYGASS...EVI'),
    'cds_seq': Seq('atggtcagcgtgaacgcgcccctcggggctccagtggagagttcttacgacacg...tag'),
    'cds_start': 106,
    'cds_end': 1465}]],
 'HNRNPU': [[{'transcript': 'NM_031844.3',
    'protein_id': 'NP_114032.2',
    'protein_seq': Seq('MSSSPVNVKKLKVSELKEELKKRRLSDKGLKAELMERLQAALDDEEAGGRPAME...GYY'),
    'cds_seq': Seq('atgagttcctcgcctgttaatgtaaaaaagctgaaggtgtcggagctgaaagag...tga'),
    'cds_start': 236,
    'cds_end': 2714}]],
 'HOGA1': [[{'transcript': 'NM_138413.4',
    'protein_id': 'NP_612422.2',
    'protein_seq': Seq('MLGPQVWSSVRQGLSRSLSRNVGVWASGEGKKVDIAGIYPPVTTPFTATAEVDY...GWL'),
    'cds_seq': Seq('atgctgggtccccaagtctggtcttctgtgaggcaggggctaagcaggagcttg...tga'),
    'cds_start': 315,
    'cds_end': 1299}]],
 'HPRT1': [[{'transcript': 'NM_000194.2',
    'protein_id': 'NP_000185.1',
    'protein_seq': Seq('MATRSPGVVISDDEPGYDLDLFCIPNHYAEDLERVFIPHGLIMDRTERLARDVM...YKA'),
    'cds_seq': Seq('atggcgacccgcagccctggcgtcgtgattagtgatgatgaaccaggttatgac...taa'),
    'cds_start': 167,
    'cds_end': 824}],
  [{'transcript': 'NM_000194.3',
    'protein_id': 'NP_000185.1',
    'protein_seq': Seq('MATRSPGVVISDDEPGYDLDLFCIPNHYAEDLERVFIPHGLIMDRTERLARDVM...YKA'),
    'cds_seq': Seq('atggcgacccgcagccctggcgtcgtgattagtgatgatgaaccaggttatgac...taa'),
    'cds_start': 147,
    'cds_end': 804}]],
 'HPS1': [[{'transcript': 'NM_000195.5',
    'protein_id': 'NP_000186.2',
    'protein_seq': Seq('MKCVLVATEGAEVLFYWTDQEFEESLRLKFGQSENEEEELPALEDQLSTLLAPV...PLL'),
    'cds_seq': Seq('atgaagtgcgtcttggtggccactgagggcgcagaggtcctcttctactggaca...tag'),
    'cds_start': 234,
    'cds_end': 2337}]],
 'HPS3': [[{'transcript': 'NM_032383.5',
    'protein_id': 'NP_115759.2',
    'protein_seq': Seq('MVQLYNLHPFGSQQVVPCKLEPDRFCGGGRDALFVAAGCKVEAFAVAGQELCQP...PLT'),
    'cds_seq': Seq('atggtgcagctgtacaacctgcacccgttcgggtcgcagcaggtggtgccctgc...taa'),
    'cds_start': 86,
    'cds_end': 3101}]],
 'HPS4': [[{'transcript': 'NM_022081.6',
    'protein_id': 'NP_071364.4',
    'protein_seq': Seq('MATSTSTEAKSASWWNYFFLYDGSKVKEEGDPTRAGICYFYPSQTLLDQQELLC...NLL'),
    'cds_seq': Seq('atggccacctctacctccacagaggcaaagtcagcctcgtggtggaattatttt...tga'),
    'cds_start': 588,
    'cds_end': 2715}]],
 'HPS5': [[{'transcript': 'NM_181507.2',
    'protein_id': 'NP_852608.1',
    'protein_seq': Seq('MAFVPVIPESYSHVLAEFESLDPLLSALRLDSSRLKCTSIAVSRKWLALGSSGG...QQA'),
    'cds_seq': Seq('atggcttttgtgccagtgataccagagtcctacagccatgttcttgcagagttt...tag'),
    'cds_start': 244,
    'cds_end': 3634}]],
 'HSD17B3': [[{'transcript': 'NM_000197.1',
    'protein_id': 'NP_000188.1',
    'protein_seq': Seq('MGDVLEQFFILTGLLVCLACLAKCVRFSRCVLLNYWKVLPKSFLRSMGQWAVIT...KVR'),
    'cds_seq': Seq('atgggggacgtcctggaacagttcttcatcctcacagggctgctggtgtgcctg...tag'),
    'cds_start': 48,
    'cds_end': 981}],
  [{'transcript': 'NM_000197.2',
    'protein_id': 'NP_000188.1',
    'protein_seq': Seq('MGDVLEQFFILTGLLVCLACLAKCVRFSRCVLLNYWKVLPKSFLRSMGQWAVIT...KVR'),
    'cds_seq': Seq('atgggggacgtcctggaacagttcttcatcctcacagggctgctggtgtgcctg...tag'),
    'cds_start': 72,
    'cds_end': 1005}]],
 'HSD17B4': [[{'transcript': 'NM_000414.4',
    'protein_id': 'NP_000405.1',
    'protein_seq': Seq('MGSPLRFDGRVVLVTGAGAGLGRAYALAFAERGALVVVNDLGGDFKGVGKGSLA...AKL'),
    'cds_seq': Seq('atgggctcaccgctgaggttcgacgggcgggtggtactggtcaccggcgcgggg...tga'),
    'cds_start': 79,
    'cds_end': 2290}]],
 'HSD3B2': [[{'transcript': 'NM_000198.4',
    'protein_id': 'NP_000189.1',
    'protein_seq': Seq('MGWSCLVTGAGGLLGQRIVRLLVEEKELKEIRALDKAFRPELREEFSKLQNRTK...KTQ'),
    'cds_seq': Seq('atgggctggagctgccttgtgacaggagcaggagggcttctgggtcagaggatc...tga'),
    'cds_start': 142,
    'cds_end': 1261}]],
 'HSPG2': [[{'transcript': 'NM_005529.7',
    'protein_id': 'NP_005520.4',
    'protein_seq': Seq('MGWRAAGALLLALLLHGRLLAVTHGLRAYDGLSLPEDIETVTASQMRWTHSYLS...CPS'),
    'cds_seq': Seq('atggggtggcgggcggcgggcgcgctgctgctggcgctgctgctgcacgggcgg...tag'),
    'cds_start': 93,
    'cds_end': 13269}]],
 'HUWE1': [[{'transcript': 'NM_031407.7',
    'protein_id': 'NP_113584.3',
    'protein_seq': Seq('MKVDRTKLKKTPTEAPADCRALIDKLKVCNDEQLLLELQQIKTWNIGKCELYHW...GLA'),
    'cds_seq': Seq('atgaaagtagacaggactaaactgaagaagacacctactgaggctcctgcagac...taa'),
    'cds_start': 393,
    'cds_end': 13518}]],
 'IDS': [[{'transcript': 'NM_000202.8',
    'protein_id': 'NP_000193.1',
    'protein_seq': Seq('MPPPRTGRGLLWLGLVLSSVCVALGSETQANSTTDALNVLLIIVDDLRPSLGCY...LMP'),
    'cds_seq': Seq('atgccgccaccccggaccggccgaggccttctctggctgggtctggttctgagc...tga'),
    'cds_start': 169,
    'cds_end': 1822}]],
 'IDUA': [[{'transcript': 'NM_000203.4',
    'protein_id': 'NP_000194.2',
    'protein_seq': Seq('MRPLRPRAALLALLASLLAAPPVAPAEAPHLVHVDAARALWPLRRFWRSTGFCP...GNP'),
    'cds_seq': Seq('atgcgtcccctgcgcccccgcgccgcgctgctggcgctcctggcctcgctcctg...tga'),
    'cds_start': 88,
    'cds_end': 2050}],
  [{'transcript': 'NM_000203.5',
    'protein_id': 'NP_000194.2',
    'protein_seq': Seq('MRPLRPRAALLALLASLLAAPPVAPAEAPHLVHVDAARALWPLRRFWRSTGFCP...GNP'),
    'cds_seq': Seq('atgcgtcccctgcgcccccgcgccgcgctgctggcgctcctggcctcgctcctg...tga'),
    'cds_start': 41,
    'cds_end': 2003}]],
 'IFT122': [[{'transcript': 'NM_052989.3',
    'protein_id': 'NP_443715.1',
    'protein_seq': Seq('MRAVLTWRDKAEHCINDIAFKPDGTQLILAAGSRLLVYDTSDGTLLQPLKGHKD...PGP'),
    'cds_seq': Seq('atgagggccgtgttgacgtggagagataaagccgagcactgtataaatgacatc...tga'),
    'cds_start': 107,
    'cds_end': 3833}]],
 'IFT140': [[{'transcript': 'NM_014714.4',
    'protein_id': 'NP_055529.2',
    'protein_seq': Seq('MALYYDHQIEAPDAAGSPSFISWHPVHPFLAVAYISTTSTGSVDIYLEQGECVP...DDP'),
    'cds_seq': Seq('atggccctctattatgaccaccagatagaagccccggatgcagcagggtcaccc...tga'),
    'cds_start': 326,
    'cds_end': 4715}]],
 'IFT172': [[{'transcript': 'NM_015662.3',
    'protein_id': 'NP_056477.1',
    'protein_seq': Seq('MHLKHLRTLLSPQDGAAKVTCMAWSQNNAKFAVCTVDRVVLLYDEHGERRDKFS...SFQ'),
    'cds_seq': Seq('atgcacttgaagcacctgaggaccctgctgagccctcaggatggagctgcaaag...tag'),
    'cds_start': 90,
    'cds_end': 5340}]],
 'IGF1R': [[{'transcript': 'NM_000875.5',
    'protein_id': 'NP_000866.1',
    'protein_seq': Seq('MKSGSGGGSPTSLWGLLFLSAALSLWPTSGEICGPGIDIRNDYQQLKRLENCTV...STC'),
    'cds_seq': Seq('atgaagtctggctccggaggagggtccccgacctcgctgtgggggctcctgttt...tga'),
    'cds_start': 1043,
    'cds_end': 5147}]],
 'IGHMBP2': [[{'transcript': 'NM_002180.3',
    'protein_id': 'NP_002171.2',
    'protein_seq': Seq('MASAAVESFVTKQLDLLELERDAEVEERRSWQENISLKELQSRGVCLLKLQVSS...RGT'),
    'cds_seq': Seq('atggcctcggcagctgtggagagcttcgtgaccaagcaactggacctgctggag...tga'),
    'cds_start': 62,
    'cds_end': 3044}]],
 'IL12RB1': [[{'transcript': 'NM_005535.3',
    'protein_id': 'NP_005526.1',
    'protein_seq': Seq('MEPLVTWVVPLLFLFLLSRQGAACRTSECCFQDPPYPDADSGSASGPRDLRCYR...AKM'),
    'cds_seq': Seq('atggagccgctggtgacctgggtggtccccctcctcttcctcttcctgctgtcc...tga'),
    'cds_start': 111,
    'cds_end': 2100}]],
 'IL2RG': [[{'transcript': 'NM_000206.3',
    'protein_id': 'NP_000197.1',
    'protein_seq': Seq('MLKPSLPFTSLLFLQLPLLGVGLNTTILTPNGNEDTTADFFLTTMPTDSLSVST...PET'),
    'cds_seq': Seq('atgttgaagccatcattaccattcacatccctcttattcctgcagctgcccctg...tga'),
    'cds_start': 38,
    'cds_end': 1148}]],
 'IMPG2': [[{'transcript': 'NM_016247.4',
    'protein_id': 'NP_057331.2',
    'protein_seq': Seq('MIMFPLFGKISLGILIFVLIEGDFPSLTAQTYLSIEEIQEPKSAVSFLLPEEST...EEV'),
    'cds_seq': Seq('atgattatgtttcctctttttgggaagatttctctgggtattttgatatttgtc...taa'),
    'cds_start': 203,
    'cds_end': 3929}]],
 'INF2': [[{'transcript': 'NM_022489.4',
    'protein_id': 'NP_071934.3',
    'protein_seq': Seq('MSVKEGAQRKWAALKEKLGPQDSDPTEANLESADPELCIRLLQMPSVVNYSGLR...VIQ'),
    'cds_seq': Seq('atgtcggtgaaggagggcgcacagcgcaagtgggcagcgctgaaggagaagctg...taa'),
    'cds_start': 131,
    'cds_end': 3881}]],
 'INSR': [[{'transcript': 'NM_000208.4',
    'protein_id': 'NP_000199.2',
    'protein_seq': Seq('MATGGRRGAAAAPLLVAVAALLLGAAGHLYPGEVCPGMDIRNNLTRLHELENCS...NPS'),
    'cds_seq': Seq('atggccaccgggggccggcggggggcggcggccgcgccgctgctggtggcggtg...taa'),
    'cds_start': 523,
    'cds_end': 4672}]],
 'INVS': [[{'transcript': 'NM_014425.5',
    'protein_id': 'NP_055240.2',
    'protein_seq': Seq('MNKSENLLFAGSSLASQVHAAAVNGDKGALQRLIVGNSALKDKEDQFGRTPLMY...TKP'),
    'cds_seq': Seq('atgaacaagtcagagaacctgctgtttgctggttcatcattagcatcacaagtc...tga'),
    'cds_start': 198,
    'cds_end': 3396}]],
 'IQCB1': [[{'transcript': 'NM_001023570.4',
    'protein_id': 'NP_001018864.2',
    'protein_seq': Seq('MKPTGTDPRILSIAAEVAKSPEQNVPVILLKLKEIINITPLGSSELKKIKQDIY...KPP'),
    'cds_seq': Seq('atgaagccaacaggtacagacccaaggatcttatctatagctgctgaagttgca...tag'),
    'cds_start': 196,
    'cds_end': 1993}]],
 'IQSEC2': [[{'transcript': 'NM_001111125.3',
    'protein_id': 'NP_001104595.1',
    'protein_seq': Seq('MEAGSGPPGGPGSESPNRAVEYLLELNNIIESQQQLLETQRRRIEELEGQLDQL...TVV'),
    'cds_seq': Seq('atggaggcggggtcggggcccccgggcggcccgggatccgagagcccaaatcgg...tga'),
    'cds_start': 227,
    'cds_end': 4694}]],
 'IRF6': [[{'transcript': 'NM_006147.4',
    'protein_id': 'NP_006138.1',
    'protein_seq': Seq('MALHPRRVRLKPWLVAQVDSGLYPGLIWLHRDSKRFQIPWKHATRHSPQQEEEN...PPQ'),
    'cds_seq': Seq('atggccctccacccccgcagagtccggctaaagccctggctggtggcccaggtg...taa'),
    'cds_start': 271,
    'cds_end': 1675}]],
 'ITGA2B': [[{'transcript': 'NM_000419.5',
    'protein_id': 'NP_000410.2',
    'protein_seq': Seq('MARALCPLQALWLLEWVLLLLGPCAAPPAWALNLDPVQLTFYAGPNGSQFGFSL...EGE'),
    'cds_seq': Seq('atggccagagctttgtgtccactgcaagccctctggcttctggagtgggtgctg...tga'),
    'cds_start': 176,
    'cds_end': 3296}]],
 'ITGB2': [[{'transcript': 'NM_000211.5',
    'protein_id': 'NP_000202.3',
    'protein_seq': Seq('MLGLRPPLLALVGLLSLGCVLSQECTKFKVSSCRECIESGPGCTWCQKLNFTGP...AES'),
    'cds_seq': Seq('atgctgggcctgcgccccccactgctcgccctggtggggctgctctccctcggg...tag'),
    'cds_start': 82,
    'cds_end': 2392}]],
 'ITGB3': [[{'transcript': 'NM_000212.3',
    'protein_id': 'NP_000203.2',
    'protein_seq': Seq('MRARPRPRPLWATVLALGALAGVGVGGPNICTTRGVSSCQQCLAVSPMCAWCSD...RGT'),
    'cds_seq': Seq('atgcgagcgcggccgcggccccggccgctctgggcgactgtgctggcgctgggg...taa'),
    'cds_start': 35,
    'cds_end': 2402}]],
 'ITGB4': [[{'transcript': 'NM_000213.5',
    'protein_id': 'NP_000204.3',
    'protein_seq': Seq('MAGPRPSPWARLLLAALISVSLSGTLANRCKKAPVKSCTECVRVDKDCAYCTDE...FQT'),
    'cds_seq': Seq('atggcagggccacgccccagcccatgggccaggctgctcctggcagccttgatc...tga'),
    'cds_start': 164,
    'cds_end': 5633}]],
 'ITPR1': [[{'transcript': 'NM_001378452.1',
    'protein_id': 'NP_001365381.1',
    'protein_seq': Seq('MSDKMSSFLHIGDICSLYAEGSTNGFISTLGLVDDRCVVQPETGDLNNPPKKFR...QPA'),
    'cds_seq': Seq('atgtctgacaaaatgtctagcttcctacatattggagacatttgttctctgtac...taa'),
    'cds_start': 350,
    'cds_end': 8627}]],
 'IVD': [[{'transcript': 'NM_002225.5',
    'protein_id': 'NP_002216.3',
    'protein_seq': Seq('MATATRLLGWRVASWRLRPPLAGFVSQRAHSLLPVDDAINGLSEEQRQLRQTMA...DFH'),
    'cds_seq': Seq('atggcgactgcgactcggctgctggggtggcgtgtggcgagctggaggctgcgg...tag'),
    'cds_start': 33,
    'cds_end': 1305}]],
 'JAG1': [[{'transcript': 'NM_000214.3',
    'protein_id': 'NP_000205.1',
    'protein_seq': Seq('MRSPRTRGRSGRPLSLLLALLCALRAKVCGASGQFELEILSMQNVNGELQNGNC...YIV'),
    'cds_seq': Seq('atgcgttccccacggacgcgcggccggtccgggcgccccctaagcctcctgctc...tag'),
    'cds_start': 469,
    'cds_end': 4126}]],
 'JAK3': [[{'transcript': 'NM_000215.4',
    'protein_id': 'NP_000206.2',
    'protein_seq': Seq('MAPPSEETPLIPQRSCSLLSTEAGALHVLLPARGPGPPQRLSFSFGDHLAEDLC...SFS'),
    'cds_seq': Seq('atggcacctccaagtgaagagacgcccctgatccctcagcgttcatgcagcctc...tag'),
    'cds_start': 50,
    'cds_end': 3425}]],
 'KAT6A': [[{'transcript': 'NM_006766.5',
    'protein_id': 'NP_006757.2',
    'protein_seq': Seq('MVKLANPLYTEWILEAIKKVKKQKQRPSEERICNAVSSSHGLDRKTVLEQLELS...MRR'),
    'cds_seq': Seq('atggtaaaactcgcaaacccgctttatactgagtggattttggaggccatcaaa...tga'),
    'cds_start': 412,
    'cds_end': 6427}]],
 'KAT6B': [[{'transcript': 'NM_012330.4',
    'protein_id': 'NP_036462.2',
    'protein_seq': Seq('MVKLANPLYTEWILEAIQKIKKQKQRPSEERICHAVSTSHGLDKKTVSEQLELS...MRR'),
    'cds_seq': Seq('atggtaaaacttgcaaacccactttatacagagtggattcttgaagctatacag...tag'),
    'cds_start': 514,
    'cds_end': 6736}]],
 'KCNA2': [[{'transcript': 'NM_004974.4',
    'protein_id': 'NP_004965.1',
    'protein_seq': Seq('MTVATGDPADEAAALPGHPQDTYDPEADHECCERVVINISGLRFETQLKTLAQF...TDV'),
    'cds_seq': Seq('atgacagtggccaccggagacccagcagacgaggctgctgccctccctgggcac...tga'),
    'cds_start': 626,
    'cds_end': 2126}]],
 'KCNB1': [[{'transcript': 'NM_004975.4',
    'protein_id': 'NP_004966.1',
    'protein_seq': Seq('MPAGMTKHGSRSTSSLPPEPMEIVRSKACSRRVRLNVGGLAHEVLWRTLDRLPR...QSI'),
    'cds_seq': Seq('atgccggcgggcatgacgaagcatggctcccgctccaccagctcgctgccgccc...tga'),
    'cds_start': 188,
    'cds_end': 2765}]],
 'KCNH2': [[{'transcript': 'NM_000238.4',
    'protein_id': 'NP_000229.1',
    'protein_seq': Seq('MPVRRGHVAPQNTFLDTIIRKFEGQSRKFIIANARVENCAVIYCNDGFCELCGY...PGS'),
    'cds_seq': Seq('atgccggtgcggaggggccacgtcgcgccgcagaacaccttcctggacaccatc...tag'),
    'cds_start': 408,
    'cds_end': 3888}]],
 'KCNJ1': [[{'transcript': 'NM_153766.3',
    'protein_id': 'NP_722450.1',
    'protein_seq': Seq('MFKHLRKWVVTRFFGHSRQRARLVSKDGRCNIEFGNVEAQSRFIFFVDIWTTVL...TKM'),
    'cds_seq': Seq('atgttcaaacatcttcggaaatgggtcgtcactcgcttttttgggcattctcgg...taa'),
    'cds_start': 315,
    'cds_end': 1434}]],
 'KCNJ11': [[{'transcript': 'NM_000525.4',
    'protein_id': 'NP_000516.3',
    'protein_seq': Seq('MLSRKGIIPEEYVLTRLAEDPAKPRYRARQRRARFVSKKGNCNVAHKNIREQGR...SLS'),
    'cds_seq': Seq('atgctgtcccgcaagggcatcatccccgaggaatacgtgctgacacgcctggca...tga'),
    'cds_start': 568,
    'cds_end': 1741}]],
 'KCNJ2': [[{'transcript': 'NM_000891.3',
    'protein_id': 'NP_000882.1',
    'protein_seq': Seq('MGSVRTNRYSIVSSEEDGMKLATMAVANGFGNGKSKVHTRQQCRSRFVKKDGHC...SEI'),
    'cds_seq': Seq('atgggcagtgtgcgaaccaaccgctacagcatcgtctcttcagaagaagacggt...tga'),
    'cds_start': 386,
    'cds_end': 1670}]],
 'KCNQ1': [[{'transcript': 'NM_000218.3',
    'protein_id': 'NP_000209.2',
    'protein_seq': Seq('MAAASSPPRAERKRWGWGRLPGARRGSAGLAKKCPFSLELAEGGPAGGALYAPI...EGS'),
    'cds_seq': Seq('atggccgcggcctcctccccgcccagggccgagaggaagcgctggggttggggc...tga'),
    'cds_start': 91,
    'cds_end': 2122}]],
 'KCNQ2': [[{'transcript': 'NM_172107.4',
    'protein_id': 'NP_742105.1',
    'protein_seq': Seq('MVQKSRNGGVYPGPSGEKKLKVGFVGLDPGAPDSTRDGALLIAGSEAPKRGSIL...PRK'),
    'cds_seq': Seq('atggtgcagaagtcgcgcaacggcggcgtataccccggcccgagcggggagaag...tga'),
    'cds_start': 192,
    'cds_end': 2811}]],
 'KCNT1': [[{'transcript': 'NM_020822.3',
    'protein_id': 'NP_065873.2',
    'protein_seq': Seq('MPLPDGARTPGGVCREARGGGYTNRTFEFDDGQCAPRRPCAGDGALLDTAGFKM...TQL'),
    'cds_seq': Seq('atgccactccctgacggggcgcggaccccggggggcgtctgccgggaggcgcgc...tga'),
    'cds_start': 74,
    'cds_end': 3782}]],
 'KCNV2': [[{'transcript': 'NM_133497.4',
    'protein_id': 'NP_598004.1',
    'protein_seq': Seq('MLKQSERRRSWSYRPWNTTENEGSQHRRSICSLGARSGSQASIHGWTEGNYNYY...QEN'),
    'cds_seq': Seq('atgctcaaacagagtgagaggagacggtcctggagctacaggccctggaacacg...tag'),
    'cds_start': 230,
    'cds_end': 1868}]],
 'KDM5B': [[{'transcript': 'NM_006618.5',
    'protein_id': 'NP_006609.3',
    'protein_seq': Seq('MEAATTLHPGPRPALPLGGPGPLGEFLPPPECPVFEPSWEEFADPFAFIHKIRP...SRK'),
    'cds_seq': Seq('atggaggcggccaccacactgcacccaggcccgcgcccggcgctgcccctcggg...taa'),
    'cds_start': 116,
    'cds_end': 4751}]],
 'KDM5C': [[{'transcript': 'NM_004187.5',
    'protein_id': 'NP_004178.2',
    'protein_seq': Seq('MEPGSDDFLPPPECPVFEPSWAEFRDPLGYIAKIRPIAEKSGICKIRPPADWQP...QQL'),
    'cds_seq': Seq('atggagccggggtccgacgatttcctaccgccaccggagtgcccggtgttcgag...tga'),
    'cds_start': 318,
    'cds_end': 5001}]],
 'KDM6A': [[{'transcript': 'NM_001291415.2',
    'protein_id': 'NP_001278344.1',
    'protein_seq': Seq('MKSCGVSLATAAAAAAAFGDEEKKMAAGKASGESEEASPSLTAEEREALGGLDS...ASS'),
    'cds_seq': Seq('atgaaatcctgcggagtgtcgctcgctaccgccgccgctgccgccgccgctttc...tga'),
    'cds_start': 364,
    'cds_end': 4726}]],
 'KDM6B': [[{'transcript': 'NM_001348716.2',
    'protein_id': 'NP_001335645.1',
    'protein_seq': Seq('MHRAVDPPGARAAREAFALGGLSCAGAWSSCPPHPPPRSAWLPGGRCSASIGQP...TSR'),
    'cds_seq': Seq('atgcatcgggcagtggaccctccaggggcccgcgctgcacgggaagcctttgcc...tga'),
    'cds_start': 521,
    'cds_end': 5453}]],
 'KIAA0586': [[{'transcript': 'NM_001329943.3',
    'protein_id': 'NP_001316872.1',
    'protein_seq': Seq('MKGSEVSLEKKKKIKMPVKRLREVVSQNHGDHLVLLKDELPCVPPALSANKRLP...DTF'),
    'cds_seq': Seq('atgaaaggctctgaggtcagcttggagaagaaaaaaaagattaagatgccagtg...tga'),
    'cds_start': 546,
    'cds_end': 5193}]],
 'KIF11': [[{'transcript': 'NM_004523.4',
    'protein_id': 'NP_004514.2',
    'protein_seq': Seq('MASQPNSSAKKKEEKGKNIQVVVRCRPFNLAERKASAHSIVECDPVRKEVSVRT...INL'),
    'cds_seq': Seq('atggcgtcgcagccaaattcgtctgcgaagaagaaagaggagaaggggaagaac...taa'),
    'cds_start': 246,
    'cds_end': 3417}]],
 'KIF1A': [[{'transcript': 'NM_001244008.2',
    'protein_id': 'NP_001230937.1',
    'protein_seq': Seq('MAGASVKVAVRVRPFNSREMSRDSKCIIQMSGSTTTIVNPKQPKETPKSFSFDY...MRV'),
    'cds_seq': Seq('atggccggggcttcggtgaaggtggcggtgcgggtccgccccttcaattcccgg...tga'),
    'cds_start': 158,
    'cds_end': 5534}]],
 'KIF5A': [[{'transcript': 'NM_004984.4',
    'protein_id': 'NP_004975.2',
    'protein_seq': Seq('MAETNNECSIKVLCRFRPLNQAEILRGDKFIPIFQGDDSVVIGGKPYVFDRVFP...AAS'),
    'cds_seq': Seq('atggcggagaccaacaacgaatgtagcatcaaggtgctctgccgattccggccc...taa'),
    'cds_start': 228,
    'cds_end': 3327}]],
 'KIF7': [[{'transcript': 'NM_198525.3',
    'protein_id': 'NP_940927.2',
    'protein_seq': Seq('MGLEAQRLPGAEEAPVRVALRVRPLLPKELLHGHQSCLQVEPGLGRVTLGRDRH...NPL'),
    'cds_seq': Seq('atggggctggaggctcagaggctgccaggggctgaggaggccccagtgcgggtt...taa'),
    'cds_start': 93,
    'cds_end': 4125}]],
 'KIT': [[{'transcript': 'NM_000222.3',
    'protein_id': 'NP_000213.1',
    'protein_seq': Seq('MRGARGAWDFLCVLLLLLRVQTGSSQPSVSPGEPSPPSIHPGKSDLIVRVGDEI...DDV'),
    'cds_seq': Seq('atgagaggcgctcgcggcgcctgggattttctctgcgttctgctcctactgctt...tga'),
    'cds_start': 58,
    'cds_end': 2989}]],
 'KMT2A': [[{'transcript': 'NM_001197104.2',
    'protein_id': 'NP_001184033.1',
    'protein_seq': Seq('MAHSCRWRFPARPGTTGGGGGGGRRGLGGAPRQRVPALLLPPGPPVGGGGPGAP...FLN'),
    'cds_seq': Seq('atggcgcacagctgtcggtggcgcttccccgcccgacccgggaccaccgggggc...taa'),
    'cds_start': 21,
    'cds_end': 11940}]],
 'KMT2B': [[{'transcript': 'NM_014727.3',
    'protein_id': 'NP_055542.1',
    'protein_seq': Seq('MAAAAGGGSCPGPGSARGRFPGRPRGAGGGGGRGGRGNGAERVRVALRRGGGAT...FLN'),
    'cds_seq': Seq('atggcggcggcggcgggcggcggcagttgccccgggcctggctccgcgcggggc...tga'),
    'cds_start': 16,
    'cds_end': 8164}]],
 'KMT2C': [[{'transcript': 'NM_170606.3',
    'protein_id': 'NP_733751.2',
    'protein_seq': Seq('MSSEEDKSVEQPQPPPPPPEEPGAPAPSPAAADKRPRGRPRKDGASPFQRARKK...WMN'),
    'cds_seq': Seq('atgtcgtcggaggaggacaagagcgtggagcagccgcagccgccgccaccaccc...tga'),
    'cds_start': 217,
    'cds_end': 14953}]],
 'KMT2D': [[{'transcript': 'NM_003482.4',
    'protein_id': 'NP_003473.3',
    'protein_seq': Seq('MDSQKLAGEDKDSEPAADGPAASEDPSATESDLPNPHVGEVSVLSSGSPRLQET...WMN'),
    'cds_seq': Seq('atggacagccagaagctggctggtgaggataaagattcagaaccggcagctgat...taa'),
    'cds_start': 1219,
    'cds_end': 17833}]],
 'KMT2E': [[{'transcript': 'NM_182931.3',
    'protein_id': 'NP_891847.1',
    'protein_seq': Seq('MSIVIPLGVDTAETSYLEMAAGSEPESVEASPVVVEKSNSYPHQLYTSSSHHSH...GWH'),
    'cds_seq': Seq('atgagcatagtgatcccattgggggttgatacagcagagacgtcatacttggaa...taa'),
    'cds_start': 519,
    'cds_end': 6096}]],
 'KRAS': [[{'transcript': 'NM_004985.5',
    'protein_id': 'NP_004976.2',
    'protein_seq': Seq('MTEYKLVVVGAGGVGKSALTIQLIQNHFVDEYDPTIEDSYRKQVVIDGETCLLD...VIM'),
    'cds_seq': Seq('atgactgaatataaacttgtggtagttggagctggtggcgtaggcaagagtgcc...taa'),
    'cds_start': 190,
    'cds_end': 757}],
  [{'transcript': 'NM_033360.4',
    'protein_id': 'NP_203524.1',
    'protein_seq': Seq('MTEYKLVVVGAGGVGKSALTIQLIQNHFVDEYDPTIEDSYRKQVVIDGETCLLD...IIM'),
    'cds_seq': Seq('atgactgaatataaacttgtggtagttggagctggtggcgtaggcaagagtgcc...taa'),
    'cds_start': 190,
    'cds_end': 760}]],
 'KRIT1': [[{'transcript': 'NM_194454.3',
    'protein_id': 'NP_919436.1',
    'protein_seq': Seq('MGNPENIEDAYVAVIRPKNTASLNSREYRAKSYEILLHEVPIEGQKKKRKKVLL...RNS'),
    'cds_seq': Seq('atgggaaatccagaaaacatagaagatgcatatgttgctgttattcgtccaaag...tga'),
    'cds_start': 545,
    'cds_end': 2756}]],
 'KRT14': [[{'transcript': 'NM_000526.5',
    'protein_id': 'NP_000517.3',
    'protein_seq': Seq('MTTCSRQFTSSSSMKGSCGIGGGIGGGSSRISSVLAGGSCRAPSTYGGGLSVSS...TKN'),
    'cds_seq': Seq('atgaccacctgcagccgccagttcacctcctccagctccatgaagggctcctgc...tga'),
    'cds_start': 61,
    'cds_end': 1480}]],
 'KRT5': [[{'transcript': 'NM_000424.4',
    'protein_id': 'NP_000415.2',
    'protein_seq': Seq('MSRQSSVSFRSGGSRSFSTASAITPSVSRTSFTSVSRSGGGGGGGFGRVSLAGA...FKS'),
    'cds_seq': Seq('atgtctcgccagtcaagtgtgtccttccggagcgggggcagtcgtagcttcagc...taa'),
    'cds_start': 98,
    'cds_end': 1871}]],
 'L1CAM': [[{'transcript': 'NM_001278116.2',
    'protein_id': 'NP_001265045.1',
    'protein_seq': Seq('MVVALRYVWPLLLCSPCLLIQIPEEYEGHHVMEPPVITEQSPRRLVVFPTDDIS...ALE'),
    'cds_seq': Seq('atggtcgtggcgctgcggtacgtgtggcctctcctcctctgcagcccctgcctg...tag'),
    'cds_start': 217,
    'cds_end': 3991}]],
 'LAMA1': [[{'transcript': 'NM_005559.4',
    'protein_id': 'NP_005550.2',
    'protein_seq': Seq('MRGGVLLVLLLCVAAQCRQRGLFPAILNLASNAHISTNATCGEKGPEMFCKLVE...TES'),
    'cds_seq': Seq('atgcgcgggggcgtgctcctggtcttgctgctgtgtgtcgccgcgcagtgccgg...tga'),
    'cds_start': 77,
    'cds_end': 9305}]],
 'LAMA2': [[{'transcript': 'NM_000426.4',
    'protein_id': 'NP_000417.3',
    'protein_seq': Seq('MPGAAGVLLLLLLSGGLGGVQAQRPQQQRQSQAHQQRGLFPAVLNLASNALITT...PAN'),
    'cds_seq': Seq('atgccgggagccgccggggtcctcctccttctgctgctctccggaggcctcggg...taa'),
    'cds_start': 108,
    'cds_end': 9477}]],
 'LAMA3': [[{'transcript': 'NM_000227.6',
    'protein_id': 'NP_000218.3',
    'protein_seq': Seq('MPPAVRRSACSMGWLWIFGAALGQCLGYSSQQQRVPFLQPPGQSQLQASYVEFR...PDQ'),
    'cds_seq': Seq('atgcctccagcagtgaggcggtcagcctgcagcatgggatggctgtggatcttt...taa'),
    'cds_start': 25,
    'cds_end': 5200}],
  [{'transcript': 'NM_198129.4',
    'protein_id': 'NP_937762.2',
    'protein_seq': Seq('MAAAARPRGRALGPVLPPTPLLLLVLRVLPACGATARDPGAAAGLSLHPTYFNL...PDQ'),
    'cds_seq': Seq('atggcggcggccgcgcggcctcggggtcgggcactggggccagtactgccgccg...taa'),
    'cds_start': 231,
    'cds_end': 10233}]],
 'LAMB2': [[{'transcript': 'NM_002292.4',
    'protein_id': 'NP_002283.3',
    'protein_seq': Seq('MELTSRERGRGQPLPWELRLGLLLSVLAATLAQAPAPDVPGCSRGSCYPATGDL...TCQ'),
    'cds_seq': Seq('atggagctgacctcaagggaaagagggaggggacagcctctgccctgggaactt...tga'),
    'cds_start': 183,
    'cds_end': 5580}]],
 'LAMB3': [[{'transcript': 'NM_000228.3',
    'protein_id': 'NP_000219.2',
    'protein_seq': Seq('MRPFFLLCFALPGLLHAQQACSRGACYPPVGDLLVGRTRFLRASSTCGLTKPET...TCK'),
    'cds_seq': Seq('atgagaccattcttcctcttgtgttttgccctgcctggcctcctgcatgcccaa...tga'),
    'cds_start': 94,
    'cds_end': 3613}]],
 'LAMC2': [[{'transcript': 'NM_005562.3',
    'protein_id': 'NP_005553.2',
    'protein_seq': Seq('MPALWLGCCLCFSLLLPAARATSRREVCDCNGKSRQCIFDRELHRQTGNGFRCL...EQQ'),
    'cds_seq': Seq('atgcctgcgctctggctgggctgctgcctctgcttctcgctcctcctgcccgca...tga'),
    'cds_start': 89,
    'cds_end': 3671}]],
 'LAMC3': [[{'transcript': 'NM_006059.4',
    'protein_id': 'NP_006050.3',
    'protein_seq': Seq('MAAAALLLGLALLAPRAAGAGMGACYDGAGRPQRCLPVFENAAFGRLAQASHTC...SWQ'),
    'cds_seq': Seq('atggcggcggctgcgcttctgctggggctggcgctgctggcaccgcgggcggcc...tga'),
    'cds_start': 41,
    'cds_end': 4769}]],
 'LAMP2': [[{'transcript': 'NM_002294.3',
    'protein_id': 'NP_002285.1',
    'protein_seq': Seq('MVCFRLFPVPGSGLVLVCLVLGAVRSYALELNLTDSENATCLYAKWQMNFTVRY...EQF'),
    'cds_seq': Seq('atggtgtgcttccgcctcttcccggttccgggctcagggctcgttctggtctgc...tag'),
    'cds_start': 127,
    'cds_end': 1360}]],
 'LCA5': [[{'transcript': 'NM_001122769.3',
    'protein_id': 'NP_001116241.1',
    'protein_seq': Seq('MGERAGSPGTDQERKAGKHHYSYLSDFETPQSSGRSSLVSSSPASVRRKNPKRQ...ALR'),
    'cds_seq': Seq('atgggggaaagagcaggaagtccaggtactgatcaagaaagaaaggcaggcaaa...tga'),
    'cds_start': 457,
    'cds_end': 2551}]],
 'LDLR': [[{'transcript': 'NM_000527.4',
    'protein_id': 'NP_000518.1',
    'protein_seq': Seq('MGPWGWKLRWTVALLLAAAGTAVGDRCERNEFQCQDGKCISYKWVCDGSAECQD...DVA'),
    'cds_seq': Seq('atggggccctggggctggaaattgcgctggaccgtcgccttgctcctcgccgcg...tga'),
    'cds_start': 187,
    'cds_end': 2770}],
  [{'transcript': 'NM_000527.5',
    'protein_id': 'NP_000518.1',
    'protein_seq': Seq('MGPWGWKLRWTVALLLAAAGTAVGDRCERNEFQCQDGKCISYKWVCDGSAECQD...DVA'),
    'cds_seq': Seq('atggggccctggggctggaaattgcgctggaccgtcgccttgctcctcgccgcg...tga'),
    'cds_start': 86,
    'cds_end': 2669}],
  [{'transcript': 'NM_001195803.1',
    'protein_id': 'NP_001182732.1',
    'protein_seq': Seq('MGPWGWKLRWTVALLLAAAGTAVGDRCERNEFQCQDGKCISYKWVCDGSAECQD...DVA'),
    'cds_seq': Seq('atggggccctggggctggaaattgcgctggaccgtcgccttgctcctcgccgcg...tga'),
    'cds_start': 187,
    'cds_end': 2236}]],
 'LIFR': [[{'transcript': 'NM_001127671.2',
    'protein_id': 'NP_001121143.1',
    'protein_seq': Seq('MMDIYVCLKRPSWMVDNKRMRTASNFQWLLSTFILLYLMNQVNSQKKGAPHDLK...PND'),
    'cds_seq': Seq('atgatggatatttacgtatgtttgaaacgaccatcctggatggtggacaataaa...taa'),
    'cds_start': 332,
    'cds_end': 3626}]],
 'LIPA': [[{'transcript': 'NM_000235.4',
    'protein_id': 'NP_000226.2',
    'protein_seq': Seq('MKMRFLGLVVCLVLWTLHSEGSGGKLTAVDPETNMNVSEIISYWGFPSEEYLVE...KYQ'),
    'cds_seq': Seq('atgaaaatgcggttcttggggttggtggtctgtttggttctctggaccctgcat...tga'),
    'cds_start': 40,
    'cds_end': 1240}]],
 'LMNA': [[{'transcript': 'NM_170707.4',
    'protein_id': 'NP_733821.1',
    'protein_seq': Seq('METPSQRRATRSGAQASSTPLSPTRITRLQEKEDLQELNDRLAVYIDRVRSLET...SIM'),
    'cds_seq': Seq('atggagaccccgtcccagcggcgcgccacccgcagcggggcgcaggccagctcc...taa'),
    'cds_start': 208,
    'cds_end': 2203}]],
 'LMX1B': [[{'transcript': 'NM_001174147.2',
    'protein_id': 'NP_001167618.1',
    'protein_seq': Seq('MDIATGPESLERCFPRGQTDCAKMLDGIKMEEHALRPGPATLGVLLGSDCPHPA...FAS'),
    'cds_seq': Seq('atggatatagcaacaggtcccgagtcgctggagaggtgcttccctcgcgggcag...tga'),
    'cds_start': 522,
    'cds_end': 1731}]],
 'LOXHD1': [[{'transcript': 'NM_001384474.1',
    'protein_id': 'NP_001371403.1',
    'protein_seq': Seq('MMPQKKRRRKKDIDFLALYEAELLNYASEDDEGELEHEYYKARVYEVVTATGDV...PSV'),
    'cds_seq': Seq('atgatgccccagaagaaaaggcggaggaagaaggacatcgacttcctggccctg...tga'),
    'cds_start': 187,
    'cds_end': 7009}]],
 'LPL': [[{'transcript': 'NM_000237.3',
    'protein_id': 'NP_000228.1',
    'protein_seq': Seq('MESKALLVLTLAVWLQSLTASRGGVAAADQRRDFIDIESKFALRTPEDTAEDTC...KSG'),
    'cds_seq': Seq('atggagagcaaagccctgctcgtgctgactctggccgtgtggctccagagtctg...tga'),
    'cds_start': 188,
    'cds_end': 1616}]],
 'LRBA': [[{'transcript': 'NM_001364905.1',
    'protein_id': 'NP_001351834.1',
    'protein_seq': Seq('MASEDNRVPSPPPTGDDGGGGGREETPTEGGALSLKPGLPIRGIRMKFAVLTGL...TRY'),
    'cds_seq': Seq('atggctagcgaagacaatcgtgtcccttccccgccaccaacaggtgatgacggg...tga'),
    'cds_start': 302,
    'cds_end': 8861}]],
 'LRP2': [[{'transcript': 'NM_004525.3',
    'protein_id': 'NP_004516.2',
    'protein_seq': Seq('MDRGPAAVACTLLLALVACLAPASGQECDSAHFRCGSGHCIPADWRCDGTKDCS...SEV'),
    'cds_seq': Seq('atggatcgcgggccggcagcagtggcgtgcacgctgctcctggctctcgtcgcc...tag'),
    'cds_start': 135,
    'cds_end': 14103}]],
 'LRP5': [[{'transcript': 'NM_002335.4',
    'protein_id': 'NP_002326.2',
    'protein_seq': Seq('MEAAPPGPPWPLLLLLLLLLALCGCPAPAAASPLLLFANRRDVRLVDAGGVKLE...DSS'),
    'cds_seq': Seq('atggaggcagcgccgcccgggccgccgtggccgctgctgctgctgctgctgctg...tga'),
    'cds_start': 124,
    'cds_end': 4972}]],
 'LRPPRC': [[{'transcript': 'NM_133259.4',
    'protein_id': 'NP_573566.2',
    'protein_seq': Seq('MAALLRSARWLLRAGAAPRLPLSLRLLPGGPGRLHAASYLPAARAGPVAGGLLS...NSS'),
    'cds_seq': Seq('atggcagccctgctgagatccgcgcgttggttgctgcgtgccggggcggccccg...tga'),
    'cds_start': 42,
    'cds_end': 4227}]],
 'LRSAM1': [[{'transcript': 'NM_001005373.4',
    'protein_id': 'NP_001005373.1',
    'protein_seq': Seq('MPLFFRKRKPSEEARKRLEYQMCLAKEAGADDILDISKCELSEIPFGAFATCKV...HSS'),
    'cds_seq': Seq('atgccgctcttcttccggaagcggaaacccagtgaggaggctcggaaacgcctg...tga'),
    'cds_start': 348,
    'cds_end': 2520}]],
 'LYST': [[{'transcript': 'NM_000081.4',
    'protein_id': 'NP_000072.2',
    'protein_seq': Seq('MSTDSNSLAREFLTDVNRLCNAVVQRVEAREEEEEETHMATLGQYLVHGRGFLL...AAG'),
    'cds_seq': Seq('atgagcaccgacagtaactcactggcacgtgaatttctgaccgatgtcaaccgg...tga'),
    'cds_start': 161,
    'cds_end': 11567}]],
 'LZTR1': [[{'transcript': 'NM_006767.4',
    'protein_id': 'NP_006758.2',
    'protein_seq': Seq('MAGPGSTGGQIGAAALAGGARSKVAPSVDFDHSCSDSVEYLTLNFGPFETVHRW...ADI'),
    'cds_seq': Seq('atggctggaccgggcagcacgggggggcagatcggggctgcggccctggcaggc...tga'),
    'cds_start': 75,
    'cds_end': 2598}]],
 'MAN2B1': [[{'transcript': 'NM_000528.4',
    'protein_id': 'NP_000519.2',
    'protein_seq': Seq('MGAYARASGVCARGCLDSAGPWTMSRALRPPLPPLCFFLLLLAAAGARAGGYET...VDG'),
    'cds_seq': Seq('atgggcgcctacgcgcgggcttcgggggtctgcgctcgcggctgcctggactca...tag'),
    'cds_start': 41,
    'cds_end': 3077}]],
 'MANBA': [[{'transcript': 'NM_005908.4',
    'protein_id': 'NP_005899.3',
    'protein_seq': Seq('MRLHLLLLLALCGAGTTAAELSYSLRGNWSICNGNGSLELPGAVPGCVHSALFQ...DIY'),
    'cds_seq': Seq('atgcgcctccacctgctcctgctgctcgcgctgtgcggtgcaggcaccaccgcc...tga'),
    'cds_start': 74,
    'cds_end': 2714}]],
 'MBD4': [[{'transcript': 'NM_001276270.2',
    'protein_id': 'NP_001263199.1',
    'protein_seq': Seq('MGTTGLESLSLGDRGAAPTVTSSERLVPDPPNDLRKEDVAMELERVGEDEEQMM...SLS'),
    'cds_seq': Seq('atgggcacgactgggctggagagtctgagtctgggggaccgcggagctgccccc...taa'),
    'cds_start': 115,
    'cds_end': 1840}]],
 'MBD5': [[{'transcript': 'NM_001378120.1',
    'protein_id': 'NP_001365049.1',
    'protein_seq': Seq('MNGGKECDGGDKEGGLPAIQVPVGWQRRVDQNGVLYVSPSGSLLSCLEQVKTYL...ISR'),
    'cds_seq': Seq('atgaatggaggcaaagagtgtgacggaggggacaaggaaggaggtcttccagct...taa'),
    'cds_start': 1518,
    'cds_end': 6702}]],
 'MCCC1': [[{'transcript': 'NM_020166.5',
    'protein_id': 'NP_064551.3',
    'protein_seq': Seq('MAAASAVSVLLVAAERNRWHRLPSLLLPPRTWVWRQRTMKYTTATGRNITKVLI...ESE'),
    'cds_seq': Seq('atggcggcggcctctgcggtgtcggtgctgctggtggcggcggagaggaaccgg...taa'),
    'cds_start': 56,
    'cds_end': 2234}]],
 'MCCC2': [[{'transcript': 'NM_022132.5',
    'protein_id': 'NP_071415.1',
    'protein_seq': Seq('MWAVLRLALRPCARASPAGPRAYHGDSVASLGTQPDLGSALYQENYKQMKALVN...FRM'),
    'cds_seq': Seq('atgtgggccgtcctgaggttagccctgcggccgtgtgcccgcgcctctcccgcc...taa'),
    'cds_start': 86,
    'cds_end': 1778}]],
 'MCOLN1': [[{'transcript': 'NM_020533.3',
    'protein_id': 'NP_065394.1',
    'protein_seq': Seq('MTAPAGPRGSETERLLTPNPGYGTQAGPSPAPPTPPEEEDLRRRLKYFFMSPCD...LVN'),
    'cds_seq': Seq('atgacagccccggcgggtccgcgcggctcagagaccgagcggcttctgaccccc...tga'),
    'cds_start': 127,
    'cds_end': 1870}]],
 'MCPH1': [[{'transcript': 'NM_024596.5',
    'protein_id': 'NP_078872.3',
    'protein_seq': Seq('MAAPILKDVVAYVEVWSSNGTENYSKTFTTQLVDMGAKVSKTFNKQVTHVIFKD...LSQ'),
    'cds_seq': Seq('atggcggcccccatcctgaaagatgtagtggcctatgttgaagtgtggtcatcc...tga'),
    'cds_start': 41,
    'cds_end': 2549}]],
 'MECP2': [[{'transcript': 'NM_001110792.2',
    'protein_id': 'NP_001104262.1',
    'protein_seq': Seq('MAAAAAAAPSGGGGGGEEERLEEKSEDQDLQGLKDKPLKFKKVKKDKKEEKEGK...RVS'),
    'cds_seq': Seq('atggccgccgccgccgccgccgcgccgagcggaggaggaggaggaggcgaggag...tga'),
    'cds_start': 52,
    'cds_end': 1549}],
  [{'transcript': 'NM_004992.4',
    'protein_id': 'NP_004983.1',
    'protein_seq': Seq('MVAGMLGLREEKSEDQDLQGLKDKPLKFKKVKKDKKEEKEGKHEPVQPSAHHSA...RVS'),
    'cds_seq': Seq('atggtagctgggatgttagggctcagggaagaaaagtcagaagaccaggacctc...tga'),
    'cds_start': 212,
    'cds_end': 1673}]],
 'MED12': [[{'transcript': 'NM_005120.3',
    'protein_id': 'NP_005111.2',
    'protein_seq': Seq('MAAFGILSYEHRPLKRPRLGPPDVYPQDPKQKEDELTALNVKQGFNNQPAVSGD...GRY'),
    'cds_seq': Seq('atggcggccttcgggatcttgagctacgaacaccggcccctgaagcggccgcgg...tga'),
    'cds_start': 159,
    'cds_end': 6693}]],
 'MED13L': [[{'transcript': 'NM_015335.5',
    'protein_id': 'NP_056150.1',
    'protein_seq': Seq('MTAAANWVANGASLEDCHSNLFSLAELTGIKWRRYNFGGHGDCGPIISAPAQDD...NIL'),
    'cds_seq': Seq('atgactgcggcagcgaactgggtggcgaacggggcgagcctggaggattgtcac...taa'),
    'cds_start': 562,
    'cds_end': 7195}]],
 'MED17': [[{'transcript': 'NM_004268.5',
    'protein_id': 'NP_004259.3',
    'protein_seq': Seq('MSGVRAVRISIESACEKQVHEVGLDGTETYLPPLSMSQNLARLAQRIDFSQGSG...CLL'),
    'cds_seq': Seq('atgtccggggtgcgcgcagtgcggatcagcatcgaatcggcctgcgagaagcag...tga'),
    'cds_start': 232,
    'cds_end': 2188}]],
 'MEF2C': [[{'transcript': 'NM_002397.5',
    'protein_id': 'NP_002388.2',
    'protein_seq': Seq('MGRKKIQITRIMDERNRQVTFTKRKFGLMKKAYELSVLCDCEIALIIFNSTNKL...WAT'),
    'cds_seq': Seq('atggggagaaaaaagattcagattacgaggattatggatgaacgtaacagacag...tga'),
    'cds_start': 372,
    'cds_end': 1794}]],
 'MEN1': [[{'transcript': 'NM_001370259.2',
    'protein_id': 'NP_001357188.2',
    'protein_seq': Seq('MGLKAAQKTLFPLRSIDDVVRLFAAELGREEPDLVLLSLVLGFVEHFLAVNRVI...KGL'),
    'cds_seq': Seq('atggggctgaaggccgcccagaagacgctgttcccgctgcgctccatcgacgac...tga'),
    'cds_start': 61,
    'cds_end': 1894}]],
 'MERTK': [[{'transcript': 'NM_006343.3',
    'protein_id': 'NP_006334.2',
    'protein_seq': Seq('MGPAPLPLLLGLFLPALWRRAITEAREEAKPYPLFPGPFPGSLQTDHTPLLSLP...VLM'),
    'cds_seq': Seq('atggggccggccccgctgccgctgctgctgggcctcttcctccccgcgctctgg...tga'),
    'cds_start': 129,
    'cds_end': 3129}]],
 'MFN2': [[{'transcript': 'NM_014874.4',
    'protein_id': 'NP_055689.1',
    'protein_seq': Seq('MSLLFSRCNSIVTVKKNKRHMAEVNASPLKHFVTAKKKINGIFEQLGAYIQESA...PSR'),
    'cds_seq': Seq('atgtccctgctcttctctcgatgcaactctatcgtcacagtcaagaaaaataag...tag'),
    'cds_start': 190,
    'cds_end': 2464}]],
 'MFSD8': [[{'transcript': 'NM_001371596.2',
    'protein_id': 'NP_001358525.1',
    'protein_seq': Seq('MAGLRNESEQEPLLGDTPGSREWDILETEEHYKSRWRSIRILYLTMFLSSVGFS...IQE'),
    'cds_seq': Seq('atggccggcctgcggaacgaaagtgaacaggagccgctcttaggcgacacacct...taa'),
    'cds_start': 40,
    'cds_end': 1597}]],
 'MITF': [[{'transcript': 'NM_000248.4',
    'protein_id': 'NP_000239.1',
    'protein_seq': Seq('MLEMLEYNHYQVQTHLENPTKYHIQQAQRQQVKQYLSTTLANKHANQVLSLPCP...HTC'),
    'cds_seq': Seq('atgctggaaatgctagaatataatcactatcaggtgcagacccacctcgaaaac...tag'),
    'cds_start': 131,
    'cds_end': 1391}],
  [{'transcript': 'NM_001354604.2',
    'protein_id': 'NP_001341533.1',
    'protein_seq': Seq('MQSESGIVPDFEVGEEFHEEPKTYYELKSQPLKSSSSAEHPGASKPPISSSSMT...HTC'),
    'cds_seq': Seq('atgcagtccgaatcggggatcgtgccggatttcgaagtcggggaggagtttcat...tag'),
    'cds_start': 134,
    'cds_end': 1715}]],
 'MKKS': [[{'transcript': 'NM_170784.3',
    'protein_id': 'NP_740754.1',
    'protein_seq': Seq('MSRLEAKKPSLCKSEPLTTERVRTTLSVLKRIVTSCYGPSGRLKQLHNGFGGYV...DKN'),
    'cds_seq': Seq('atgtctcgtttggaagctaagaagccatcattgtgtaagagtgaaccactgaca...taa'),
    'cds_start': 763,
    'cds_end': 2476}]],
 'MKS1': [[{'transcript': 'NM_017777.4',
    'protein_id': 'NP_060247.2',
    'protein_seq': Seq('MAETVWSTDTGEAVYRSRDPVRNLRLRVHLQRITSSNFLHYQPAAELGKDLIDL...LVS'),
    'cds_seq': Seq('atggcggagaccgtctggagcactgacaccggggaggcagtgtatcgctcccgg...tag'),
    'cds_start': 25,
    'cds_end': 1705}]],
 'MLC1': [[{'transcript': 'NM_001376473.1',
    'protein_id': 'NP_001363402.1',
    'protein_seq': Seq('MTQEPFREELAYDRMPTLERGRQDPASYAPDAKPSDLQLSKRLPPCFSHKTWVF...MAQ'),
    'cds_seq': Seq('atgacccaggagccattcagagaggagctggcctatgaccggatgcccacgctg...tga'),
    'cds_start': 392,
    'cds_end': 1526}],
  [{'transcript': 'NM_015166.4',
    'protein_id': 'NP_055981.1',
    'protein_seq': Seq('MTQEPFREELAYDRMPTLERGRQDPASYAPDAKPSDLQLSKRLPPCFSHKTWVF...MAQ'),
    'cds_seq': Seq('atgacccaggagccattcagagaggagctggcctatgaccggatgcccacgctg...tga'),
    'cds_start': 131,
    'cds_end': 1265}]],
 'MLH1': [[{'transcript': 'NM_000249.4',
    'protein_id': 'NP_000240.1',
    'protein_seq': Seq('MSFVAGVIRRLDETVVNRIAAGEVIQRPANAIKEMIENCLDAKSTSIQVIVKEG...ERC'),
    'cds_seq': Seq('atgtcgttcgtggcaggggttattcggcggctggacgagacagtggtgaaccgc...taa'),
    'cds_start': 30,
    'cds_end': 2301}]],
 'MMAA': [[{'transcript': 'NM_172250.3',
    'protein_id': 'NP_758454.1',
    'protein_seq': Seq('MPMLLPHPHQHFLKGLLRAPFRCYHFIFHSSTHLGSGIPCAQPFNSLGLHCTKW...SRD'),
    'cds_seq': Seq('atgcccatgctgctaccacatcctcaccagcatttcctaaaaggccttttaaga...taa'),
    'cds_start': 88,
    'cds_end': 1345}]],
 'MMAB': [[{'transcript': 'NM_052845.4',
    'protein_id': 'NP_443077.1',
    'protein_seq': Seq('MAVCGLGSRLGLGSRLGLRGCFGAARLLYPRFQSRGPQGVEDGDRPQPSSKTPR...EGL'),
    'cds_seq': Seq('atggctgtgtgcggcctggggagccgtcttggcctggggagccgtcttggcctg...tga'),
    'cds_start': 24,
    'cds_end': 777}]],
 'MMACHC': [[{'transcript': 'NM_015506.3',
    'protein_id': 'NP_056321.2',
    'protein_seq': Seq('MEPKVAELKQKIEDTLCPFGFEVYPFQVAWYNELLPPAFHLPLPGPTLAFLVLS...PGP'),
    'cds_seq': Seq('atggagccgaaagtcgcagagctgaagcagaagatcgaggacacgctatgtcct...tga'),
    'cds_start': 33,
    'cds_end': 882}]],
 'MME': [[{'transcript': 'NM_007289.4',
    'protein_id': 'NP_009220.2',
    'protein_seq': Seq('MGKSESQMDITDINTPKPKKKQRWTPLEISLSVLVLLLTIIAVTMIALYATYDD...RVW'),
    'cds_seq': Seq('atgggcaagtcagaaagtcagatggatataactgatatcaacactccaaagcca...tga'),
    'cds_start': 158,
    'cds_end': 2411}]],
 'MMUT': [[{'transcript': 'NM_000255.4',
    'protein_id': 'NP_000246.2',
    'protein_seq': Seq('MLRAKNQLFLLSPHYLRQVKESSGSRLIQQRLLHQQQPLHPEWAALAKKQLKGK...QSV'),
    'cds_seq': Seq('atgttaagagctaagaatcagctttttttactttcacctcattacctgaggcag...taa'),
    'cds_start': 190,
    'cds_end': 2443}]],
 'MPDZ': [[{'transcript': 'NM_001378778.1',
    'protein_id': 'NP_001365707.1',
    'protein_seq': Seq('MLEAIDKNRALHAAERLQTKLRERGDVANEDKLSLLKSVLQSPLFSQILSLQTS...VLS'),
    'cds_seq': Seq('atgttggaagccattgacaaaaatcgggccctgcatgcagcagagcgcttgcaa...tga'),
    'cds_start': 350,
    'cds_end': 6563}]],
 'MPI': [[{'transcript': 'NM_002435.3',
    'protein_id': 'NP_002426.1',
    'protein_seq': Seq('MAAPRVFPLSCAVQQYAWGKMGSNSEVARLLASSDPLAQIAEDKPYAELWMGTH...CLL'),
    'cds_seq': Seq('atggccgctccgcgagtattcccactttcctgtgcggtgcagcagtatgcctgg...taa'),
    'cds_start': 32,
    'cds_end': 1304}]],
 'MPL': [[{'transcript': 'NM_005373.3',
    'protein_id': 'NP_005364.1',
    'protein_seq': Seq('MPSWALFMVTSCLLLAPQNLAQVSSQDVSLLASDSEPLKCFSRTFEDLTCFWDE...QQP'),
    'cds_seq': Seq('atgccctcctgggccctcttcatggtcacctcctgcctcctcctggcccctcaa...tga'),
    'cds_start': 31,
    'cds_end': 1939}]],
 'MPV17': [[{'transcript': 'NM_002437.5',
    'protein_id': 'NP_002428.1',
    'protein_seq': Seq('MALWRAYQRALAAHPWKVQVLTAGSLMGLGDIISQQLVERRGLQEHQRGRTLTM...HRL'),
    'cds_seq': Seq('atggcactctggcgggcataccagcgggccctggccgctcacccgtggaaagta...taa'),
    'cds_start': 51,
    'cds_end': 582}]],
 'MPZ': [[{'transcript': 'NM_000530.8',
    'protein_id': 'NP_000521.2',
    'protein_seq': Seq('MAPGAPSSSPSPILAVLLFSSLVLSPAQAIVVYTDREVHGAVGSRVTLHCSFWS...DKK'),
    'cds_seq': Seq('atggctcctggggctccctcatccagccccagccctatcctggctgtgctgctc...tag'),
    'cds_start': 63,
    'cds_end': 810}]],
 'MRE11': [[{'transcript': 'NM_005591.4',
    'protein_id': 'NP_005582.1',
    'protein_seq': Seq('MSTADALDDENTFKILVATDIHLGFMEKDAVRGNDTFVTLDEILRLAQENEVDF...NRR'),
    'cds_seq': Seq('atgagtactgcagatgcacttgatgatgaaaacacatttaaaatattagttgca...taa'),
    'cds_start': 159,
    'cds_end': 2286}]],
 'MSH2': [[{'transcript': 'NM_000251.3',
    'protein_id': 'NP_000242.1',
    'protein_seq': Seq('MAVQPKETLQLESAAEVGFVRFFQGMPEKPTTTVRLFDRGDFYTAHGEDALLAA...VTT'),
    'cds_seq': Seq('atggcggtgcagccgaaggagacgctgcagttggagagcgcggccgaggtcggc...tga'),
    'cds_start': 36,
    'cds_end': 2841}]],
 'MSH3': [[{'transcript': 'NM_002439.5',
    'protein_id': 'NP_002430.3',
    'protein_seq': Seq('MSRRKPASGGLAASSSAPARQAVLSRFFQSTGSLKSTSSSTGAADQVDPGAAAA...LLH'),
    'cds_seq': Seq('atgtctcgccggaagcctgcgtcgggcggcctcgctgcctccagctcagcccct...taa'),
    'cds_start': 76,
    'cds_end': 3490}]],
 'MSH6': [[{'transcript': 'NM_000179.3',
    'protein_id': 'NP_000170.1',
    'protein_seq': Seq('MSRQSTLYSFFPKSPALSDANKASARASREGGRAAAAPGASPSPGGDAAWSEAG...KEL'),
    'cds_seq': Seq('atgtcgcgacagagcaccctgtacagcttcttccccaagtctccggcgctgagt...tag'),
    'cds_start': 89,
    'cds_end': 4172}]],
 'MTHFR': [[{'transcript': 'NM_005957.5',
    'protein_id': 'NP_005948.3',
    'protein_seq': Seq('MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLREKMRRRLE...EAP'),
    'cds_seq': Seq('atggtgaacgaagccagaggaaacagcagcctcaacccctgcttggagggcagt...tga'),
    'cds_start': 90,
    'cds_end': 2061}]],
 'MTM1': [[{'transcript': 'NM_000252.3',
    'protein_id': 'NP_000243.1',
    'protein_seq': Seq('MASASTSKYNSHSLENESIKRTSRDGVNRDLTEAVPRLPGETLITDKEVIYICP...THF'),
    'cds_seq': Seq('atggcttctgcatcaacttctaaatataattcacactccttggagaatgagtct...tga'),
    'cds_start': 52,
    'cds_end': 1864}]],
 'MTOR': [[{'transcript': 'NM_004958.4',
    'protein_id': 'NP_004949.1',
    'protein_seq': Seq('MLGTGPAAATTAATTSSNVSVLQQFASGLKSRNEETRAKAAKELQHYVTMELRE...PFW'),
    'cds_seq': Seq('atgcttggaaccggacctgccgccgccaccaccgctgccaccacatctagcaat...taa'),
    'cds_start': 121,
    'cds_end': 7771}]],
 'MTR': [[{'transcript': 'NM_000254.3',
    'protein_id': 'NP_000245.2',
    'protein_seq': Seq('MSPALQDLSQPEGLKKTLRDEINAILQKRIMVLDGGMGTMIQREKLNEEHFRGQ...DTD'),
    'cds_seq': Seq('atgtcacccgcgctccaagacctgtcgcaacccgaaggtctgaagaaaaccctg...taa'),
    'cds_start': 412,
    'cds_end': 4210}]],
 'MTRR': [[{'transcript': 'NM_002454.3',
    'protein_id': 'NP_002445.2',
    'protein_seq': Seq('MRRFLLLYATQQGQAKAIAEEICEQAVVHGFSADLHCISESDKYDLKTETAPLV...IWS'),
    'cds_seq': Seq('atgaggaggtttctgttactatatgctacacagcagggacaggcaaaggccatc...taa'),
    'cds_start': 93,
    'cds_end': 2190}]],
 'MTTP': [[{'transcript': 'NM_001386140.1',
    'protein_id': 'NP_001373069.1',
    'protein_seq': Seq('MILLAVLFLCFISSYSASVKGHTTGLSLNNDRLYKLTYSTEVLLDRGKGKLQDS...GWF'),
    'cds_seq': Seq('atgattcttcttgctgtgctttttctctgcttcatttcctcatattcagcttct...tga'),
    'cds_start': 86,
    'cds_end': 2771}]],
 'MUTYH': [[{'transcript': 'NM_001048174.2',
    'protein_id': 'NP_001041639.1',
    'protein_seq': Seq('MRKPRAAVGSGHRKQAASQEGRQKHAKNNSQAKPSACDGLARQPEEVVLQASVS...AAQ'),
    'cds_seq': Seq('atgaggaagccacgagcagccgtgggaagtggtcacaggaagcaggcagccagc...tga'),
    'cds_start': 78,
    'cds_end': 1644}],
  [{'transcript': 'NM_001128425.2',
    'protein_id': 'NP_001121897.1',
    'protein_seq': Seq('MTPLVSRLSRLWAIMRKPRAAVGSGHRKQAASQEGRQKHAKNNSQAKPSACDAC...AAQ'),
    'cds_seq': Seq('atgacaccgctcgtctcccgcctgagtcgtctgtgggccatcatgaggaagcca...tga'),
    'cds_start': 186,
    'cds_end': 1836}]],
 'MVK': [[{'transcript': 'NM_000431.4',
    'protein_id': 'NP_000422.1',
    'protein_seq': Seq('MLSEVLLVSAPGKVILHGEHAVVHGKVALAVSLNLRTFLRLQPHSNGKVDLSLP...DGL'),
    'cds_seq': Seq('atgttgtcagaagtcctactggtgtctgctccggggaaagtcatccttcatgga...tga'),
    'cds_start': 94,
    'cds_end': 1285}]],
 'MYBPC3': [[{'transcript': 'NM_000256.3',
    'protein_id': 'NP_000247.2',
    'protein_seq': Seq('MPEPGKKPVSAFSKKPRSVEVAAGSPAVFEAETERAGVKVRWQRGGSDISASNK...VPQ'),
    'cds_seq': Seq('atgcctgagccggggaagaagccagtctcagcttttagcaagaagccacggtca...tga'),
    'cds_start': 55,
    'cds_end': 3880}]],
 'MYH11': [[{'transcript': 'NM_001040113.2',
    'protein_id': 'NP_001035202.1',
    'protein_seq': Seq('MAQKGQLSDDEKFLFVDKNFINSPVAQADWAAKRLVWVPSEKQGFEAASIKEEK...TSQ'),
    'cds_seq': Seq('atggcgcagaagggccaactcagtgacgatgagaagttcctctttgtggacaaa...tga'),
    'cds_start': 105,
    'cds_end': 5943}],
  [{'transcript': 'NM_002474.3',
    'protein_id': 'NP_002465.1',
    'protein_seq': Seq('MAQKGQLSDDEKFLFVDKNFINSPVAQADWAAKRLVWVPSEKQGFEAASIKEEK...ASE'),
    'cds_seq': Seq('atggcgcagaagggccaactcagtgacgatgagaagttcctctttgtggacaaa...taa'),
    'cds_start': 105,
    'cds_end': 6024}]],
 'MYH2': [[{'transcript': 'NM_017534.6',
    'protein_id': 'NP_060004.3',
    'protein_seq': Seq('MSSDSELAVFGEAAPFLRKSERERIEAQNRPFDAKTSVFVAEPKESFVKGTIQS...SEE'),
    'cds_seq': Seq('atgagttcagactcagaattggctgtttttggggaggctgctcctttcctccga...tga'),
    'cds_start': 86,
    'cds_end': 5912}]],
 'MYH3': [[{'transcript': 'NM_002470.4',
    'protein_id': 'NP_002461.2',
    'protein_seq': Seq('MSSDTEMEVFGIAAPFLRKSEKERIEAQNQPFDAKTYCFVVDSKEEYAKGKIKS...SEE'),
    'cds_seq': Seq('atgagtagtgacactgaaatggaagtgttcggcatagctgctcctttcctccgg...tga'),
    'cds_start': 88,
    'cds_end': 5911}]],
 'MYH7': [[{'transcript': 'NM_000257.4',
    'protein_id': 'NP_000248.2',
    'protein_seq': Seq('MGDSEMAVFGAAAPYLRKSEKERLEAQTRPFDLKKDVFVPDDKQEFVKAKIVSR...NEE'),
    'cds_seq': Seq('atgggagattcggagatggcagtctttggggctgccgccccctacctgcgcaag...tag'),
    'cds_start': 105,
    'cds_end': 5913}]],
 'MYO15A': [[{'transcript': 'NM_016239.4',
    'protein_id': 'NP_057323.3',
    'protein_seq': Seq('MAKEEDEEKKAKKGKKGKKAPEPEKPKRSLKGTSRLFMGFRDRTPKISKKGQFR...TLL'),
    'cds_seq': Seq('atggcgaaggaggaagatgaggagaagaaagccaagaaagggaagaaggggaag...tga'),
    'cds_start': 288,
    'cds_end': 10881}]],
 'MYO18B': [[{'transcript': 'NM_032608.7',
    'protein_id': 'NP_115997.5',
    'protein_seq': Seq('MAISSRLALWEQKIREEDKSPPPSSPPPLFSVIPGGFIKQLVRGTEKEAKEARQ...LQK'),
    'cds_seq': Seq('atggccatctcatcacgcctcgccctgtgggagcagaagattcgggaagaggac...tag'),
    'cds_start': 215,
    'cds_end': 7919}]],
 'MYO5B': [[{'transcript': 'NM_001080467.3',
    'protein_id': 'NP_001073936.1',
    'protein_seq': Seq('MSVGELYSQCTRVWIPDPDEVWRSAELTKDYKEGDKSLQLRLEDETILEYPIDV...NEV'),
    'cds_seq': Seq('atgtcggtgggcgagctctacagccagtgcacaagggtctggatccctgaccct...tga'),
    'cds_start': 354,
    'cds_end': 5901}]],
 'MYO6': [[{'transcript': 'NM_004999.4',
    'protein_id': 'NP_004990.3',
    'protein_seq': Seq('MEDGKPVWAPHPTDGFQMGNIVDIGPDSLTIEPLNQKGKTFLALINQVFPAEED...LLK'),
    'cds_seq': Seq('atggaggatggaaagcccgtttgggcgccacaccctacagatggatttcagatg...tag'),
    'cds_start': 232,
    'cds_end': 4090}]],
 'MYO7A': [[{'transcript': 'NM_000260.4',
    'protein_id': 'NP_000251.3',
    'protein_seq': Seq('MVILQQGDHVWMDLRLGQEFDVPIGAVVKLCDSGQVQVVDDEDNEHWISPQNAT...SGK'),
    'cds_seq': Seq('atggtgattcttcagcagggggaccatgtgtggatggacctgagattggggcag...tga'),
    'cds_start': 290,
    'cds_end': 6938}]],
 'MYT1L': [[{'transcript': 'NM_001303052.2',
    'protein_id': 'NP_001289981.1',
    'protein_seq': Seq('MEVDTEEKRHRTRSKGVRVPVEPAIQELFSCPTPGCDGSGHVSGKYARHRSVYG...IQV'),
    'cds_seq': Seq('atggaggtggacaccgaggagaagcggcatcgcacgcggtccaaaggggttcga...tga'),
    'cds_start': 829,
    'cds_end': 4390}]],
 'NAA15': [[{'transcript': 'NM_057175.5',
    'protein_id': 'NP_476516.1',
    'protein_seq': Seq('MPAVSLPPKENALFKRILRCYEHKQYRNGLKFCKQILSNPKFAEHGETLAMKGL...NEI'),
    'cds_seq': Seq('atgccggccgtgagcctcccgcccaaggagaatgcgctcttcaagcggatcttg...tga'),
    'cds_start': 273,
    'cds_end': 2874}]],
 'NAGLU': [[{'transcript': 'NM_000263.4',
    'protein_id': 'NP_000254.2',
    'protein_seq': Seq('MEAVAVAAAVGVLLLAGAGGAAGDEAREAAAVRALVARLLGPGPAADFSVSVER...GSW'),
    'cds_seq': Seq('atggaggcggtggcggtggccgcggcggtgggggtccttctcctggccggggcc...tga'),
    'cds_start': 32,
    'cds_end': 2264}]],
 'NAGS': [[{'transcript': 'NM_153006.3',
    'protein_id': 'NP_694551.1',
    'protein_seq': Seq('MATALMAVVLRAAAVAPRLRGRGGTGGARRLSCGARRRAARGTSPGRRLSTAWS...PGS'),
    'cds_seq': Seq('atggcgacggcgctgatggctgtggttctgcgggcagctgctgtagccccgagg...tga'),
    'cds_start': 42,
    'cds_end': 1647}]],
 'NALCN': [[{'transcript': 'NM_052867.4',
    'protein_id': 'NP_443099.1',
    'protein_seq': Seq('MLKRKQSSRVEAQPVTDFGPDESLSDNADILWINKPWVHSLLRICAIISVISVC...LDI'),
    'cds_seq': Seq('atgctcaaaaggaagcagagttccagggtggaagcccagccagtcactgacttt...tag'),
    'cds_start': 235,
    'cds_end': 5452}]],
 'NBAS': [[{'transcript': 'NM_015909.4',
    'protein_id': 'NP_056993.2',
    'protein_seq': Seq('MAAPESGPALSPGTAEGEEETILYDLLVNTEWPPETEVQPRGNQKHGASFIITK...HWV'),
    'cds_seq': Seq('atggcggcccccgagtcagggccggctttgagtccaggcactgcagagggtgag...tga'),
    'cds_start': 30,
    'cds_end': 7146}]],
 'NBEA': [[{'transcript': 'NM_001385012.1',
    'protein_id': 'NP_001371941.1',
    'protein_seq': Seq('MASEKPGPGPGLEPQPVGLIAVGAAGGGGGGSGGGGTGGSGMGELRGASGSGSV...NRY'),
    'cds_seq': Seq('atggctagcgagaagccgggcccgggcccggggctcgagcctcagcccgtgggg...tga'),
    'cds_start': 551,
    'cds_end': 9455}]],
 'NBN': [[{'transcript': 'NM_002485.5',
    'protein_id': 'NP_002476.2',
    'protein_seq': Seq('MWKLLPAAGPAGGEPYRLLTGVEYVVGRKNCAILIENDQSISRNHAVLTANFSV...RRR'),
    'cds_seq': Seq('atgtggaaactgctgcccgccgcgggcccggcaggaggagaaccatacagactt...taa'),
    'cds_start': 106,
    'cds_end': 2371}]],
 'NDP': [[{'transcript': 'NM_000266.4',
    'protein_id': 'NP_000257.1',
    'protein_seq': Seq('MRKHVLAASFSMLSLLVIMGDTDSKTDSSFIMDSDPRRCMRHHYVDSISHPLYK...CNS'),
    'cds_seq': Seq('atgagaaaacatgtactagctgcatccttttctatgctctccctgctggtgata...tga'),
    'cds_start': 294,
    'cds_end': 696}]],
 'NDUFAF5': [[{'transcript': 'NM_024120.5',
    'protein_id': 'NP_077025.2',
    'protein_seq': Seq('MLRPAGLWRLCRRPWAARVPAENLGRREVTSGVSPRGSTSPRTLNIFDRDLKRK...KSQ'),
    'cds_seq': Seq('atgctgcggccggcagggctctggcgcttatgtcggcgaccttgggcggcgagg...taa'),
    'cds_start': 41,
    'cds_end': 1079}]],
 'NEB': [[{'transcript': 'NM_001164507.2',
    'protein_id': 'NP_001157979.2',
    'protein_seq': Seq('MADDEDYEEVVEYYTEEVVYEEVPGETITKIYETTTTRTSDYEQSETSKPALAQ...EAI'),
    'cds_seq': Seq('atggcagatgacgaagactatgaggaggtggtggagtactacacagaagaagtg...tag'),
    'cds_start': 192,
    'cds_end': 25770}],
  [{'transcript': 'NM_001164508.2',
    'protein_id': 'NP_001157980.2',
    'protein_seq': Seq('MADDEDYEEVVEYYTEEVVYEEVPGETITKIYETTTTRTSDYEQSETSKPALAQ...EAI'),
    'cds_seq': Seq('atggcagatgacgaagactatgaggaggtggtggagtactacacagaagaagtg...tag'),
    'cds_start': 192,
    'cds_end': 25770}]],
 'NEK1': [[{'transcript': 'NM_001199397.3',
    'protein_id': 'NP_001186326.1',
    'protein_seq': Seq('MEKYVRLQKIGEGSFGKAILVKSTEDGRQYVIKEINISRMSSKEREESRREVAV...NDE'),
    'cds_seq': Seq('atggagaagtatgttagactacagaagattggagaaggttcatttggaaaagcc...taa'),
    'cds_start': 534,
    'cds_end': 4395}]],
 'NEU1': [[{'transcript': 'NM_000434.4',
    'protein_id': 'NP_000425.1',
    'protein_seq': Seq('MTGERPSTALPDRRWGPRILGFWGGCRVWVFAAIFLLLSLAASWSKAENDFGLV...GTL'),
    'cds_seq': Seq('atgactggggagcgacccagcacggcgctcccggacagacgctgggggccgcgg...tga'),
    'cds_start': 45,
    'cds_end': 1293}]],
 'NEXMIF': [[{'transcript': 'NM_001008537.3',
    'protein_id': 'NP_001008537.1',
    'protein_seq': Seq('MDNQQDKAIVASANGENTLINGVKENDSEDQDVAMKSFAALEAAAPIQPTPVAQ...KDI'),
    'cds_seq': Seq('atggataaccaacaagataaggctattgttgcctcagccaacggagaaaacact...tga'),
    'cds_start': 617,
    'cds_end': 5168}]],
 'NF1': [[{'transcript': 'NM_001042492.3',
    'protein_id': 'NP_001035957.1',
    'protein_seq': Seq('MAAHRPVEWVQAVVSRFDEQLPIKTGQQNTHTKVSTEHNKECLINISKYKFSLV...KIV'),
    'cds_seq': Seq('atggccgcgcacaggccggtggaatgggtccaggccgtggtcagccgcttcgac...tga'),
    'cds_start': 333,
    'cds_end': 8853}]],
 'NF2': [[{'transcript': 'NM_000268.4',
    'protein_id': 'NP_000259.1',
    'protein_seq': Seq('MAGAIASRMSFSSLKRKQPKTFTVRIVTMDAEMEFNCEMKWKGKDLFDLVCRTL...EEL'),
    'cds_seq': Seq('atggccggggccatcgcttcccgcatgagcttcagctctctcaagaggaagcaa...tag'),
    'cds_start': 366,
    'cds_end': 2154}]],
 'NFIX': [[{'transcript': 'NM_001365902.3',
    'protein_id': 'NP_001352831.1',
    'protein_seq': Seq('MYSPYCLTQDEFHPFIEALLPHVRAFSYTWFNLQARKRKYFKKHEKRMSKDEER...WFL'),
    'cds_seq': Seq('atgtactccccgtactgcctcacccaggatgagttccacccgttcatcgaggca...tga'),
    'cds_start': 363,
    'cds_end': 1872}]],
 'NFKB1': [[{'transcript': 'NM_003998.4',
    'protein_id': 'NP_003989.2',
    'protein_seq': Seq('MAEDDPYLGRPEQMFHLDPSLTHTIFNPEVFQPQMALPTADGPYLQILEQPKQR...GKI'),
    'cds_seq': Seq('atggcagaagatgatccatatttgggaaggcctgaacaaatgtttcatttggat...tag'),
    'cds_start': 437,
    'cds_end': 3347}]],
 'NGLY1': [[{'transcript': 'NM_018297.4',
    'protein_id': 'NP_060767.2',
    'protein_seq': Seq('MAAAALGSSSGSASPAVAELCQNTPETFLEASKLLLTYADNILRNPNDEKYRSI...SDL'),
    'cds_seq': Seq('atggcggcggcggcattgggcagctcctcaggctcggcgtccccggccgtggct...tga'),
    'cds_start': 53,
    'cds_end': 2018}]],
 'NIPBL': [[{'transcript': 'NM_133433.4',
    'protein_id': 'NP_597677.2',
    'protein_seq': Seq('MNGDMPHVPITTLAGIASLTDLLNQLPLPSPLPATTTKSLLFNARIAEEVNCLL...TSS'),
    'cds_seq': Seq('atgaatggggatatgccccatgtccccattactactcttgcggggattgctagt...taa'),
    'cds_start': 489,
    'cds_end': 8904}]],
 'NKX2-1': [[{'transcript': 'NM_001079668.3',
    'protein_id': 'NP_001073136.1',
    'protein_seq': Seq('MWSGGSGKARGWEAAAGGRSSPGRLSRRRIMSMSPKHTTPFSVSDILSPLEESY...RTW'),
    'cds_seq': Seq('atgtggtccggaggcagtgggaaggcgcggggctgggaggccgcggcgggaggg...tga'),
    'cds_start': 103,
    'cds_end': 1309}]],
 'NKX2-5': [[{'transcript': 'NM_004387.4',
    'protein_id': 'NP_004378.1',
    'protein_seq': Seq('MFPSPALTPTPFSVKDILNLEQQQRSLAAAGELSARLEATLAPSSCMLAAFKPE...RAW'),
    'cds_seq': Seq('atgttccccagccctgctctcacgcccacgcccttctcagtcaaagacatccta...tag'),
    'cds_start': 123,
    'cds_end': 1098}]],
 'NLRP3': [[{'transcript': 'NM_001243133.2',
    'protein_id': 'NP_001230062.1',
    'protein_seq': Seq('MASTRCKLARYLEDLEDVDLKKFKMHLEDYPPQKGCIPLPRGQTEKADHVDLAT...PSW'),
    'cds_seq': Seq('atggcaagcacccgctgcaagctggccaggtacctggaggacctggaggatgtg...tag'),
    'cds_start': 769,
    'cds_end': 3874}]],
 'NMNAT1': [[{'transcript': 'NM_022787.4',
    'protein_id': 'NP_073624.2',
    'protein_seq': Seq('MENSEKTEVVLLACGSFNPITNMHLRLFELAKDYMNGTGRYTVVKGIISPVGDA...AKT'),
    'cds_seq': Seq('atggaaaattccgagaagactgaagtggttctccttgcttgtggttcattcaat...tag'),
    'cds_start': 97,
    'cds_end': 937}]],
 'NOTCH1': [[{'transcript': 'NM_017617.5',
    'protein_id': 'NP_060087.3',
    'protein_seq': Seq('MPPLLAPLLCLALLPALAARGPRCSQPGETCLNGGKCEAANGTEACVCGGAFVG...AFK'),
    'cds_seq': Seq('atgccgccgctcctggcgcccctgctctgcctggcgctgctgcccgcgctcgcc...taa'),
    'cds_start': 262,
    'cds_end': 7930}]],
 'NOTCH2': [[{'transcript': 'NM_024408.4',
    'protein_id': 'NP_077719.2',
    'protein_seq': Seq('MPALRPALLWALLALWLCCAAPAHALQCRDGYEPCVNEGMCVTYHNGTGYCKCP...VYA'),
    'cds_seq': Seq('atgcccgccctgcgccccgctctgctgtgggcgctgctggcgctctggctgtgc...tga'),
    'cds_start': 256,
    'cds_end': 7672}]],
 'NOTCH3': [[{'transcript': 'NM_000435.3',
    'protein_id': 'NP_000426.2',
    'protein_seq': Seq('MGPGARGRRRRRRPMSPPPPPPPVRALPLLLLLAGPGAAAPPCLDGSPCANGGR...VLA'),
    'cds_seq': Seq('atggggccgggggcccgtggccgccgccgccgccgtcgcccgatgtcgccgcca...tga'),
    'cds_start': 90,
    'cds_end': 7056}]],
 'NPC1': [[{'transcript': 'NM_000271.5',
    'protein_id': 'NP_000262.2',
    'protein_seq': Seq('MTARGLALGLLLLLLCPAQVFSQSCVWYGECGIAYGDKRYNCEYSGPPKPLPKD...LNF'),
    'cds_seq': Seq('atgaccgctcgcggcctggcccttggcctcctcctgctgctactgtgtccagcg...tag'),
    'cds_start': 163,
    'cds_end': 4000}]],
 'NPHP1': [[{'transcript': 'NM_001128178.3',
    'protein_id': 'NP_001121650.1',
    'protein_seq': Seq('MLARRQRDPLQALRRRNQELKQQVDSLLSESQLKEALEPNKRQHIYQRCIQLKQ...NAV'),
    'cds_seq': Seq('atgctggcgagacgacagcgagatcctctccaggccctgcggcgccgcaatcag...tga'),
    'cds_start': 45,
    'cds_end': 2079}]],
 'NPHP3': [[{'transcript': 'NM_153240.5',
    'protein_id': 'NP_694972.3',
    'protein_seq': Seq('MGTASSLVSPAGGEVIEDTYGAGGGEACEIPVEVKPKARLLRNSFRRGAGAAAG...GQR'),
    'cds_seq': Seq('atggggaccgcctcgtcgctcgtgagccccgcgggcggggaagtgatcgaggac...taa'),
    'cds_start': 54,
    'cds_end': 4047}]],
 'NPHP4': [[{'transcript': 'NM_015102.5',
    'protein_id': 'NP_055917.1',
    'protein_seq': Seq('MNDWHRIFTQNVLVPPHPQRARQPWKESTAFQCVLKWLDGPVIRQGVLEVLSEV...IYQ'),
    'cds_seq': Seq('atgaacgactggcacaggatcttcacccaaaacgtgcttgtccctccccaccca...tga'),
    'cds_start': 220,
    'cds_end': 4501}]],
 'NPHS1': [[{'transcript': 'NM_004646.4',
    'protein_id': 'NP_004637.1',
    'protein_seq': Seq('MALGTTLRASLLLLGLLTEGLAQLAIPASVPRGFWALPENLTVVEGASVELRCG...HLV'),
    'cds_seq': Seq('atggccctggggacgacgctcagggcttctctcctgctcctggggctgctgact...taa'),
    'cds_start': 667,
    'cds_end': 4393}]],
 'NPHS2': [[{'transcript': 'NM_014625.4',
    'protein_id': 'NP_055440.1',
    'protein_seq': Seq('MERRARSSSRESRGRGGRTPHKENKRAKAERSGGGRGRQEAGPEPSGSGRAGTP...PML'),
    'cds_seq': Seq('atggagaggagggcgcggagctcctccagggagtcccgcgggcgaggcggcagg...tag'),
    'cds_start': 84,
    'cds_end': 1236}]],
 'NPR2': [[{'transcript': 'NM_003995.4',
    'protein_id': 'NP_003986.2',
    'protein_seq': Seq('MALPSLLLLVAALAGGVRPPGARNLTLAVVLPEHNLSYAWAWPRVGPAVALAVE...GLL'),
    'cds_seq': Seq('atggcgctgccatcacttctgctgttggtggcagccctggcaggtggggtgcgt...taa'),
    'cds_start': 818,
    'cds_end': 3962}]],
 'NPRL3': [[{'transcript': 'NM_001077350.3',
    'protein_id': 'NP_001070818.1',
    'protein_seq': Seq('MRDNTSPISVILVSSGSRGNKLLFRYPFQRSQEHPASQTSKPRSRYAASNTGDH...LLP'),
    'cds_seq': Seq('atgcgggacaacaccagccccatcagcgtgattctggtgagctcggggagcagg...tga'),
    'cds_start': 99,
    'cds_end': 1809}]],
 'NR0B1': [[{'transcript': 'NM_000475.5',
    'protein_id': 'NP_000466.2',
    'protein_seq': Seq('MAGENHQWQGSILYNMLMSAKQTRAAPEAPETRLVDQCWGCSCGDEPGVGREGL...TKI'),
    'cds_seq': Seq('atggcgggcgagaaccaccagtggcagggcagcatcctctacaacatgcttatg...taa'),
    'cds_start': 27,
    'cds_end': 1440}]],
 'NR2E3': [[{'transcript': 'NM_014249.4',
    'protein_id': 'NP_055064.1',
    'protein_seq': Seq('METRPTALMSSTVAAAAPAAGAASRKESPGRWGLGEDPTGVSPSLQCRVCGDSS...FKN'),
    'cds_seq': Seq('atggagaccagaccaacagctctgatgagctccacagtggctgcagctgcgcct...tag'),
    'cds_start': 190,
    'cds_end': 1423}]],
 'NR2F1': [[{'transcript': 'NM_005654.6',
    'protein_id': 'NP_005645.1',
    'protein_seq': Seq('MAMVVSSWRDPQDDVAGGNPGGPNPAAQAARGGGGGAGEQQQQAGSGAPHTPQT...QCS'),
    'cds_seq': Seq('atggcaatggtagttagcagctggcgagatccgcaggacgacgtggccgggggc...tag'),
    'cds_start': 1802,
    'cds_end': 3074}]],
 'NR5A1': [[{'transcript': 'NM_004959.5',
    'protein_id': 'NP_004950.2',
    'protein_seq': Seq('MDYSYDEDLDELCPVCGDKVSGYHYGLLTCESCKGFFKRTVQNNKHYTCTESQS...KQT'),
    'cds_seq': Seq('atggactattcgtacgacgaggacctggacgagctgtgccccgtgtgcggggac...tga'),
    'cds_start': 166,
    'cds_end': 1552}]],
 'NSD1': [[{'transcript': 'NM_022455.5',
    'protein_id': 'NP_071900.2',
    'protein_seq': Seq('MDQTCELPRRNCLLPFSNPVNLDAPEDKDSPFGNGQSNFSEPLNGCTMQLSTVS...EQK'),
    'cds_seq': Seq('atggatcagacctgtgaactacccagaagaaattgtctgctgcccttttccaat...tag'),
    'cds_start': 197,
    'cds_end': 8288}]],
 'NTHL1': [[{'transcript': 'NM_002528.7',
    'protein_id': 'NP_002519.2',
    'protein_seq': Seq('MTALSARMLTRSRSLGPGAGPRGCREEPGPLRRREAAAEARKSHSPVKRPRKAQ...QGL'),
    'cds_seq': Seq('atgaccgccttgagcgcgaggatgctgacccggagccggagcctgggacccggg...tga'),
    'cds_start': 11,
    'cds_end': 926}]],
 'NTRK1': [[{'transcript': 'NM_002529.4',
    'protein_id': 'NP_002520.2',
    'protein_seq': Seq('MLRGGRRGQLGWHSWAAGPGSLLAWLILASAGAAPCPDACCPHGSSGLRCTRDG...VLG'),
    'cds_seq': Seq('atgctgcgaggcggacggcgcgggcagcttggctggcacagctgggctgcgggg...tag'),
    'cds_start': 70,
    'cds_end': 2461}]],
 'OAT': [[{'transcript': 'NM_000274.4',
    'protein_id': 'NP_000265.1',
    'protein_seq': Seq('MFSKLAHLQRFAVLSRGVHSSVASATSVATKKTVQGPPTSDDIFEREYKYGAHN...LSF'),
    'cds_seq': Seq('atgttttccaaactagcacatttgcagaggtttgctgtacttagtcgcggagtt...tga'),
    'cds_start': 80,
    'cds_end': 1400}]],
 'OCA2': [[{'transcript': 'NM_000275.3',
    'protein_id': 'NP_000266.2',
    'protein_seq': Seq('MHLEGRDGRRYPGAPAVELLQTSVPSGLAELVAGKRRLPRGAGGADPSHSCPRG...GWN'),
    'cds_seq': Seq('atgcatctggagggcagagacggcaggcggtaccccggcgcgccggcggtggag...taa'),
    'cds_start': 113,
    'cds_end': 2630}]],
 'OCRL': [[{'transcript': 'NM_000276.4',
    'protein_id': 'NP_000267.2',
    'protein_seq': Seq('MEPPLPVGAQPLATVEGMEMKGPLREPCALTLAQRNGQYELIIQLHEKEQHVQD...EED'),
    'cds_seq': Seq('atggagccgccgctcccggtcggagcccagccgcttgccactgtcgagggtatg...taa'),
    'cds_start': 181,
    'cds_end': 2887}]],
 'OFD1': [[{'transcript': 'NM_003611.3',
    'protein_id': 'NP_003602.1',
    'protein_seq': Seq('MMAQSNMFTVADVLSQDELRKKLYQTFKDRGILDTLKTQLRNQLIHELMHPVLS...DSW'),
    'cds_seq': Seq('atgatggcgcagtccaacatgtttaccgtggctgatgtgttgagtcaagatgaa...taa'),
    'cds_start': 324,
    'cds_end': 3363}]],
 'OPA1': [[{'transcript': 'NM_130837.3',
    'protein_id': 'NP_570850.2',
    'protein_seq': Seq('MWRLRRAAVACEVCQSLVKHSSGIKGSLPLQKLHLVSRSIYHSHHPTLKLQRPQ...QEK'),
    'cds_seq': Seq('atgtggcgactacgtcgggccgctgtggcctgtgaggtctgccagtctttagtg...taa'),
    'cds_start': 170,
    'cds_end': 3218}]],
 'OPHN1': [[{'transcript': 'NM_002547.3',
    'protein_id': 'NP_002538.1',
    'protein_seq': Seq('MGHPPLEFSDCYLDSPDFRERLKCYEQELERTNKFIKDVIKDGNALISAMRNYS...DES'),
    'cds_seq': Seq('atgggtcatcccccgctggagttcagcgactgctacctggacagccccgatttc...tga'),
    'cds_start': 332,
    'cds_end': 2741}]],
 'OTC': [[{'transcript': 'NM_000531.6',
    'protein_id': 'NP_000522.3',
    'protein_seq': Seq('MLFNLRILLNNAAFRNGHNFMVRNFRCGQPLQNKVQLKGRDLLTLKNFTGEEIK...PKF'),
    'cds_seq': Seq('atgctgtttaatctgaggatcctgttaaacaatgcagcttttagaaatggtcac...tga'),
    'cds_start': 93,
    'cds_end': 1158}]],
 'OTOF': [[{'transcript': 'NM_194248.3',
    'protein_id': 'NP_919224.1',
    'protein_seq': Seq('MALLIHLKTVSELRGRGDRIAKVTFRGQSFYSRVLENCEDVADFDETFRWPVAS...LGA'),
    'cds_seq': Seq('atggccttgctcatccacctcaagacagtctcggagctgcggggcaggggcgac...tga'),
    'cds_start': 185,
    'cds_end': 6179}],
  [{'transcript': 'NM_194323.3',
    'protein_id': 'NP_919304.1',
    'protein_seq': Seq('MIKTEKSYPERRLRGVLEELSCGCCRFLSLADKDQGHSSRTRLDRERLKSCMRE...LGA'),
    'cds_seq': Seq('atgatcaaaacggagaagtcctaccctgagcgtcgcctgcggggcgtcctggag...tga'),
    'cds_start': 308,
    'cds_end': 4001}]],
 'OTOG': [[{'transcript': 'NM_001292063.2',
    'protein_id': 'NP_001278992.1',
    'protein_seq': Seq('MGVLASALCWLLCVWLPWGEQAAESLRVQRLAAAPVLWGSAEPQPEPAGQPSSS...QWS'),
    'cds_seq': Seq('atgggagtcctggcgtctgcgctctgctggctgctttgtgtctggctgccctgg...tga'),
    'cds_start': 114,
    'cds_end': 8856}]],
 'OTOGL': [[{'transcript': 'NM_001378609.3',
    'protein_id': 'NP_001365538.2',
    'protein_seq': Seq('MNIVRKLNLMIPWSIFLLHVLLFSLQEYICASSILMGTSKNGFNENRQKRALLA...QWN'),
    'cds_seq': Seq('atgaacattgtaagaaaactcaatttaatgataccttggagtatattcttgctt...taa'),
    'cds_start': 88,
    'cds_end': 7150}]],
 'P3H1': [[{'transcript': 'NM_022356.4',
    'protein_id': 'NP_071751.3',
    'protein_seq': Seq('MAVRALKLLTTLLAVVAAASQAEVESEAGWGMVTPDLLFAEGTAAYARGDWPGV...DEL'),
    'cds_seq': Seq('atggcggtacgcgcgttgaagctgctgaccacactgctggctgtcgtggccgct...tga'),
    'cds_start': 57,
    'cds_end': 2268}]],
 'PAFAH1B1': [[{'transcript': 'NM_000430.4',
    'protein_id': 'NP_000421.1',
    'protein_seq': Seq('MVLSQRQRDELNRAIADYLRSNGYEEAYSVFKKEAELDVNEELDKKYAGLLEKK...ECR'),
    'cds_seq': Seq('atggtgctgtcccagagacaacgagatgaactaaatcgagctatagcagattat...tga'),
    'cds_start': 543,
    'cds_end': 1776}]],
 'PAH': [[{'transcript': 'NM_000277.3',
    'protein_id': 'NP_000268.1',
    'protein_seq': Seq('MSTAVLENPGLGRKLSDFGQETSYIEDNCNQNGAISLIFSLKEEVGALAKVLRL...KIK'),
    'cds_seq': Seq('atgtccactgcggtcctggaaaacccaggcttgggcaggaaactctctgacttt...taa'),
    'cds_start': 114,
    'cds_end': 1473}]],
 'PALB2': [[{'transcript': 'NM_024675.4',
    'protein_id': 'NP_078951.2',
    'protein_seq': Seq('MDEPPGKPLSCEEKEKLKEKLAFLKREYSKTLARLQRAQRAEKIKHSIKKTVEE...HYS'),
    'cds_seq': Seq('atggacgagcctcccgggaagcccctcagctgtgaggagaaggaaaagttaaag...taa'),
    'cds_start': 153,
    'cds_end': 3714}]],
 'PANK2': [[{'transcript': 'NM_001386393.1',
    'protein_id': 'NP_001373322.1',
    'protein_seq': Seq('MGGLLGRQRLLLRMGGGRLGAPMERHGRASATSVSSAGEQAAGDPEGRRQEPLR...KIP'),
    'cds_seq': Seq('ctggggggcttgctcgggcggcagcgactgctgctgcggatgggagggggccgg...tga'),
    'cds_start': 44,
    'cds_end': 1427}]],
 'PARN': [[{'transcript': 'NM_002582.4',
    'protein_id': 'NP_002573.1',
    'protein_seq': Seq('MEIIRSNFKSNLHKVYQAIEEADFFAIDGEFSGISDGPSVSALTNGFDTPEERY...DTW'),
    'cds_seq': Seq('atggagataatcaggagcaattttaagagtaatcttcacaaagtgtaccaggcc...taa'),
    'cds_start': 135,
    'cds_end': 2055}]],
 'PAX2': [[{'transcript': 'NM_000278.5',
    'protein_id': 'NP_000269.3',
    'protein_seq': Seq('MDMHCKADPFSAMHPGHGGVNQLGGVFVNGRPLPDVVRQRIVELAHQGVRPCDI...DRH'),
    'cds_seq': Seq('atggatatgcactgcaaagcagaccccttctccgcgatgcacccagggcacggg...tag'),
    'cds_start': 679,
    'cds_end': 1864}]],
 'PAX3': [[{'transcript': 'NM_181457.3',
    'protein_id': 'NP_852122.1',
    'protein_seq': Seq('MTTLAGAVPRMMRPGPGQNYPRSGFPLEVSTPLGQGRVNQLGGVFINGRPLPNH...WTF'),
    'cds_seq': Seq('atgaccacgctggccggcgctgtgcccaggatgatgcggccgggcccggggcag...tag'),
    'cds_start': 381,
    'cds_end': 1821}],
  [{'transcript': 'NM_181458.4',
    'protein_id': 'NP_852123.1',
    'protein_seq': Seq('MTTLAGAVPRMMRPGPGQNYPRSGFPLEVSTPLGQGRVNQLGGVFINGRPLPNH...DIA'),
    'cds_seq': Seq('atgaccacgctggccggcgctgtgcccaggatgatgcggccgggcccggggcag...taa'),
    'cds_start': 383,
    'cds_end': 1838}]],
 'PAX6': [[{'transcript': 'NM_000280.6',
    'protein_id': 'NP_000271.1',
    'protein_seq': Seq('MQNSHSGVNQLGGVFVNGRPLPDSTRQKIVELAHSGARPCDISRILQVSNGCVS...RLQ'),
    'cds_seq': Seq('atgcagaacagtcacagcggagtgaatcagctcggtggtgtctttgtcaacggg...taa'),
    'cds_start': 524,
    'cds_end': 1793}],
  [{'transcript': 'NM_001368894.2',
    'protein_id': 'NP_001355823.1',
    'protein_seq': Seq('MQNSHSGVNQLGGVFVNGRPLPDSTRQKIVELAHSGARPCDISRILQTHADAKV...RLQ'),
    'cds_seq': Seq('atgcagaacagtcacagcggagtgaatcagctcggtggtgtctttgtcaacggg...taa'),
    'cds_start': 524,
    'cds_end': 1835}]],
 'PC': [[{'transcript': 'NM_001040716.2',
    'protein_id': 'NP_001035806.1',
    'protein_seq': Seq('MLKFRTVHGGLRLLGIRRTSTAPAASPNVRRLEYKPIKKVMVANRGEIAIRVFR...EIE'),
    'cds_seq': Seq('atgctgaagttccgaacagtccatgggggcctgaggctcctgggaatccgccga...tga'),
    'cds_start': 289,
    'cds_end': 3826}]],
 'PCARE': [[{'transcript': 'NM_001029883.3',
    'protein_id': 'NP_001025054.1',
    'protein_seq': Seq('MGCTPSHSDLVNSVAKSGIQFLKKPKAIRPGCQGGSERGSIPLLVKNSTCYDAG...EVS'),
    'cds_seq': Seq('atggggtgtacaccttcacacagtgaccttgtaaacagcgttgcaaagagtggc...tga'),
    'cds_start': 262,
    'cds_end': 4129}]],
 'PCCA': [[{'transcript': 'NM_000282.4',
    'protein_id': 'NP_000273.2',
    'protein_seq': Seq('MAGFWVGTAPLVAAGRRGRWPPQQLMLSAALRTLKHVLYYSRQCLMVSRNLGSV...ELE'),
    'cds_seq': Seq('atggcggggttctgggtcgggacagcaccgctggtcgctgccggacggcgtggg...tga'),
    'cds_start': 28,
    'cds_end': 2215}]],
 'PCCB': [[{'transcript': 'NM_000532.5',
    'protein_id': 'NP_000523.2',
    'protein_seq': Seq('MAAALRVAAVGARLSVLASGLRAAVRSLCSQATSVNERIENKRRTALLGGGQRR...IPL'),
    'cds_seq': Seq('atggcggcggcattacgggtggcggcggtcggggcaaggctcagcgttctggcg...taa'),
    'cds_start': 36,
    'cds_end': 1656}]],
 'PCDH15': [[{'transcript': 'NM_001384140.1',
    'protein_id': 'NP_001371069.1',
    'protein_seq': Seq('MFRQFYLWTCLASGIILGSLFEICLGQYDDDCKLARGGPPATIVAIDEESRNGT...TKL'),
    'cds_seq': Seq('atgtttcgacagttttatctctggacatgtttagcttcagggatcatcctgggc...tga'),
    'cds_start': 335,
    'cds_end': 5558}],
  [{'transcript': 'NM_033056.4',
    'protein_id': 'NP_149045.3',
    'protein_seq': Seq('MFRQFYLWTCLASGIILGSLFEICLGQYDDDCKLARGGPPATIVAIDEESRNGT...TSL'),
    'cds_seq': Seq('atgtttcgacagttttatctctggacatgtttagcttcagggatcatcctgggc...taa'),
    'cds_start': 335,
    'cds_end': 6203}]],
 'PCDH19': [[{'transcript': 'NM_001184880.2',
    'protein_id': 'NP_001171809.1',
    'protein_seq': Seq('MESLLLPVLLLLAILWTQAAALINLKYSVEEEQRAGTVIANVAKDAREAGFALD...IVL'),
    'cds_seq': Seq('atggagtcgctcctgctgccggtgctgctgctgctggccatactgtggacgcag...taa'),
    'cds_start': 1676,
    'cds_end': 5123}]],
 'PCNT': [[{'transcript': 'NM_006031.6',
    'protein_id': 'NP_006022.3',
    'protein_seq': Seq('MEVEQEQRRRKVEAGRTKLAHFRQRKTKGDSSHSEKKTAKRKGSAVDASVQEES...IKQ'),
    'cds_seq': Seq('atggaagttgagcaagagcagcggcgcagaaaggtggaggccgggaggacgaag...tga'),
    'cds_start': 73,
    'cds_end': 10084}]],
 'PDE6A': [[{'transcript': 'NM_000440.3',
    'protein_id': 'NP_000431.2',
    'protein_seq': Seq('MGEVTAEEVEKFLDSNIGFAKQYYNLHYRAKLISDLLGAKEAAVDFSNYHSPSS...CIQ'),
    'cds_seq': Seq('atgggcgaggtgacagcagaggaggtggagaagttcctggactcgaatattggc...taa'),
    'cds_start': 120,
    'cds_end': 2703}]],
 'PDE6B': [[{'transcript': 'NM_000283.4',
    'protein_id': 'NP_000274.3',
    'protein_seq': Seq('MSLSEEQARSFLDQNPDFARQYFGKKLSPENVAAACEDGCPPDCDSLRDLCQVE...CIL'),
    'cds_seq': Seq('atgagcctcagtgaggagcaggcccggagctttctggaccagaaccccgatttt...tga'),
    'cds_start': 54,
    'cds_end': 2619}]],
 'PDE6C': [[{'transcript': 'NM_006204.4',
    'protein_id': 'NP_006195.3',
    'protein_seq': Seq('MGEINQVAVEKYLEENPQFAKEYFDRKLRVEVLGEIFKNSQVPVQSSMSFSELT...LML'),
    'cds_seq': Seq('atgggtgagatcaaccaagttgccgtggagaaatacctggaggagaaccctcag...taa'),
    'cds_start': 189,
    'cds_end': 2766}]],
 'PDHA1': [[{'transcript': 'NM_000284.4',
    'protein_id': 'NP_000275.1',
    'protein_seq': Seq('MRKMLAAVSRVLSGASQKPASRVLVASRNFANDATFEIKKCDLHRLEEGPPVTT...SVS'),
    'cds_seq': Seq('atgaggaagatgctcgccgccgtctcccgcgtgctgtctggcgcttctcagaag...taa'),
    'cds_start': 111,
    'cds_end': 1284}]],
 'PEPD': [[{'transcript': 'NM_000285.4',
    'protein_id': 'NP_000276.2',
    'protein_seq': Seq('MAAATGPSFWLGNETLKVPLALFALNRQRLCERLRKNPAVQAGSIVVLQGGEET...GPK'),
    'cds_seq': Seq('atggcggcggccaccggaccctcgttttggctggggaatgaaaccctgaaggtg...tag'),
    'cds_start': 31,
    'cds_end': 1513}]],
 'PEX1': [[{'transcript': 'NM_000466.3',
    'protein_id': 'NP_000457.1',
    'protein_seq': Seq('MWGSDRLAGAGGGGAAVTVAFTNARDCFLHLPRRLVAQLHLLQNQAIEVVWSHQ...TLA'),
    'cds_seq': Seq('atgtggggcagcgatcgcctggcgggtgctgggggaggcggggcggcagtgact...taa'),
    'cds_start': 85,
    'cds_end': 3937}]],
 'PEX10': [[{'transcript': 'NM_002617.4',
    'protein_id': 'NP_002608.1',
    'protein_seq': Seq('MAPAAASPPEVIRAAQKDEYYRGGLRSAAGGALHSLAGARKWLEWRKEVELLSD...HYR'),
    'cds_seq': Seq('atggccccggccgccgccagccccccggaggtgatccgcgcggcgcagaaggac...tga'),
    'cds_start': 62,
    'cds_end': 1043}]],
 'PEX6': [[{'transcript': 'NM_000287.4',
    'protein_id': 'NP_000278.3',
    'protein_seq': Seq('MALAVLRVLEPFPTETPPLAVLLPPGGPWPAAELGLVLALRPAGESPAGPALLV...AAC'),
    'cds_seq': Seq('atggcgctggctgtcttgcgggtcctggagccctttccgaccgagacacccccg...tag'),
    'cds_start': 31,
    'cds_end': 2974}]],
 'PEX7': [[{'transcript': 'NM_000288.4',
    'protein_id': 'NP_000279.1',
    'protein_seq': Seq('MSAVCGGAARMLRTPGRHGYAAEFSPYLPGRLACATAQHYGIAGCGTLLILDPD...IPA'),
    'cds_seq': Seq('atgagtgcggtgtgcggtggagcggcgcggatgctgcggacgccgggacgccac...tga'),
    'cds_start': 74,
    'cds_end': 1046}]],
 'PFKM': [[{'transcript': 'NM_000289.6',
    'protein_id': 'NP_000280.1',
    'protein_seq': Seq('MTHEEHHAAKTLGIGKAIAVLTSGGDAQGMNAAVRAVVRVGIFTGARVFFVHEG...AAV'),
    'cds_seq': Seq('atgacccatgaagagcaccatgcagccaaaaccctggggattggcaaagccatt...taa'),
    'cds_start': 51,
    'cds_end': 2394}]],
 'PHEX': [[{'transcript': 'NM_000444.6',
    'protein_id': 'NP_000435.3',
    'protein_seq': Seq('MEAETGSSVETGKKANRGTRIALVVFVGGTLVLGTILFLVSQGLLSLQAKQEYC...RLW'),
    'cds_seq': Seq('atggaagcagaaacagggagcagcgtggagactggaaagaaggccaacagaggc...tag'),
    'cds_start': 681,
    'cds_end': 2931}]],
 'PHGDH': [[{'transcript': 'NM_006623.4',
    'protein_id': 'NP_006614.2',
    'protein_seq': Seq('MAFANLRKVLISDSLDPCCRKILQDGGLQVVEKQNLSKEELIAELQDCEGLIVR...FHF'),
    'cds_seq': Seq('atggcttttgcaaatctgcggaaagtgctcatcagtgacagcctggacccttgc...taa'),
    'cds_start': 89,
    'cds_end': 1691}]],
 'PHIP': [[{'transcript': 'NM_017934.7',
    'protein_id': 'NP_060404.4',
    'protein_seq': Seq('MSCERKGLSELRSELYFLIARFLEDGPCQQAAQVLIREVAEKELLPRRTDWTGK...IGW'),
    'cds_seq': Seq('atgtcttgtgagaggaaaggcctctcggagctgcgatcggagctctacttcctc...taa'),
    'cds_start': 186,
    'cds_end': 5652}]],
 'PHKA2': [[{'transcript': 'NM_000292.3',
    'protein_id': 'NP_000283.1',
    'protein_seq': Seq('MRSRSNSGVRLDGYARLVQQTILCYQNPVTGLLSASHEQKDAWVRDNIYSILAV...QMQ'),
    'cds_seq': Seq('atgcggagcaggagcaattccggggtccgcttggacgggtacgcgcggctggtg...tag'),
    'cds_start': 182,
    'cds_end': 3890}]],
 'PHKB': [[{'transcript': 'NM_000293.3',
    'protein_id': 'NP_000284.1',
    'protein_seq': Seq('MAGAAGLTAEVSWKVLERRARTKRSGSVYEPLKSINLPRPDNETLWDKLDHYYR...LIS'),
    'cds_seq': Seq('atggcgggggcggcgggactcacggcagaagtgagctggaaggtcttggagcga...tag'),
    'cds_start': 20,
    'cds_end': 3302}]],
 'PIEZO1': [[{'transcript': 'NM_001142864.4',
    'protein_id': 'NP_001136336.2',
    'protein_seq': Seq('MEPHVLGAVLYWLLLPCALLAACLLRFSGLSLVYLLFLLLLPWFPGPTRCGLQG...EKE'),
    'cds_seq': Seq('atggagccgcacgtgctcggcgcggtcctgtactggctgctgctgccctgcgcg...tag'),
    'cds_start': 256,
    'cds_end': 7822}]],
 'PIEZO2': [[{'transcript': 'NM_001378183.1',
    'protein_id': 'NP_001365112.1',
    'protein_seq': Seq('MASEVVCGLIFRLLLPICLAVACAFRYNGLSFVYLIYLLLIPLFSEPTKTTMQG...KTN'),
    'cds_seq': Seq('atggcctcagaagtggtgtgcgggctcatcttcaggctgctgctgcccatctgc...tga'),
    'cds_start': 981,
    'cds_end': 9579}]],
 'PIGN': [[{'transcript': 'NM_176787.5',
    'protein_id': 'NP_789744.1',
    'protein_seq': Seq('MLLFFTLGLLIHFVFFASIFDIYFTSPLVHGMTPQFTPLPPPARRLVLFVADGL...HFM'),
    'cds_seq': Seq('atgctgctgttctttactttgggattgcttatacattttgtgttcttcgcctcc...tga'),
    'cds_start': 448,
    'cds_end': 3244}]],
 'PIK3CA': [[{'transcript': 'NM_006218.4',
    'protein_id': 'NP_006209.2',
    'protein_seq': Seq('MPPRPSSGELWGIHLMPPRILVECLLPNGMIVTLECLREATLITIKHELFKEAR...ALN'),
    'cds_seq': Seq('atgcctccacgaccatcatcaggtgaactgtggggcatccacttgatgccccca...tga'),
    'cds_start': 323,
    'cds_end': 3530}]],
 'PKD1': [[{'transcript': 'NM_001009944.3',
    'protein_id': 'NP_001009944.3',
    'protein_seq': Seq('MPPAAPARLALALGLGLWLGALAGGPGRGCGPCEPPCLCGPAPGAACRVNCSGR...SST'),
    'cds_seq': Seq('atgccgcccgccgcgcccgcccgcctggcgctggccctgggcctgggcctgtgg...tag'),
    'cds_start': 209,
    'cds_end': 13121}]],
 'PKD2': [[{'transcript': 'NM_000297.4',
    'protein_id': 'NP_000288.1',
    'protein_seq': Seq('MVNSSRVQPQQPGDAKRPPAPRAPDPGRLMAGCAAVGASLAAPGGLCEQRGLEI...VHV'),
    'cds_seq': Seq('atggtgaactccagtcgcgtgcagcctcagcagcccggggacgccaagcggccg...tga'),
    'cds_start': 99,
    'cds_end': 3006}]],
 'PKHD1': [[{'transcript': 'NM_138694.4',
    'protein_id': 'NP_619639.3',
    'protein_seq': Seq('MTAWLISLMSIEVLLLAVRHLSLHIEPEEGSLAGGTWITVIFDGLELGVLYPNN...EQL'),
    'cds_seq': Seq('atgactgcctggctgatctctctgatgagtattgaagtactacttttggcagta...tga'),
    'cds_start': 264,
    'cds_end': 12489}]],
 'PKLR': [[{'transcript': 'NM_000298.6',
    'protein_id': 'NP_000289.1',
    'protein_seq': Seq('MSIQENISSLQLRSWVSKSQRDLAKSILIGAPGGPAGYLRRASVAQLTQELGTA...SIS'),
    'cds_seq': Seq('atgtcgatccaggagaacatatcatccctgcagcttcggtcatgggtctctaag...tga'),
    'cds_start': 43,
    'cds_end': 1768}]],
 'PKP2': [[{'transcript': 'NM_001005242.3',
    'protein_id': 'NP_001005242.2',
    'protein_seq': Seq('MAAPGAPAEYGYIRTVLGQQILGQLDSSSLALPSEAKLKLAGSSGRGGQTVKSL...LKD'),
    'cds_seq': Seq('atggcagcccccggcgccccagctgagtacggctacatccggaccgtcctgggc...tga'),
    'cds_start': 46,
    'cds_end': 2560}]],
 'PLA2G6': [[{'transcript': 'NM_003560.4',
    'protein_id': 'NP_003551.2',
    'protein_seq': Seq('MQFFGRLVNTFSGVTNLFSNPFRVKEVAVADYTSSDRVREEGQLILFQNTPNRT...LSP'),
    'cds_seq': Seq('atgcagttctttggccgcctggtcaataccttcagtggcgtcaccaacttgttc...tga'),
    'cds_start': 212,
    'cds_end': 2633}]],
 'PLEC': [[{'transcript': 'NM_201378.4',
    'protein_id': 'NP_958780.1',
    'protein_seq': Seq('MAGPLPDEQDFIQAYEEVREKYKDERDRVQKKTFTKWVNKHLIKAQRHISDLYE...AVA'),
    'cds_seq': Seq('atggccggcccgctgcccgacgagcaggacttcatccaggcctacgaggaggtg...tga'),
    'cds_start': 57,
    'cds_end': 13659}],
  [{'transcript': 'NM_201384.3',
    'protein_id': 'NP_958786.1',
    'protein_seq': Seq('MSQHQLRVPQPEGLGRKRTSSEDNLYLAVLRASEGKKDERDRVQKKTFTKWVNK...AVA'),
    'cds_seq': Seq('atgtctcagcaccagctccgcgtgccgcagcccgagggcctgggccgaaagaga...tga'),
    'cds_start': 136,
    'cds_end': 13780}]],
 'PLOD1': [[{'transcript': 'NM_000302.4',
    'protein_id': 'NP_000293.2',
    'protein_seq': Seq('MRPLLLLALLGWLLLAEAKGDAKPEDNLLVLTVATKETEGFRRFKRSAQFFNYK...VDP'),
    'cds_seq': Seq('atgcggcccctgctgctactggccctgctgggctggctgctgctggccgaagcg...taa'),
    'cds_start': 63,
    'cds_end': 2247}]],
 'PLP1': [[{'transcript': 'NM_000533.5',
    'protein_id': 'NP_000524.3',
    'protein_seq': Seq('MGLLECCARCLVGAPFASLVATGLCFFGVALFCGCGHEALTGTEKLIETYFSKN...TKF'),
    'cds_seq': Seq('atgggcttgttagagtgctgtgcaagatgtctggtaggggccccctttgcttcc...tga'),
    'cds_start': 156,
    'cds_end': 990}]],
 'PMM2': [[{'transcript': 'NM_000303.3',
    'protein_id': 'NP_000294.1',
    'protein_seq': Seq('MAAPGPALCLFDVDGTLTAPRQKITKEMDDFLQKLRQKIKIGVVGGSDFEKVQE...LFS'),
    'cds_seq': Seq('atggcagcgcctggcccagcgctctgcctcttcgacgtggatgggaccctcacc...taa'),
    'cds_start': 44,
    'cds_end': 785}]],
 'PMP22': [[{'transcript': 'NM_000304.4',
    'protein_id': 'NP_000295.1',
    'protein_seq': Seq('MLLLLLSIIVLHVAVLVLLFVSTIVSQWIVGNGHATDLWQNCSTSSSGNVHHCF...KRE'),
    'cds_seq': Seq('atgctcctcctgttgctgagtatcatcgtcctccacgtcgcggtgctggtgctg...tga'),
    'cds_start': 207,
    'cds_end': 690}]],
 'PMS2': [[{'transcript': 'NM_000535.7',
    'protein_id': 'NP_000526.2',
    'protein_seq': Seq('MERAESSSTEPAKAIKPIDRKSVHQICSGQVVLSLSTAVKELVENSLDAGATNI...SQN'),
    'cds_seq': Seq('atggagcgagctgagagctcgagtacagaacctgctaaggccatcaaacctatt...tga'),
    'cds_start': 30,
    'cds_end': 2619}]],
 'PNKP': [[{'transcript': 'NM_007254.4',
    'protein_id': 'NP_009185.2',
    'protein_seq': Seq('MGEVEAPGRLWLESPPGGAPPIFLPSDGQALVLGRGPLTQVTDRKCSRTQVELV...SEG'),
    'cds_seq': Seq('atgggcgaggtggaggccccgggccgcttgtggctcgagagcccccctggggga...tga'),
    'cds_start': 121,
    'cds_end': 1687}]],
 'PNPLA6': [[{'transcript': 'NM_001166114.2',
    'protein_id': 'NP_001159586.1',
    'protein_seq': Seq('MGTSSHGLATNSSGAKVAERDGFQDVLAPGEGSAGRICGAQPVPFVPQVLGVMI...TDA'),
    'cds_seq': Seq('atggggacatcgagtcacgggctggctacgaactcctcgggggcgaaggtggcg...tga'),
    'cds_start': 72,
    'cds_end': 4170}]],
 'PNPT1': [[{'transcript': 'NM_033109.5',
    'protein_id': 'NP_149100.2',
    'protein_seq': Seq('MAACRYCCSCLRLRPLSDGPFLLPRRDRALTQLQVRALWSSAGSRAVAVDLGNR...NSQ'),
    'cds_seq': Seq('atggcggcctgcaggtactgctgctcgtgcctccggctccggcccctgagcgat...tga'),
    'cds_start': 21,
    'cds_end': 2373}]],
 'POGZ': [[{'transcript': 'NM_015100.4',
    'protein_id': 'NP_055915.2',
    'protein_seq': Seq('MADTDLFMECEEEELEPWQKISDVIEDSVVEDYNSVDKTTTVSVSQQPVSAPVP...MEI'),
    'cds_seq': Seq('atggcggacaccgacctgttcatggaatgtgaggaggaggagttggagccatgg...tga'),
    'cds_start': 344,
    'cds_end': 4577}]],
 'POLE': [[{'transcript': 'NM_006231.4',
    'protein_id': 'NP_006222.2',
    'protein_seq': Seq('MSLRSGGRRRADPGADGEASRDDGATSSVSALKRLERSQWTDKMDLRFGFERLK...LGH'),
    'cds_seq': Seq('atgtctctgaggagcggcgggcggcggcgcgcggacccaggcgcggatggcgag...tag'),
    'cds_start': 27,
    'cds_end': 6888}]],
 'POLG': [[{'transcript': 'NM_002693.3',
    'protein_id': 'NP_002684.1',
    'protein_seq': Seq('MSRLLWRKVAGATVGPGPVPAPGRWVSSSVPASDPSDGQRRRQQQQQQQQQQQQ...PGP'),
    'cds_seq': Seq('atgagccgcctgctctggaggaaggtggccggcgccaccgtcgggccagggccg...tag'),
    'cds_start': 311,
    'cds_end': 4031}]],
 'POLR3A': [[{'transcript': 'NM_007055.4',
    'protein_id': 'NP_008986.2',
    'protein_seq': Seq('MVKEQFRETDVAKKISHICFGMKSPEEMRQQAHIQVVSKNLYSQDNQHAPLLYG...LVT'),
    'cds_seq': Seq('atggtgaaggagcagttccgggagacggatgtggccaagaaaataagccacatc...tag'),
    'cds_start': 108,
    'cds_end': 4281}]],
 'POLR3B': [[{'transcript': 'NM_018082.6',
    'protein_id': 'NP_060552.4',
    'protein_seq': Seq('MDVLAEEFGNLTPEQLAAPIPTVEEKWRLLPAFLKVKGLVKQHIDSFNYFINVE...YNE'),
    'cds_seq': Seq('atggacgtgctagcggaggagtttgggaacctgactccggagcagctggcggcg...tga'),
    'cds_start': 132,
    'cds_end': 3534}]],
 'POMGNT1': [[{'transcript': 'NM_017739.4',
    'protein_id': 'NP_060209.4',
    'protein_seq': Seq('MDDWKPSPLIKPFGARKKRSWYLTWKYKLTNQRALRRFCQTGAVLFLLVTVIVN...EQT'),
    'cds_seq': Seq('atggacgactggaagcccagccccctcatcaagccctttggggctcggaagaag...tga'),
    'cds_start': 149,
    'cds_end': 2132}]],
 'POMT1': [[{'transcript': 'NM_001077365.2',
    'protein_id': 'NP_001070833.1',
    'protein_seq': Seq('MWGFLKRPVVVTADINLSLVALTGMGLLSRLWRLTYPRAVVFDEVYYGQYISFY...RKH'),
    'cds_seq': Seq('atgtggggatttttgaagcgccctgtagtggtgacggctgacatcaacttgagc...tag'),
    'cds_start': 186,
    'cds_end': 2364}]],
 'POMT2': [[{'transcript': 'NM_013382.7',
    'protein_id': 'NP_037514.2',
    'protein_seq': Seq('MPPATGGGLAESELRPRRGRCGPQAARAAGRDVAAEAVARSPKRPAWGSRRFEA...WDF'),
    'cds_seq': Seq('atgccgccggccacgggcggaggcctggcagagtccgagctgcgtccccggagg...tga'),
    'cds_start': 202,
    'cds_end': 2455}]],
 'POR': [[{'transcript': 'NM_001395413.1',
    'protein_id': 'NP_001382342.1',
    'protein_seq': Seq('MGDSHVDTSSTVSEAVAEEVSLFSMTDMILFSLIVGLLTYWFLFRKKKEEVPEF...VWS'),
    'cds_seq': Seq('atgggagactcccacgtggacaccagctccaccgtgtccgaggcggtggccgaa...tag'),
    'cds_start': 38,
    'cds_end': 2072}]],
 'POT1': [[{'transcript': 'NM_015450.3',
    'protein_id': 'NP_056265.2',
    'protein_seq': Seq('MSLVPATNYIYTPLNQLKGGTIVNVYGVVKFFKPPYLSKGTDYCSVVTIVDQTN...DVI'),
    'cds_seq': Seq('atgtctttggttccagcaacaaattatatatatacacccctgaatcaacttaag...taa'),
    'cds_start': 443,
    'cds_end': 2348}]],
 'POU3F4': [[{'transcript': 'NM_000307.5',
    'protein_id': 'NP_000298.3',
    'protein_seq': Seq('MATAASNPYSILSSTSLVHADSAGMQQGSPFRNPQKLLQSDYLQGVPSNGHPLG...HDL'),
    'cds_seq': Seq('atggccacagctgcctcgaatccctacagcattctcagttccacctccctagtc...tga'),
    'cds_start': 35,
    'cds_end': 1121}]],
 'PPT1': [[{'transcript': 'NM_000310.4',
    'protein_id': 'NP_000301.1',
    'protein_seq': Seq('MASPGCLWLLAVALLPWTCASRALQHLDPPAPLPLVIWHGMGDSCCNPLSMGAI...FLG'),
    'cds_seq': Seq('atggcgtcgcccggctgcctgtggctcttggctgtggctctcctgccatggacc...tga'),
    'cds_start': 14,
    'cds_end': 935}]],
 'PRF1': [[{'transcript': 'NM_001083116.3',
    'protein_id': 'NP_001076585.1',
    'protein_seq': Seq('MAARLLLLGILLLLLPLPVPAPCHTAARSECKRSHKFVPGAWLAGEGVDVTSLR...AVW'),
    'cds_seq': Seq('atggcagcccgtctgctcctcctgggcatccttctcctgctgctgcccctgccc...tga'),
    'cds_start': 127,
    'cds_end': 1795}]],
 'PRKAR1A': [[{'transcript': 'NM_001276290.1',
    'protein_id': 'NP_001263219.1',
    'protein_seq': Seq('MESGSTAASEEARSLRECELYVQKHNIQALLKDSIVQLCTARPERPMAFLREYF...PLG'),
    'cds_seq': Seq('atggagtctggcagtaccgccgccagtgaggaggcacgcagccttcgagaatgt...taa'),
    'cds_start': 6,
    'cds_end': 1020}],
  [{'transcript': 'NM_002734.5',
    'protein_id': 'NP_002725.1',
    'protein_seq': Seq('MESGSTAASEEARSLRECELYVQKHNIQALLKDSIVQLCTARPERPMAFLREYF...LSV'),
    'cds_seq': Seq('atggagtctggcagtaccgccgccagtgaggaggcacgcagccttcgagaatgt...tga'),
    'cds_start': 125,
    'cds_end': 1271}]],
 'PROC': [[{'transcript': 'NM_000312.4',
    'protein_id': 'NP_000303.1',
    'protein_seq': Seq('MWQLTSLLLFVATWGISGTPAPLDSVFSSSERAHQVLRIRKRANSFLEELRHSS...WAP'),
    'cds_seq': Seq('atgtggcagctcacaagcctcctgctgttcgtggccacctggggaatttccggc...tag'),
    'cds_start': 87,
    'cds_end': 1473}]],
 'PROM1': [[{'transcript': 'NM_006017.3',
    'protein_id': 'NP_006008.1',
    'protein_seq': Seq('MALVLGSLLLLGLCGNSFSGGQPSSTDAPKAWNYELPATNYETQDSHKAGPIGI...SQH'),
    'cds_seq': Seq('atggccctcgtactcggctccctgttgctgctggggctgtgcgggaactccttt...tga'),
    'cds_start': 258,
    'cds_end': 2856}]],
 'PROP1': [[{'transcript': 'NM_006261.5',
    'protein_id': 'NP_006252.4',
    'protein_seq': Seq('MEAERRRQAEKPKKGRVGSNLLPERHPATGTPTTTVDSSAPPCRRLPGAGGGRS...SWN'),
    'cds_seq': Seq('atggaagcagaaaggaggcgccaggctgagaagccaaagaaggggcgagtcggc...tga'),
    'cds_start': 309,
    'cds_end': 990}]],
 'PROS1': [[{'transcript': 'NM_000313.4',
    'protein_id': 'NP_000304.2',
    'protein_seq': Seq('MRVLGGRCGALLACLLLVLPVSEANFLSKQQASQVLVRKRRANSLLEETKQGNL...KNS'),
    'cds_seq': Seq('atgagggtcctgggtgggcgctgcggggcgctgctggcgtgtctcctcctagtg...taa'),
    'cds_start': 147,
    'cds_end': 2178}]],
 'PRPF31': [[{'transcript': 'NM_015629.4',
    'protein_id': 'NP_056444.3',
    'protein_seq': Seq('MSLADELLADLEEAAEEEEGGSYGEEEEEPAIEDVQEETQLDLSGDSVKTIAKL...MST'),
    'cds_seq': Seq('atgtctctggcagatgagctcttagctgatctcgaagaggcagcagaagaggag...tga'),
    'cds_start': 52,
    'cds_end': 1552}]],
 'PRPF8': [[{'transcript': 'NM_006445.4',
    'protein_id': 'NP_006436.3',
    'protein_seq': Seq('MAGVFPYRGPGNPVPGPLAPLPDYMSEEKLQEKARKWQQLQAKRYAEKRKFGFV...LYA'),
    'cds_seq': Seq('atggccggagtgtttccttatcgagggccgggtaacccggtgcctggccctcta...tga'),
    'cds_start': 99,
    'cds_end': 7107}]],
 'PRPH2': [[{'transcript': 'NM_000322.5',
    'protein_id': 'NP_000313.2',
    'protein_seq': Seq('MALLKVKFDQKKRVKLAQGLWLMNWFSVLAGIIIFSLGLFLKIELRKRSDVMNN...EAG'),
    'cds_seq': Seq('atggcgctactgaaagtcaagtttgaccagaagaagcgggtcaagttggcccaa...tga'),
    'cds_start': 263,
    'cds_end': 1304}]],
 'PRRT2': [[{'transcript': 'NM_145239.3',
    'protein_id': 'NP_660282.2',
    'protein_seq': Seq('MAASSSEISEMKGVEESPKVPGEGPGHSEAETGPPQVLAGVPDQPEAPQPGPNT...VYK'),
    'cds_seq': Seq('atggcagccagcagctctgagatctctgagatgaagggggttgaggagagtccc...tga'),
    'cds_start': 196,
    'cds_end': 1219}]],
 'PSAP': [[{'transcript': 'NM_002778.4',
    'protein_id': 'NP_002769.1',
    'protein_seq': Seq('MYALFLLASLLGAALAGPVLGLKECTRGSAVWCQNVKTASDCGAVKHCLQTVWN...VWN'),
    'cds_seq': Seq('atgtacgccctcttcctcctggccagcctcctgggcgcggctctagccggcccg...tag'),
    'cds_start': 30,
    'cds_end': 1605}]],
 'PSEN1': [[{'transcript': 'NM_000021.4',
    'protein_id': 'NP_000012.1',
    'protein_seq': Seq('MTELPAPLSYFQNAQMSEDNHLSNTVRSQNDNRERQEHNDRRSLGHPEPLSNGR...FYI'),
    'cds_seq': Seq('atgacagagttacctgcaccgttgtcctacttccagaatgcacagatgtctgag...tag'),
    'cds_start': 212,
    'cds_end': 1616}]],
 'PTCH1': [[{'transcript': 'NM_000264.5',
    'protein_id': 'NP_000255.2',
    'protein_seq': Seq('MASAGNAAEPQDRGGGGSGCIGAPGRPAGGGRRRRTGGLRRAAAPDRDYLHRPS...SSN'),
    'cds_seq': Seq('atggcctcggctggtaacgccgccgagccccaggaccgcggcggcggcggcagc...tga'),
    'cds_start': 905,
    'cds_end': 5249}],
  [{'transcript': 'NM_001083603.3',
    'protein_id': 'NP_001077072.1',
    'protein_seq': Seq('MELLNRNRLVIVSPRCTPPKASGGPARRGFYTFRSFCKDGGGGEEEEENGGEEK...SSN'),
    'cds_seq': Seq('atggaactgcttaatagaaacaggcttgtaattgtgagtccgcgctgcactccg...tga'),
    'cds_start': 151,
    'cds_end': 4492}]],
 'PTEN': [[{'transcript': 'NM_000314.8',
    'protein_id': 'NP_000305.3',
    'protein_seq': Seq('MTAIIKEIVSRNKRRYQEDGFDLDLTYIYPNIIAMGFPAERLEGVYRNNIDDVV...TKV'),
    'cds_seq': Seq('atgacagccatcatcaaagagatcgttagcagaaacaaaaggagatatcaagag...tga'),
    'cds_start': 845,
    'cds_end': 2057}]],
 'PTPN11': [[{'transcript': 'NM_002834.5',
    'protein_id': 'NP_002825.3',
    'protein_seq': Seq('MTSRRWFHPNITGVEAENLLLTRGVDGSFLARPSKSNPGDFTLSVRRNGAVTHI...SFR'),
    'cds_seq': Seq('atgacatcgcggagatggtttcacccaaatatcactggtgtggaggcagaaaac...tga'),
    'cds_start': 165,
    'cds_end': 1947}]],
 'PTS': [[{'transcript': 'NM_000317.3',
    'protein_id': 'NP_000308.1',
    'protein_seq': Seq('MSTEGGGRRCQAQVSRRISFSASHRLYSKFLSDEENLKLFGKCNNPNGHGHNYK...KGE'),
    'cds_seq': Seq('atgagcacggaaggtggtggccgtcgctgccaggcacaagtgtcccgccgcatc...tag'),
    'cds_start': 16,
    'cds_end': 454}]],
 'PUF60': [[{'transcript': 'NM_078480.3',
    'protein_id': 'NP_510965.1',
    'protein_seq': Seq('MATATIALQVNGQQGGGSEPAAAAAVVAAGDKWKPPQGTDSIKMENGQSTAAKL...LSA'),
    'cds_seq': Seq('atggcgacggcgaccatagctctccaggtcaatggccagcaaggaggggggtcc...tga'),
    'cds_start': 12,
    'cds_end': 1692}]],
 'PURA': [[{'transcript': 'NM_005859.5',
    'protein_id': 'NP_005850.1',
    'protein_seq': Seq('MADRDSGSEQGGAALGSGGSLGHPGSGSGSGGGGGGGGGGGGSGGGGGGAPGGL...EED'),
    'cds_seq': Seq('atggcggaccgagacagcggcagcgagcagggtggtgcggcgctgggttcgggc...tga'),
    'cds_start': 73,
    'cds_end': 1042}]],
 'PYGL': [[{'transcript': 'NM_002863.5',
    'protein_id': 'NP_002854.3',
    'protein_seq': Seq('MAKPLTDQEKRRQISIRGIVGVENVAELKKSFNRHLHFTLVKDRNVATTRDYYF...NGN'),
    'cds_seq': Seq('atggcgaagcccctgacggaccaggagaagcggcggcagatcagcatccgcggc...tga'),
    'cds_start': 80,
    'cds_end': 2624}]],
 'PYGM': [[{'transcript': 'NM_005609.4',
    'protein_id': 'NP_005600.1',
    'protein_seq': Seq('MSRPLSDQEKRKQISVRGLAGVENVTELKKNFNRHLHFTLVKDRNVATPRDYYF...EAI'),
    'cds_seq': Seq('atgtcccggcccctgtcagaccaagagaaaagaaagcaaatcagtgtgcgtggc...tga'),
    'cds_start': 76,
    'cds_end': 2605}]],
 'RAD50': [[{'transcript': 'NM_005732.4',
    'protein_id': 'NP_005723.2',
    'protein_seq': Seq('MSRIEKMSILGVRSFGIEDKDKQIITFFSPLTILVGPNGAGKTTIIECLKYICT...NVH'),
    'cds_seq': Seq('atgtcccggatcgaaaagatgagcattctgggcgtgcggagttttggaatagag...taa'),
    'cds_start': 348,
    'cds_end': 4287}]],
 'RAD51C': [[{'transcript': 'NM_058216.3',
    'protein_id': 'NP_478123.1',
    'protein_seq': Seq('MRGKTFRFEMQRDLVSFPLSPAVRVKLVSAGFQTAEELLEVKPSELSKEVGISK...EEL'),
    'cds_seq': Seq('atgcgcgggaagacgttccgctttgaaatgcagcgggatttggtgagtttcccg...taa'),
    'cds_start': 42,
    'cds_end': 1173}]],
 'RAD51D': [[{'transcript': 'NM_002878.4',
    'protein_id': 'NP_002869.3',
    'protein_seq': Seq('MGVLRVGLCPGLTEEMIQLLRSHRIKTVVDLVSADLEEVAQKCGLSYKALVALR...DQT'),
    'cds_seq': Seq('atgggcgtgctcagggtcggactgtgccctggccttaccgaggagatgatccag...tga'),
    'cds_start': 247,
    'cds_end': 1234}]],
 'RAF1': [[{'transcript': 'NM_002880.4',
    'protein_id': 'NP_002871.1',
    'protein_seq': Seq('MEHIQGAWKTISNGFGFKDAVFDGSSCISPTIVQQFGYQRRASDDGKLTDPSKT...PVF'),
    'cds_seq': Seq('atggagcacatacagggagcttggaagacgatcagcaatggttttggattcaaa...tag'),
    'cds_start': 331,
    'cds_end': 2278}]],
 'RAG1': [[{'transcript': 'NM_000448.3',
    'protein_id': 'NP_000439.2',
    'protein_seq': Seq('MAASFPPTLGLSSAPDEIQHPHIKFSEWKFKLFRVRSFEKTPEEAQKEKKDSFE...MEF'),
    'cds_seq': Seq('atggcagcctctttcccacccaccttgggactcagttctgccccagatgaaatt...taa'),
    'cds_start': 130,
    'cds_end': 3262}]],
 'RAG2': [[{'transcript': 'NM_000536.4',
    'protein_id': 'NP_000527.2',
    'protein_seq': Seq('MSLQMVTVSNNIALIQPGFSLMNFDGQVFFFGQKGWPKRSCPTGVFHLDVKHNH...LFD'),
    'cds_seq': Seq('atgtctctgcagatggtaacagtcagtaataacatagccttaattcagccaggc...tag'),
    'cds_start': 162,
    'cds_end': 1746}]],
 'RAI1': [[{'transcript': 'NM_030665.4',
    'protein_id': 'NP_109590.3',
    'protein_seq': Seq('MQSFRERCGFHGKQQNYQQTSQETSRLENYRQPSQAGLSCDRQRLLAKDYYNPQ...RLP'),
    'cds_seq': Seq('atgcagtcttttcgagaaaggtgtggtttccatggcaaacaacagaactaccag...tag'),
    'cds_start': 484,
    'cds_end': 6205}]],
 'RAPSN': [[{'transcript': 'NM_005055.5',
    'protein_id': 'NP_005046.2',
    'protein_seq': Seq('MGQDQTKQQIEKGLQLYQSNQTEKALQVWTKVLEKSSDLMGRFRVLGCLVTAHS...GFV'),
    'cds_seq': Seq('atggggcaggaccagaccaagcagcagatcgagaaggggctccagctgtaccag...tga'),
    'cds_start': 172,
    'cds_end': 1411}]],
 'RARS2': [[{'transcript': 'NM_020320.5',
    'protein_id': 'NP_064716.2',
    'protein_seq': Seq('MACGFRRAIACQLSRVLNLPPENLITSISAVPISQKEEVADFQLSVDSLLEKDN...CRM'),
    'cds_seq': Seq('atggcgtgcggctttcgccgcgctattgcttgccagctttccagagtgttgaat...taa'),
    'cds_start': 30,
    'cds_end': 1767}]],
 'RASA1': [[{'transcript': 'NM_002890.3',
    'protein_id': 'NP_002881.1',
    'protein_seq': Seq('MMAAEAGSEEGGPVTAGAGGGGAAAGSSAYPAVCRVKIPAALPVAAAPYPGLVE...DVR'),
    'cds_seq': Seq('atgatggcggccgaggccggcagtgaggagggcggcccggtaacagccggagct...tag'),
    'cds_start': 569,
    'cds_end': 3713}]],
 'RB1': [[{'transcript': 'NM_000321.3',
    'protein_id': 'NP_000312.2',
    'protein_seq': Seq('MPPKTPRKTAATAAAAAAEPPAPPPPPPPEEDPEQDSGPEDLPLVRLEFEETEE...EEK'),
    'cds_seq': Seq('atgccgcccaaaaccccccgaaaaacggccgccaccgccgccgctgccgccgcg...tga'),
    'cds_start': 162,
    'cds_end': 2949}]],
 'RBM20': [[{'transcript': 'NM_001134363.3',
    'protein_id': 'NP_001127835.2',
    'protein_seq': Seq('MVLAAAMSQDADPSGPEQPDRVACSVPGARASPAPSGPRGMQQPPPPPQPPPPP...KKL'),
    'cds_seq': Seq('atggtgctggcagcagccatgagccaggacgcggaccccagcggtccggagcag...tga'),
    'cds_start': 119,
    'cds_end': 3803}]],
 'RDH12': [[{'transcript': 'NM_152443.3',
    'protein_id': 'NP_689656.2',
    'protein_seq': Seq('MLVTLGLLTSFFSFLYMVAPSIRKFFAGGVCRTNVQLPGKVVVITGANTGIGKE...RWE'),
    'cds_seq': Seq('atgctggtcaccttgggactgctcacctccttcttctcgttcctgtatatggta...tag'),
    'cds_start': 324,
    'cds_end': 1275}]],
 'RECQL4': [[{'transcript': 'NM_004260.4',
    'protein_id': 'NP_004251.4',
    'protein_seq': Seq('MERLRDVRERLQAWERAFRRQRGRRPSQDDVEAAPEETRALYREYRTLKRTTGQ...VAR'),
    'cds_seq': Seq('atggagcggctgcgggacgtgcgggagcggctgcaggcgtgggagcgcgcgttc...tga'),
    'cds_start': 49,
    'cds_end': 3676}]],
 'REEP1': [[{'transcript': 'NM_001371279.1',
    'protein_id': 'NP_001358208.1',
    'protein_seq': Seq('MVSWIISRLVVLIFGTLYPAYYSYKAVKSKDIKEYVKWMMYWIIFALFTTAETF...ETT'),
    'cds_seq': Seq('atggtgtcatggatcatctccaggctggtggtgcttatatttggcaccctttac...tga'),
    'cds_start': 116,
    'cds_end': 971}]],
 'RELN': [[{'transcript': 'NM_005045.4',
    'protein_id': 'NP_005036.2',
    'protein_seq': Seq('MERSGWARQTFLLALLLGATLRARAAAGYYPRFSPFFFLCTHHGELEGDGEQGE...RYP'),
    'cds_seq': Seq('atggagcgcagtggctgggcccggcagactttcctcctagcgctgttgctgggg...tga'),
    'cds_start': 302,
    'cds_end': 10685}]],
 'RET': [[{'transcript': 'NM_020975.6',
    'protein_id': 'NP_066124.1',
    'protein_seq': Seq('MAKATSGAAGLRLLLLLLLPLLGKVALGLYFSRDAYWEKLYVDQAAGTPLLYVH...FDS'),
    'cds_seq': Seq('atggcgaaggcgacgtccggtgccgcggggctgcgtctgctgttgctgctgctg...taa'),
    'cds_start': 190,
    'cds_end': 3535}]],
 'RHO': [[{'transcript': 'NM_000539.3',
    'protein_id': 'NP_000530.1',
    'protein_seq': Seq('MNGTEGPNFYVPFSNATGVVRSPFEYPQYYLAEPWQFSMLAAYMFLLIVLGFPI...APA'),
    'cds_seq': Seq('atgaatggcacagaaggccctaacttctacgtgcccttctccaatgcgacgggt...taa'),
    'cds_start': 95,
    'cds_end': 1142}]],
 'RP1': [[{'transcript': 'NM_001375654.1',
    'protein_id': 'NP_001362583.1',
    'protein_seq': Seq('MSDTPSTGFSIIHPTSSEGQVPPPRHLSLTHPVVAKRISFYKSGDPQFGGVRVV...TIS'),
    'cds_seq': Seq('atgagtgataccccttctactggtttttccatcattcatcctacgtcttctgaa...tga'),
    'cds_start': 148,
    'cds_end': 4300}],
  [{'transcript': 'NM_006269.2',
    'protein_id': 'NP_006260.1',
    'protein_seq': Seq('MSDTPSTGFSIIHPTSSEGQVPPPRHLSLTHPVVAKRISFYKSGDPQFGGVRVV...EDL'),
    'cds_seq': Seq('atgagtgataccccttctactggtttttccatcattcatcctacgtcttctgaa...taa'),
    'cds_start': 119,
    'cds_end': 6590}]],
 'RP2': [[{'transcript': 'NM_006915.3',
    'protein_id': 'NP_008846.2',
    'protein_seq': Seq('MGCFFSKRRKADKESRPENEEERPKQYSWDQREKVDPKDYMFSGLKDETVGRLP...MGI'),
    'cds_seq': Seq('atgggctgcttcttctccaagagacggaaggctgacaaggagtcgcggcccgag...tga'),
    'cds_start': 58,
    'cds_end': 1111}]],
 'RPE65': [[{'transcript': 'NM_000329.3',
    'protein_id': 'NP_000320.1',
    'protein_seq': Seq('MSIQVEHPAGGYKKLFETVEELSSPLTAHVTGRIPLWLTGSLLRCGPGLFEVGS...KKS'),
    'cds_seq': Seq('atgtctatccaggttgagcatcctgctggtggttacaagaaactgtttgaaact...tga'),
    'cds_start': 49,
    'cds_end': 1651}]],
 'RPGR': [[{'transcript': 'NM_001034853.2',
    'protein_id': 'NP_001030025.1',
    'protein_seq': Seq('MREPEELMPDSGAVFTFGKSKFAENNPGKFWFKNDVPVHLSCGDEHSAVVTGNN...ELK'),
    'cds_seq': Seq('atgagggagccggaagagctgatgcccgattcgggtgctgtgtttacatttggg...taa'),
    'cds_start': 142,
    'cds_end': 3601}]],
 'RPGRIP1': [[{'transcript': 'NM_020366.4',
    'protein_id': 'NP_065099.3',
    'protein_seq': Seq('MSHLVDPTSGDLPVRDIDAIPLVLPASKGKNMKTQPPLSRMNREELEDSFFRLR...LFS'),
    'cds_seq': Seq('atgtcacatctggtggaccctacatcaggagacttgccagttagagacatagat...tga'),
    'cds_start': 115,
    'cds_end': 3976}]],
 'RPGRIP1L': [[{'transcript': 'NM_015272.5',
    'protein_id': 'NP_056087.2',
    'protein_seq': Seq('MSGPTDETAGDLPVKDTGLNLFGMGGLQETSTTRTMKSRQAVSRVSREELEDRF...LEA'),
    'cds_seq': Seq('atgtctggtccaactgatgagactgcaggagacttgcctgtgaaagatacaggt...tga'),
    'cds_start': 64,
    'cds_end': 4012}]],
 'RPS19': [[{'transcript': 'NM_001022.4',
    'protein_id': 'NP_001013.1',
    'protein_seq': Seq('MPGVTVKDVNQQEFVRALAAFLKKSGKLKVPEWVDTVKLAKHKELAPYDENWFY...KKH'),
    'cds_seq': Seq('atgcctggagttactgtaaaagacgtgaaccagcaggagttcgtcagagctctg...tag'),
    'cds_start': 35,
    'cds_end': 473}]],
 'RPS6KA3': [[{'transcript': 'NM_004586.3',
    'protein_id': 'NP_004577.1',
    'protein_seq': Seq('MPLAQLADPWQKMAVESPSDSAENGQQIMDEPMGEEEINPQTEEVSIKEIAITH...TAL'),
    'cds_seq': Seq('atgccgctggcgcagctggcggacccgtggcagaagatggctgtggagagcccg...tga'),
    'cds_start': 277,
    'cds_end': 2500}]],
 'RS1': [[{'transcript': 'NM_000330.4',
    'protein_id': 'NP_000321.1',
    'protein_seq': Seq('MSRKIEGFLLLLLFGYEATLGLSSTEDEGEDPWYQKACKCDCQGGPNALWSAGA...KCA'),
    'cds_seq': Seq('atgtcacgcaagatagaaggctttttgttattacttctctttggctatgaagcc...tga'),
    'cds_start': 40,
    'cds_end': 715}]],
 'RTEL1': [[{'transcript': 'NM_001283009.1',
    'protein_id': 'NP_001269938.1',
    'protein_seq': Seq('MPKIVLNGVTVDFPFQPYKCQQEYMTKVLECLQQKVNGILESPTGTGKTLCLLC...EPQ'),
    'cds_seq': Seq('atgcccaagatagtcctgaatggtgtgaccgtagacttccctttccagccctac...tga'),
    'cds_start': 827,
    'cds_end': 4730}],
  [{'transcript': 'NM_001283009.2',
    'protein_id': 'NP_001269938.1',
    'protein_seq': Seq('MPKIVLNGVTVDFPFQPYKCQQEYMTKVLECLQQKVNGILESPTGTGKTLCLLC...EPQ'),
    'cds_seq': Seq('atgcccaagatagtcctgaatggtgtgaccgtagacttccctttccagccctac...tga'),
    'cds_start': 325,
    'cds_end': 4228}]],
 'RTTN': [[{'transcript': 'NM_173630.4',
    'protein_id': 'NP_775901.3',
    'protein_seq': Seq('MVLAGLIRKLGHQLAEIRERALKSILCKIEHNLICYADLIQERQLFLHLLEWFN...NSS'),
    'cds_seq': Seq('atggtcctggcagggctcatcaggaaactcggtcatcagctggccgagatcagg...tga'),
    'cds_start': 29,
    'cds_end': 6710}]],
 'RUNX1': [[{'transcript': 'NM_001754.4',
    'protein_id': 'NP_001745.2',
    'protein_seq': Seq('MASDSIFESFPSYPQCFMRECILGMNPSRDVHDASTSRRFTPPSTALSPGKMSE...RPY'),
    'cds_seq': Seq('atggcttcagacagcatatttgagtcatttccttcgtacccacagtgcttcatg...tga'),
    'cds_start': 190,
    'cds_end': 1633}],
  [{'transcript': 'NM_001754.5',
    'protein_id': 'NP_001745.2',
    'protein_seq': Seq('MASDSIFESFPSYPQCFMRECILGMNPSRDVHDASTSRRFTPPSTALSPGKMSE...RPY'),
    'cds_seq': Seq('atggcttcagacagcatatttgagtcatttccttcgtacccacagtgcttcatg...tga'),
    'cds_start': 194,
    'cds_end': 1637}]],
 'RUNX2': [[{'transcript': 'NM_001024630.4',
    'protein_id': 'NP_001019801.3',
    'protein_seq': Seq('MASNSLFSTVTPCQQNFFWDPSTSRRFSPPSSSLQPGKMSDVSPVVAAQQQQQQ...RPY'),
    'cds_seq': Seq('atggcatcaaacagcctcttcagcacagtgacaccatgtcagcaaaacttcttt...tga'),
    'cds_start': 197,
    'cds_end': 1763}]],
 'RYR1': [[{'transcript': 'NM_000540.2',
    'protein_id': 'NP_000531.2',
    'protein_seq': Seq('MGDAEGEDEVQFLRTDDEVVLQCSATVLKEQLKLCLAAEGFGNRLCFLEPTSNA...QLS'),
    'cds_seq': Seq('atgggtgacgcagaaggcgaagacgaggtccagttcctgcggacggacgatgag...tga'),
    'cds_start': 130,
    'cds_end': 15247}],
  [{'transcript': 'NM_000540.3',
    'protein_id': 'NP_000531.2',
    'protein_seq': Seq('MGDAEGEDEVQFLRTDDEVVLQCSATVLKEQLKLCLAAEGFGNRLCFLEPTSNA...QLS'),
    'cds_seq': Seq('atgggtgacgcagaaggcgaagacgaggtccagttcctgcggacggacgatgag...tga'),
    'cds_start': 139,
    'cds_end': 15256}]],
 'RYR2': [[{'transcript': 'NM_001035.3',
    'protein_id': 'NP_001026.2',
    'protein_seq': Seq('MADGGEGEDEIQFLRTDDEVVLQCTATIHKEQQKLCLAAEGFGNRLCFLESTSN...QLN'),
    'cds_seq': Seq('atggccgatgggggcgagggcgaagacgagatccagttcctgcgaactgatgat...taa'),
    'cds_start': 338,
    'cds_end': 15242}]],
 'SACS': [[{'transcript': 'NM_014363.6',
    'protein_id': 'NP_055178.3',
    'protein_seq': Seq('METKENRWVPVTVLPGCVGCRTVAALASWTVRDVKERIFAETGFPVSEQRLWRG...QKV'),
    'cds_seq': Seq('atggagaccaaggagaacaggtgggtcccggtgaccgtgctccccggctgcgtg...tga'),
    'cds_start': 589,
    'cds_end': 14329}]],
 'SAMHD1': [[{'transcript': 'NM_015474.4',
    'protein_id': 'NP_056289.2',
    'protein_seq': Seq('MQRADSEQPSKRPRCDDSPRTPSNTPSAEADWSPGLELHPDYKTWGPEQVCSFL...DPM'),
    'cds_seq': Seq('atgcagcgagccgattccgagcagccctccaagcgtccccgttgcgatgacagc...tga'),
    'cds_start': 65,
    'cds_end': 1946}]],
 'SATB2': [[{'transcript': 'NM_001172509.2',
    'protein_id': 'NP_001165980.1',
    'protein_seq': Seq('MERRSESPCLRDSPDRRSGSPDVKGPPPVKVARLEQNGSPMGARGRPNGAVAKA...DQR'),
    'cds_seq': Seq('atggagcggcggagcgagagcccgtgtctgcgggacagccccgaccggcggagc...taa'),
    'cds_start': 660,
    'cds_end': 2862}],
  [{'transcript': 'NM_001172517.1',
    'protein_id': 'NP_001165988.1',
    'protein_seq': Seq('MERRSESPCLRDSPDRRSGSPDVKGPPPVKVARLEQNGSPMGARGRPNGAVAKA...DQR'),
    'cds_seq': Seq('atggagcggcggagcgagagcccgtgtctgcgggacagccccgaccggcggagc...taa'),
    'cds_start': 413,
    'cds_end': 2615}]],
 'SBF2': [[{'transcript': 'NM_030962.4',
    'protein_id': 'NP_112224.1',
    'protein_seq': Seq('MARLADYFIVVGYDHEKPGSGEGLGKIIQRFPQKDWDDTPFPQGIELFCQPGGW...SDA'),
    'cds_seq': Seq('atggcccggctggctgactacttcatcgtggtaggctatgaccacgagaagcca...tga'),
    'cds_start': 150,
    'cds_end': 5700}]],
 'SCN1A': [[{'transcript': 'NM_001165963.4',
    'protein_id': 'NP_001159435.1',
    'protein_seq': Seq('MEQTVLVPPGPDSFNFFTRESLAAIERRIAEEKAKNPKPDKKDDDENGPKPNSD...KGK'),
    'cds_seq': Seq('atggagcaaacagtgcttgtaccaccaggacctgacagcttcaacttcttcacc...taa'),
    'cds_start': 478,
    'cds_end': 6508}]],
 'SCN2A': [[{'transcript': 'NM_001040142.2',
    'protein_id': 'NP_001035232.1',
    'protein_seq': Seq('MAQSVLVPPGPDSFRFFTRESLAAIEQRIAEEKAKRPKQERKDEDDENGPKPNS...SKK'),
    'cds_seq': Seq('atggcacagtcagtgctggtaccgccaggacctgacagcttccgcttctttacc...taa'),
    'cds_start': 278,
    'cds_end': 6296}],
  [{'transcript': 'NM_001371246.1',
    'protein_id': 'NP_001358175.1',
    'protein_seq': Seq('MAQSVLVPPGPDSFRFFTRESLAAIEQRIAEEKAKRPKQERKDEDDENGPKPNS...SKK'),
    'cds_seq': Seq('atggcacagtcagtgctggtaccgccaggacctgacagcttccgcttctttacc...taa'),
    'cds_start': 278,
    'cds_end': 6296}]],
 'SCN4A': [[{'transcript': 'NM_000334.4',
    'protein_id': 'NP_000325.4',
    'protein_seq': Seq('MARPSLCTLVPLGPECLRPFTRESLAAIEQRAVEEEARLQRNKQMEIEEPERKP...SLV'),
    'cds_seq': Seq('atggccagaccatctctgtgcaccctggtgcctctgggccctgagtgcttgcgc...tag'),
    'cds_start': 77,
    'cds_end': 5588}]],
 'SCN5A': [[{'transcript': 'NM_000335.5',
    'protein_id': 'NP_000326.2',
    'protein_seq': Seq('MANFLLPRGTSSFRRFTRESLAAIEKRMAEKQARGSTTLQESREGLPEEEAPRP...SIV'),
    'cds_seq': Seq('atggcaaacttcctattacctcggggcaccagcagcttccgcaggttcacacgg...tga'),
    'cds_start': 209,
    'cds_end': 6257}],
  [{'transcript': 'NM_001099404.2',
    'protein_id': 'NP_001092874.1',
    'protein_seq': Seq('MANFLLPRGTSSFRRFTRESLAAIEKRMAEKQARGSTTLQESREGLPEEEAPRP...SIV'),
    'cds_seq': Seq('atggcaaacttcctattacctcggggcaccagcagcttccgcaggttcacacgg...tga'),
    'cds_start': 209,
    'cds_end': 6260}]],
 'SCN8A': [[{'transcript': 'NM_001330260.2',
    'protein_id': 'NP_001317189.1',
    'protein_seq': Seq('MAARLLAPPGPDSFKPFTPESLANIERRIAESKLKKPPKADGSHREDDEDSKPK...SKC'),
    'cds_seq': Seq('atggcagcgcggctgcttgcaccaccaggccctgatagtttcaagcctttcacc...tag'),
    'cds_start': 181,
    'cds_end': 6124}],
  [{'transcript': 'NM_014191.4',
    'protein_id': 'NP_055006.1',
    'protein_seq': Seq('MAARLLAPPGPDSFKPFTPESLANIERRIAESKLKKPPKADGSHREDDEDSKPK...SKC'),
    'cds_seq': Seq('atggcagcgcggctgcttgcaccaccaggccctgatagtttcaagcctttcacc...tag'),
    'cds_start': 181,
    'cds_end': 6124}]],
 'SCN9A': [[{'transcript': 'NM_001365536.1',
    'protein_id': 'NP_001352465.1',
    'protein_seq': Seq('MAMLPPPGPQSFVHFTKQSLALIEQRIAERKSKEPKEEKKDDDEEAPKPSSDLE...SKK'),
    'cds_seq': Seq('atggcaatgttgcctcccccaggacctcagagctttgtccatttcacaaaacag...tag'),
    'cds_start': 298,
    'cds_end': 6265}]],
 'SDCCAG8': [[{'transcript': 'NM_006642.5',
    'protein_id': 'NP_006633.1',
    'protein_seq': Seq('MAKSPENSTLEEILGQYQRSLREHASRSIHQLTCALKEGDVTIGEDAPNLSFST...SDC'),
    'cds_seq': Seq('atggcgaagtccccggagaactctaccctggaggagattctggggcagtatcaa...tga'),
    'cds_start': 133,
    'cds_end': 2275}]],
 'SDHA': [[{'transcript': 'NM_004168.4',
    'protein_id': 'NP_004159.2',
    'protein_seq': Seq('MSGVRGLSRLLSARRLALAKAWPTVLQTGTRGFHFTVDGNKRASAKVSDSISAQ...RSY'),
    'cds_seq': Seq('atgtcgggggtccggggcctgtcgcggctgctgagcgctcggcgcctggcgctg...tga'),
    'cds_start': 36,
    'cds_end': 2031}]],
 'SDHB': [[{'transcript': 'NM_003000.3',
    'protein_id': 'NP_002991.2',
    'protein_seq': Seq('MAAVVALSLRRRLPATTLGGACLQASRGAQTAAATAPRIKKFAIYRWDPDKAGD...ASV'),
    'cds_seq': Seq('atggcggcggtggtcgccctctccttgaggcgccggttgccggccacaaccctt...taa'),
    'cds_start': 13,
    'cds_end': 856}]],
 'SDHC': [[{'transcript': 'NM_003001.5',
    'protein_id': 'NP_002992.1',
    'protein_seq': Seq('MAALLLRHVGRHCLRAHFSPQLCIRNAVPLGTTAKEEMERFWNKNIGSNRPLSP...AAM'),
    'cds_seq': Seq('atggctgcgctgttgctgagacacgttggtcgtcattgcctccgagcccacttt...tga'),
    'cds_start': 25,
    'cds_end': 535}]],
 'SDHD': [[{'transcript': 'NM_003002.4',
    'protein_id': 'NP_002993.1',
    'protein_seq': Seq('MAVLWRLSAVCGALGGRALLLRTPVVRPAHISAFLQDRPIPEWCGVQHIHLSPS...WKL'),
    'cds_seq': Seq('atggcggttctctggaggctgagtgccgtttgcggtgccctaggaggccgagct...tga'),
    'cds_start': 35,
    'cds_end': 515}]],
 'SEC23B': [[{'transcript': 'NM_006363.6',
    'protein_id': 'NP_006354.2',
    'protein_seq': Seq('MATYLEFIQQNEERDGVRFSWNVWPSSRLEATRMVVPLACLLTPLKERPDLPPV...SAC'),
    'cds_seq': Seq('atggcgacatacctggagttcatccagcagaatgaagaacgggatggtgtgcgt...taa'),
    'cds_start': 47,
    'cds_end': 2351}]],
 'SELENON': [[{'transcript': 'NM_020451.2',
    'protein_id': 'NP_065184.2',
    'protein_seq': Seq('MGRARPGQRGPPSPGPAAQPPAPPRRRARSLALLGALLAAAAAAAVRVCARHAE...LQP'),
    'cds_seq': Seq('atgggccgggcccggccgggccaacgcgggccgcccagccccggccccgccgcg...tag'),
    'cds_start': 55,
    'cds_end': 1828}],
  [{'transcript': 'NM_020451.3',
    'protein_id': 'NP_065184.2',
    'protein_seq': Seq('MGRARPGQRGPPSPGPAAQPPAPPRRRARSLALLGALLAAAAAAAVRVCARHAE...LQP'),
    'cds_seq': Seq('atgggccgggcccggccgggccaacgcgggccgcccagccccggccccgccgcg...tag'),
    'cds_start': 38,
    'cds_end': 1811}],
  [{'transcript': 'NM_206926.2',
    'protein_id': 'NP_996809.1',
    'protein_seq': Seq('MGRARPGQRGPPSPGPAAQPPAPPRRRARSLALLGALLAAAAAAAVRVCARHAE...LQP'),
    'cds_seq': Seq('atgggccgggcccggccgggccaacgcgggccgcccagccccggccccgccgcg...tag'),
    'cds_start': 38,
    'cds_end': 1709}]],
 'SEPSECS': [[{'transcript': 'NM_016955.4',
    'protein_id': 'NP_058651.3',
    'protein_seq': Seq('MNRESFAAGERLVSPAYVRQGCEARRSHEHLIRLLLEKGKCPENGWDESTLELF...ASS'),
    'cds_seq': Seq('atgaaccgcgagagcttcgcggcgggagagcggctggtgtcgccggcttacgtg...tga'),
    'cds_start': 80,
    'cds_end': 1586}]],
 'SERPINC1': [[{'transcript': 'NM_000488.4',
    'protein_id': 'NP_000479.1',
    'protein_seq': Seq('MYSNVIGTVTSGKRKVYLLSLLLIGFWDCVTCHGSPVDICTAKPRDIPMNPMCI...CVK'),
    'cds_seq': Seq('atgtattccaatgtgataggaactgtaacctctggaaaaaggaaggtttatctt...taa'),
    'cds_start': 68,
    'cds_end': 1463}]],
 'SERPING1': [[{'transcript': 'NM_000062.3',
    'protein_id': 'NP_000053.2',
    'protein_seq': Seq('MASRLTLLTLLLLLLAGDRASSNPNATSSSSQDPESLQDRGEGKVATTVISKML...PRA'),
    'cds_seq': Seq('atggcctccaggctgaccctgctgaccctcctgctgctgctgctggctggggat...tga'),
    'cds_start': 60,
    'cds_end': 1563}]],
 'SETBP1': [[{'transcript': 'NM_015559.3',
    'protein_id': 'NP_056374.2',
    'protein_seq': Seq('MESRETLSSSRQRGGESDFLPVSSAKPPAAPGCAGEPLLSTPGPGKGIPVGGER...VLP'),
    'cds_seq': Seq('atggagtccagggaaaccttaagcagctcccggcaaagagggggcgagtcagac...tag'),
    'cds_start': 306,
    'cds_end': 5097}]],
 'SETD5': [[{'transcript': 'NM_001080517.3',
    'protein_id': 'NP_001073986.1',
    'protein_seq': Seq('MSIAIPLGVTTSDTSYSDMAAGSDPESVEASPAVNEKSVYSTHNYGTTQRHGCR...GLS'),
    'cds_seq': Seq('atgagcattgcaatccctctgggagtcaccacatcagatacatcctactcagat...tag'),
    'cds_start': 539,
    'cds_end': 4868}]],
 'SETX': [[{'transcript': 'NM_015046.7',
    'protein_id': 'NP_055861.3',
    'protein_seq': Seq('MSTCCWCTPGGASTIDFLKRYASNTPSGEFQTADEDLCYCLECVAEYHKARDEL...KLL'),
    'cds_seq': Seq('atgagcacatgttgttggtgtacgccaggtggtgcttccaccattgacttccta...tag'),
    'cds_start': 184,
    'cds_end': 8218}]],
 'SGCA': [[{'transcript': 'NM_000023.4',
    'protein_id': 'NP_000014.1',
    'protein_seq': Seq('MAETLFWTPLLVVLLAGLGDTEAQQTTLHPLVGRVFVHTLDHETFLSLPEHVAV...DQH'),
    'cds_seq': Seq('atggctgagacactcttctggactcctctcctcgtggttctcctggcagggctg...tga'),
    'cds_start': 36,
    'cds_end': 1200}]],
 'SGCB': [[{'transcript': 'NM_000232.5',
    'protein_id': 'NP_000223.1',
    'protein_seq': Seq('MAAAAAAAAEQQSSNGPVKKSMREKAVERRSVNKEHNSNFKAGYIPIDEDRLHK...NTH'),
    'cds_seq': Seq('atggcggcagcggcggcggcggctgcagaacagcaaagttccaatggtcctgta...taa'),
    'cds_start': 40,
    'cds_end': 997}]],
 'SGCE': [[{'transcript': 'NM_003919.3',
    'protein_id': 'NP_003910.1',
    'protein_seq': Seq('MQLPRWWELGDPCAWTGQGRGTRRMSPATTGTFLLTVYSIFSKVHSDRNVYPSA...WYP'),
    'cds_seq': Seq('atgcaattgccccggtggtgggagctgggagacccctgtgcttggacgggacag...tga'),
    'cds_start': 35,
    'cds_end': 1349}]],
 'SGCG': [[{'transcript': 'NM_000231.3',
    'protein_id': 'NP_000222.2',
    'protein_seq': Seq('MVREQYTTATEGICIERPENQYVYKIGIYGWRKRCLYLFVLLLLIILVVNLALT...ICL'),
    'cds_seq': Seq('atggtgcgtgagcagtacactacagccacagaaggcatctgcatagagaggcca...tga'),
    'cds_start': 97,
    'cds_end': 973}]],
 'SGSH': [[{'transcript': 'NM_000199.5',
    'protein_id': 'NP_000190.1',
    'protein_seq': Seq('MSCPVPACCALLLVLGLCRARPRNALLLLADDGGFESGAYNNSAIATPHLDALA...NEL'),
    'cds_seq': Seq('atgagctgccccgtgcccgcctgctgcgcgctgctgctagtcctggggctctgc...tga'),
    'cds_start': 20,
    'cds_end': 1529}]],
 'SH3TC2': [[{'transcript': 'NM_024577.4',
    'protein_id': 'NP_078853.2',
    'protein_seq': Seq('MGGCFCIPRERSLTRGPGKETPSKDPTVSSECIASSEYKEKCFLPQNINPDLTL...LAL'),
    'cds_seq': Seq('atgggtggctgcttctgcatccccagggagcggagtctgacccggggcccaggt...tga'),
    'cds_start': 40,
    'cds_end': 3907}]],
 'SHANK3': [[{'transcript': 'NM_001372044.2',
    'protein_id': 'NP_001358973.1',
    'protein_seq': Seq('MQLSRAAAAAAAAPAEPPEPLSPAPAPAPAPPGPLPRSAADGAPAGGKGGPGRR...DGS'),
    'cds_seq': Seq('atgcagctgagccgcgccgccgccgccgccgccgccgcccctgcggagcccccg...tga'),
    'cds_start': 370,
    'cds_end': 5791}]],
 'SHH': [[{'transcript': 'NM_000193.4',
    'protein_id': 'NP_000184.1',
    'protein_seq': Seq('MLLLARCLLLVLVSSLLVCSGLACGPGRGFGKRRHPKKLTPLAYKQFIPNVAEK...KSS'),
    'cds_seq': Seq('atgctgctgctggcgagatgtctgctgctagtcctcgtctcctcgctgctggta...tga'),
    'cds_start': 341,
    'cds_end': 1730}]],
 'SHOX': [[{'transcript': 'NM_000451.4',
    'protein_id': 'NP_000442.1',
    'protein_seq': Seq('MEELTAFVSKSFDQKSKDGNGGGGGGGGKKDSITYREVLESGLARSRELGTSDS...LGL'),
    'cds_seq': Seq('atggaagagctcacggcttttgtatccaagtcttttgaccagaaaagcaaggac...tga'),
    'cds_start': 107,
    'cds_end': 986}]],
 'SI': [[{'transcript': 'NM_001041.4',
    'protein_id': 'NP_001032.2',
    'protein_seq': Seq('MARKKFSGLEISLIVLFVIVTIIAIALIVVLATKTPAVDEISDSTSTPATTRVT...NWS'),
    'cds_seq': Seq('atggcaagaaagaaatttagtggattggaaatctctctgattgtcctttttgtc...tga'),
    'cds_start': 64,
    'cds_end': 5548}]],
 'SIN3A': [[{'transcript': 'NM_001145358.2',
    'protein_id': 'NP_001138830.1',
    'protein_seq': Seq('MKRRLDDQESPVYAAQQRRIPGSTEAFPHQHRVLAPAPPVYEAVSETMQSATGI...KAP'),
    'cds_seq': Seq('atgaagcggcgtttggatgaccaggagtcaccggtgtatgcagcccagcagcgt...taa'),
    'cds_start': 301,
    'cds_end': 4123}]],
 'SKIC2': [[{'transcript': 'NM_006929.5',
    'protein_id': 'NP_008860.4',
    'protein_seq': Seq('MMETERLVLPPPDPLDLPLRAVELGCTGHWELLNLPGAPESSLPHGLPPCAPDL...YTQ'),
    'cds_seq': Seq('atgatggagacagagcgacttgtgctaccccctccagatcccctggacctaccc...tga'),
    'cds_start': 18,
    'cds_end': 3759}]],
 'SKIC3': [[{'transcript': 'NM_014639.4',
    'protein_id': 'NP_055454.1',
    'protein_seq': Seq('MSSKEVKTALKSARDAIRNKEYKEALKHCKTVLKQEKNNYNAWVFIGVAAAELE...SSQ'),
    'cds_seq': Seq('atgtccagcaaggaagtgaagactgctctaaaaagtgctagagatgcaatcaga...taa'),
    'cds_start': 269,
    'cds_end': 4964}]],
 'SLC12A1': [[{'transcript': 'NM_000338.3',
    'protein_id': 'NP_000329.2',
    'protein_seq': Seq('MSLNNSSNVFLDSVPSNTNRFQVSVINENHESSAAADDNTDPPHYEETSFGDEA...FYS'),
    'cds_seq': Seq('atgtcactgaacaactcttccaatgtatttctggattcagtgcccagtaatacc...taa'),
    'cds_start': 215,
    'cds_end': 3515}]],
 'SLC12A3': [[{'transcript': 'NM_001126108.2',
    'protein_id': 'NP_001119580.2',
    'protein_seq': Seq('MAELPTTETPGDATLCSGRFTISTLLSSDEPSPPAAYDSSHPSHLTHSSTFCMR...YCQ'),
    'cds_seq': Seq('atggcagaactgcccacaacagagacgcctggggacgccactttgtgcagcggg...taa'),
    'cds_start': 29,
    'cds_end': 3095}]],
 'SLC12A6': [[{'transcript': 'NM_001365088.1',
    'protein_id': 'NP_001352017.1',
    'protein_seq': Seq('MHPPETTTKMASVRFMVTPTKIDDIPGLSDTSPDLSSRSSSRVRFSSRESVPET...IYS'),
    'cds_seq': Seq('atgcatcctccagaaaccaccaccaagatggcttcagttcggttcatggtgaca...taa'),
    'cds_start': 522,
    'cds_end': 3975}]],
 'SLC16A2': [[{'transcript': 'NM_006517.5',
    'protein_id': 'NP_006508.2',
    'protein_seq': Seq('MALQSQASEEAKGPWQEADQEQQEPVGSPEPESEPEPEPEPEPVPVPPPEPQPE...EPI'),
    'cds_seq': Seq('atggcgctgcaaagccaggcgagcgaggaagcaaaggggccctggcaggaggca...taa'),
    'cds_start': 145,
    'cds_end': 1765}]],
 'SLC17A5': [[{'transcript': 'NM_012434.5',
    'protein_id': 'NP_036566.1',
    'protein_seq': Seq('MRSPVRDLARNDGEESTDRTPLLPGAPRAEAAPVCCSARYNLAILAFFGFFIVY...HRH'),
    'cds_seq': Seq('atgaggtctccggttcgagacctggcccggaacgatggcgaggagagcacggac...tga'),
    'cds_start': 106,
    'cds_end': 1594}]],
 'SLC20A2': [[{'transcript': 'NM_001257180.2',
    'protein_id': 'NP_001244109.1',
    'protein_seq': Seq('MAMDEYLWMVILGFIIAFILAFSVGANDVANSFGTAVGSGVVTLRQACILASIF...PYV'),
    'cds_seq': Seq('atggccatggatgagtatttgtggatggtcattttgggtttcatcatagctttc...tga'),
    'cds_start': 465,
    'cds_end': 2424}]],
 'SLC22A5': [[{'transcript': 'NM_003060.4',
    'protein_id': 'NP_003051.1',
    'protein_seq': Seq('MRDYDEVTAFLGEWGPFQRLIFFLLSASIIPNGFTGLSSVFLIATPEHRCRVPD...TAF'),
    'cds_seq': Seq('atgcgggactacgacgaggtgaccgccttcctgggcgagtgggggcccttccag...taa'),
    'cds_start': 263,
    'cds_end': 1937}]],
 'SLC25A13': [[{'transcript': 'NM_014251.3',
    'protein_id': 'NP_055066.1',
    'protein_seq': Seq('MAAAKVALTKRADPAELRTIFLKYASIEKNGEFFMSPNDFVTRYLNIFGESQPN...GGP'),
    'cds_seq': Seq('atggcggccgccaaggtggctttaaccaagagagcagatccagctgagcttaga...tag'),
    'cds_start': 142,
    'cds_end': 2170}]],
 'SLC26A2': [[{'transcript': 'NM_000112.4',
    'protein_id': 'NP_000103.2',
    'protein_seq': Seq('MSSESKEQHNVSPRDSAEGNDSYPSGIHLELQRESSTDFKQFETNDQCRPYHRI...SSD'),
    'cds_seq': Seq('atgtcttcagaaagtaaagagcaacataacgtttcacccagagactcagctgaa...taa'),
    'cds_start': 247,
    'cds_end': 2467}]],
 'SLC26A3': [[{'transcript': 'NM_000111.3',
    'protein_id': 'NP_000102.1',
    'protein_seq': Seq('MIEPFGNQYIVARPVYSTNAFEENHKKTGRHHKTFLDHLKVCCSCSPQKAKRIV...TKF'),
    'cds_seq': Seq('atgattgaaccctttgggaatcagtatattgtggccaggccagtgtattctaca...taa'),
    'cds_start': 201,
    'cds_end': 2496}]],
 'SLC26A4': [[{'transcript': 'NM_000441.2',
    'protein_id': 'NP_000432.1',
    'protein_seq': Seq('MAAPGGRSEPPQLPEYSCSYMVSRPVYSELAFQQQHERRLQERKTLRESLAKCC...LAS'),
    'cds_seq': Seq('atggcagcgccaggcggcaggtcggagccgccgcagctccccgagtacagctgc...tga'),
    'cds_start': 31,
    'cds_end': 2374}]],
 'SLC2A1': [[{'transcript': 'NM_006516.4',
    'protein_id': 'NP_006507.2',
    'protein_seq': Seq('MEPSSKKLTGRLMLAVGGAVLGSLQFGYNTGVINAPQKVIEEFYNQTWVHRYGE...SQV'),
    'cds_seq': Seq('atggagcccagcagcaagaagctgacgggtcgcctcatgctggccgtgggagga...tga'),
    'cds_start': 217,
    'cds_end': 1696}]],
 'SLC34A3': [[{'transcript': 'NM_001177316.2',
    'protein_id': 'NP_001170787.2',
    'protein_seq': Seq('MPSSLPGSQVPHPTLDAVDLVEKTLRNEGTSSSAPVLEEGDTDPWTLPQLKDTS...QQL'),
    'cds_seq': Seq('atgccgagttcccttcccggcagccaggtcccccaccccactctggacgcggtt...tga'),
    'cds_start': 77,
    'cds_end': 1877}]],
 'SLC37A4': [[{'transcript': 'NM_001164277.2',
    'protein_id': 'NP_001157749.1',
    'protein_seq': Seq('MAAQGYGYYRTVIFSAMFGGYSLYYFNRKTFSFVMPSLVEEIPLDKDDLGFITS...KAE'),
    'cds_seq': Seq('atggcagcccagggctatggctattatcgcactgtgatcttctcagccatgttt...tga'),
    'cds_start': 728,
    'cds_end': 2018}]],
 'SLC39A4': [[{'transcript': 'NM_130849.4',
    'protein_id': 'NP_570901.3',
    'protein_seq': Seq('MASLVSLELGLLLAVLVVTATASPPAGLLSLLTSGQGALDQEALGGLLNTLADR...ITF'),
    'cds_seq': Seq('atggcgtccctggtctcgctggagctggggctgcttctggctgtgctggtggtg...tga'),
    'cds_start': 55,
    'cds_end': 1999}]],
 'SLC3A1': [[{'transcript': 'NM_000341.4',
    'protein_id': 'NP_000332.2',
    'protein_seq': Seq('MAEDKSKRDSIEMSMKGCQTNNGFVHNEDILEQTPDPGSSTDNLKHSTRGILGS...TSC'),
    'cds_seq': Seq('atggctgaagataaaagcaagagagactccatcgagatgagtatgaagggatgc...tag'),
    'cds_start': 56,
    'cds_end': 2114}]],
 'SLC45A2': [[{'transcript': 'NM_016180.5',
    'protein_id': 'NP_057264.4',
    'protein_seq': Seq('MGSNSGQAGRHIYKSLADDGPFDSVEPPKRPTSRLIMHSMAMFGREFCYAVEAA...YVD'),
    'cds_seq': Seq('atgggtagcaacagtgggcaggctggccgccacatctataaatccctagctgat...tag'),
    'cds_start': 110,
    'cds_end': 1703}]],
 'SLC4A1': [[{'transcript': 'NM_000342.3',
    'protein_id': 'NP_000333.1',
    'protein_seq': Seq('MEELQDDYEDMMEENLEQEEYEDPDIPESQMEEPAAHDTEATATDYHTTSHPGT...MPV'),
    'cds_seq': Seq('atggaggagctgcaggatgattatgaagacatgatggaggagaatctggagcag...tga'),
    'cds_start': 149,
    'cds_end': 2885}],
  [{'transcript': 'NM_000342.4',
    'protein_id': 'NP_000333.1',
    'protein_seq': Seq('MEELQDDYEDMMEENLEQEEYEDPDIPESQMEEPAAHDTEATATDYHTTSHPGT...MPV'),
    'cds_seq': Seq('atggaggagctgcaggatgattatgaagacatgatggaggagaatctggagcag...tga'),
    'cds_start': 150,
    'cds_end': 2886}]],
 'SLC4A11': [[{'transcript': 'NM_001174089.2',
    'protein_id': 'NP_001167560.1',
    'protein_seq': Seq('MAAATRRVFHLQPCENSPTMSQNGYFEDSSYYKCDTDDTFEAREEILGDEAFDT...HRP'),
    'cds_seq': Seq('atggccgcggccaccaggcgcgtgttccatctgcagccgtgcgaaaactctccc...tga'),
    'cds_start': 53,
    'cds_end': 2681}]],
 'SLC6A1': [[{'transcript': 'NM_003042.4',
    'protein_id': 'NP_003033.3',
    'protein_seq': Seq('MATNGSKVADGQISTEVSEAPVANDKPKTLVVKVQKKAADLPDRDTWKGRFDFL...AYI'),
    'cds_seq': Seq('atggcgaccaacggcagcaaggtggccgacgggcagatctccaccgaggtcagc...tag'),
    'cds_start': 397,
    'cds_end': 2197}]],
 'SLC6A8': [[{'transcript': 'NM_005629.4',
    'protein_id': 'NP_005620.1',
    'protein_seq': Seq('MAKKSAENGIYSVSGDEKKGPLIAPGPDGAPAKGDGPVGLGTPGGRLAVPPRET...SVM'),
    'cds_seq': Seq('atggcgaagaagagcgccgagaacggcatctatagcgtgtccggcgacgagaag...tga'),
    'cds_start': 649,
    'cds_end': 2557}]],
 'SLC7A7': [[{'transcript': 'NM_003982.4',
    'protein_id': 'NP_003973.3',
    'protein_seq': Seq('MVDSTEYEVASQPEVETSPLGDGASPGPEQVKLKKEISLLNGVCLIVGNMIGSG...KSN'),
    'cds_seq': Seq('atggttgacagcactgagtatgaagtggcctcccagcctgaggtggaaacctcc...taa'),
    'cds_start': 158,
    'cds_end': 1694}]],
 'SLC7A9': [[{'transcript': 'NM_014270.5',
    'protein_id': 'NP_055085.1',
    'protein_seq': Seq('MGDTGLRKRREDEKSIQSQEPKTTSLQKELGLISGISIIVGTIIGSGIFVSPKS...DPE'),
    'cds_seq': Seq('atgggggatactggcctgagaaagcggagagaggatgagaagtcgatccagagc...taa'),
    'cds_start': 193,
    'cds_end': 1657}]],
 'SLX4': [[{'transcript': 'NM_032444.4',
    'protein_id': 'NP_115820.2',
    'protein_seq': Seq('MKLSVNEAQLGFYLGSLSHLSACPGIDPRSSEDQPESLKTGQMMDESDEDFKEL...ERN'),
    'cds_seq': Seq('atgaaactgagtgtgaatgaggctcagctaggcttctacttgggttcactttct...tga'),
    'cds_start': 649,
    'cds_end': 6154}]],
 'SMAD3': [[{'transcript': 'NM_005902.4',
    'protein_id': 'NP_005893.1',
    'protein_seq': Seq('MSSILPFTPPIVKRLLGWKKGEQNGQEEKWCEKAVKSLVKKLKKTGQLDELEKA...SVS'),
    'cds_seq': Seq('atgtcgtccatcctgcctttcactcccccgatcgtgaagcgcctgctgggctgg...tag'),
    'cds_start': 553,
    'cds_end': 1831}]],
 'SMAD4': [[{'transcript': 'NM_005359.6',
    'protein_id': 'NP_005350.1',
    'protein_seq': Seq('MDNMSITNTPTSNDACLSIVHSLMCHRQGGESETFAKRAIESLVKKLKEKKDEL...PLD'),
    'cds_seq': Seq('atggacaatatgtctattacgaatacaccaacaagtaatgatgcctgtctgagc...tga'),
    'cds_start': 538,
    'cds_end': 2197}]],
 'SMARCA2': [[{'transcript': 'NM_003070.5',
    'protein_id': 'NP_003061.3',
    'protein_seq': Seq('MSTPTDPGAMPHPGPSPGPGPSPGPILGPSPGPGPSPGSVHSMMGPSPGPPSVS...DDE'),
    'cds_seq': Seq('atgtccacgcccacagaccctggtgcgatgccccacccagggccttcgccgggg...tga'),
    'cds_start': 94,
    'cds_end': 4867}]],
 'SMARCA4': [[{'transcript': 'NM_003072.5',
    'protein_id': 'NP_003063.2',
    'protein_seq': Seq('MSTPDPPLGGTPRPGPSPGPGPSPGAMLGPSPGPSPGSAHSMMGPSPGPPSAGH...EED'),
    'cds_seq': Seq('atgtccactccagacccacccctgggcggaactcctcggccaggtccttccccg...tga'),
    'cds_start': 176,
    'cds_end': 5120}]],
 'SMARCAL1': [[{'transcript': 'NM_014140.4',
    'protein_id': 'NP_054859.2',
    'protein_seq': Seq('MSLPLTEEQRKKIEENRQKALARRAEKLLAEQHQRTSSGTSIAGNPFQAKQGPS...SPL'),
    'cds_seq': Seq('atgtccttgcctcttacagaggagcagaggaaaaagattgaagagaatcgacaa...taa'),
    'cds_start': 260,
    'cds_end': 3125}]],
 'SMARCB1': [[{'transcript': 'NM_003073.5',
    'protein_id': 'NP_003064.2',
    'protein_seq': Seq('MMMMALSKTFGQKPVKFQLEDDGEFYMIGSEVGNYLRMFRGSLYKRYPSLWRRL...PAW'),
    'cds_seq': Seq('atgatgatgatggcgctgagcaagaccttcgggcagaagcccgtgaagttccag...taa'),
    'cds_start': 204,
    'cds_end': 1362}]],
 'SMC1A': [[{'transcript': 'NM_006306.4',
    'protein_id': 'NP_006297.2',
    'protein_seq': Seq('MGFLKLIEIENFKSYKGRQIIGPFQRFTAIIGPNGSGKSNLMDAISFVLGEKTS...NEQ'),
    'cds_seq': Seq('atggggttcctgaaactgattgagattgagaactttaagtcgtacaagggtcga...tag'),
    'cds_start': 54,
    'cds_end': 3756}]],
 'SMC3': [[{'transcript': 'NM_005445.4',
    'protein_id': 'NP_005436.1',
    'protein_seq': Seq('MYIKQVIIQGFRSYRDQTIVDPFSSKHNVIVGRNGSGKSNFFYAIQFVLSDEFS...THG'),
    'cds_seq': Seq('atgtacataaagcaggtgattatccagggttttcgaagttacagagatcaaaca...taa'),
    'cds_start': 122,
    'cds_end': 3776}]],
 'SMCHD1': [[{'transcript': 'NM_015295.3',
    'protein_id': 'NP_056110.2',
    'protein_seq': Seq('MAAADGGGPGGASVGTEEDGGGVGHRTVYLFDRREKESELGDRPLQVGERSDYA...TDV'),
    'cds_seq': Seq('atggcagcggcggacggcggcgggcctggtggggcctctgtggggactgaggag...tga'),
    'cds_start': 350,
    'cds_end': 6368}]],
 'SMPD1': [[{'transcript': 'NM_000543.5',
    'protein_id': 'NP_000534.3',
    'protein_seq': Seq('MPRYGASLRQSCPRSGREQGQDGTAGAPGLLWMGLVLALALALALALALSDSRV...LFC'),
    'cds_seq': Seq('atgccccgctacggagcgtcactccgccagagctgccccaggtccggccgggag...tag'),
    'cds_start': 125,
    'cds_end': 2021}]],
 'SOD1': [[{'transcript': 'NM_000454.5',
    'protein_id': 'NP_000445.1',
    'protein_seq': Seq('MATKAVCVLKGDGPVQGIINFEQKESNGPVKVWGSIKGLTEGLHGFHVHEFGDN...IAQ'),
    'cds_seq': Seq('atggcgacgaaggccgtgtgcgtgctgaagggcgacggcccagtgcagggcatc...taa'),
    'cds_start': 77,
    'cds_end': 542}]],
 'SOS1': [[{'transcript': 'NM_005633.4',
    'protein_id': 'NP_005624.2',
    'protein_seq': Seq('MQAQQLPYEFFSEENAPKWRGLLVPALKKVQGQVHPTLESNDDALQYVEELILQ...HSS'),
    'cds_seq': Seq('atgcaggcgcagcagctgccctacgagtttttcagcgaagagaacgcgcccaag...tga'),
    'cds_start': 629,
    'cds_end': 4631}]],
 'SOX10': [[{'transcript': 'NM_006941.4',
    'protein_id': 'NP_008872.1',
    'protein_seq': Seq('MAEEQDLSEVELSPVGSEEPRCLSPGSAPSLGPDGGGGGSGLRASPGPGELGKV...SRP'),
    'cds_seq': Seq('atggcggaggagcaggacctatcggaggtggagctgagccccgtgggctcggag...taa'),
    'cds_start': 301,
    'cds_end': 1702}]],
 'SOX11': [[{'transcript': 'NM_003108.4',
    'protein_id': 'NP_003099.1',
    'protein_seq': Seq('MVQQAESLEAESNLPREALDTEEGEFMACSPVALDESDPDWCKTASGHIKRPMN...FTY'),
    'cds_seq': Seq('atggtgcagcaggcggagagcttggaagcggagagcaacctgccccgggaggcg...tga'),
    'cds_start': 338,
    'cds_end': 1664}]],
 'SOX5': [[{'transcript': 'NM_006940.6',
    'protein_id': 'NP_008871.3',
    'protein_seq': Seq('MLTDPDLPQEFERMSSKRPASPYGEADGEVAMVTSRQKVEEEESDGLPAFHLPL...QAN'),
    'cds_seq': Seq('atgcttactgaccctgatttacctcaggagtttgaaaggatgtcttccaagcga...tga'),
    'cds_start': 69,
    'cds_end': 2361}]],
 'SOX9': [[{'transcript': 'NM_000346.4',
    'protein_id': 'NP_000337.1',
    'protein_seq': Seq('MNLLDPFMKMTDEQEKGLSGAPSPTMSEDSAGSPCPSGSGSDTENTRPQENTFP...TRP'),
    'cds_seq': Seq('atgaatctcctggaccccttcatgaagatgaccgacgagcaggagaagggcctg...tga'),
    'cds_start': 372,
    'cds_end': 1902}]],
 'SPAST': [[{'transcript': 'NM_014946.4',
    'protein_id': 'NP_055761.2',
    'protein_seq': Seq('MNSPGGRGKKKGSGGASNPVPPRPPPPCLAPAPPAAGPAPPPESPHKRNLYYFS...TTV'),
    'cds_seq': Seq('atgaattctccgggtggacgagggaagaagaaaggctccggcggcgccagcaac...taa'),
    'cds_start': 276,
    'cds_end': 2127}]],
 'SPG11': [[{'transcript': 'NM_025137.4',
    'protein_id': 'NP_079413.3',
    'protein_seq': Seq('MAAEEGVASAASAGGSWGTAAMGRVLPMLLVPVPAEAMGQLGSRAQLRTQPEAL...LAG'),
    'cds_seq': Seq('atggctgcagaggaaggggtcgcgagtgctgcttccgccggcggtagctggggc...tag'),
    'cds_start': 15,
    'cds_end': 7347}]],
 'SPG7': [[{'transcript': 'NM_003119.4',
    'protein_id': 'NP_003110.1',
    'protein_seq': Seq('MAVLLLLLRALRRGPGPGPRPLWGPGPAWSPGFPARPGRGRPYMASRPPGDLAE...WPK'),
    'cds_seq': Seq('atggccgtgctgctgctgctgctccgtgccctccgccggggtccaggcccgggt...tag'),
    'cds_start': 15,
    'cds_end': 2403}]],
 'SPINK5': [[{'transcript': 'NM_006846.4',
    'protein_id': 'NP_006837.2',
    'protein_seq': Seq('MKIATVSVLLPLALCLIQDAASKNEDQEMCHEFQAFMKNGKLFCPQDKKFFQSL...SDE'),
    'cds_seq': Seq('atgaagatagccacagtgtcagtgcttctgcccttggctctttgcctcatacaa...tga'),
    'cds_start': 65,
    'cds_end': 3260}]],
 'SPRED1': [[{'transcript': 'NM_152594.3',
    'protein_id': 'NP_689807.1',
    'protein_seq': Seq('MSEETATSDNDNSYARVRAVVMTRDDSSGGWLPLGGSGLSSVTVFKVPHQEENG...AAG'),
    'cds_seq': Seq('atgagcgaggagacggcgacttctgacaacgataatagttatgcacgagtgcga...tga'),
    'cds_start': 350,
    'cds_end': 1685}]],
 'SPTA1': [[{'transcript': 'NM_003126.2',
    'protein_id': 'NP_003117.2',
    'protein_seq': Seq('MEQFPKETVVESSGPKVLETAEEIQERRQEVLTRYQSFKERVAERGQKLEDSYH...FGN'),
    'cds_seq': Seq('atggagcaatttccaaaggaaaccgttgtggagagcagtgggccaaaggttttg...taa'),
    'cds_start': 199,
    'cds_end': 7459}],
  [{'transcript': 'NM_003126.4',
    'protein_id': 'NP_003117.2',
    'protein_seq': Seq('MEQFPKETVVESSGPKVLETAEEIQERRQEVLTRYQSFKERVAERGQKLEDSYH...FGN'),
    'cds_seq': Seq('atggagcaatttccaaaggaaaccgttgtggagagcagtgggccaaaggttttg...taa'),
    'cds_start': 198,
    'cds_end': 7458}]],
 'SPTAN1': [[{'transcript': 'NM_001130438.3',
    'protein_id': 'NP_001123910.1',
    'protein_seq': Seq('MDPSGVKVLETAEDIQERRQQVLDRYHRFKELSTLRRQKLEDSYRFQFFQRDAE...FVN'),
    'cds_seq': Seq('atggacccaagtggggtcaaagtgctggaaacagcagaggacatccaggagagg...tga'),
    'cds_start': 113,
    'cds_end': 7547}]],
 'SPTB': [[{'transcript': 'NM_001355436.2',
    'protein_id': 'NP_001342365.1',
    'protein_seq': Seq('MTSATEFENVGNQPPYSRINARWDAPDDELDNDNSSARLFERSRIKALADEREV...KKK'),
    'cds_seq': Seq('atgacatcggccacagagtttgaaaatgtgggcaaccagccaccttacagcagg...tag'),
    'cds_start': 167,
    'cds_end': 7154}]],
 'SRD5A2': [[{'transcript': 'NM_000348.4',
    'protein_id': 'NP_000339.2',
    'protein_seq': Seq('MQVQCQQSPVLAGSATLVALGALALYVAKPSGYGKHTESLKPAATRLPARAAWF...FIF'),
    'cds_seq': Seq('atgcaggttcagtgccagcagagcccagtgctggcaggcagcgccactttggtc...taa'),
    'cds_start': 38,
    'cds_end': 803}]],
 'STAR': [[{'transcript': 'NM_000349.3',
    'protein_id': 'NP_000340.2',
    'protein_seq': Seq('MLLATFKLCAGSSYRHMRNMKGLRQQAVMAISQELNRRALGGPTPSTWINQVRR...ARC'),
    'cds_seq': Seq('atgctgctagcgacattcaagctgtgcgctgggagctcctacagacacatgcgc...tga'),
    'cds_start': 134,
    'cds_end': 992}]],
 'STAT1': [[{'transcript': 'NM_007315.4',
    'protein_id': 'NP_009330.1',
    'protein_seq': Seq('MSQWYELQQLDSKFLEQVHQLYDDSFPMEIRQYLAQWLEKQDWEHAANDVSFAT...NTV'),
    'cds_seq': Seq('atgtctcagtggtacgaacttcagcagcttgactcaaaattcctggagcaggtt...tag'),
    'cds_start': 309,
    'cds_end': 2562}]],
 'STAT3': [[{'transcript': 'NM_139276.3',
    'protein_id': 'NP_644805.1',
    'protein_seq': Seq('MAQWNQLQQLDTRYLEQLHQLYSDSFPMELRQFLAPWIESQDWAYAASKESHAT...SPM'),
    'cds_seq': Seq('atggcccaatggaatcagctacagcagcttgacacacggtacctggagcagctc...tga'),
    'cds_start': 187,
    'cds_end': 2500}]],
 'STK11': [[{'transcript': 'NM_000455.5',
    'protein_id': 'NP_000446.1',
    'protein_seq': Seq('MEVVDPQQLGMFTEGELMSVGMDTFIHRIDSTEVIYQPRRKRAKLIGKYLMGDL...KQQ'),
    'cds_seq': Seq('atggaggtggtggacccgcagcagctgggcatgttcacggagggcgagctgatg...tga'),
    'cds_start': 1136,
    'cds_end': 2438}]],
 'STXBP1': [[{'transcript': 'NM_001032221.6',
    'protein_id': 'NP_001027392.1',
    'protein_seq': Seq('MAPIGLKAVVGEKIMHDVIKKVKKKGEWKVLVVDQLSMRMLSSCCKMTDIMTEG...ISS'),
    'cds_seq': Seq('atggcccccattggcctcaaagctgttgtcggagagaagattatgcatgatgtg...taa'),
    'cds_start': 127,
    'cds_end': 1912}],
  [{'transcript': 'NM_003165.6',
    'protein_id': 'NP_003156.1',
    'protein_seq': Seq('MAPIGLKAVVGEKIMHDVIKKVKKKGEWKVLVVDQLSMRMLSSCCKMTDIMTEG...TME'),
    'cds_seq': Seq('atggcccccattggcctcaaagctgttgtcggagagaagattatgcatgatgtg...tga'),
    'cds_start': 127,
    'cds_end': 1939}]],
 'STXBP2': [[{'transcript': 'NM_006949.4',
    'protein_id': 'NP_008880.2',
    'protein_seq': Seq('MAPSGLKAVVGEKILSGVIRSVKKDGEWKVLIMDHPSMRILSSCCKMSDILAEG...ALP'),
    'cds_seq': Seq('atggcgccctcggggctgaaggcggtggtgggggaaaaaattctgagcggagtt...tga'),
    'cds_start': 40,
    'cds_end': 1822}]],
 'SUFU': [[{'transcript': 'NM_016169.4',
    'protein_id': 'NP_057253.2',
    'protein_seq': Seq('MAELRPSGAPGPTAPPAPGPTAPPAFASLFPPGLHAIYGECRRLYPDQPNPLQV...PLH'),
    'cds_seq': Seq('atggcggagctgcggcctagcggcgcccccggccccaccgcgcccccggcccct...tag'),
    'cds_start': 181,
    'cds_end': 1636}]],
 'SUMF1': [[{'transcript': 'NM_182760.4',
    'protein_id': 'NP_877437.2',
    'protein_seq': Seq('MAAPALGLVCGRCPELGLVLLLLLLSLLCGAAGSQEAGTGAGAGSLAGSCGCGT...TMD'),
    'cds_seq': Seq('atggctgcgcccgcactagggctggtgtgtggacgttgccctgagctgggtctc...tga'),
    'cds_start': 24,
    'cds_end': 1149}]],
 'SURF1': [[{'transcript': 'NM_003172.4',
    'protein_id': 'NP_003163.1',
    'protein_seq': Seq('MAAVAALQLGLRAAGLGRAPASAAWRSVLRVSPRPGVAWRPSRCGSSAAEASAT...PGV'),
    'cds_seq': Seq('atggcggcggtggctgcgttgcagctggggctgcgggcggcggggctgggacgg...tga'),
    'cds_start': 34,
    'cds_end': 937}]],
 'SYNE1': [[{'transcript': 'NM_001347702.2',
    'protein_id': 'NP_001334631.1',
    'protein_seq': Seq('MVVAEDLSALRMAEDSCVDADLPDCNCDVTRVKKLKETLVAVQQLDKNMSSLRT...PPL'),
    'cds_seq': Seq('atggtggtggcggaggacctgagtgccctgaggatggcagaggacagctgtgtg...tga'),
    'cds_start': 108,
    'cds_end': 3036}],
  [{'transcript': 'NM_182961.4',
    'protein_id': 'NP_892006.3',
    'protein_seq': Seq('MATSRGASRCPRDIANVMQRLQDEQEIVQKRTFTKWINSHLAKRKPPMVVDDLF...PPL'),
    'cds_seq': Seq('atggcaacctccagaggggcctcccggtgtcctcgggatatcgccaatgtgatg...tga'),
    'cds_start': 565,
    'cds_end': 26959}]],
 'SYNGAP1': [[{'transcript': 'NM_006772.3',
    'protein_id': 'NP_006763.2',
    'protein_seq': Seq('MSRSRASIHRGSIPAMSYAPFRDVRGPSMHRTQYVHSPYDRPGWNPRFCIISGN...ADH'),
    'cds_seq': Seq('atgagcaggtctcgagcctccatccatcgggggagcatccccgcgatgtcctat...tag'),
    'cds_start': 200,
    'cds_end': 4232}]],
 'SZT2': [[{'transcript': 'NM_001365999.1',
    'protein_id': 'NP_001352928.1',
    'protein_seq': Seq('MASERPEPEVEEAGQVFLLMKKDYRISRNVRLAWFLSHLHQTVQATPQEMLLQS...RLL'),
    'cds_seq': Seq('atggcctcggagcgcccggagccggaggtggaagaagctgggcaggtgttcctg...tga'),
    'cds_start': 70,
    'cds_end': 10369}]],
 'TAFAZZIN': [[{'transcript': 'NM_000116.5',
    'protein_id': 'NP_000107.1',
    'protein_seq': Seq('MPLHVKWPFPAVPPLTWTLASSVVMGLVGTYSCFWTKYMNHLTVHNREVLYELI...PGR'),
    'cds_seq': Seq('atgcctctgcacgtgaagtggccgttccccgcggtgccgccgctcacctggacc...tag'),
    'cds_start': 305,
    'cds_end': 1184}]],
 'TAOK1': [[{'transcript': 'NM_020791.4',
    'protein_id': 'NP_065842.1',
    'protein_seq': Seq('MPSTNRAGSLKDPEIAELFFKEDPEKLFTDLREIGHGSFGAVYFARDVRTNEVV...SYT'),
    'cds_seq': Seq('atgccatcaactaacagagcaggcagcctgaaggaccctgaaattgcagagctc...taa'),
    'cds_start': 756,
    'cds_end': 3762}]],
 'TBC1D24': [[{'transcript': 'NM_001199107.2',
    'protein_id': 'NP_001186036.1',
    'protein_seq': Seq('MDSPGYNCFVDKDKMDAAIQDLGPKELSCTELQELKQLARQGYWAQSHALRGKV...DTQ'),
    'cds_seq': Seq('atggactctccaggatacaactgcttcgtggacaaagacaagatggacgctgcc...tga'),
    'cds_start': 159,
    'cds_end': 1839}]],
 'TBCD': [[{'transcript': 'NM_005993.5',
    'protein_id': 'NP_005984.3',
    'protein_seq': Seq('MALSDEPAAGGPEEEAEDETLAFGAALEAFGESAETRALLGRLREVHGGGAERE...GAC'),
    'cds_seq': Seq('atggccctgagcgacgaaccggccgcgggcggccccgaggaggaggcggaggac...tga'),
    'cds_start': 129,
    'cds_end': 3708}]],
 'TBCK': [[{'transcript': 'NM_001163435.3',
    'protein_id': 'NP_001156907.2',
    'protein_seq': Seq('MFPLKDAEMGAFTFFASALPHDVCGSNGLPLTPNSIKILGRFQILKTITHPRLC...PQI'),
    'cds_seq': Seq('atgtttcccctgaaggacgctgaaatgggagcctttaccttctttgcctcggct...tga'),
    'cds_start': 308,
    'cds_end': 2990}]],
 'TBL1XR1': [[{'transcript': 'NM_024665.7',
    'protein_id': 'NP_078941.2',
    'protein_seq': Seq('MSISSDEVNFLVYRYLQESGFSHSAFTFGIESHISQSNINGALVPPAALISIIQ...LRK'),
    'cds_seq': Seq('atgagtataagcagtgatgaggtcaacttcttggtatatagatacttgcaagag...tag'),
    'cds_start': 483,
    'cds_end': 2028}]],
 'TBX5': [[{'transcript': 'NM_181486.4',
    'protein_id': 'NP_852259.1',
    'protein_seq': Seq('MADADEGFGLAHTPLEPDAKDLPCDSKPESALGAPSKSPSSPQAAFTQQGMEGI...DNS'),
    'cds_seq': Seq('atggccgacgcagacgagggctttggcctggcgcacacgcctctggagcctgac...taa'),
    'cds_start': 555,
    'cds_end': 2112}]],
 'TCF12': [[{'transcript': 'NM_207037.2',
    'protein_id': 'NP_996920.1',
    'protein_seq': Seq('MNPQQQRMAAIGTDKELSDLLDFSAMFSPPVNSGKTRPTTLGSSQFSGSGIDER...GHM'),
    'cds_seq': Seq('atgaatccccagcaacaacgcatggccgctatagggaccgacaaggagctgagc...taa'),
    'cds_start': 285,
    'cds_end': 2406}]],
 'TCF20': [[{'transcript': 'NM_001378418.1',
    'protein_id': 'NP_001365347.1',
    'protein_seq': Seq('MQSFREQSSYHGNQQSYPQEVHGSSRLEEFSPRQAQMFQNFGGTGGSSGSSGSG...ERG'),
    'cds_seq': Seq('atgcagtcctttcgggagcaaagcagttaccacggaaaccagcaaagctaccca...tga'),
    'cds_start': 351,
    'cds_end': 6234}]],
 'TCF4': [[{'transcript': 'NM_001083962.2',
    'protein_id': 'NP_001077431.1',
    'protein_seq': Seq('MHHQQRMAALGTDKELSDLLDFSAMFSPPVSSGKNGPTSLASGHFTGSNVEDRS...GQM'),
    'cds_seq': Seq('atgcatcaccaacagcgaatggctgccttagggacggacaaagagctgagtgat...taa'),
    'cds_start': 175,
    'cds_end': 2191}],
  [{'transcript': 'NM_001243226.3',
    'protein_id': 'NP_001230155.2',
    'protein_seq': Seq('MFSKRLEKIPQVPLLFPFIFIILTNYSKMEGAVESQPSFFKTSQDIVTCTWVEN...GQM'),
    'cds_seq': Seq('atgttttctaaaaggctggagaaaataccacaggtgcctctcctctttcccttc...taa'),
    'cds_start': 60,
    'cds_end': 2382}]],
 'TCIRG1': [[{'transcript': 'NM_006019.4',
    'protein_id': 'NP_006010.2',
    'protein_seq': Seq('MGSMFRSEEVALVQLFLPTAAAYTCVSRLGELGLVEFRDLNASVSAFQRRFVVD...TDD'),
    'cds_seq': Seq('atgggctccatgttccggagcgaggaggtggccctggtccagctctttctgccc...tag'),
    'cds_start': 99,
    'cds_end': 2592}]],
 'TCOF1': [[{'transcript': 'NM_001371623.1',
    'protein_id': 'NP_001358552.1',
    'protein_seq': Seq('MAEARKRRELLPLIYHHLLRAGYVRAAREVKEQSGQKCFLAQPVTLLDIYTHWQ...QTV'),
    'cds_seq': Seq('atggccgaggccaggaagcggcgggagctacttcccctgatctaccaccatctg...tga'),
    'cds_start': 50,
    'cds_end': 4520}]],
 'TECPR2': [[{'transcript': 'NM_014844.5',
    'protein_id': 'NP_055659.2',
    'protein_seq': Seq('MASISEPVTFREFCPLYYLLNAIPTKIQKGFRSIVVYLTALDTNGDYIAVGSSI...EVI'),
    'cds_seq': Seq('atggcatcgatatcagagcctgttacattcagagagttctgcccgttgtactat...tga'),
    'cds_start': 248,
    'cds_end': 4484}]],
 'TECTA': [[{'transcript': 'NM_005422.4',
    'protein_id': 'NP_005413.2',
    'protein_seq': Seq('MNYSSFLRIWVSFIFALVQHQAQPRELMYPFWQNDTKTPKVDDGSSSEIKLAIP...TTS'),
    'cds_seq': Seq('atgaattattcatcattccttagaatttgggtctctttcatcttcgcacttgta...taa'),
    'cds_start': 201,
    'cds_end': 6669}]],
 'TERT': [[{'transcript': 'NM_198253.3',
    'protein_id': 'NP_937983.2',
    'protein_seq': Seq('MPRAPRCRAVRSLLRSHYREVLPLATFVRRLGPQGWRLVQRGDPAAFRALVAQC...ILD'),
    'cds_seq': Seq('atgccgcgcgctccccgctgccgagccgtgcgctccctgctgcgcagccactac...tga'),
    'cds_start': 79,
    'cds_end': 3478}]],
 'TET2': [[{'transcript': 'NM_001127208.3',
    'protein_id': 'NP_001120680.1',
    'protein_seq': Seq('MEQDRTNHVEGNRLSPFLIPSPPICQTEPLATKLQNGSPLPERAHPEVNGDTKW...RYI'),
    'cds_seq': Seq('atggaacaggatagaaccaaccatgttgagggcaacagactaagtccattcctg...tga'),
    'cds_start': 296,
    'cds_end': 6305}]],
 'TFR2': [[{'transcript': 'NM_003227.4',
    'protein_id': 'NP_003218.2',
    'protein_seq': Seq('MERLWGLFQRAQQLSPRSSQTVYQRVEGPRKGHLEEEEEDGEEGAETLAHFCPM...NNF'),
    'cds_seq': Seq('atggagcggctttggggtctattccagagagcgcaacaactgtccccaagatcc...tga'),
    'cds_start': 43,
    'cds_end': 2449}]],
 'TG': [[{'transcript': 'NM_003235.5',
    'protein_id': 'NP_003226.4',
    'protein_seq': Seq('MALVLEIFTLLASICWVSANIFEYQVDAQPLRPCELQRETAFLKQADYVPQCAE...YSK'),
    'cds_seq': Seq('atggccctggtcctggagatcttcaccctgctggcctccatctgctgggtgtcg...tga'),
    'cds_start': 43,
    'cds_end': 8350}]],
 'TGFB2': [[{'transcript': 'NM_003238.6',
    'protein_id': 'NP_003229.1',
    'protein_seq': Seq('MHYCVLSAFLILHLVTVALSLSTCSTLDMDQFMRKRIEAIRGQILSKLKLTSPP...KCS'),
    'cds_seq': Seq('atgcactactgtgtgctgagcgcttttctgatcctgcatctggtcacggtcgcg...taa'),
    'cds_start': 1366,
    'cds_end': 2611}]],
 'TGFBR1': [[{'transcript': 'NM_004612.4',
    'protein_id': 'NP_004603.1',
    'protein_seq': Seq('MEAAVAAPRPRLLLLVLAAAAAAAAALLPGATALQCFCHLCTKDNFTCVTDGLC...IKM'),
    'cds_seq': Seq('atggaggcggcggtcgctgctccgcgtccccggctgctcctcctcgtgctggcg...taa'),
    'cds_start': 93,
    'cds_end': 1605}]],
 'TGFBR2': [[{'transcript': 'NM_003242.6',
    'protein_id': 'NP_003233.4',
    'protein_seq': Seq('MGRGLLRGLWPLHIVLWTRIASTIPPHVQKSVNNDMIVTDNNGAVKFPQLCKFC...TTK'),
    'cds_seq': Seq('atgggtcgggggctgctcaggggcctgtggccgctgcacatcgtcctgtggacg...tag'),
    'cds_start': 283,
    'cds_end': 1987}]],
 'TGM1': [[{'transcript': 'NM_000359.3',
    'protein_id': 'NP_000350.1',
    'protein_seq': Seq('MMDGPRSDVGRWGGNPLQPPTTPSPEPEPEPDGRSRRGGGRSFWARCCGCCSCR...GGA'),
    'cds_seq': Seq('atgatggatgggccacgttccgatgtgggccgttggggtggcaaccccttgcag...tag'),
    'cds_start': 91,
    'cds_end': 2545}]],
 'TH': [[{'transcript': 'NM_000360.4',
    'protein_id': 'NP_000351.2',
    'protein_seq': Seq('MPTPDATTPQAKGFRRAVSELDAKQAEAIMSPRFIGRRQSLIEDARKEREAAVA...AIG'),
    'cds_seq': Seq('atgcccacccccgacgccaccacgccacaggccaagggcttccgcagggccgtg...tag'),
    'cds_start': 29,
    'cds_end': 1523}],
  [{'transcript': 'NM_199292.3',
    'protein_id': 'NP_954986.2',
    'protein_seq': Seq('MPTPDATTPQAKGFRRAVSELDAKQAEAIMVRGQGAPGPSLTGSPWPGTAAPAA...AIG'),
    'cds_seq': Seq('atgcccacccccgacgccaccacgccacaggccaagggcttccgcagggccgtg...tag'),
    'cds_start': 29,
    'cds_end': 1616}]],
 'THRB': [[{'transcript': 'NM_001354712.2',
    'protein_id': 'NP_001341641.1',
    'protein_seq': Seq('MTPNSMTENGLTAWDKPKHCPDREHDWKLVGMSEACLHRKSHSERRSTLKNEQS...FED'),
    'cds_seq': Seq('atgactcccaacagtatgacagaaaatggccttacagcctgggacaaaccgaag...tag'),
    'cds_start': 459,
    'cds_end': 1845}]],
 'TJP2': [[{'transcript': 'NM_004817.4',
    'protein_id': 'NP_004808.2',
    'protein_seq': Seq('MPVRGDRGFPPRRELSGWLRAPGMEELIWEQYTVTLQKDSKRGFGIAVSGGRDN...TEL'),
    'cds_seq': Seq('atgccggtgcgaggagaccgcgggtttccaccccggcgggagctgtcaggttgg...tag'),
    'cds_start': 96,
    'cds_end': 3669}]],
 'TK2': [[{'transcript': 'NM_004614.5',
    'protein_id': 'NP_004605.4',
    'protein_seq': Seq('MLLWPLRGWAARALRCFGPGSRGSPASGPGPRRVQRRAWPPDKEQEKEKKSVIC...HCP'),
    'cds_seq': Seq('atgctgctgtggccgctgcggggctgggccgcccgggcgctgcgctgctttggg...tag'),
    'cds_start': 61,
    'cds_end': 859}]],
 'TLK2': [[{'transcript': 'NM_006852.6',
    'protein_id': 'NP_006843.2',
    'protein_seq': Seq('MMEELHSLDPRRQELLEARFTGVGVSKGPLNSESSNQSLCSVGSLSDKEVETPE...SSN'),
    'cds_seq': Seq('atgatggaagaattgcatagcctggacccacgacggcaggaattattggaggcc...tga'),
    'cds_start': 471,
    'cds_end': 2724}]],
 'TMC1': [[{'transcript': 'NM_138691.3',
    'protein_id': 'NP_619636.2',
    'protein_seq': Seq('MSPKKVQIKVEEKEDETEESSSEEEEEVEDKLPRRESLRPKRKRTRDVINEDDP...GRQ'),
    'cds_seq': Seq('atgtcacccaaaaaagtacaaatcaaagtggaggaaaaagaagacgagactgag...taa'),
    'cds_start': 733,
    'cds_end': 3016}]],
 'TMEM67': [[{'transcript': 'NM_153704.6',
    'protein_id': 'NP_714915.3',
    'protein_seq': Seq('MATRGGAGVAMAVWSLLSARAVTAFLLLFLPRFLQAQTFSFPFQQPEKCDNNQY...FLI'),
    'cds_seq': Seq('atggcgacgcgcggtggggctggggtggcaatggcggtttggtccctcttatcc...taa'),
    'cds_start': 21,
    'cds_end': 3009}]],
 'TMPRSS3': [[{'transcript': 'NM_001256317.3',
    'protein_id': 'NP_001243246.1',
    'protein_seq': Seq('MGENDPPAVEAPFSFRSLFGLDDLKISPVAPDADAVAAQILSLLPLKFFPIIVI...LKT'),
    'cds_seq': Seq('atgggggaaaatgatccgcctgctgttgaagcccccttctcattccgatcgctt...tga'),
    'cds_start': 162,
    'cds_end': 1524}]],
 'TNNI3': [[{'transcript': 'NM_000363.5',
    'protein_id': 'NP_000354.4',
    'protein_seq': Seq('MADGSSDAAREPRPAPAPIRRRSSNYRAYATEPHAKKKSKISASRKLQLKTLLL...FES'),
    'cds_seq': Seq('atggcggatgggagcagcgatgcggctagggaacctcgccctgcaccagcccca...tga'),
    'cds_start': 143,
    'cds_end': 776}]],
 'TNNT2': [[{'transcript': 'NM_001276345.2',
    'protein_id': 'NP_001263274.1',
    'protein_seq': Seq('MSDIEEVVEEYEEEEQEEAAVEEEEDWREDEDEQEEAAEEDAEAEAETEETRAE...RWK'),
    'cds_seq': Seq('atgtctgacatagaagaggtggtggaagagtacgaggaggaggagcaggaagaa...tag'),
    'cds_start': 72,
    'cds_end': 969}]],
 'TNXB': [[{'transcript': 'NM_001365276.2',
    'protein_id': 'NP_001352205.1',
    'protein_seq': Seq('MMPAQYALTSSLVLLVLLSTARAGPFSSRSNVTLPAPRPPPQPGGHTVGAGVGS...GGG'),
    'cds_seq': Seq('atgatgccagcccagtatgctctaacctccagcctggttctcctggtgctgctg...tga'),
    'cds_start': 166,
    'cds_end': 12901}]],
 'TP53': [[{'transcript': 'NM_000546.6',
    'protein_id': 'NP_000537.3',
    'protein_seq': Seq('MEEPQSDPSVEPPLSQETFSDLWKLLPENNVLSPLPSQAMDDLMLSPDDIEQWF...DSD'),
    'cds_seq': Seq('atggaggagccgcagtcagatcctagcgtcgagccccctctgagtcaggaaaca...tga'),
    'cds_start': 142,
    'cds_end': 1324}]],
 'TP63': [[{'transcript': 'NM_001114980.2',
    'protein_id': 'NP_001108452.1',
    'protein_seq': Seq('MLYLENNAQTQFSEPQYTNLGLLNSMDQQIQNGSSSTSPYNTDHAQNSVTAPSP...EGE'),
    'cds_seq': Seq('atgttgtacctggaaaacaatgcccagactcaatttagtgagccacagtacacg...tga'),
    'cds_start': 142,
    'cds_end': 1903}],
  [{'transcript': 'NM_003722.5',
    'protein_id': 'NP_003713.3',
    'protein_seq': Seq('MNFETSRCATLQYCPDPYIQRFVETPAHFSWKESYYRSTMSQSTQTNEFLSPEV...EGE'),
    'cds_seq': Seq('atgaattttgaaacttcacggtgtgccaccctacagtactgccctgacccttac...tga'),
    'cds_start': 127,
    'cds_end': 2170}]],
 'TPM1': [[{'transcript': 'NM_001018005.2',
    'protein_id': 'NP_001018005.1',
    'protein_seq': Seq('MDAIKKKMQMLKLDKENALDRAEQAEADKKAAEDRSKQLEDELVSLQKKLKGTE...TSI'),
    'cds_seq': Seq('atggacgccatcaagaagaagatgcagatgctgaagctcgacaaggagaacgcc...taa'),
    'cds_start': 83,
    'cds_end': 938}]],
 'TPO': [[{'transcript': 'NM_001206744.2',
    'protein_id': 'NP_001193673.1',
    'protein_seq': Seq('MRALAVLSVTLVMACTEAFFPFISRGKELLWGKPEESRVSSVLEESKRLVDTAM...RAL'),
    'cds_seq': Seq('atgagagcgctcgctgtgctgtctgtcacgctggttatggcctgcacagaagcc...tga'),
    'cds_start': 84,
    'cds_end': 2886}]],
 'TPP1': [[{'transcript': 'NM_000391.4',
    'protein_id': 'NP_000382.3',
    'protein_seq': Seq('MGLQACLLGLFALILSGKCSYSPEPDQRRTLPPGWVSLGRADPEEELSLTFALR...LNP'),
    'cds_seq': Seq('atgggactccaagcctgcctcctagggctctttgccctcatcctctctggcaaa...tga'),
    'cds_start': 22,
    'cds_end': 1714}]],
 'TRIM37': [[{'transcript': 'NM_001005207.5',
    'protein_id': 'NP_001005207.1',
    'protein_seq': Seq('MDEQSVESIAEVFRCFICMEKLRDARLCPHCSKLCCFSCIRRWLTEQRAQCPHC...SGR'),
    'cds_seq': Seq('atggatgaacagagcgtggagagcattgctgaggttttccgatgtttcatttgt...taa'),
    'cds_start': 419,
    'cds_end': 3314}],
  [{'transcript': 'NM_015294.6',
    'protein_id': 'NP_056109.1',
    'protein_seq': Seq('MDEQSVESIAEVFRCFICMEKLRDARLCPHCSKLCCFSCIRRWLTEQRAQCPHC...SGR'),
    'cds_seq': Seq('atggatgaacagagcgtggagagcattgctgaggttttccgatgtttcatttgt...taa'),
    'cds_start': 419,
    'cds_end': 3314}]],
 'TRIO': [[{'transcript': 'NM_007118.4',
    'protein_id': 'NP_009049.2',
    'protein_seq': Seq('MSGSSGGAAAPAASSGPAAAASAAGSGCGGGAGEGAEEAAKDLADIAAFFRSGF...PRV'),
    'cds_seq': Seq('atgagcggcagcagcggcggagccgccgcccccgccgcgtcctccggccccgcc...tga'),
    'cds_start': 384,
    'cds_end': 9678}]],
 'TRIOBP': [[{'transcript': 'NM_001039141.3',
    'protein_id': 'NP_001034230.1',
    'protein_seq': Seq('MEEVPGDALCEHFEANILTQNRCQNCFHPEEAHGARYQELRSPSGAEVPYCDLP...LAE'),
    'cds_seq': Seq('atggaggaggtgcctggggatgccctgtgtgaacactttgaggccaacatactt...tag'),
    'cds_start': 211,
    'cds_end': 7309}]],
 'TRMU': [[{'transcript': 'NM_018006.5',
    'protein_id': 'NP_060476.2',
    'protein_seq': Seq('MQALRHVVCALSGGVDSAVAALLLRRRGYQVTGVFMKNWDSLDEHGVCTADKDC...PLL'),
    'cds_seq': Seq('atgcaggccttgcggcacgtcgtgtgcgccctgtccggcggcgtggacagcgcc...tga'),
    'cds_start': 51,
    'cds_end': 1317}]],
 'TRPM1': [[{'transcript': 'NM_001252024.2',
    'protein_id': 'NP_001238953.1',
    'protein_seq': Seq('MGQKSWIEKTFCKRECIFVIPSMKDSNRCCCGQFTNQHIPPLPSATPSKNEEES...TEC'),
    'cds_seq': Seq('atgggtcagaaatcttggatagagaaaaccttttgcaaacgggaatgtatcttt...tag'),
    'cds_start': 152,
    'cds_end': 5030}]],
 'TRPS1': [[{'transcript': 'NM_014112.5',
    'protein_id': 'NP_054831.2',
    'protein_seq': Seq('MPYEVNAGYDFTNMVRKKNPPLRNVASEGEGQILEPIGTESKVSGKNKEFSADQ...PKE'),
    'cds_seq': Seq('atgccttatgaagtcaatgctgggtatgattttacaaatatggtccggaaaaag...taa'),
    'cds_start': 552,
    'cds_end': 4437}]],
 'TRPV4': [[{'transcript': 'NM_021625.5',
    'protein_id': 'NP_067638.3',
    'protein_seq': Seq('MADSSEGPRAGPGEVAELPGDESGTPGGEAFPLSSLANLFEGEDGSLSPSPADA...APL'),
    'cds_seq': Seq('atggcggattccagcgaaggcccccgcgcggggcccggggaggtggctgagctc...tag'),
    'cds_start': 80,
    'cds_end': 2696}]],
 'TSC1': [[{'transcript': 'NM_000368.5',
    'protein_id': 'NP_000359.1',
    'protein_seq': Seq('MAQQANVGELLAMLDSPMLGVRDDVTAVFKENLNSDRGPMLVNTLVDYYLETSS...EHS'),
    'cds_seq': Seq('atggcccaacaagcaaatgtcggggagcttcttgccatgctggactcccccatg...taa'),
    'cds_start': 217,
    'cds_end': 3712}]],
 'TSC2': [[{'transcript': 'NM_000548.5',
    'protein_id': 'NP_000539.2',
    'protein_seq': Seq('MAKPTSKDSGLKEKFKILLGLGTPRPNPRSAEGKQTEFIITAEILRELSMECGL...EFV'),
    'cds_seq': Seq('atggccaaaccaacaagcaaagattcaggcttgaaggagaagtttaagattctg...tga'),
    'cds_start': 110,
    'cds_end': 5534}]],
 'TSHR': [[{'transcript': 'NM_000369.5',
    'protein_id': 'NP_000360.2',
    'protein_seq': Seq('MRPADLLQLVLLLDLPRDLGGMGCSSPPCECHQEEDFRVTCKDIQRIPSLPPST...TVL'),
    'cds_seq': Seq('atgaggccggcggacttgctgcagctggtgctgctgctcgacctgcccagggac...taa'),
    'cds_start': 60,
    'cds_end': 2355}]],
 'TTC21B': [[{'transcript': 'NM_024753.5',
    'protein_id': 'NP_079029.3',
    'protein_seq': Seq('MDSQELKTLINYYCQERYFHHVLLVASEGIKRYGSDPVFRFYHAYGTLMEGKTQ...LRP'),
    'cds_seq': Seq('atggactcgcaggaattgaagactttgattaattactattgtcaagagagatat...tga'),
    'cds_start': 71,
    'cds_end': 4022}]],
 'TTC7A': [[{'transcript': 'NM_020458.4',
    'protein_id': 'NP_065191.2',
    'protein_seq': Seq('MAAKGAHGSYLKVESELERCRAEGHWDRMPELVRQLQTLSMPGGGGNRRGSPSA...REL'),
    'cds_seq': Seq('atggctgcgaagggcgcgcacggctcctacctgaaggtggagagcgagctggag...tga'),
    'cds_start': 318,
    'cds_end': 2895}]],
 'TTLL5': [[{'transcript': 'NM_015072.5',
    'protein_id': 'NP_055887.3',
    'protein_seq': Seq('MPIVMARDLEETASSSEDEEVISQEDHPCIMWTGGCRRIPVLVFHADAILTKDN...TKI'),
    'cds_seq': Seq('atgccaatcgtgatggcccgggacctggaggaaacagcatcatcctcagaggat...tga'),
    'cds_start': 237,
    'cds_end': 4083}]],
 'TTN': [[{'transcript': 'NM_001267550.1',
    'protein_id': 'NP_001254479.1',
    'protein_seq': Seq('MTTQAPTFTQPLQSVVVLEGSTATFEAHISGFPVPEVSWFRDGQVISTSTLPGV...RSI'),
    'cds_seq': Seq('atgacaactcaagcaccgacgtttacgcagccgttacaaagcgttgtggtactg...taa'),
    'cds_start': 225,
    'cds_end': 108201}],
  [{'transcript': 'NM_001267550.2',
    'protein_id': 'NP_001254479.2',
    'protein_seq': Seq('MTTQAPTFTQPLQSVVVLEGSTATFEAHISGFPVPEVSWFRDGQVISTSTLPGV...RSI'),
    'cds_seq': Seq('atgacaactcaagcaccgacgtttacgcagccgttacaaagcgttgtggtactg...taa'),
    'cds_start': 225,
    'cds_end': 108201}]],
 'TTR': [[{'transcript': 'NM_000371.4',
    'protein_id': 'NP_000362.1',
    'protein_seq': Seq('MASHRLLLLCLAGLVFVSEAGPTGTGESKCPLMVKVLDAVRGSPAINVAVHVFR...PKE'),
    'cds_seq': Seq('atggcttctcatcgtctgctcctcctctgccttgctggactggtatttgtgtct...tga'),
    'cds_start': 26,
    'cds_end': 470}]],
 'TUBA1A': [[{'transcript': 'NM_006009.4',
    'protein_id': 'NP_006000.2',
    'protein_seq': Seq('MRECISIHVGQAGVQIGNACWELYCLEHGIQPDGQMPSDKTIGGGDDSFNTFFS...EEY'),
    'cds_seq': Seq('atgcgtgagtgcatctccatccacgttggccaggctggtgtccagattggcaat...taa'),
    'cds_start': 101,
    'cds_end': 1457}]],
 'TUBB2B': [[{'transcript': 'NM_178012.5',
    'protein_id': 'NP_821080.1',
    'protein_seq': Seq('MREIVHIQAGQCGNQIGAKFWEVISDEHGIDPTGSYHGDSDLQLERINVYYNEA...DEA'),
    'cds_seq': Seq('atgcgtgagatcgtgcacatccaggcgggccagtgcggcaaccagatcggcgcc...tag'),
    'cds_start': 110,
    'cds_end': 1448}]],
 'TUBB3': [[{'transcript': 'NM_006086.4',
    'protein_id': 'NP_006077.2',
    'protein_seq': Seq('MREIVHIQAGQCGNQIGAKFWEVISDEHGIDPSGNYVGDSDLQLERISVYYNEA...GPK'),
    'cds_seq': Seq('atgagggagatcgtgcacatccaggccggccagtgcggcaaccagatcggggcc...tga'),
    'cds_start': 60,
    'cds_end': 1413}]],
 'TUBGCP6': [[{'transcript': 'NM_020461.4',
    'protein_id': 'NP_065194.3',
    'protein_seq': Seq('MASITQLFDDLCEALLPAAKTHLGQRSVNRKRAKRSLKKVAYNALFTNLFQDET...QDA'),
    'cds_seq': Seq('atggccagcatcacgcagctgttcgacgacctgtgtgaggccctcctgccggct...tga'),
    'cds_start': 564,
    'cds_end': 6024}]],
 'TULP1': [[{'transcript': 'NM_003322.6',
    'protein_id': 'NP_003313.3',
    'protein_seq': Seq('MPLRDETLREVWASDSGHEEESLSPEAPRRPKQRPAPAQRLRKKRTEAPESPCP...ACE'),
    'cds_seq': Seq('atgcctctgcgggatgaaaccctccgagaggtgtgggcctctgacagtgggcat...tga'),
    'cds_start': 38,
    'cds_end': 1667}]],
 'TWIST1': [[{'transcript': 'NM_000474.4',
    'protein_id': 'NP_000465.1',
    'protein_seq': Seq('MMQDVSSSPVSPADDSLSNSEEEPDRQQPPSGKRGGRKRRSSRRSAGGGAGPGG...ASH'),
    'cds_seq': Seq('atgatgcaggacgtgtccagctcgccagtctcgccggccgacgacagcctgagc...tag'),
    'cds_start': 315,
    'cds_end': 924}]],
 'TWNK': [[{'transcript': 'NM_021830.5',
    'protein_id': 'NP_068602.2',
    'protein_seq': Seq('MWVLLRSGYPLRILLPLRGEWMGRRGLPRNLAPGPPRRRYRKETLQALDMPVLP...RSK'),
    'cds_seq': Seq('atgtgggtcctcctccgaagtgggtaccccctccgtatcttgttacccctgcgt...tga'),
    'cds_start': 668,
    'cds_end': 2723}]],
 'TYMP': [[{'transcript': 'NM_001953.5',
    'protein_id': 'NP_001944.1',
    'protein_seq': Seq('MAALMTPGTGAPPAPGDFSGEGSQGLPDPSPEPKQLPELIRMKRDGGRLSEADI...PQQ'),
    'cds_seq': Seq('atggcagccttgatgaccccgggaaccggggccccacccgcgcctggtgacttc...taa'),
    'cds_start': 119,
    'cds_end': 1568}]],
 'TYR': [[{'transcript': 'NM_000372.4',
    'protein_id': 'NP_000363.1',
    'protein_seq': Seq('MLLAVLYCLLWSFQTSAGHFPRACVSSKNLMEKECCPPWSGDRSPCGQLSGRGS...SHL'),
    'cds_seq': Seq('atgctcctggctgttttgtactgcctgctgtggagtttccagacctccgctggc...taa'),
    'cds_start': 82,
    'cds_end': 1672}],
  [{'transcript': 'NM_000372.5',
    'protein_id': 'NP_000363.1',
    'protein_seq': Seq('MLLAVLYCLLWSFQTSAGHFPRACVSSKNLMEKECCPPWSGDRSPCGQLSGRGS...SHL'),
    'cds_seq': Seq('atgctcctggctgttttgtactgcctgctgtggagtttccagacctccgctggc...taa'),
    'cds_start': 79,
    'cds_end': 1669}]],
 'TYRP1': [[{'transcript': 'NM_000550.3',
    'protein_id': 'NP_000541.1',
    'protein_seq': Seq('MSAPKLLSLGCIFFPLLLFQQARAQFPRQCATVEALRSGMCCPDLSPVSGPGTD...SVV'),
    'cds_seq': Seq('atgagtgctcctaaactcctctctctgggctgtatcttcttccccttgctactt...taa'),
    'cds_start': 179,
    'cds_end': 1793}]],
 'UBE3A': [[{'transcript': 'NM_130839.5',
    'protein_id': 'NP_570854.1',
    'protein_seq': Seq('MATACKRSGEPQSDDIEASRMKRAAAKHLIERYYHQLTEGCGNEACTNEFCASC...GML'),
    'cds_seq': Seq('atggccacagcttgtaaaagatcaggagaacctcagtctgacgacattgaagct...taa'),
    'cds_start': 700,
    'cds_end': 3319}]],
 'UBR1': [[{'transcript': 'NM_174916.3',
    'protein_id': 'NP_777576.1',
    'protein_seq': Seq('MADEEAGGTERMEISAELPQTPQRLASWWDQQVDFYTAFLHHLAQLVPEIYFAE...QLL'),
    'cds_seq': Seq('atggcggacgaggaggctggaggtactgagaggatggaaatcagcgcggagtta...tga'),
    'cds_start': 16,
    'cds_end': 5266}]],
 'UMOD': [[{'transcript': 'NM_003361.4',
    'protein_id': 'NP_003352.2',
    'protein_seq': Seq('MGQPSLTWMLMVVVASWFITTAATDTSEARWCSECHSNATCTEDEAVTTCTCQE...TFQ'),
    'cds_seq': Seq('atggggcagccatctctgacttggatgctgatggtggtggtggcctcttggttc...tga'),
    'cds_start': 129,
    'cds_end': 2052}]],
 'UNC13D': [[{'transcript': 'NM_199242.3',
    'protein_id': 'NP_954712.1',
    'protein_seq': Seq('MATLLSHPQQRPPFLRQAIKIRRRRVRDLQDPPPQMAPEIQPPSHHFSPEQRAL...PAP'),
    'cds_seq': Seq('atggcgacactcctctcccatccgcagcagcgccctcccttcttgcgccaggcc...tag'),
    'cds_start': 67,
    'cds_end': 3340}]],
 'UNC80': [[{'transcript': 'NM_001371986.1',
    'protein_id': 'NP_001358915.1',
    'protein_seq': Seq('MVKRKSSEGQEQDGGRGIPLPIQTFLWRQTSAFLRPKLGKQYEASCVSFERVLV...SHV'),
    'cds_seq': Seq('atggtgaagaggaagagctccgagggccaggagcaggacggcggccgcggcatc...taa'),
    'cds_start': 241,
    'cds_end': 10216}]],
 'USH1C': [[{'transcript': 'NM_005709.4',
    'protein_id': 'NP_005700.2',
    'protein_seq': Seq('MDRKVAREFRHKVDFLIENDAEKDYLYDVLRMYHQTMDVAVLVGDLKLVINEPS...TFF'),
    'cds_seq': Seq('atggaccgaaaagtggcccgagaattccggcataaggtggattttctgattgaa...tga'),
    'cds_start': 109,
    'cds_end': 1768}],
  [{'transcript': 'NM_153676.4',
    'protein_id': 'NP_710142.1',
    'protein_seq': Seq('MDRKVAREFRHKVDFLIENDAEKDYLYDVLRMYHQTMDVAVLVGDLKLVINEPS...IHR'),
    'cds_seq': Seq('atggaccgaaaagtggcccgagaattccggcataaggtggattttctgattgaa...tag'),
    'cds_start': 109,
    'cds_end': 2809}]],
 'USH2A': [[{'transcript': 'NM_206933.4',
    'protein_id': 'NP_996816.3',
    'protein_seq': Seq('MNCPVLSLGSGFLFQVIEMLIFAYFASISLTESRGLFPRLENVGAFKKVSIVPT...THL'),
    'cds_seq': Seq('atgaattgcccagttctttcattgggctctggcttcttgtttcaggtcattgaa...taa'),
    'cds_start': 439,
    'cds_end': 16048}]],
 'USP9X': [[{'transcript': 'NM_001039591.3',
    'protein_id': 'NP_001034680.2',
    'protein_seq': Seq('MTATTRGSPVGGNDNQGQAPDGQSQPPLQQNQTSSPDSSNENSPATPPDEQGQG...KDQ'),
    'cds_seq': Seq('atgacagccacgactcgtggctctccggtcggagggaatgacaaccagggccag...tga'),
    'cds_start': 823,
    'cds_end': 8488}]],
 'VCP': [[{'transcript': 'NM_007126.5',
    'protein_id': 'NP_009057.1',
    'protein_seq': Seq('MASGADSKGDDLSTAILKQKNRPNRLIVDEAINEDNSVVSLSQPKMDELQLFRG...LYG'),
    'cds_seq': Seq('atggcttctggagccgattcaaaaggtgatgacctatcaacagccattctcaaa...taa'),
    'cds_start': 272,
    'cds_end': 2693}]],
 'VHL': [[{'transcript': 'NM_000551.4',
    'protein_id': 'NP_000542.1',
    'protein_seq': Seq('MPRRAENWDEAEVGAEEAGVEEYGPEEDGGEESGAEESGPEESGPEELGAEEEM...MGD'),
    'cds_seq': Seq('atgccccggagggcggagaactgggacgaggccgaggtaggcgcggaggaggca...tga'),
    'cds_start': 70,
    'cds_end': 712}]],
 'VPS13A': [[{'transcript': 'NM_033305.3',
    'protein_id': 'NP_150648.2',
    'protein_seq': Seq('MVFESVVVDVLNRFLGDYVVDLDTSQLSLGIWKGAVALKNLQIKENALSQLDVP...PSL'),
    'cds_seq': Seq('atggttttcgagtcggtggtcgtggacgtgttgaaccggttcttgggggactat...tga'),
    'cds_start': 171,
    'cds_end': 9696}]],
 'VPS13B': [[{'transcript': 'NM_017890.5',
    'protein_id': 'NP_060360.3',
    'protein_seq': Seq('MLESYVTPILMSYVNRYIKNLKPSDLQLSLWGGDVVLSKLELKLDVLEQELKLP...GFP'),
    'cds_seq': Seq('atgctggagtcatatgtaactccaattttaatgagctatgtgaatcgctacatc...tga'),
    'cds_start': 103,
    'cds_end': 12172}],
  [{'transcript': 'NM_152564.5',
    'protein_id': 'NP_689777.3',
    'protein_seq': Seq('MLESYVTPILMSYVNRYIKNLKPSDLQLSLWGGDVVLSKLELKLDVLEQELKLP...GFP'),
    'cds_seq': Seq('atgctggagtcatatgtaactccaattttaatgagctatgtgaatcgctacatc...tga'),
    'cds_start': 103,
    'cds_end': 12097}]],
 'VPS13C': [[{'transcript': 'NM_020821.3',
    'protein_id': 'NP_065872.1',
    'protein_seq': Seq('MVLESVVADLLNRFLGDYVENLNKSQLKLGIWGGNVALDNLQIKENALSELDVP...LPS'),
    'cds_seq': Seq('atggtgctggagtcggtggtcgcggacttgctgaaccgcttcctgggggactat...taa'),
    'cds_start': 73,
    'cds_end': 11335}]],
 'VPS13D': [[{'transcript': 'NM_015378.4',
    'protein_id': 'NP_056193.2',
    'protein_seq': Seq('MLEGLVAWVLNTYLGKYVNNLNTDQLSVALLKGAVELENLPLKKDALKELELPF...LDS'),
    'cds_seq': Seq('atgttggaaggccttgtagcctgggttctcaatacctatttgggaaaatatgtc...tga'),
    'cds_start': 167,
    'cds_end': 13334}]],
 'VWF': [[{'transcript': 'NM_000552.5',
    'protein_id': 'NP_000543.3',
    'protein_seq': Seq('MIPARFAGVLLALALILPGTLCAEGTRGRSSTARCSLFGSDFVNTFDGSMYSFA...CSK'),
    'cds_seq': Seq('atgattcctgccagatttgccggggtgctgcttgctctggccctcattttgcca...tga'),
    'cds_start': 250,
    'cds_end': 8692}]],
 'WAS': [[{'transcript': 'NM_000377.3',
    'protein_id': 'NP_000368.1',
    'protein_seq': Seq('MSGGPMGGRPGGRGAPAVQQNIPSTLLQDHENQRLFEMLGRKCLTLATAVVQLY...WDD'),
    'cds_seq': Seq('atgagtgggggcccaatgggaggaaggcccgggggccgaggagcaccagcggtt...tga'),
    'cds_start': 55,
    'cds_end': 1564}]],
 'WDFY3': [[{'transcript': 'NM_014991.6',
    'protein_id': 'NP_055806.2',
    'protein_seq': Seq('MNMVKRIMGRPRQEECSPQDNALGLMHLRRLFTELCHPPRHMTQKEQEEKLYMM...RNC'),
    'cds_seq': Seq('atgaacatggtgaagaggatcatggggcggccgaggcaggaggagtgcagccca...tga'),
    'cds_start': 707,
    'cds_end': 11288}]],
 'WDR19': [[{'transcript': 'NM_025132.4',
    'protein_id': 'NP_079408.3',
    'protein_seq': Seq('MKRIFSLLEKTWLGAPIQFAWQKTSGNYLAVTGADYIVKIFDRHGQKRSEINLP...EEL'),
    'cds_seq': Seq('atgaagcgtattttctcactgctagaaaagacttggcttggcgcaccaatacag...tga'),
    'cds_start': 29,
    'cds_end': 4058}]],
 'WDR45': [[{'transcript': 'NM_001029896.2',
    'protein_id': 'NP_001025067.1',
    'protein_seq': Seq('MTQQPLRGVTSLRFNQDQSCFCCAMETGVRIYNVEPLMEKGHLDHEQVGSMGLV...DDF'),
    'cds_seq': Seq('atgactcaacagccacttcgaggagtgaccagcctgcgtttcaaccaagaccaa...taa'),
    'cds_start': 154,
    'cds_end': 1237}]],
 'WDR62': [[{'transcript': 'NM_001083961.2',
    'protein_id': 'NP_001077430.1',
    'protein_seq': Seq('MAAVGSGGYARNDAGEKLPSVMAGVPARRGQSSPPPAPPICLRRRTRLSTASEE...RGH'),
    'cds_seq': Seq('atggcggccgtagggtccggaggctatgcgcggaacgatgcaggggagaagctg...tga'),
    'cds_start': 75,
    'cds_end': 4647}]],
 'WFS1': [[{'transcript': 'NM_006005.3',
    'protein_id': 'NP_005996.2',
    'protein_seq': Seq('MDSNTAPLGPSCPQPPPAPQPQARSRLNATASLEQERSERPRAPGPQAGPGPGV...SAA'),
    'cds_seq': Seq('atggactccaacactgctccgctgggcccctcctgcccacagcccccgccagca...tga'),
    'cds_start': 170,
    'cds_end': 2843}]],
 'WNT10A': [[{'transcript': 'NM_025216.3',
    'protein_id': 'NP_079492.2',
    'protein_seq': Seq('MGSAHPRPWLRLRPQPQPRPALWVLLFFLLLLAAAMPRSAPNDILDLRLPPEPV...VCK'),
    'cds_seq': Seq('atgggcagcgcccaccctcgcccctggctgcggctccgaccccagccccagccg...tga'),
    'cds_start': 144,
    'cds_end': 1398}]],
 'WRN': [[{'transcript': 'NM_000553.6',
    'protein_id': 'NP_000544.2',
    'protein_seq': Seq('MSEKKLETTAQQRKCPEWMNVQNKRCAVEERKACVRKSVFEDDLPFLEFTGSIV...LFS'),
    'cds_seq': Seq('atgagtgaaaaaaaattggaaacaactgcacagcagcggaaatgtcctgaatgg...taa'),
    'cds_start': 240,
    'cds_end': 4539}]],
 'WT1': [[{'transcript': 'NM_024426.6',
    'protein_id': 'NP_077744.4',
    'protein_seq': Seq('MDFLLLQDPASTCVPEPASQHTLRSGPGCLQQPEQQGVRDPGGIWAKLGAAEAS...LAL'),
    'cds_seq': Seq('ctggacttcctcttgctgcaggacccggcttccacgtgtgtcccggagccggcg...tga'),
    'cds_start': 179,
    'cds_end': 1748}]],
 'WWOX': [[{'transcript': 'NM_016373.4',
    'protein_id': 'NP_057457.1',
    'protein_seq': Seq('MAALRYAGLDDTDSEDELPPGWEERTTKDGWVYYANHTEEKTQWEHPKTGKRKR...QSG'),
    'cds_seq': Seq('atggcagcgctgcgctacgcggggctggacgacacggacagtgaggacgagctg...taa'),
    'cds_start': 125,
    'cds_end': 1370}]],
 'XPC': [[{'transcript': 'NM_004628.5',
    'protein_id': 'NP_004619.3',
    'protein_seq': Seq('MARKRAAGGEPRGRELRSQKSKAKSKARREEEEEDAFEDEKPPKKSLLSKVSQG...EQL'),
    'cds_seq': Seq('atggctcggaaacgcgcggccggcggggagccgcggggacgcgaactgcgcagc...tga'),
    'cds_start': 33,
    'cds_end': 2856}]],
 'ZBTB20': [[{'transcript': 'NM_001348800.3',
    'protein_id': 'NP_001335729.1',
    'protein_seq': Seq('MLERKKPKTAENQKASEENEITQPGGSSAKPGLPCLNFEAVLSPDPALIHSTHS...SDG'),
    'cds_seq': Seq('atgctagaacggaagaaacccaagacagctgaaaaccagaaggcatctgaggag...taa'),
    'cds_start': 772,
    'cds_end': 2998}]],
 'ZEB2': [[{'transcript': 'NM_014795.4',
    'protein_id': 'NP_055610.1',
    'protein_seq': Seq('MKQPIMADGPRCKRRKQANPRRKNVVNYDNVVDTGSETDEEDKLHIAEDDGIAN...DGM'),
    'cds_seq': Seq('atgaagcagccgatcatggcggatggcccccggtgcaagaggcgcaaacaagcc...taa'),
    'cds_start': 250,
    'cds_end': 3895}]],
 'ZFYVE26': [[{'transcript': 'NM_015346.4',
    'protein_id': 'NP_056161.2',
    'protein_seq': Seq('MNHPFGKEEAASQKQLFGFFCECLRRGEWELAQACVPQLQEGQGDIPKRVEDIL...SRK'),
    'cds_seq': Seq('atgaatcatccatttggaaaagaggaagctgcttcgcagaagcagctttttgga...tga'),
    'cds_start': 140,
    'cds_end': 7760}]],
 'ZNF469': [[{'transcript': 'NM_001367624.2',
    'protein_id': 'NP_001354553.1',
    'protein_seq': Seq('MPGERPRGAPPPTMTGDLQPRQVASSPGHPSQPPLEDNTPATRTTKGAREAGGQ...ASE'),
    'cds_seq': Seq('atgcctggggagcgcccccgaggagcgccgccccccaccatgactggagacctg...taa'),
    'cds_start': 487,
    'cds_end': 12349}]]}

In [31]:
import os
#os.makedirs(f"fasta_lociii_rodentia_match", exist_ok=True)
os.getcwd()
os.chdir('/Users/adesinamary/Documents/kondrashov/')

In [ ]:
match= write_best_species_matches(
            gene=gene,
            reference_seq=reference_seq,
            aligner=aligner,
            outfile=f"fasta_lociii_match/{gene}_{protein_id}_match.fasta"
        )
print(match)

In [32]:
#loci = ['ALPL', 'F8', 'F9', 'TYR']
score_record = {}

for gene in locie:

    print(f"\nProcessing {gene}")

    for ref in reference_proteins[gene]:

        transcript = ref[0]["transcript"]
        protein_id = ref[0]["protein_id"]
        reference_seq = ref[0]["protein_seq"]
        prot_length = len(reference_seq)
        print(f"  {transcript} ({protein_id}), {prot_length} amino acids")

        #record_id, species, score = 
        matches= write_best_species_matches(
            gene=gene,
            reference_seq=reference_seq,
            aligner=aligner,
            outfile=f"fasta_lociii_match/{gene}_{protein_id}_match.fasta"
        )
        print(matches)
        
        score_record[gene]= {
            "record": matches
        }

Processing AAAS
  NM_015665.6 (NP_056480.1), 546 amino acids
{'[Homo sapiens]': {'record': SeqRecord(seq=Seq('MCSLGLFPPPPPRGQVTLYEHNNELVTGSSYESPPPDFRGQWINLPVLQLTKDP...SHL'), id='NP_056480.1', name='NP_056480.1', description='NP_056480.1 aladin isoform 1 [Homo sapiens]', dbxrefs=[]), 'score': 1.0}, '[Pan troglodytes]': {'record': SeqRecord(seq=Seq('MCSMGLFPPPPPRGQVTLYEHNNELVTGSSYESPPPDFRGQWINLPVLQLTKDP...SHL'), id='NP_001233360.1', name='NP_001233360.1', description='NP_001233360.1 aladin [Pan troglodytes]', dbxrefs=[]), 'score': 0.9976}, '[Macaca fascicularis]': {'record': SeqRecord(seq=Seq('MCSLGLFPPPPPRGQVTLYEHNNELVTGSSYESPPPDFRGQWINLPVLHLTKDP...SHL'), id='XP_005571057.1', name='XP_005571057.1', description='XP_005571057.1 aladin isoform X1 [Macaca fascicularis]', dbxrefs=[]), 'score': 0.9849}, '[Callithrix jacchus]': {'record': SeqRecord(seq=Seq('MCSLGLFPPPPPRGQVTLYEHNNELVTGSSYESPPPDFRGQWINLPILHLAKDP...SHL'), id='XP_035112532.1', name='XP_035112532.1', description='XP_035112532.1 aladin isoform X1 [Callithrix jacchus]', dbxrefs=[]), 'score': 0.9711}, '[Eulemur rufifrons]': {'record': SeqRecord(seq=Seq('MCSLALFPPPPPRGQVTLYEHNNELVTGNSYESPPPDFRGQWINLPVLHLTKDP...HTQ'), id='XP_069345812.1', name='XP_069345812.1', description='XP_069345812.1 aladin isoform X2 [Eulemur rufifrons]', dbxrefs=[]), 'score': 0.9475}, '[Gorilla gorilla gorilla]': {'record': SeqRecord(seq=Seq('MCSLGLFPPPPPRDQVTLYEHNNELVTGGRYESPPPDFRGQWINLPVLQLTKDP...SHL'), id='XP_055213105.1', name='XP_055213105.1', description='XP_055213105.1 aladin isoform X1 [Gorilla gorilla gorilla]', dbxrefs=[]), 'score': 0.9919}, '[Symphalangus syndactylus]': {'record': SeqRecord(seq=Seq('MCSLGLFPPPPPRGQVTLYEHNNELVTGSSYESPPPDFRGQWINLPVLHLTKDP...SHL'), id='XP_055104476.1', name='XP_055104476.1', description='XP_055104476.1 aladin isoform X1 [Symphalangus syndactylus]', dbxrefs=[]), 'score': 0.9886}, '[Pongo pygmaeus]': {'record': SeqRecord(seq=Seq('MCSLGLFPPPPPRGQVTLYEHNNELVTGSSYESPPPDFRGQWINLPVLHLTKDP...SCL'), id='XP_054299001.1', name='XP_054299001.1', description='XP_054299001.1 aladin isoform X1 [Pongo pygmaeus]', dbxrefs=[]), 'score': 0.9855}, '[Nycticebus coucang]': {'record': SeqRecord(seq=Seq('MCSLGLFPPPPPRGQVTLYEHNNELVTGNSYESPPPDFRGQWINLPVLHLTKDP...PLQ'), id='XP_053410634.1', name='XP_053410634.1', description='XP_053410634.1 aladin isoform X1 [Nycticebus coucang]', dbxrefs=[]), 'score': 0.9384}, '[Macaca thibetana thibetana]': {'record': SeqRecord(seq=Seq('MCSLGLFPPPPPRGQVTLYEHNNELVTGSSYESPPPDFRGQWINLPVLHLTKDP...SHL'), id='XP_050604835.1', name='XP_050604835.1', description='XP_050604835.1 aladin isoform X1 [Macaca thibetana thibetana]', dbxrefs=[]), 'score': 0.9808}, '[Lemur catta]': {'record': SeqRecord(seq=Seq('MCSLALFPLPPPRGQVTLYEHNNELVTGNSYESPPPDFRGQWINLPVLHLTKDP...HIQ'), id='XP_045409832.1', name='XP_045409832.1', description='XP_045409832.1 aladin [Lemur catta]', dbxrefs=[]), 'score': 0.9418}, '[Trachypithecus francoisi]': {'record': SeqRecord(seq=Seq('MCSLGLFPPPPPRGQVTLYEHNNELVTGSSYESPPPDFRGQWINLPVLHLTKDP...SHL'), id='XP_033077807.1', name='XP_033077807.1', description='XP_033077807.1 aladin isoform X2 [Trachypithecus francoisi]', dbxrefs=[]), 'score': 0.9815}, '[Sapajus apella]': {'record': SeqRecord(seq=Seq('MCSLGLFPPPPPRGQVTLYEHNNELVTGSSYESPPPDFRGQWINLPILHLTKDP...SHL'), id='XP_032148505.1', name='XP_032148505.1', description='XP_032148505.1 aladin isoform X1 [Sapajus apella]', dbxrefs=[]), 'score': 0.9765}, '[Hylobates moloch]': {'record': SeqRecord(seq=Seq('MCSLGLFPPPPPRSQVTLYEHNNELVTGSSYESPPPDFRGQWINLPVLHLTKDP...SHL'), id='XP_032029499.1', name='XP_032029499.1', description='XP_032029499.1 aladin isoform X1 [Hylobates moloch]', dbxrefs=[]), 'score': 0.9855}, '[Theropithecus gelada]': {'record': SeqRecord(seq=Seq('MCSLGLFPPPPPRGQVTLYEHNNELVTGSSYESPPPDFRGQVARWINLPVLHLT...SHL'), id='XP_086578366.1', name='XP_086578366.1', description='XP_086578366.1 aladin isoform X3 [Theropithecus gelada]', dbxrefs=[]), 'score': 0.9802}, '[Piliocolobus tephrosceles]': {'record': SeqRecord(seq=Seq('MCSLGLFPPPPPRGQVTLYEHNNELVTGSSYESPPPDFRGQWINLPVLHLTKDP...SHL'), id='XP_026310460.1', name='XP_026310460.1', description='XP_026310460.1 aladin [Piliocolobus tephrosceles]', dbxrefs=[]), 'score': 0.9657}, '[Rhinopithecus bieti]': {'record': SeqRecord(seq=Seq('MCSLGLFPPPPPRGQVTLYEHNNELVTGSSYESPPPDFRGQWINLPVLHLTKDP...SHL'), id='XP_017717028.1', name='XP_017717028.1', description='XP_017717028.1 aladin isoform X2 [Rhinopithecus bieti]', dbxrefs=[]), 'score': 0.9845}, '[Cebus imitator]': {'record': SeqRecord(seq=Seq('MCSLGLFPPPPPRGQVTLYEHNNELVTGSSYESPPPDFRGQWINLPILHLTKDP...SHL'), id='XP_017357257.1', name='XP_017357257.1', description='XP_017357257.1 aladin [Cebus imitator]', dbxrefs=[]), 'score': 0.9724}, '[Microcebus murinus]': {'record': SeqRecord(seq=Seq('MCSLALFPPPPPRGQVTLYEHNNELVTGNSYESPPPDFRGQWINLPVLHLAKDP...HIQ'), id='XP_012619003.1', name='XP_012619003.1', description='XP_012619003.1 aladin isoform X2 [Microcebus murinus]', dbxrefs=[]), 'score': 0.9354}, '[Propithecus coquereli]': {'record': SeqRecord(seq=Seq('MCSLALFPPPPPRGQVTLYEHNNELVTGNSYESPPPDFRGQWINLPVLHLAKDP...HTQ'), id='XP_012505753.1', name='XP_012505753.1', description='XP_012505753.1 PREDICTED: aladin [Propithecus coquereli]', dbxrefs=[]), 'score': 0.8517}, '[Aotus nancymaae]': {'record': SeqRecord(seq=Seq('MCSLGLFPPPPPWGQVTLYEHNNELVTGSSYESPPPDFRGQWINLPILHLTKDP...SHL'), id='XP_012305739.1', name='XP_012305739.1', description='XP_012305739.1 aladin [Aotus nancymaae]', dbxrefs=[]), 'score': 0.9704}, '[Cercocebus atys]': {'record': SeqRecord(seq=Seq('MCSLGLFPPPPPRGQVTLYEHNNELVTGSSYESPPPDFRGQWINLPVLHLTKDP...SHL'), id='XP_011903473.1', name='XP_011903473.1', description='XP_011903473.1 PREDICTED: aladin isoform X1 [Cercocebus atys]', dbxrefs=[]), 'score': 0.9771}, '[Mandrillus leucophaeus]': {'record': SeqRecord(seq=Seq('MCSLGLFPPPPPRGQVTLYEHNNELVTGSSYESPPPDFRGQWINLPVLHLTKDP...SHL'), id='XP_011856967.1', name='XP_011856967.1', description='XP_011856967.1 PREDICTED: aladin isoform X1 [Mandrillus leucophaeus]', dbxrefs=[]), 'score': 0.9812}, '[Colobus angolensis palliatus]': {'record': SeqRecord(seq=Seq('MCSLGLFPPPPPRGQVTLYEHNNELVTGSSYESPPPDFRGQWINLPVLHLTKDP...SHL'), id='XP_011785910.1', name='XP_011785910.1', description='XP_011785910.1 PREDICTED: aladin isoform X1 [Colobus angolensis palliatus]', dbxrefs=[]), 'score': 0.9805}, '[Rhinopithecus roxellana]': {'record': SeqRecord(seq=Seq('MCSLGLFPPPPPRGQVTLYEHNNELVTGSSYESPPPDFRGQWINLPVLHLTKDP...SHL'), id='XP_010372226.2', name='XP_010372226.2', description='XP_010372226.2 aladin [Rhinopithecus roxellana]', dbxrefs=[]), 'score': 0.9855}, '[Carlito syrichta]': {'record': SeqRecord(seq=Seq('MCSLGLFPPPPPRGQVTLYEHNNELVTGNSYESPPPDFRGQWINLPVLHLTKDP...SHL'), id='XP_008047682.1', name='XP_008047682.1', description='XP_008047682.1 aladin isoform X1 [Carlito syrichta]', dbxrefs=[]), 'score': 0.9475}, '[Chlorocebus sabaeus]': {'record': SeqRecord(seq=Seq('MCSLGLFPPPPPRGQVTLYEHNNELVTGSSYESPPPDFRGQWINLPVLHLTKDP...SHL'), id='XP_037852980.1', name='XP_037852980.1', description='XP_037852980.1 aladin isoform X1 [Chlorocebus sabaeus]', dbxrefs=[]), 'score': 0.9812}, '[Saimiri boliviensis]': {'record': SeqRecord(seq=Seq('MCSLGLFPPPPPRDQVTLYEHNNELVTGSSYESPPPDFRGQWINLPILHLTKDP...SHL'), id='XP_003939275.2', name='XP_003939275.2', description='XP_003939275.2 aladin isoform X1 [Saimiri boliviensis]', dbxrefs=[]), 'score': 0.9684}, '[Papio anubis]': {'record': SeqRecord(seq=Seq('MCSLGLFPPPPPQGQVTLYEHNNELVTGSSYESPPPDFRGQWINLPVLHLTKDP...SHL'), id='XP_003906503.2', name='XP_003906503.2', description='XP_003906503.2 aladin isoform X1 [Papio anubis]', dbxrefs=[]), 'score': 0.9835}, '[Pan paniscus]': {'record': SeqRecord(seq=Seq('MCSMGLFPPPPPRGQVTLYEHNNELVTGSSYESPPPDFRGQWINLPVLQLTKDP...SHL'), id='XP_003831067.1', name='XP_003831067.1', description='XP_003831067.1 aladin isoform X2 [Pan paniscus]', dbxrefs=[]), 'score': 0.9956}, '[Otolemur garnettii]': {'record': SeqRecord(seq=Seq('MCSLALFPPPPPRGQVTLYEHNNELVTGNSYESPPPDFRGQWINLPVLHLTKDP...PLQ'), id='XP_003790477.1', name='XP_003790477.1', description='XP_003790477.1 aladin isoform X2 [Otolemur garnettii]', dbxrefs=[]), 'score': 0.9435}, '[Nomascus leucogenys]': {'record': SeqRecord(seq=Seq('MCSLGLFPPPPPRGQVTLYEHNNELVTGSSYESPPPDFRGQWINLPVLHLTKDP...SHL'), id='XP_003252106.1', name='XP_003252106.1', description='XP_003252106.1 aladin isoform X1 [Nomascus leucogenys]', dbxrefs=[]), 'score': 0.9882}, '[Pongo abelii]': {'record': SeqRecord(seq=Seq('MALCQWASSLHGSLFPHLSLRSEDLIAEFAQVTNWSSCCLRVFAWHPHTNKFAV...SCL'), id='XP_054383964.1', name='XP_054383964.1', description='XP_054383964.1 aladin isoform X4 [Pongo abelii]', dbxrefs=[]), 'score': 0.7323}}

Processing ABCA1
  NM_005502.4 (NP_005493.2), 2261 amino acids
{'[Homo sapiens]': {'record': SeqRecord(seq=Seq('MACWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILISVRLSYPPYEQHEC...SYV'), id='NP_005493.2', name='NP_005493.2', description='NP_005493.2 phospholipid-transporting ATPase ABCA1 [Homo sapiens]', dbxrefs=[]), 'score': 1.0}, '[Pan troglodytes]': {'record': SeqRecord(seq=Seq('MACWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILISVRLSYPPYEQHEC...SYV'), id='XP_001138040.1', name='XP_001138040.1', description='XP_001138040.1 phospholipid-transporting ATPase ABCA1 isoform X2 [Pan troglodytes]', dbxrefs=[]), 'score': 0.9971}, '[Macaca mulatta]': {'record': SeqRecord(seq=Seq('MACWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILISVRLSYPPYEQHEC...SYV'), id='XP_014972644.2', name='XP_014972644.2', description='XP_014972644.2 phospholipid-transporting ATPase ABCA1 isoform X2 [Macaca mulatta]', dbxrefs=[]), 'score': 0.9898}, '[Callithrix jacchus]': {'record': SeqRecord(seq=Seq('MACWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILISVRLSYPPYEQHEC...SYV'), id='XP_035109459.3', name='XP_035109459.3', description='XP_035109459.3 phospholipid-transporting ATPase ABCA1 isoform X2 [Callithrix jacchus]', dbxrefs=[]), 'score': 0.9819}, '[Eulemur rufifrons]': {'record': SeqRecord(seq=Seq('MACWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILISVRLSYPPYEQHEC...SYV'), id='XP_069332747.1', name='XP_069332747.1', description='XP_069332747.1 phospholipid-transporting ATPase ABCA1 [Eulemur rufifrons]', dbxrefs=[]), 'score': 0.9652}, '[Symphalangus syndactylus]': {'record': SeqRecord(seq=Seq('MACWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILISVRLSYPPYEQHEC...SYV'), id='XP_055127584.1', name='XP_055127584.1', description='XP_055127584.1 phospholipid-transporting ATPase ABCA1 [Symphalangus syndactylus]', dbxrefs=[]), 'score': 0.9929}, '[Pongo pygmaeus]': {'record': SeqRecord(seq=Seq('MACWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILISVRLSYPPYEQHEC...SYV'), id='XP_054356634.1', name='XP_054356634.1', description='XP_054356634.1 phospholipid-transporting ATPase ABCA1 isoform X2 [Pongo pygmaeus]', dbxrefs=[]), 'score': 0.9886}, '[Nycticebus coucang]': {'record': SeqRecord(seq=Seq('MACWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILISVRLSYPPYEQHEC...SYV'), id='XP_053423052.1', name='XP_053423052.1', description='XP_053423052.1 phospholipid-transporting ATPase ABCA1 isoform X1 [Nycticebus coucang]', dbxrefs=[]), 'score': 0.9617}, '[Macaca thibetana thibetana]': {'record': SeqRecord(seq=Seq('MACWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILISVRLSYPPYEQHEC...SYV'), id='XP_050617797.1', name='XP_050617797.1', description='XP_050617797.1 phospholipid-transporting ATPase ABCA1 isoform X2 [Macaca thibetana thibetana]', dbxrefs=[]), 'score': 0.9903}, '[Lemur catta]': {'record': SeqRecord(seq=Seq('MACWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILISVRLSYPPYEQHEC...SYV'), id='XP_045419793.1', name='XP_045419793.1', description='XP_045419793.1 phospholipid-transporting ATPase ABCA1 [Lemur catta]', dbxrefs=[]), 'score': 0.9669}, '[Trachypithecus francoisi]': {'record': SeqRecord(seq=Seq('MACWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILISVRLSYPPYEQHEC...SYV'), id='XP_033093812.1', name='XP_033093812.1', description='XP_033093812.1 phospholipid-transporting ATPase ABCA1 isoform X2 [Trachypithecus francoisi]', dbxrefs=[]), 'score': 0.9899}, '[Sapajus apella]': {'record': SeqRecord(seq=Seq('MACWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILISVRLSYPPYEQHEC...SYV'), id='XP_032096133.1', name='XP_032096133.1', description='XP_032096133.1 phospholipid-transporting ATPase ABCA1 isoform X2 [Sapajus apella]', dbxrefs=[]), 'score': 0.9819}, '[Hylobates moloch]': {'record': SeqRecord(seq=Seq('MACWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILISVRLSYPPYEQHEC...SYV'), id='XP_032020666.1', name='XP_032020666.1', description='XP_032020666.1 phospholipid-transporting ATPase ABCA1 isoform X1 [Hylobates moloch]', dbxrefs=[]), 'score': 0.9921}, '[Theropithecus gelada]': {'record': SeqRecord(seq=Seq('MACWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILISVRLSYPPYEQHEC...SYV'), id='XP_025214779.1', name='XP_025214779.1', description='XP_025214779.1 phospholipid-transporting ATPase ABCA1 [Theropithecus gelada]', dbxrefs=[]), 'score': 0.9898}, '[Piliocolobus tephrosceles]': {'record': SeqRecord(seq=Seq('MACWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILISVRLSYPPYEQHEC...SYV'), id='XP_023058206.2', name='XP_023058206.2', description='XP_023058206.2 phospholipid-transporting ATPase ABCA1 isoform X2 [Piliocolobus tephrosceles]', dbxrefs=[]), 'score': 0.9897}, '[Rhinopithecus bieti]': {'record': SeqRecord(seq=Seq('MACWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILISVRLSYPPYEQHEC...SYV'), id='XP_017732217.1', name='XP_017732217.1', description='XP_017732217.1 phospholipid-transporting ATPase ABCA1 isoform X2 [Rhinopithecus bieti]', dbxrefs=[]), 'score': 0.9892}, '[Cebus imitator]': {'record': SeqRecord(seq=Seq('MACWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILISVRLSYPPYEQHEC...SYV'), id='XP_017383250.1', name='XP_017383250.1', description='XP_017383250.1 phospholipid-transporting ATPase ABCA1 isoform X2 [Cebus imitator]', dbxrefs=[]), 'score': 0.982}, '[Microcebus murinus]': {'record': SeqRecord(seq=Seq('MACWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILISVRLSYPPYEQHEC...SYV'), id='XP_012592277.2', name='XP_012592277.2', description='XP_012592277.2 phospholipid-transporting ATPase ABCA1 isoform X2 [Microcebus murinus]', dbxrefs=[]), 'score': 0.9613}, '[Propithecus coquereli]': {'record': SeqRecord(seq=Seq('MACWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILLSVRLSYPPYEQHEC...SYV'), id='XP_012493997.1', name='XP_012493997.1', description='XP_012493997.1 PREDICTED: ATP-binding cassette sub-family A member 1 [Propithecus coquereli]', dbxrefs=[]), 'score': 0.9584}, '[Aotus nancymaae]': {'record': SeqRecord(seq=Seq('MAYWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILISVRLSYPPYEQHEC...SYV'), id='XP_064235471.1', name='XP_064235471.1', description='XP_064235471.1 phospholipid-transporting ATPase ABCA1 isoform X2 [Aotus nancymaae]', dbxrefs=[]), 'score': 0.9814}, '[Cercocebus atys]': {'record': SeqRecord(seq=Seq('MACWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILISVRLSYPPYEQHEC...SYV'), id='XP_011946774.1', name='XP_011946774.1', description='XP_011946774.1 PREDICTED: LOW QUALITY PROTEIN: ATP-binding cassette sub-family A member 1 [Cercocebus atys]', dbxrefs=[]), 'score': 0.9745}, '[Mandrillus leucophaeus]': {'record': SeqRecord(seq=Seq('MACWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILISVRLSYPPYEQHEC...LTK'), id='XP_011821789.1', name='XP_011821789.1', description='XP_011821789.1 PREDICTED: ATP-binding cassette sub-family A member 1, partial [Mandrillus leucophaeus]', dbxrefs=[]), 'score': 0.8098}, '[Colobus angolensis palliatus]': {'record': SeqRecord(seq=Seq('MACWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILISVRLNYPPYEQHEC...SYV'), id='XP_011803622.1', name='XP_011803622.1', description='XP_011803622.1 PREDICTED: ATP-binding cassette sub-family A member 1 isoform X1 [Colobus angolensis palliatus]', dbxrefs=[]), 'score': 0.9908}, '[Macaca nemestrina]': {'record': SeqRecord(seq=Seq('MACWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILISVRLSYPPYEQHEC...SYV'), id='XP_011738561.2', name='XP_011738561.2', description='XP_011738561.2 phospholipid-transporting ATPase ABCA1 isoform X2 [Macaca nemestrina]', dbxrefs=[]), 'score': 0.9889}, '[Rhinopithecus roxellana]': {'record': SeqRecord(seq=Seq('MACWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILISVRLSYPPYEQHEC...SYV'), id='XP_010351612.1', name='XP_010351612.1', description='XP_010351612.1 phospholipid-transporting ATPase ABCA1 isoform X2 [Rhinopithecus roxellana]', dbxrefs=[]), 'score': 0.9901}, '[Carlito syrichta]': {'record': SeqRecord(seq=Seq('MACWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILISVRLSYPPYEQHEC...SYV'), id='XP_008071655.1', name='XP_008071655.1', description='XP_008071655.1 ATP-binding cassette sub-family A member 1 [Carlito syrichta]', dbxrefs=[]), 'score': 0.968}, '[Chlorocebus sabaeus]': {'record': SeqRecord(seq=Seq('MACWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILISVRLSYPPYEQHEC...SYV'), id='XP_007966715.3', name='XP_007966715.3', description='XP_007966715.3 phospholipid-transporting ATPase ABCA1 isoform X2 [Chlorocebus sabaeus]', dbxrefs=[]), 'score': 0.9917}, '[Macaca fascicularis]': {'record': SeqRecord(seq=Seq('MACWPQLRLLLWKNLTFRKRQTCQLLLEVAWPLFIFLILISVRLSYPPYEQHEC...SYV'), id='XP_005581200.3', name='XP_005581200.3', description='XP_005581200.3 phospholipid-transporting ATPase ABCA1 isoform X2 [Macaca fascicularis]', dbxrefs=[]), 'score': 0.9901}, '[Gorilla gorilla gorilla]': {'record': SeqRecord(seq=Seq('MACWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILISVRLSYPPYEQHEC...SYV'), id='XP_004048440.2', name='XP_004048440.2', description='XP_004048440.2 phospholipid-transporting ATPase ABCA1 isoform X2 [Gorilla gorilla gorilla]', dbxrefs=[]), 'score': 0.9953}, '[Saimiri boliviensis]': {'record': SeqRecord(seq=Seq('MACWPQLRLLLWKNFTFRRRQTCQLLLEVSWPLFIFLILISVRLSYPPYEQHEC...SYV'), id='XP_003925310.1', name='XP_003925310.1', description='XP_003925310.1 phospholipid-transporting ATPase ABCA1 [Saimiri boliviensis]', dbxrefs=[]), 'score': 0.9796}, '[Papio anubis]': {'record': SeqRecord(seq=Seq('MACWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILISVRLSYPPYEQHEC...SYV'), id='XP_003911461.1', name='XP_003911461.1', description='XP_003911461.1 phospholipid-transporting ATPase ABCA1 isoform X2 [Papio anubis]', dbxrefs=[]), 'score': 0.991}, '[Pan paniscus]': {'record': SeqRecord(seq=Seq('MACWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILISVRLSYPPYEQHEC...SYV'), id='XP_003809287.2', name='XP_003809287.2', description='XP_003809287.2 phospholipid-transporting ATPase ABCA1 [Pan paniscus]', dbxrefs=[]), 'score': 0.9953}, '[Otolemur garnettii]': {'record': SeqRecord(seq=Seq('MACWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILISVRLSYPPYEQHEC...SYV'), id='XP_003785245.1', name='XP_003785245.1', description='XP_003785245.1 ATP-binding cassette sub-family A member 1 isoform X2 [Otolemur garnettii]', dbxrefs=[]), 'score': 0.961}, '[Nomascus leucogenys]': {'record': SeqRecord(seq=Seq('MACWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILISVRLSYPPYEQHEC...SYV'), id='XP_030682459.1', name='XP_030682459.1', description='XP_030682459.1 phospholipid-transporting ATPase ABCA1 isoform X1 [Nomascus leucogenys]', dbxrefs=[]), 'score': 0.9943}, '[Pongo abelii]': {'record': SeqRecord(seq=Seq('MACWPQLRLLLWKNLTFRRRQTCQLLLEVAWPLFIFLILISVRLSYPPYEQHEC...SYV'), id='XP_024108241.3', name='XP_024108241.3', description='XP_024108241.3 phospholipid-transporting ATPase ABCA1 isoform X2 [Pongo abelii]', dbxrefs=[]), 'score': 0.9903}}

Processing ABCA12
  NM_173076.3 (NP_775099.2), 2595 amino acids

KeyboardInterrupt:

In [17]:
#loci = ['ALPL', 'F8', 'F9', 'TYR']
#score_recordxx = {}

for gene in locie:

    #print(f"\nProcessing {gene}")

    for ref in reference_proteins[gene]:

        transcript = ref[0]["transcript"]
        protein_id = ref[0]["protein_id"]
        reference_seq = ref[0]["protein_seq"]
        prot_length = len(reference_seq)
        print(f" {gene} {transcript} {protein_id} {prot_length} aminoacids", sep='\t')

 AAAS NM_015665.6 NP_056480.1 60 aminoacids
 ABCA1 NM_005502.4 NP_005493.2 60 aminoacids
 ABCA12 NM_173076.3 NP_775099.2 60 aminoacids
 ABCA3 NM_001089.3 NP_001080.2 60 aminoacids
 ABCA4 NM_000350.3 NP_000341.2 60 aminoacids
 ABCB11 NM_003742.4 NP_003733.2 60 aminoacids
 ABCB4 NM_000443.4 NP_000434.1 60 aminoacids
 ABCC2 NM_000392.5 NP_000383.2 60 aminoacids
 ABCC6 NM_001171.6 NP_001162.5 60 aminoacids
 ABCC8 NM_000352.6 NP_000343.2 60 aminoacids
 ABCC9 NM_020297.4 NP_064693.2 60 aminoacids
 ABCD1 NM_000033.4 NP_000024.2 60 aminoacids
 ACAD9 NM_014049.4 NP_054768.2 60 aminoacids
 ACAD9 NM_014049.5 NP_054768.2 60 aminoacids
 ACADM NM_000016.6 NP_000007.1 60 aminoacids
 ACADS NM_000017.4 NP_000008.1 60 aminoacids
 ACADVL NM_000018.4 NP_000009.1 60 aminoacids
 ACAN NM_001369268.1 NP_001356197.1 60 aminoacids
 ACAT1 NM_000019.4 NP_000010.1 60 aminoacids
 ACO2 NM_001098.3 NP_001089.1 60 aminoacids
 ACSF3 NM_001243279.3 NP_001230208.1 60 aminoacids
 ACTA1 NM_001100.4 NP_001091.1 60 aminoacids
 ACTB NM_001101.5 NP_001092.1 60 aminoacids
 ACTG1 NM_001614.5 NP_001605.1 60 aminoacids
 ACVRL1 NM_000020.3 NP_000011.2 60 aminoacids
 ADA NM_000022.4 NP_000013.2 60 aminoacids
 ADA2 NM_001282225.2 NP_001269154.1 60 aminoacids
 ADAMTS13 NM_139027.6 NP_620596.2 60 aminoacids
 ADAMTS2 NM_014244.5 NP_055059.2 60 aminoacids
 ADAMTSL4 NM_019032.6 NP_061905.2 60 aminoacids
 ADAR NM_001111.5 NP_001102.3 60 aminoacids
 ADGRG1 NM_201525.4 NP_958933.1 60 aminoacids
 ADGRV1 NM_032119.4 NP_115495.3 60 aminoacids
 ADNP NM_001282531.3 NP_001269460.1 60 aminoacids
 ADSL NM_000026.4 NP_000017.1 60 aminoacids
 AFG2A NM_145207.3 NP_660208.2 60 aminoacids
 AFG3L2 NM_006796.3 NP_006787.2 60 aminoacids
 AGA NM_000027.4 NP_000018.2 60 aminoacids
 AGL NM_000642.3 NP_000633.2 60 aminoacids
 AGXT NM_000030.3 NP_000021.1 60 aminoacids
 AHDC1 NM_001371928.1 NP_001358857.1 60 aminoacids
 AHI1 NM_001134831.2 NP_001128303.1 60 aminoacids
 AIPL1 NM_014336.5 NP_055151.3 60 aminoacids
 AIRE NM_000383.4 NP_000374.1 60 aminoacids
 ALDH3A2 NM_000382.3 NP_000373.1 60 aminoacids
 ALDH5A1 NM_001080.3 NP_001071.1 60 aminoacids
 ALDH7A1 NM_001182.5 NP_001173.2 60 aminoacids
 ALDOB NM_000035.4 NP_000026.2 60 aminoacids
 ALG1 NM_019109.5 NP_061982.3 60 aminoacids
 ALG6 NM_013339.4 NP_037471.2 60 aminoacids
 ALMS1 NM_001378454.1 NP_001365383.1 60 aminoacids
 ALOX12B NM_001139.3 NP_001130.1 60 aminoacids
 ALPK3 NM_020778.5 NP_065829.4 60 aminoacids
 ALPL NM_000478.6 NP_000469.3 60 aminoacids
 ALS2 NM_020919.3 NP_065970.2 60 aminoacids
 ALS2 NM_020919.4 NP_065970.2 60 aminoacids
 AMT NM_000481.4 NP_000472.2 60 aminoacids
 ANK1 NM_000037.4 NP_000028.3 60 aminoacids
 ANK2 NM_001148.6 NP_001139.3 60 aminoacids
 ANKRD11 NM_013275.6 NP_037407.4 60 aminoacids
 ANO5 NM_213599.3 NP_998764.1 60 aminoacids
 ANOS1 NM_000216.4 NP_000207.2 60 aminoacids
 APC NM_000038.6 NP_000029.2 60 aminoacids
 APC NM_001127510.3 NP_001120982.1 60 aminoacids
 APC NM_001127511.3 NP_001120983.2 60 aminoacids
 APOB NM_000384.3 NP_000375.3 60 aminoacids
 APRT NM_000485.3 NP_000476.1 60 aminoacids
 AQP2 NM_000486.6 NP_000477.1 60 aminoacids
 AR NM_000044.6 NP_000035.2 60 aminoacids
 ARG1 NM_000045.4 NP_000036.2 60 aminoacids
 ARID1A NM_006015.6 NP_006006.3 60 aminoacids
 ARID1B NM_001374828.1 NP_001361757.1 60 aminoacids
 ARSA NM_000487.6 NP_000478.3 60 aminoacids
 ARSB NM_000046.5 NP_000037.2 60 aminoacids
 ARX NM_139058.3 NP_620689.1 60 aminoacids
 ASAH1 NM_177924.5 NP_808592.2 60 aminoacids
 ASH1L NM_018489.3 NP_060959.2 60 aminoacids
 ASL NM_000048.4 NP_000039.2 60 aminoacids
 ASNS NM_001673.5 NP_001664.3 60 aminoacids
 ASPA NM_000049.4 NP_000040.1 60 aminoacids
 ASPM NM_018136.5 NP_060606.3 60 aminoacids
 ASS1 NM_054012.4 NP_446464.1 60 aminoacids
 ASXL1 NM_015338.6 NP_056153.2 60 aminoacids
 ASXL3 NM_030632.3 NP_085135.1 60 aminoacids
 ATL1 NM_015915.5 NP_056999.2 60 aminoacids
 ATM NM_000051.4 NP_000042.3 60 aminoacids
 ATP1A2 NM_000702.4 NP_000693.1 60 aminoacids
 ATP1A3 NM_152296.5 NP_689509.1 60 aminoacids
 ATP2A2 NM_170665.4 NP_733765.1 60 aminoacids
 ATP6V0A4 NM_020632.3 NP_065683.2 60 aminoacids
 ATP6V1B1 NM_001692.4 NP_001683.2 60 aminoacids
 ATP7A NM_000052.7 NP_000043.4 60 aminoacids
 ATP7B NM_000053.4 NP_000044.2 60 aminoacids
 ATP8B1 NM_001374385.1 NP_001361314.1 60 aminoacids
 ATR NM_001184.4 NP_001175.2 60 aminoacids
 ATRX NM_000489.6 NP_000480.3 60 aminoacids
 AUTS2 NM_015570.4 NP_056385.1 60 aminoacids
 AVPR2 NM_000054.7 NP_000045.1 60 aminoacids
 AXIN2 NM_004655.4 NP_004646.3 60 aminoacids
 BAG3 NM_004281.4 NP_004272.2 60 aminoacids
 BAP1 NM_004656.4 NP_004647.1 60 aminoacids
 BARD1 NM_000465.4 NP_000456.2 60 aminoacids
 BBS1 NM_024649.5 NP_078925.3 60 aminoacids
 BBS10 NM_024685.4 NP_078961.3 60 aminoacids
 BBS12 NM_152618.3 NP_689831.2 60 aminoacids
 BBS2 NM_031885.5 NP_114091.4 60 aminoacids
 BBS4 NM_033028.5 NP_149017.2 60 aminoacids
 BBS7 NM_176824.3 NP_789794.1 60 aminoacids
 BBS9 NM_198428.3 NP_940820.1 60 aminoacids
 BCKDHA NM_000709.4 NP_000700.1 60 aminoacids
 BCKDHB NM_183050.4 NP_898871.1 60 aminoacids
 BCS1L NM_001079866.2 NP_001073335.1 60 aminoacids
 BEST1 NM_004183.4 NP_004174.1 60 aminoacids
 BLM NM_000057.4 NP_000048.1 60 aminoacids
 BMPR1A NM_004329.3 NP_004320.2 60 aminoacids
 BMPR2 NM_001204.7 NP_001195.2 60 aminoacids
 BRAF NM_004333.6 NP_004324.2 60 aminoacids
 BRAT1 NM_152743.4 NP_689956.2 60 aminoacids
 BRCA1 NM_007294.4 NP_009225.1 60 aminoacids
 BRCA2 NM_000059.4 NP_000050.3 60 aminoacids
 BRIP1 NM_032043.3 NP_114432.2 60 aminoacids
 BTD NM_001370658.1 NP_001357587.1 60 aminoacids
 BTK NM_000061.3 NP_000052.1 60 aminoacids
 C3 NM_000064.4 NP_000055.2 60 aminoacids
 CACNA1A NM_001127221.2 NP_001120693.1 60 aminoacids
 CACNA1A NM_001127222.2 NP_001120694.1 60 aminoacids
 CACNA1C NM_000719.7 NP_000710.5 60 aminoacids
 CACNA1C NM_001167623.2 NP_001161095.1 60 aminoacids
 CACNA1F NM_001256789.3 NP_001243718.1 60 aminoacids
 CACNA1F NM_005183.4 NP_005174.2 60 aminoacids
 CACNA1S NM_000069.3 NP_000060.2 60 aminoacids
 CAD NM_004341.5 NP_004332.2 60 aminoacids
 CAMTA1 NM_015215.4 NP_056030.1 60 aminoacids
 CAPN3 NM_000070.3 NP_000061.1 60 aminoacids
 CASK NM_001367721.1 NP_001354650.1 60 aminoacids
 CASQ2 NM_001232.4 NP_001223.2 60 aminoacids
 CASR NM_000388.4 NP_000379.3 60 aminoacids
 CBS NM_000071.3 NP_000062.1 60 aminoacids
 CC2D2A NM_001378615.1 NP_001365544.1 60 aminoacids
 CCDC39 NM_181426.2 NP_852091.1 60 aminoacids
 CCDC40 NM_017950.4 NP_060420.2 60 aminoacids
 CCDC88C NM_001080414.4 NP_001073883.2 60 aminoacids
 CCM2 NM_031443.4 NP_113631.1 60 aminoacids
 CD40LG NM_000074.3 NP_000065.1 60 aminoacids
 CDC73 NM_024529.5 NP_078805.3 60 aminoacids
 CDH1 NM_004360.5 NP_004351.1 60 aminoacids
 CDH23 NM_022124.6 NP_071407.4 60 aminoacids
 CDHR1 NM_033100.4 NP_149091.1 60 aminoacids
 CDK13 NM_003718.5 NP_003709.3 60 aminoacids
 CDKL5 NM_001037343.2 NP_001032420.1 60 aminoacids
 CDKL5 NM_001323289.2 NP_001310218.1 60 aminoacids
 CDKN2A NM_000077.5 NP_000068.1 60 aminoacids
 CDKN2A NM_058195.4 NP_478102.2 60 aminoacids
 CEP152 NM_001194998.2 NP_001181927.1 60 aminoacids
 CEP164 NM_014956.5 NP_055771.4 60 aminoacids
 CEP250 NM_007186.6 NP_009117.2 60 aminoacids
 CEP290 NM_025114.4 NP_079390.3 60 aminoacids
 CERKL NM_201548.5 NP_963842.1 60 aminoacids
 CFH NM_000186.4 NP_000177.2 60 aminoacids
 CFI NM_000204.5 NP_000195.3 60 aminoacids
 CFTR NM_000492.3 NP_000483.3 60 aminoacids
 CFTR NM_000492.4 NP_000483.3 60 aminoacids
 CHAT NM_020549.5 NP_065574.4 60 aminoacids
 CHD2 NM_001271.4 NP_001262.3 60 aminoacids
 CHD3 NM_001005273.3 NP_001005273.1 60 aminoacids
 CHD4 NM_001273.5 NP_001264.2 60 aminoacids
 CHD7 NM_017780.4 NP_060250.2 60 aminoacids
 CHD8 NM_001170629.2 NP_001164100.1 60 aminoacids
 CHEK2 NM_007194.4 NP_009125.1 60 aminoacids
 CHM NM_000390.4 NP_000381.1 60 aminoacids
 CHRNE NM_000080.4 NP_000071.1 60 aminoacids
 CLCN1 NM_000083.3 NP_000074.3 60 aminoacids
 CLCN4 NM_001830.4 NP_001821.2 60 aminoacids
 CLCN5 NM_001127898.4 NP_001121370.1 60 aminoacids
 CLCN7 NM_001287.6 NP_001278.1 60 aminoacids
 CLCNKB NM_000085.5 NP_000076.2 60 aminoacids
 CLN3 NM_001042432.2 NP_001035897.1 60 aminoacids
 CLN5 NM_006493.2 NP_006484.1 60 aminoacids
 CLN5 NM_006493.4 NP_006484.2 60 aminoacids
 CLN6 NM_017882.3 NP_060352.1 60 aminoacids
 CLN8 NM_018941.4 NP_061764.2 60 aminoacids
 CLRN1 NM_052995.2 NP_443721.1 60 aminoacids
 CLRN1 NM_174878.3 NP_777367.1 60 aminoacids
 CLTC NM_004859.4 NP_004850.1 60 aminoacids
 CNGA3 NM_001298.3 NP_001289.1 60 aminoacids
 CNGB1 NM_001297.5 NP_001288.3 60 aminoacids
 CNGB3 NM_019098.5 NP_061971.3 60 aminoacids
 CNTNAP2 NM_014141.6 NP_054860.1 60 aminoacids
 COL11A1 NM_001854.4 NP_001845.3 60 aminoacids
 COL11A2 NM_080680.3 NP_542411.2 60 aminoacids
 COL12A1 NM_004370.6 NP_004361.3 60 aminoacids
 COL17A1 NM_000494.4 NP_000485.3 60 aminoacids
 COL18A1 NM_001379500.1 NP_001366429.1 60 aminoacids
 COL1A1 NM_000088.4 NP_000079.2 60 aminoacids
 COL1A2 NM_000089.4 NP_000080.2 60 aminoacids
 COL27A1 NM_032888.4 NP_116277.2 60 aminoacids
 COL2A1 NM_001844.5 NP_001835.3 60 aminoacids
 COL3A1 NM_000090.4 NP_000081.2 60 aminoacids
 COL4A1 NM_001845.6 NP_001836.3 60 aminoacids
 COL4A2 NM_001846.4 NP_001837.2 60 aminoacids
 COL4A3 NM_000091.4 NP_000082.2 60 aminoacids
 COL4A3 NM_000091.5 NP_000082.2 60 aminoacids
 COL4A4 NM_000092.5 NP_000083.3 60 aminoacids
 COL4A5 NM_033380.2 NP_203699.1 60 aminoacids
 COL4A5 NM_033380.3 NP_203699.1 60 aminoacids
 COL5A1 NM_000093.5 NP_000084.3 60 aminoacids
 COL5A2 NM_000393.5 NP_000384.2 60 aminoacids
 COL6A1 NM_001848.3 NP_001839.2 60 aminoacids
 COL6A2 NM_001849.4 NP_001840.3 60 aminoacids
 COL6A2 NM_058174.3 NP_478054.2 60 aminoacids
 COL6A3 NM_004369.4 NP_004360.2 60 aminoacids
 COL7A1 NM_000094.3 NP_000085.1 60 aminoacids
 COL7A1 NM_000094.4 NP_000085.1 60 aminoacids
 COL9A1 NM_001851.6 NP_001842.3 60 aminoacids
 COLQ NM_005677.4 NP_005668.2 60 aminoacids
 COMP NM_000095.3 NP_000086.2 60 aminoacids
 COQ8A NM_020247.5 NP_064632.2 60 aminoacids
 CP NM_000096.4 NP_000087.2 60 aminoacids
 CPLANE1 NM_001384732.1 NP_001371661.1 60 aminoacids
 CPS1 NM_001875.5 NP_001866.2 60 aminoacids
 CPT1A NM_001876.4 NP_001867.2 60 aminoacids
 CPT2 NM_000098.3 NP_000089.1 60 aminoacids
 CRB1 NM_201253.3 NP_957705.1 60 aminoacids
 CREBBP NM_004380.3 NP_004371.2 60 aminoacids
 CSF1R NM_001288705.3 NP_001275634.1 60 aminoacids
 CSF1R NM_005211.3 NP_005202.2 60 aminoacids
 CSNK2A1 NM_177559.3 NP_808227.1 60 aminoacids
 CSNK2B NM_001320.7 NP_001311.3 60 aminoacids
 CSPP1 NM_001382391.1 NP_001369320.1 60 aminoacids
 CTC1 NM_025099.6 NP_079375.3 60 aminoacids
 CTCF NM_006565.4 NP_006556.1 60 aminoacids
 CTNNA1 NM_001903.5 NP_001894.2 60 aminoacids
 CTNNB1 NM_001904.4 NP_001895.1 60 aminoacids
 CTNS NM_004937.3 NP_004928.2 60 aminoacids
 CTSC NM_001814.6 NP_001805.4 60 aminoacids
 CTSK NM_000396.4 NP_000387.1 60 aminoacids
 CUBN NM_001081.4 NP_001072.2 60 aminoacids
 CUL3 NM_003590.5 NP_003581.1 60 aminoacids
 CUL7 NM_014780.5 NP_055595.2 60 aminoacids
 CYBB NM_000397.4 NP_000388.2 60 aminoacids
 CYP11B1 NM_000497.4 NP_000488.3 60 aminoacids
 CYP11B2 NM_000498.3 NP_000489.3 60 aminoacids
 CYP17A1 NM_000102.4 NP_000093.1 60 aminoacids
 CYP19A1 NM_000103.4 NP_000094.2 60 aminoacids
 CYP1B1 NM_000104.4 NP_000095.2 60 aminoacids
 CYP21A2 NM_000500.9 NP_000491.4 60 aminoacids
 CYP27A1 NM_000784.4 NP_000775.1 60 aminoacids
 CYP27B1 NM_000785.4 NP_000776.1 60 aminoacids
 CYP4V2 NM_207352.4 NP_997235.3 60 aminoacids
 DBT NM_001918.5 NP_001909.4 60 aminoacids
 DCLRE1C NM_001033855.3 NP_001029027.1 60 aminoacids
 DCX NM_001195553.2 NP_001182482.1 60 aminoacids
 DDC NM_001082971.2 NP_001076440.2 60 aminoacids
 DDX3X NM_001356.5 NP_001347.3 60 aminoacids
 DDX41 NM_016222.4 NP_057306.2 60 aminoacids
 DEAF1 NM_021008.4 NP_066288.2 60 aminoacids
 DEPDC5 NM_001242896.3 NP_001229825.1 60 aminoacids
 DES NM_001927.4 NP_001918.3 60 aminoacids
 DHCR7 NM_001360.3 NP_001351.2 60 aminoacids
 DICER1 NM_177438.3 NP_803187.1 60 aminoacids
 DLD NM_000108.5 NP_000099.2 60 aminoacids
 DLG4 NM_001321075.3 NP_001308004.1 60 aminoacids
 DMD NM_004006.3 NP_003997.2 60 aminoacids
 DNAH1 NM_015512.5 NP_056327.4 60 aminoacids
 DNAH11 NM_001277115.2 NP_001264044.1 60 aminoacids
 DNAH5 NM_001369.3 NP_001360.1 60 aminoacids
 DNAH8 NM_001206927.2 NP_001193856.1 60 aminoacids
 DNAH9 NM_001372.4 NP_001363.2 60 aminoacids
 DNAI1 NM_012144.4 NP_036276.1 60 aminoacids
 DNAI2 NM_023036.6 NP_075462.3 60 aminoacids
 DNM1 NM_001288739.2 NP_001275668.1 60 aminoacids
 DNM1 NM_004408.4 NP_004399.2 60 aminoacids
 DNMT3A NM_022552.5 NP_072046.2 60 aminoacids
 DOCK6 NM_020812.4 NP_065863.2 60 aminoacids
 DOCK8 NM_203447.4 NP_982272.2 60 aminoacids
 DOK7 NM_173660.5 NP_775931.3 60 aminoacids
 DPYD NM_000110.4 NP_000101.2 60 aminoacids
 DSG2 NM_001943.5 NP_001934.2 60 aminoacids
 DSP NM_004415.4 NP_004406.2 60 aminoacids
 DST NM_001374736.1 NP_001361665.1 60 aminoacids
 DST NM_001723.7 NP_001714.1 60 aminoacids
 DUOX2 NM_001363711.2 NP_001350640.1 60 aminoacids
 DYNC1H1 NM_001376.5 NP_001367.2 60 aminoacids
 DYNC2H1 NM_001080463.2 NP_001073932.1 60 aminoacids
 DYNC2H1 NM_001377.3 NP_001368.2 60 aminoacids
 DYRK1A NM_001347721.2 NP_001334650.1 60 aminoacids
 DYSF NM_001130987.2 NP_001124459.1 60 aminoacids
 DYSF NM_003494.4 NP_003485.1 60 aminoacids
 EBF3 NM_001375380.1 NP_001362309.1 60 aminoacids
 EBP NM_006579.3 NP_006570.1 60 aminoacids
 ECHS1 NM_004092.4 NP_004083.3 60 aminoacids
 EDA NM_001399.5 NP_001390.1 60 aminoacids
 EDAR NM_022336.4 NP_071731.1 60 aminoacids
 EFTUD2 NM_004247.4 NP_004238.3 60 aminoacids
 EHMT1 NM_024757.5 NP_079033.4 60 aminoacids
 EIF2AK3 NM_004836.7 NP_004827.4 60 aminoacids
 EIF2B5 NM_003907.3 NP_003898.2 60 aminoacids
 ELAC2 NM_018127.7 NP_060597.4 60 aminoacids
 ELANE NM_001972.4 NP_001963.1 60 aminoacids
 ELN NM_000501.4 NP_000492.2 60 aminoacids
 ELP1 NM_003640.5 NP_003631.2 60 aminoacids
 EMC1 NM_015047.3 NP_055862.1 60 aminoacids
 ENG NM_001114753.3 NP_001108225.1 60 aminoacids
 ENPP1 NM_006208.3 NP_006199.2 60 aminoacids
 EP300 NM_001429.3 NP_001420.2 60 aminoacids
 EP300 NM_001429.4 NP_001420.2 60 aminoacids
 EPG5 NM_020964.3 NP_066015.2 60 aminoacids
 EPHB4 NM_004444.5 NP_004435.3 60 aminoacids
 ERCC2 NM_000400.4 NP_000391.1 60 aminoacids
 ERCC6 NM_000124.4 NP_000115.1 60 aminoacids
 ERCC6 NM_001277058.2 NP_001263987.1 60 aminoacids
 ERCC8 NM_000082.4 NP_000073.1 60 aminoacids
 ESCO2 NM_001017420.3 NP_001017420.1 60 aminoacids
 ETFDH NM_004453.4 NP_004444.2 60 aminoacids
 ETHE1 NM_014297.5 NP_055112.2 60 aminoacids
 EVC NM_153717.3 NP_714928.1 60 aminoacids
 EVC2 NM_147127.5 NP_667338.3 60 aminoacids
 EXT1 NM_000127.3 NP_000118.2 60 aminoacids
 EXT2 NM_207122.2 NP_997005.1 60 aminoacids
 EYA1 NM_000503.6 NP_000494.2 60 aminoacids
 EYA4 NM_004100.5 NP_004091.3 60 aminoacids
 EYS NM_001142800.2 NP_001136272.1 60 aminoacids
 F11 NM_000128.4 NP_000119.1 60 aminoacids
 F5 NM_000130.4 NP_000121.2 60 aminoacids
 F5 NM_000130.5 NP_000121.2 60 aminoacids
 F7 NM_000131.4 NP_000122.1 60 aminoacids
 F7 NM_000131.5 NP_000122.1 60 aminoacids
 F7 NM_019616.4 NP_062562.1 60 aminoacids
 F8 NM_000132.4 NP_000123.1 60 aminoacids
 F9 NM_000133.4 NP_000124.1 60 aminoacids
 FAH NM_000137.4 NP_000128.1 60 aminoacids
 FAM161A NM_001201543.2 NP_001188472.1 60 aminoacids
 FANCA NM_000135.4 NP_000126.2 60 aminoacids
 FANCC NM_000136.3 NP_000127.2 60 aminoacids
 FANCD2 NM_001018115.3 NP_001018125.1 60 aminoacids
 FANCG NM_004629.2 NP_004620.1 60 aminoacids
 FANCI NM_001113378.2 NP_001106849.1 60 aminoacids
 FANCL NM_018062.4 NP_060532.2 60 aminoacids
 FANCM NM_020937.4 NP_065988.1 60 aminoacids
 FAS NM_000043.6 NP_000034.1 60 aminoacids
 FBN1 NM_000138.5 NP_000129.3 60 aminoacids
 FBN2 NM_001999.4 NP_001990.2 60 aminoacids
 FBXL4 NM_001278716.2 NP_001265645.1 60 aminoacids
 FBXO11 NM_001190274.2 NP_001177203.1 60 aminoacids
 FECH NM_000140.3 NP_000131.2 60 aminoacids
 FECH NM_000140.5 NP_000131.2 60 aminoacids
 FGFR1 NM_023110.3 NP_075598.2 60 aminoacids
 FGFR2 NM_000141.5 NP_000132.3 60 aminoacids
 FGFR3 NM_000142.5 NP_000133.1 60 aminoacids
 FH NM_000143.4 NP_000134.2 60 aminoacids
 FHL1 NM_001159699.2 NP_001153171.1 60 aminoacids
 FHL1 NM_001159702.3 NP_001153174.1 60 aminoacids
 FIG4 NM_014845.6 NP_055660.1 60 aminoacids
 FKRP NM_024301.5 NP_077277.1 60 aminoacids
 FKTN NM_001079802.2 NP_001073270.1 60 aminoacids
 FLCN NM_144997.7 NP_659434.2 60 aminoacids
 FLG NM_002016.2 NP_002007.1 60 aminoacids
 FLNA NM_001110556.2 NP_001104026.1 60 aminoacids
 FLNB NM_001457.4 NP_001448.2 60 aminoacids
 FLNC NM_001458.5 NP_001449.3 60 aminoacids
 FLT4 NM_182925.5 NP_891555.2 60 aminoacids
 FMO3 NM_001002294.3 NP_001002294.1 60 aminoacids
 FOXC1 NM_001453.3 NP_001444.2 60 aminoacids
 FOXG1 NM_005249.5 NP_005240.3 60 aminoacids
 FOXL2 NM_023067.4 NP_075555.1 60 aminoacids
 FOXP1 NM_001349338.3 NP_001336267.1 60 aminoacids
 FRAS1 NM_025074.7 NP_079350.5 60 aminoacids
 FREM2 NM_207361.6 NP_997244.4 60 aminoacids
 FUCA1 NM_000147.5 NP_000138.2 60 aminoacids
 G6PC1 NM_000151.4 NP_000142.2 60 aminoacids
 G6PD NM_000402.4 NP_000393.4 60 aminoacids
 G6PD NM_001042351.3 NP_001035810.1 60 aminoacids
 G6PD NM_001360016.2 NP_001346945.1 60 aminoacids
 GAA NM_000152.5 NP_000143.2 60 aminoacids
 GABRA1 NM_001127644.2 NP_001121116.1 60 aminoacids
 GABRB2 NM_001371727.1 NP_001358656.1 60 aminoacids
 GABRB3 NM_000814.6 NP_000805.1 60 aminoacids
 GABRB3 NM_021912.5 NP_068712.1 60 aminoacids
 GABRG2 NM_198904.4 NP_944494.1 60 aminoacids
 GALC NM_000153.4 NP_000144.2 60 aminoacids
 GALC NM_001201402.2 NP_001188331.1 60 aminoacids
 GALK1 NM_000154.2 NP_000145.1 60 aminoacids
 GALNS NM_000512.5 NP_000503.1 60 aminoacids
 GALT NM_000155.4 NP_000146.2 60 aminoacids
 GAMT NM_000156.6 NP_000147.1 60 aminoacids
 GATA2 NM_032638.5 NP_116027.2 60 aminoacids
 GATAD2B NM_020699.4 NP_065750.1 60 aminoacids
 GBA1 NM_000157.4 NP_000148.2 60 aminoacids
 GBE1 NM_000158.4 NP_000149.4 60 aminoacids
 GCDH NM_000159.4 NP_000150.1 60 aminoacids
 GCH1 NM_000161.3 NP_000152.1 60 aminoacids
 GCK NM_000162.5 NP_000153.1 60 aminoacids
 GDAP1 NM_018972.4 NP_061845.2 60 aminoacids
 GFAP NM_002055.5 NP_002046.1 60 aminoacids
 GFM1 NM_024996.7 NP_079272.4 60 aminoacids
 GJA1 NM_000165.5 NP_000156.1 60 aminoacids
 GJB1 NM_000166.6 NP_000157.1 60 aminoacids
 GJB1 NM_001097642.3 NP_001091111.1 60 aminoacids
 GJB2 NM_004004.6 NP_003995.2 60 aminoacids
 GLA NM_000169.3 NP_000160.1 60 aminoacids
 GLB1 NM_000404.4 NP_000395.3 60 aminoacids
 GLDC NM_000170.3 NP_000161.2 60 aminoacids
 GLE1 NM_001003722.2 NP_001003722.1 60 aminoacids
 GLI3 NM_000168.6 NP_000159.3 60 aminoacids
 GLRA1 NM_000171.4 NP_000162.2 60 aminoacids
 GNAO1 NM_020988.3 NP_066268.1 60 aminoacids
 GNAS NM_000516.7 NP_000507.1 60 aminoacids
 GNAS NM_016592.5 NP_057676.1 60 aminoacids
 GNAS NM_080425.4 NP_536350.2 60 aminoacids
 GNB1 NM_002074.5 NP_002065.1 60 aminoacids
 GNE NM_001128227.3 NP_001121699.1 60 aminoacids
 GNE NM_005476.7 NP_005467.1 60 aminoacids
 GNPTAB NM_024312.5 NP_077288.2 60 aminoacids
 GNPTG NM_032520.5 NP_115909.1 60 aminoacids
 GPR143 NM_000273.3 NP_000264.2 60 aminoacids
 GRHPR NM_012203.2 NP_036335.1 60 aminoacids
 GRIN1 NM_007327.4 NP_015566.1 60 aminoacids
 GRIN2A NM_001134407.3 NP_001127879.1 60 aminoacids
 GRIN2B NM_000834.5 NP_000825.2 60 aminoacids
 GRN NM_002087.4 NP_002078.1 60 aminoacids
 GUCY2D NM_000180.4 NP_000171.1 60 aminoacids
 GUSB NM_000181.4 NP_000172.2 60 aminoacids
 HADHA NM_000182.5 NP_000173.2 60 aminoacids
 HADHB NM_000183.3 NP_000174.1 60 aminoacids
 HBA2 NM_000517.4 NP_000508.1 60 aminoacids
 HBA2 NM_000517.6 NP_000508.1 60 aminoacids
 HBB NM_000518.4 NP_000509.1 60 aminoacids
 HBB NM_000518.5 NP_000509.1 60 aminoacids
 HDAC8 NM_018486.3 NP_060956.1 60 aminoacids
 HEXA NM_000520.6 NP_000511.2 60 aminoacids
 HEXB NM_000521.4 NP_000512.2 60 aminoacids
 HGD NM_000187.4 NP_000178.2 60 aminoacids
 HGSNAT NM_152419.3 NP_689632.2 60 aminoacids
 HLCS NM_001352514.2 NP_001339443.1 60 aminoacids
 HMBS NM_000190.4 NP_000181.2 60 aminoacids
 HMGCL NM_000191.3 NP_000182.2 60 aminoacids
 HNF1A NM_000545.5 NP_000536.5 60 aminoacids

In [ ]:
score_record['AAAS']['record']['[Homo sapiens]']['score']

1.0

### Save 'score_record' as dataframe object

In [ ]:
import pandas as pd
score_record_df = pd.DataFrame.from_dict(score_record, orient= "index")
score_record_df.head
score_record_df.index.name = 'gene'
score_record_df = score_record_df.reset_index()
score_record_df.head(10)
score_record_df.to_csv("score_record_df.csv", index = False)

In [127]:
os.getcwd()
#os.chdir("Outputs_primates")

'/Users/adesinamary/Documents/kondrashov/Outputs_primates'

In [ ]:
import pandas as pd

rows = []

for gene, gene_data in score_record.items():
    for species, species_data in gene_data['record'].items():
        seq_record = species_data['record']
        rows.append({
            'gene': gene,
            'species': species.strip('[]'),
            'accession': seq_record.id,
            'description': seq_record.description,
            'score': species_data['score']
        })

score_df = pd.DataFrame(rows)

#score_df.to_csv("score_record_df.csv", index = False)

In [120]:
pd.set_option('display.max_columns', 50)
score_df.head(10)

,gene,species,accession,description,score
0,AAAS,Homo sapiens,NP_056480.1,NP_056480.1 aladin isoform 1 [Homo sapiens],1.0000
1,AAAS,Pan troglodytes,NP_001233360.1,NP_001233360.1 aladin [Pan troglodytes],0.9976
2,AAAS,Macaca fascicularis,XP_005571057.1,XP_005571057.1 aladin isoform X1 [Macaca fasci...,0.9849
3,AAAS,Callithrix jacchus,XP_035112532.1,XP_035112532.1 aladin isoform X1 [Callithrix j...,0.9711
4,AAAS,Eulemur rufifrons,XP_069345812.1,XP_069345812.1 aladin isoform X2 [Eulemur rufi...,0.9475
5,AAAS,Gorilla gorilla gorilla,XP_055213105.1,XP_055213105.1 aladin isoform X1 [Gorilla gori...,0.9919
6,AAAS,Symphalangus syndactylus,XP_055104476.1,XP_055104476.1 aladin isoform X1 [Symphalangus...,0.9886
7,AAAS,Pongo pygmaeus,XP_054299001.1,XP_054299001.1 aladin isoform X1 [Pongo pygmaeus],0.9855
8,AAAS,Nycticebus coucang,XP_053410634.1,XP_053410634.1 aladin isoform X1 [Nycticebus c...,0.9384
9,AAAS,Macaca thibetana thibetana,XP_050604835.1,XP_050604835.1 aladin isoform X1 [Macaca thibe...,0.9808

### For comparison sake, I'll get a score for all orthologs regardless of number per species, as save as .csv. 
* I'll use the function 'write_species_matches'

In [22]:
#run kondrashov
import os
os.makedirs("fasta_lociii_match_all", exist_ok= True)
os.getcwd()
#os.chdir('/Users/adesinamary/Documents/kondrashov/')

'/Users/adesinamary/Documents/kondrashov'

In [34]:
score_record_all = {}

for gene in locie:

    print(f"\nProcessing {gene}")

    for ref in reference_proteins[gene]:

        transcript = ref[0]["transcript"]
        protein_id = ref[0]["protein_id"]
        reference_seq = ref[0]["protein_seq"]

        print(f"  {transcript} ({protein_id}), {len(reference_seq)} amino acids")

        matches = write_species_matches(
            gene=gene,
            reference_seq=reference_seq,
            aligner=aligner
        )

        score_record_all[gene] = matches


rows = []

for gene, matches in score_record_all.items():

    for species, data in matches.items():

        rows.append({
            'gene': gene,
            'species': species.strip('[]'),
            'accession': data['record'].id,
            'score': data['score']
        })

score_df_all = pd.DataFrame(rows)

Processing AAAS
  NM_015665.6 (NP_056480.1), 546 amino acids

Processing ABCA1
  NM_005502.4 (NP_005493.2), 2261 amino acids

Processing ABCA12
  NM_173076.3 (NP_775099.2), 2595 amino acids

Processing ABCA3
  NM_001089.3 (NP_001080.2), 1704 amino acids

Processing ABCA4
  NM_000350.3 (NP_000341.2), 2273 amino acids

Processing ABCB11
  NM_003742.4 (NP_003733.2), 1321 amino acids

Processing ABCB4
  NM_000443.4 (NP_000434.1), 1279 amino acids

Processing ABCC2
  NM_000392.5 (NP_000383.2), 1545 amino acids

Processing ABCC6
  NM_001171.6 (NP_001162.5), 1503 amino acids

KeyboardInterrupt:

In [35]:
rows = []

for gene in locie:

    #print(f"\nProcessing {gene}")
    for ref in reference_proteins[gene]:
        transcript = ref[0]["transcript"]
        protein_id = ref[0]["protein_id"]
        reference_seq = ref[0]["protein_seq"]

        print(
            f"  {transcript} ({protein_id}), {len(reference_seq)} amino acids")

        infile = f"fasta_lociii/{gene}.fasta"
        records = list(SeqIO.parse(infile, "fasta"))
        max_score = aligner.score(reference_seq, reference_seq)
        for record in records:
            species = "[" + record.description.split("[")[-1]
            score = round(aligner.score(reference_seq, record.seq) / max_score, 4
            )

            rows.append({
                "gene": gene,
                #"transcript": transcript,
                "protein_id": protein_id,
                "species": species.strip("[]"),
                #"accession": record.id,
                "score": score
            })

score_df_all = pd.DataFrame(rows)

  NM_015665.6 (NP_056480.1), 546 amino acids
  NM_005502.4 (NP_005493.2), 2261 amino acids
  NM_173076.3 (NP_775099.2), 2595 amino acids
  NM_001089.3 (NP_001080.2), 1704 amino acids
  NM_000350.3 (NP_000341.2), 2273 amino acids
  NM_003742.4 (NP_003733.2), 1321 amino acids
  NM_000443.4 (NP_000434.1), 1279 amino acids
  NM_000392.5 (NP_000383.2), 1545 amino acids
  NM_001171.6 (NP_001162.5), 1503 amino acids
  NM_000352.6 (NP_000343.2), 1581 amino acids
  NM_020297.4 (NP_064693.2), 1549 amino acids
  NM_000033.4 (NP_000024.2), 745 amino acids
  NM_014049.4 (NP_054768.2), 621 amino acids
  NM_014049.5 (NP_054768.2), 621 amino acids
  NM_000016.6 (NP_000007.1), 421 amino acids
  NM_000017.4 (NP_000008.1), 412 amino acids
  NM_000018.4 (NP_000009.1), 655 amino acids
  NM_001369268.1 (NP_001356197.1), 2568 amino acids
  NM_000019.4 (NP_000010.1), 427 amino acids
  NM_001098.3 (NP_001089.1), 780 amino acids
  NM_001243279.3 (NP_001230208.1), 576 amino acids
  NM_001100.4 (NP_001091.1), 377 amino acids
  NM_001101.5 (NP_001092.1), 375 amino acids
  NM_001614.5 (NP_001605.1), 375 amino acids
  NM_000020.3 (NP_000011.2), 503 amino acids
  NM_000022.4 (NP_000013.2), 363 amino acids
  NM_001282225.2 (NP_001269154.1), 511 amino acids
  NM_139027.6 (NP_620596.2), 1371 amino acids
  NM_014244.5 (NP_055059.2), 1211 amino acids
  NM_019032.6 (NP_061905.2), 1074 amino acids
  NM_001111.5 (NP_001102.3), 1226 amino acids
  NM_201525.4 (NP_958933.1), 687 amino acids
  NM_032119.4 (NP_115495.3), 6306 amino acids
  NM_001282531.3 (NP_001269460.1), 1102 amino acids
  NM_000026.4 (NP_000017.1), 484 amino acids
  NM_145207.3 (NP_660208.2), 893 amino acids
  NM_006796.3 (NP_006787.2), 797 amino acids
  NM_000027.4 (NP_000018.2), 346 amino acids
  NM_000642.3 (NP_000633.2), 1532 amino acids
  NM_000030.3 (NP_000021.1), 392 amino acids
  NM_001371928.1 (NP_001358857.1), 1603 amino acids
  NM_001134831.2 (NP_001128303.1), 1196 amino acids
  NM_014336.5 (NP_055151.3), 384 amino acids
  NM_000383.4 (NP_000374.1), 545 amino acids
  NM_000382.3 (NP_000373.1), 485 amino acids
  NM_001080.3 (NP_001071.1), 535 amino acids
  NM_001182.5 (NP_001173.2), 539 amino acids
  NM_000035.4 (NP_000026.2), 364 amino acids
  NM_019109.5 (NP_061982.3), 464 amino acids
  NM_013339.4 (NP_037471.2), 507 amino acids
  NM_001378454.1 (NP_001365383.1), 4168 amino acids
  NM_001139.3 (NP_001130.1), 701 amino acids
  NM_020778.5 (NP_065829.4), 1705 amino acids
  NM_000478.6 (NP_000469.3), 524 amino acids
  NM_020919.3 (NP_065970.2), 1657 amino acids
  NM_020919.4 (NP_065970.2), 1657 amino acids
  NM_000481.4 (NP_000472.2), 403 amino acids
  NM_000037.4 (NP_000028.3), 1880 amino acids
  NM_001148.6 (NP_001139.3), 3957 amino acids
  NM_013275.6 (NP_037407.4), 2663 amino acids
  NM_213599.3 (NP_998764.1), 913 amino acids
  NM_000216.4 (NP_000207.2), 680 amino acids
  NM_000038.6 (NP_000029.2), 2843 amino acids
  NM_001127510.3 (NP_001120982.1), 2843 amino acids
  NM_001127511.3 (NP_001120983.2), 2825 amino acids
  NM_000384.3 (NP_000375.3), 4563 amino acids
  NM_000485.3 (NP_000476.1), 180 amino acids
  NM_000486.6 (NP_000477.1), 271 amino acids
  NM_000044.6 (NP_000035.2), 920 amino acids
  NM_000045.4 (NP_000036.2), 322 amino acids
  NM_006015.6 (NP_006006.3), 2285 amino acids
  NM_001374828.1 (NP_001361757.1), 2372 amino acids
  NM_000487.6 (NP_000478.3), 509 amino acids
  NM_000046.5 (NP_000037.2), 533 amino acids
  NM_139058.3 (NP_620689.1), 562 amino acids
  NM_177924.5 (NP_808592.2), 395 amino acids
  NM_018489.3 (NP_060959.2), 2964 amino acids
  NM_000048.4 (NP_000039.2), 464 amino acids
  NM_001673.5 (NP_001664.3), 561 amino acids
  NM_000049.4 (NP_000040.1), 313 amino acids
  NM_018136.5 (NP_060606.3), 3477 amino acids
  NM_054012.4 (NP_446464.1), 412 amino acids
  NM_015338.6 (NP_056153.2), 1541 amino acids
  NM_030632.3 (NP_085135.1), 2248 amino acids
  NM_015915.5 (NP_056999.2), 558 amino acids
  NM_000051.4 (NP_000042.3), 3056 amino acids
  NM_000702.4 (NP_000693.1), 1020 amino acids
  NM_152296.5 (NP_689509.1), 1013 amino acids
  NM_170665.4 (NP_733765.1), 1042 amino acids
  NM_020632.3 (NP_065683.2), 840 amino acids
  NM_001692.4 (NP_001683.2), 513 amino acids
  NM_000052.7 (NP_000043.4), 1500 amino acids
  NM_000053.4 (NP_000044.2), 1465 amino acids
  NM_001374385.1 (NP_001361314.1), 1251 amino acids
  NM_001184.4 (NP_001175.2), 2644 amino acids
  NM_000489.6 (NP_000480.3), 2492 amino acids
  NM_015570.4 (NP_056385.1), 1259 amino acids
  NM_000054.7 (NP_000045.1), 371 amino acids
  NM_004655.4 (NP_004646.3), 843 amino acids
  NM_004281.4 (NP_004272.2), 575 amino acids
  NM_004656.4 (NP_004647.1), 729 amino acids
  NM_000465.4 (NP_000456.2), 777 amino acids
  NM_024649.5 (NP_078925.3), 593 amino acids
  NM_024685.4 (NP_078961.3), 723 amino acids
  NM_152618.3 (NP_689831.2), 710 amino acids
  NM_031885.5 (NP_114091.4), 721 amino acids
  NM_033028.5 (NP_149017.2), 519 amino acids
  NM_176824.3 (NP_789794.1), 715 amino acids
  NM_198428.3 (NP_940820.1), 887 amino acids
  NM_000709.4 (NP_000700.1), 445 amino acids
  NM_183050.4 (NP_898871.1), 392 amino acids
  NM_001079866.2 (NP_001073335.1), 419 amino acids
  NM_004183.4 (NP_004174.1), 585 amino acids
  NM_000057.4 (NP_000048.1), 1417 amino acids
  NM_004329.3 (NP_004320.2), 532 amino acids
  NM_001204.7 (NP_001195.2), 1038 amino acids
  NM_004333.6 (NP_004324.2), 766 amino acids
  NM_152743.4 (NP_689956.2), 821 amino acids
  NM_007294.4 (NP_009225.1), 1863 amino acids
  NM_000059.4 (NP_000050.3), 3418 amino acids
  NM_032043.3 (NP_114432.2), 1249 amino acids
  NM_001370658.1 (NP_001357587.1), 523 amino acids
  NM_000061.3 (NP_000052.1), 659 amino acids
  NM_000064.4 (NP_000055.2), 1663 amino acids
  NM_001127221.2 (NP_001120693.1), 2261 amino acids
  NM_001127222.2 (NP_001120694.1), 2506 amino acids
  NM_000719.7 (NP_000710.5), 2138 amino acids
  NM_001167623.2 (NP_001161095.1), 2138 amino acids
  NM_001256789.3 (NP_001243718.1), 1966 amino acids
  NM_005183.4 (NP_005174.2), 1977 amino acids
  NM_000069.3 (NP_000060.2), 1873 amino acids
  NM_004341.5 (NP_004332.2), 2225 amino acids
  NM_015215.4 (NP_056030.1), 1673 amino acids
  NM_000070.3 (NP_000061.1), 821 amino acids
  NM_001367721.1 (NP_001354650.1), 926 amino acids
  NM_001232.4 (NP_001223.2), 399 amino acids
  NM_000388.4 (NP_000379.3), 1078 amino acids
  NM_000071.3 (NP_000062.1), 551 amino acids
  NM_001378615.1 (NP_001365544.1), 1620 amino acids
  NM_181426.2 (NP_852091.1), 941 amino acids
  NM_017950.4 (NP_060420.2), 1142 amino acids
  NM_001080414.4 (NP_001073883.2), 2028 amino acids
  NM_031443.4 (NP_113631.1), 444 amino acids
  NM_000074.3 (NP_000065.1), 261 amino acids
  NM_024529.5 (NP_078805.3), 531 amino acids
  NM_004360.5 (NP_004351.1), 882 amino acids
  NM_022124.6 (NP_071407.4), 3354 amino acids
  NM_033100.4 (NP_149091.1), 859 amino acids
  NM_003718.5 (NP_003709.3), 1512 amino acids
  NM_001037343.2 (NP_001032420.1), 1030 amino acids
  NM_001323289.2 (NP_001310218.1), 960 amino acids
  NM_000077.5 (NP_000068.1), 156 amino acids
  NM_058195.4 (NP_478102.2), 132 amino acids
  NM_001194998.2 (NP_001181927.1), 1710 amino acids
  NM_014956.5 (NP_055771.4), 1460 amino acids
  NM_007186.6 (NP_009117.2), 2442 amino acids
  NM_025114.4 (NP_079390.3), 2479 amino acids
  NM_201548.5 (NP_963842.1), 532 amino acids
  NM_000186.4 (NP_000177.2), 1231 amino acids
  NM_000204.5 (NP_000195.3), 583 amino acids
  NM_000492.3 (NP_000483.3), 1480 amino acids
  NM_000492.4 (NP_000483.3), 1480 amino acids
  NM_020549.5 (NP_065574.4), 748 amino acids
  NM_001271.4 (NP_001262.3), 1828 amino acids
  NM_001005273.3 (NP_001005273.1), 2000 amino acids
  NM_001273.5 (NP_001264.2), 1912 amino acids
  NM_017780.4 (NP_060250.2), 2997 amino acids
  NM_001170629.2 (NP_001164100.1), 2581 amino acids
  NM_007194.4 (NP_009125.1), 543 amino acids
  NM_000390.4 (NP_000381.1), 653 amino acids
  NM_000080.4 (NP_000071.1), 493 amino acids
  NM_000083.3 (NP_000074.3), 988 amino acids
  NM_001830.4 (NP_001821.2), 760 amino acids
  NM_001127898.4 (NP_001121370.1), 816 amino acids
  NM_001287.6 (NP_001278.1), 805 amino acids
  NM_000085.5 (NP_000076.2), 687 amino acids
  NM_001042432.2 (NP_001035897.1), 438 amino acids
  NM_006493.2 (NP_006484.1), 407 amino acids
  NM_006493.4 (NP_006484.2), 358 amino acids
  NM_017882.3 (NP_060352.1), 311 amino acids
  NM_018941.4 (NP_061764.2), 286 amino acids
  NM_052995.2 (NP_443721.1), 120 amino acids
  NM_174878.3 (NP_777367.1), 232 amino acids
  NM_004859.4 (NP_004850.1), 1675 amino acids
  NM_001298.3 (NP_001289.1), 694 amino acids
  NM_001297.5 (NP_001288.3), 1251 amino acids
  NM_019098.5 (NP_061971.3), 809 amino acids
  NM_014141.6 (NP_054860.1), 1331 amino acids
  NM_001854.4 (NP_001845.3), 1806 amino acids
  NM_080680.3 (NP_542411.2), 1736 amino acids
  NM_004370.6 (NP_004361.3), 3063 amino acids
  NM_000494.4 (NP_000485.3), 1497 amino acids
  NM_001379500.1 (NP_001366429.1), 1339 amino acids
  NM_000088.4 (NP_000079.2), 1464 amino acids
  NM_000089.4 (NP_000080.2), 1366 amino acids
  NM_032888.4 (NP_116277.2), 1860 amino acids
  NM_001844.5 (NP_001835.3), 1487 amino acids
  NM_000090.4 (NP_000081.2), 1466 amino acids
  NM_001845.6 (NP_001836.3), 1669 amino acids
  NM_001846.4 (NP_001837.2), 1712 amino acids
  NM_000091.4 (NP_000082.2), 1670 amino acids
  NM_000091.5 (NP_000082.2), 1670 amino acids
  NM_000092.5 (NP_000083.3), 1690 amino acids
  NM_033380.2 (NP_203699.1), 1691 amino acids
  NM_033380.3 (NP_203699.1), 1691 amino acids
  NM_000093.5 (NP_000084.3), 1838 amino acids
  NM_000393.5 (NP_000384.2), 1499 amino acids
  NM_001848.3 (NP_001839.2), 1028 amino acids
  NM_001849.4 (NP_001840.3), 1019 amino acids
  NM_058174.3 (NP_478054.2), 918 amino acids
  NM_004369.4 (NP_004360.2), 3177 amino acids
  NM_000094.3 (NP_000085.1), 2944 amino acids
  NM_000094.4 (NP_000085.1), 2944 amino acids
  NM_001851.6 (NP_001842.3), 921 amino acids
  NM_005677.4 (NP_005668.2), 455 amino acids
  NM_000095.3 (NP_000086.2), 757 amino acids
  NM_020247.5 (NP_064632.2), 647 amino acids
  NM_000096.4 (NP_000087.2), 1065 amino acids
  NM_001384732.1 (NP_001371661.1), 3251 amino acids
  NM_001875.5 (NP_001866.2), 1500 amino acids
  NM_001876.4 (NP_001867.2), 773 amino acids
  NM_000098.3 (NP_000089.1), 658 amino acids
  NM_201253.3 (NP_957705.1), 1406 amino acids
  NM_004380.3 (NP_004371.2), 2442 amino acids
  NM_001288705.3 (NP_001275634.1), 972 amino acids
  NM_005211.3 (NP_005202.2), 972 amino acids
  NM_177559.3 (NP_808227.1), 391 amino acids
  NM_001320.7 (NP_001311.3), 215 amino acids
  NM_001382391.1 (NP_001369320.1), 1226 amino acids
  NM_025099.6 (NP_079375.3), 1217 amino acids
  NM_006565.4 (NP_006556.1), 727 amino acids
  NM_001903.5 (NP_001894.2), 906 amino acids
  NM_001904.4 (NP_001895.1), 781 amino acids
  NM_004937.3 (NP_004928.2), 367 amino acids
  NM_001814.6 (NP_001805.4), 463 amino acids
  NM_000396.4 (NP_000387.1), 329 amino acids
  NM_001081.4 (NP_001072.2), 3623 amino acids
  NM_003590.5 (NP_003581.1), 768 amino acids
  NM_014780.5 (NP_055595.2), 1698 amino acids
  NM_000397.4 (NP_000388.2), 570 amino acids
  NM_000497.4 (NP_000488.3), 503 amino acids
  NM_000498.3 (NP_000489.3), 503 amino acids
  NM_000102.4 (NP_000093.1), 508 amino acids
  NM_000103.4 (NP_000094.2), 503 amino acids
  NM_000104.4 (NP_000095.2), 543 amino acids
  NM_000500.9 (NP_000491.4), 495 amino acids
  NM_000784.4 (NP_000775.1), 531 amino acids
  NM_000785.4 (NP_000776.1), 508 amino acids
  NM_207352.4 (NP_997235.3), 525 amino acids
  NM_001918.5 (NP_001909.4), 482 amino acids
  NM_001033855.3 (NP_001029027.1), 692 amino acids
  NM_001195553.2 (NP_001182482.1), 366 amino acids
  NM_001082971.2 (NP_001076440.2), 480 amino acids
  NM_001356.5 (NP_001347.3), 662 amino acids
  NM_016222.4 (NP_057306.2), 622 amino acids
  NM_021008.4 (NP_066288.2), 565 amino acids
  NM_001242896.3 (NP_001229825.1), 1603 amino acids
  NM_001927.4 (NP_001918.3), 470 amino acids
  NM_001360.3 (NP_001351.2), 475 amino acids
  NM_177438.3 (NP_803187.1), 1922 amino acids
  NM_000108.5 (NP_000099.2), 509 amino acids
  NM_001321075.3 (NP_001308004.1), 724 amino acids
  NM_004006.3 (NP_003997.2), 3685 amino acids
  NM_015512.5 (NP_056327.4), 4265 amino acids
  NM_001277115.2 (NP_001264044.1), 4516 amino acids
  NM_001369.3 (NP_001360.1), 4624 amino acids
  NM_001206927.2 (NP_001193856.1), 4707 amino acids
  NM_001372.4 (NP_001363.2), 4486 amino acids
  NM_012144.4 (NP_036276.1), 699 amino acids
  NM_023036.6 (NP_075462.3), 605 amino acids
  NM_001288739.2 (NP_001275668.1), 864 amino acids
  NM_004408.4 (NP_004399.2), 864 amino acids
  NM_022552.5 (NP_072046.2), 912 amino acids
  NM_020812.4 (NP_065863.2), 2047 amino acids
  NM_203447.4 (NP_982272.2), 2099 amino acids
  NM_173660.5 (NP_775931.3), 504 amino acids
  NM_000110.4 (NP_000101.2), 1025 amino acids
  NM_001943.5 (NP_001934.2), 1118 amino acids
  NM_004415.4 (NP_004406.2), 2871 amino acids
  NM_001374736.1 (NP_001361665.1), 7818 amino acids
  NM_001723.7 (NP_001714.1), 2649 amino acids
  NM_001363711.2 (NP_001350640.1), 1548 amino acids
  NM_001376.5 (NP_001367.2), 4646 amino acids
  NM_001080463.2 (NP_001073932.1), 4314 amino acids
  NM_001377.3 (NP_001368.2), 4307 amino acids
  NM_001347721.2 (NP_001334650.1), 754 amino acids
  NM_001130987.2 (NP_001124459.1), 2119 amino acids
  NM_003494.4 (NP_003485.1), 2080 amino acids
  NM_001375380.1 (NP_001362309.1), 629 amino acids
  NM_006579.3 (NP_006570.1), 230 amino acids
  NM_004092.4 (NP_004083.3), 290 amino acids
  NM_001399.5 (NP_001390.1), 391 amino acids
  NM_022336.4 (NP_071731.1), 448 amino acids
  NM_004247.4 (NP_004238.3), 972 amino acids
  NM_024757.5 (NP_079033.4), 1298 amino acids
  NM_004836.7 (NP_004827.4), 1116 amino acids
  NM_003907.3 (NP_003898.2), 721 amino acids
  NM_018127.7 (NP_060597.4), 826 amino acids
  NM_001972.4 (NP_001963.1), 267 amino acids
  NM_000501.4 (NP_000492.2), 724 amino acids
  NM_003640.5 (NP_003631.2), 1332 amino acids
  NM_015047.3 (NP_055862.1), 993 amino acids
  NM_001114753.3 (NP_001108225.1), 658 amino acids
  NM_006208.3 (NP_006199.2), 925 amino acids
  NM_001429.3 (NP_001420.2), 2414 amino acids
  NM_001429.4 (NP_001420.2), 2414 amino acids
  NM_020964.3 (NP_066015.2), 2579 amino acids
  NM_004444.5 (NP_004435.3), 987 amino acids
  NM_000400.4 (NP_000391.1), 760 amino acids
  NM_000124.4 (NP_000115.1), 1493 amino acids
  NM_001277058.2 (NP_001263987.1), 1061 amino acids
  NM_000082.4 (NP_000073.1), 396 amino acids
  NM_001017420.3 (NP_001017420.1), 601 amino acids
  NM_004453.4 (NP_004444.2), 617 amino acids
  NM_014297.5 (NP_055112.2), 254 amino acids
  NM_153717.3 (NP_714928.1), 992 amino acids
  NM_147127.5 (NP_667338.3), 1308 amino acids
  NM_000127.3 (NP_000118.2), 746 amino acids
  NM_207122.2 (NP_997005.1), 718 amino acids
  NM_000503.6 (NP_000494.2), 592 amino acids
  NM_004100.5 (NP_004091.3), 639 amino acids
  NM_001142800.2 (NP_001136272.1), 3144 amino acids
  NM_000128.4 (NP_000119.1), 625 amino acids
  NM_000130.4 (NP_000121.2), 2224 amino acids
  NM_000130.5 (NP_000121.2), 2224 amino acids
  NM_000131.4 (NP_000122.1), 466 amino acids
  NM_000131.5 (NP_000122.1), 466 amino acids
  NM_019616.4 (NP_062562.1), 444 amino acids
  NM_000132.4 (NP_000123.1), 2351 amino acids
  NM_000133.4 (NP_000124.1), 461 amino acids
  NM_000137.4 (NP_000128.1), 419 amino acids
  NM_001201543.2 (NP_001188472.1), 716 amino acids
  NM_000135.4 (NP_000126.2), 1455 amino acids
  NM_000136.3 (NP_000127.2), 558 amino acids
  NM_001018115.3 (NP_001018125.1), 1451 amino acids
  NM_004629.2 (NP_004620.1), 622 amino acids
  NM_001113378.2 (NP_001106849.1), 1328 amino acids
  NM_018062.4 (NP_060532.2), 375 amino acids
  NM_020937.4 (NP_065988.1), 2048 amino acids
  NM_000043.6 (NP_000034.1), 335 amino acids
  NM_000138.5 (NP_000129.3), 2871 amino acids
  NM_001999.4 (NP_001990.2), 2912 amino acids
  NM_001278716.2 (NP_001265645.1), 621 amino acids
  NM_001190274.2 (NP_001177203.1), 927 amino acids
  NM_000140.3 (NP_000131.2), 423 amino acids
  NM_000140.5 (NP_000131.2), 423 amino acids
  NM_023110.3 (NP_075598.2), 822 amino acids
  NM_000141.5 (NP_000132.3), 821 amino acids
  NM_000142.5 (NP_000133.1), 806 amino acids
  NM_000143.4 (NP_000134.2), 510 amino acids
  NM_001159699.2 (NP_001153171.1), 296 amino acids
  NM_001159702.3 (NP_001153174.1), 323 amino acids
  NM_014845.6 (NP_055660.1), 907 amino acids
  NM_024301.5 (NP_077277.1), 495 amino acids
  NM_001079802.2 (NP_001073270.1), 461 amino acids
  NM_144997.7 (NP_659434.2), 579 amino acids
  NM_002016.2 (NP_002007.1), 4061 amino acids
  NM_001110556.2 (NP_001104026.1), 2647 amino acids
  NM_001457.4 (NP_001448.2), 2602 amino acids
  NM_001458.5 (NP_001449.3), 2725 amino acids
  NM_182925.5 (NP_891555.2), 1363 amino acids
  NM_001002294.3 (NP_001002294.1), 532 amino acids
  NM_001453.3 (NP_001444.2), 553 amino acids
  NM_005249.5 (NP_005240.3), 489 amino acids
  NM_023067.4 (NP_075555.1), 376 amino acids
  NM_001349338.3 (NP_001336267.1), 677 amino acids
  NM_025074.7 (NP_079350.5), 4012 amino acids
  NM_207361.6 (NP_997244.4), 3169 amino acids
  NM_000147.5 (NP_000138.2), 466 amino acids
  NM_000151.4 (NP_000142.2), 357 amino acids
  NM_000402.4 (NP_000393.4), 545 amino acids
  NM_001042351.3 (NP_001035810.1), 515 amino acids
  NM_001360016.2 (NP_001346945.1), 515 amino acids
  NM_000152.5 (NP_000143.2), 952 amino acids
  NM_001127644.2 (NP_001121116.1), 456 amino acids
  NM_001371727.1 (NP_001358656.1), 512 amino acids
  NM_000814.6 (NP_000805.1), 473 amino acids
  NM_021912.5 (NP_068712.1), 473 amino acids
  NM_198904.4 (NP_944494.1), 475 amino acids
  NM_000153.4 (NP_000144.2), 685 amino acids
  NM_001201402.2 (NP_001188331.1), 659 amino acids
  NM_000154.2 (NP_000145.1), 392 amino acids
  NM_000512.5 (NP_000503.1), 522 amino acids
  NM_000155.4 (NP_000146.2), 379 amino acids
  NM_000156.6 (NP_000147.1), 236 amino acids
  NM_032638.5 (NP_116027.2), 480 amino acids
  NM_020699.4 (NP_065750.1), 593 amino acids
  NM_000157.4 (NP_000148.2), 536 amino acids
  NM_000158.4 (NP_000149.4), 702 amino acids
  NM_000159.4 (NP_000150.1), 438 amino acids
  NM_000161.3 (NP_000152.1), 250 amino acids
  NM_000162.5 (NP_000153.1), 465 amino acids
  NM_018972.4 (NP_061845.2), 358 amino acids
  NM_002055.5 (NP_002046.1), 432 amino acids
  NM_024996.7 (NP_079272.4), 751 amino acids
  NM_000165.5 (NP_000156.1), 382 amino acids
  NM_000166.6 (NP_000157.1), 283 amino acids
  NM_001097642.3 (NP_001091111.1), 283 amino acids
  NM_004004.6 (NP_003995.2), 226 amino acids
  NM_000169.3 (NP_000160.1), 429 amino acids
  NM_000404.4 (NP_000395.3), 677 amino acids
  NM_000170.3 (NP_000161.2), 1020 amino acids
  NM_001003722.2 (NP_001003722.1), 698 amino acids
  NM_000168.6 (NP_000159.3), 1580 amino acids
  NM_000171.4 (NP_000162.2), 449 amino acids
  NM_020988.3 (NP_066268.1), 354 amino acids
  NM_000516.7 (NP_000507.1), 394 amino acids
  NM_016592.5 (NP_057676.1), 245 amino acids
  NM_080425.4 (NP_536350.2), 1037 amino acids
  NM_002074.5 (NP_002065.1), 340 amino acids
  NM_001128227.3 (NP_001121699.1), 753 amino acids
  NM_005476.7 (NP_005467.1), 722 amino acids
  NM_024312.5 (NP_077288.2), 1256 amino acids
  NM_032520.5 (NP_115909.1), 305 amino acids
  NM_000273.3 (NP_000264.2), 404 amino acids
  NM_012203.2 (NP_036335.1), 328 amino acids
  NM_007327.4 (NP_015566.1), 938 amino acids
  NM_001134407.3 (NP_001127879.1), 1464 amino acids
  NM_000834.5 (NP_000825.2), 1484 amino acids
  NM_002087.4 (NP_002078.1), 593 amino acids
  NM_000180.4 (NP_000171.1), 1103 amino acids
  NM_000181.4 (NP_000172.2), 651 amino acids
  NM_000182.5 (NP_000173.2), 763 amino acids
  NM_000183.3 (NP_000174.1), 474 amino acids
  NM_000517.4 (NP_000508.1), 142 amino acids
  NM_000517.6 (NP_000508.1), 142 amino acids
  NM_000518.4 (NP_000509.1), 147 amino acids
  NM_000518.5 (NP_000509.1), 147 amino acids
  NM_018486.3 (NP_060956.1), 377 amino acids
  NM_000520.6 (NP_000511.2), 529 amino acids
  NM_000521.4 (NP_000512.2), 556 amino acids

In [45]:
pd.set_option("display.max_columns", 10)
score_df_all.to_csv("score_record_df_all.csv", index = False)
score_df_all.head(10)

   gene   protein_id              species   score
0  AAAS  NP_056480.1         Homo sapiens  0.9210
1  AAAS  NP_056480.1         Homo sapiens  1.0000
2  AAAS  NP_056480.1      Pan troglodytes  0.9976
3  AAAS  NP_056480.1      Pan troglodytes  0.9892
4  AAAS  NP_056480.1      Pan troglodytes  0.9102
5  AAAS  NP_056480.1      Pan troglodytes  0.9186
6  AAAS  NP_056480.1  Macaca fascicularis  0.9849
7  AAAS  NP_056480.1  Macaca fascicularis  0.9788
8  AAAS  NP_056480.1  Macaca fascicularis  0.9058
9  AAAS  NP_056480.1  Macaca fascicularis  0.6932

In [46]:
os.getcwd()

'/Users/adesinamary/Documents/kondrashov'