## Download [Variant_summary.txt.gz](https://ftp.ncbi.nlm.nih.gov/pub/clinvar/tab_delimited/) from Clinvar database

#### This file is a compilation of all gene variants and classification

In [1]:
run kondrashov

In [33]:
import pandas as pd

##### Read the file using pandas as 'pd'

In [79]:
import os
os.getcwd()

'C:\\Users\\adesi\\Documents\\GitHub\\kondrashov'

In [39]:
vardata = pd.read_table('C:\\Users\\adesi\\Downloads\\variant_summary.txt\\variant_summary.txt', sep='\t')

C:\Users\adesi\AppData\Local\Temp\ipykernel_25092\357195269.py:1: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  vardata = pd.read_table('C:\\Users\\adesi\\Downloads\\variant_summary.txt\\variant_summary.txt', sep='\t')

In [40]:
vardata.head()

,#AlleleID,Type,Name,GeneID,GeneSymbol,HGNC_ID,ClinicalSignificance,ClinSigSimple,LastEvaluated,RS# (dbSNP),...,AlternateAlleleVCF,SomaticClinicalImpact,SomaticClinicalImpactLastEvaluated,ReviewStatusClinicalImpact,Oncogenicity,OncogenicityLastEvaluated,ReviewStatusOncogenicity,SCVsForAggregateGermlineClassification,SCVsForAggregateSomaticClinicalImpact,SCVsForAggregateOncogenicityClassification
0,15041,Indel,NM_014855.3(AP5Z1):c.80_83delinsTGCTGTAAACTGTA...,9907,AP5Z1,HGNC:22197,Pathogenic/Likely pathogenic,1,"Dec 17, 2024",397704705,...,TGCTGTAAACTGTAACTGTAAA,-,-,-,-,-,-,SCV001451119|SCV005622007|SCV005909190,-,-
1,15041,Indel,NM_014855.3(AP5Z1):c.80_83delinsTGCTGTAAACTGTA...,9907,AP5Z1,HGNC:22197,Pathogenic/Likely pathogenic,1,"Dec 17, 2024",397704705,...,TGCTGTAAACTGTAACTGTAAA,-,-,-,-,-,-,SCV001451119|SCV005622007|SCV005909190,-,-
2,15042,Deletion,NM_014855.3(AP5Z1):c.1413_1426del (p.Leu473fs),9907,AP5Z1,HGNC:22197,Pathogenic,1,"Jun 29, 2010",397704709,...,G,-,-,-,-,-,-,SCV000020156,-,-
3,15042,Deletion,NM_014855.3(AP5Z1):c.1413_1426del (p.Leu473fs),9907,AP5Z1,HGNC:22197,Pathogenic,1,"Jun 29, 2010",397704709,...,G,-,-,-,-,-,-,SCV000020156,-,-
4,15043,single nucleotide variant,NM_014630.3(ZNF592):c.3136G>A (p.Gly1046Arg),9640,ZNF592,HGNC:28986,Uncertain significance,0,"Jun 29, 2015",150829393,...,A,-,-,-,-,-,-,SCV000020157,-,-

In [41]:
#vardata.ClinicalSignificance
vardata["GeneID"]
vardata.items()
vardata.keys()

Index(['#AlleleID', 'Type', 'Name', 'GeneID', 'GeneSymbol', 'HGNC_ID',
       'ClinicalSignificance', 'ClinSigSimple', 'LastEvaluated', 'RS# (dbSNP)',
       'nsv/esv (dbVar)', 'RCVaccession', 'PhenotypeIDS', 'PhenotypeList',
       'Origin', 'OriginSimple', 'Assembly', 'ChromosomeAccession',
       'Chromosome', 'Start', 'Stop', 'ReferenceAllele', 'AlternateAllele',
       'Cytogenetic', 'ReviewStatus', 'NumberSubmitters', 'Guidelines',
       'TestedInGTR', 'OtherIDs', 'SubmitterCategories', 'VariationID',
       'PositionVCF', 'ReferenceAlleleVCF', 'AlternateAlleleVCF',
       'SomaticClinicalImpact', 'SomaticClinicalImpactLastEvaluated',
       'ReviewStatusClinicalImpact', 'Oncogenicity',
       'OncogenicityLastEvaluated', 'ReviewStatusOncogenicity',
       'SCVsForAggregateGermlineClassification',
       'SCVsForAggregateSomaticClinicalImpact',
       'SCVsForAggregateOncogenicityClassification'],
      dtype='object')

##### shown above are the various categories of classfication for each variant

#### We are interested in these classification of variants
* 'Type' : 'single nucleotide variant'
* 'single nucleotide variant' : "Pathogenic", "Likely pathogenic", "Pathogenic/Likely pathogenic", "Pathogenic, low penetrance", "Likely pathogenic, and low penetrance"
* 'Assembly' : 'GRCh38'

In [47]:
vardata['ClinicalSignificance'].unique()

array(['Pathogenic/Likely pathogenic', 'Pathogenic',
       'Uncertain significance', 'Likely pathogenic',
       'Conflicting classifications of pathogenicity',
       'Pathogenic/Pathogenic, low penetrance; risk factor',
       'Conflicting classifications of pathogenicity; other', 'Benign',
       'risk factor', 'Likely benign', 'association',
       'Likely pathogenic; risk factor', 'Benign/Likely benign',
       'no classification for the single variant',
       'Conflicting classifications of pathogenicity; risk factor',
       'drug response', 'Affects', 'Benign; drug response',
       'Likely benign; drug response',
       'Conflicting classifications of pathogenicity; association; risk factor',
       'Pathogenic; risk factor', 'Benign; risk factor',
       'no classifications from unflagged records',
       'Benign/Likely benign; other',
       'Pathogenic/Likely pathogenic; risk factor', 'Benign; other',
       'not provided', 'protective; risk factor', 'Likely benign; other',
       'Conflicting classifications of pathogenicity; association',
       'Pathogenic; Affects', 'Benign/Likely benign; association',
       'association; drug response; risk factor',
       'Benign/Likely benign; other; risk factor', 'Benign; protective',
       'Pathogenic/Likely pathogenic/Likely pathogenic, low penetrance',
       'drug response; risk factor', 'Pathogenic; drug response',
       'protective', 'Likely risk allele',
       'Uncertain significance/Uncertain risk allele',
       'Conflicting classifications of pathogenicity; protective',
       'Uncertain significance; risk factor', 'drug response; other',
       'Likely benign; drug response; other', '-',
       'Uncertain significance; drug response',
       'Likely pathogenic; drug response', 'other', 'Pathogenic; other',
       'Conflicting classifications of pathogenicity; drug response; other',
       'Conflicting classifications of pathogenicity; drug response',
       'Benign; association',
       'Pathogenic/Likely pathogenic/Pathogenic, low penetrance',
       'Likely pathogenic; association',
       'Pathogenic/Likely pathogenic/Pathogenic, low penetrance/Established risk allele; risk factor',
       'Pathogenic/Likely risk allele',
       'Likely pathogenic/Likely risk allele',
       'Pathogenic/Likely pathogenic/Likely risk allele',
       'Conflicting classifications of pathogenicity; other; risk factor',
       'Pathogenic; protective', 'other; risk factor',
       'Uncertain significance; other',
       'Pathogenic/Likely pathogenic; other',
       'Likely pathogenic, low penetrance', 'Pathogenic, low penetrance',
       'Benign/Likely benign; drug response; other', 'Benign; Affects',
       'Pathogenic/Pathogenic, low penetrance; other',
       'association; protective', 'Likely benign; Affects; association',
       'conflicting data from submitters',
       'Uncertain significance; Pathogenic/Likely pathogenic',
       'Uncertain significance/VUS-high',
       'Uncertain risk allele; risk factor',
       'Pathogenic/Likely pathogenic; drug response',
       'Pathogenic/Likely pathogenic; association', 'VUS-high',
       'Uncertain significance/VUS-mid', 'Likely benign; risk factor',
       'Benign/Likely benign; drug response',
       'Benign/Likely benign; risk factor',
       'Pathogenic/Pathogenic, low penetrance', 'Uncertain risk allele',
       'Benign; confers sensitivity',
       'Uncertain significance; association',
       'Likely pathogenic/Pathogenic, low penetrance',
       'association; risk factor', 'Pathogenic; confers sensitivity',
       'Conflicting classifications of pathogenicity; Affects',
       'Pathogenic; association', 'Likely pathogenic; Affects',
       'association not found', 'Likely benign; association',
       'Likely pathogenic; protective',
       'Benign; Affects; association; other',
       'Pathogenic/Likely pathogenic/Established risk allele',
       'Uncertain significance; Affects', 'confers sensitivity',
       'confers sensitivity; other',
       'Established risk allele; association',
       'Likely pathogenic/Likely pathogenic, low penetrance',
       'Pathogenic/Likely pathogenic, low penetrance',
       'Uncertain significance/VUS-low', 'VUS-low',
       'Established risk allele', 'VUS-mid'], dtype=object)

In [ ]:
terms = ["Pathogenic", "Likely pathogenic", "Pathogenic/Likely pathogenic", "Pathogenic, low penetrance", "Likely pathogenic, low penetrance"]

XX = vardata[ 
(vardata["GeneSymbol"] == "BTK" )&
(vardata["ClinicalSignificance"].isin (terms)) &
(vardata["Type"] == "single nucleotide variant") &
(vardata["Assembly"] == "GRCh38")
]

#XX.to_csv(f"c:\\Users\\adesi\\Documents\\GitHub\\kondrashov\\clinvar\\ALPL_CS_extend.txt", sep="\t", index= False)

In [67]:
len(XX)
XX
#print(XX["ClinicalSignificance"])

,#AlleleID,Type,Name,GeneID,GeneSymbol,HGNC_ID,ClinicalSignificance,ClinSigSimple,LastEvaluated,RS# (dbSNP),...,AlternateAlleleVCF,SomaticClinicalImpact,SomaticClinicalImpactLastEvaluated,ReviewStatusClinicalImpact,Oncogenicity,OncogenicityLastEvaluated,ReviewStatusOncogenicity,SCVsForAggregateGermlineClassification,SCVsForAggregateSomaticClinicalImpact,SCVsForAggregateOncogenicityClassification
20649,26381,single nucleotide variant,NM_000061.3(BTK):c.1574G>A (p.Arg525Gln),695,BTK,HGNC:1133,Pathogenic/Likely pathogenic,1,"Nov 24, 2025",128620183,...,T,-,-,-,-,-,-,SCV000052059|SCV001375572|SCV001446420|SCV0076...,-,-
20651,26382,single nucleotide variant,NM_000061.3(BTK):c.1288A>G (p.Lys430Glu),695,BTK,HGNC:1133,Pathogenic,1,"Jan 21, 1993",128620184,...,C,-,-,-,-,-,-,SCV000032330,-,-
20653,26383,single nucleotide variant,NM_000061.3(BTK):c.37C>T (p.Arg13Ter),695,BTK,HGNC:1133,Pathogenic,1,"Dec 23, 2025",128620187,...,A,-,-,-,-,-,-,SCV000052061|SCV005839444|SCV006301773,-,-
20655,26384,single nucleotide variant,NM_000061.3(BTK):c.43C>T (p.Gln15Ter),695,BTK,HGNC:1133,Pathogenic/Likely pathogenic,1,"Jan 30, 2023",128620188,...,A,-,-,-,-,-,-,SCV001190119|SCV003445306|SCV003801331,-,-
20657,26385,single nucleotide variant,NM_000061.3(BTK):c.1082A>G (p.Tyr361Cys),695,BTK,HGNC:1133,Likely pathogenic,1,"Oct 15, 2025",28935478,...,C,-,-,-,-,-,-,SCV004300167,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8823603,4882368,single nucleotide variant,NM_000061.3(BTK):c.931A>T (p.Lys311Ter),695,BTK,HGNC:1133,Pathogenic,1,"Apr 28, 2025",-1,...,A,-,-,-,-,-,-,SCV007456406,-,-
8873723,4907724,single nucleotide variant,NM_000061.3(BTK):c.862C>G (p.Arg288Gly),695,BTK,HGNC:1133,Pathogenic,1,-,-1,...,C,-,-,-,-,-,-,SCV007495875,-,-
8873903,4907814,single nucleotide variant,NM_000061.3(BTK):c.1881T>A (p.Tyr627Ter),695,BTK,HGNC:1133,Likely pathogenic,1,"Dec 23, 2025",-1,...,T,-,-,-,-,-,-,SCV007496133,-,-
8980208,4961878,single nucleotide variant,NM_000061.3(BTK):c.1A>G (p.Met1Val),695,BTK,HGNC:1133,Likely pathogenic,1,"Mar 16, 2026",-1,...,C,-,-,-,-,-,-,SCV007595796,-,-
8987497,4965863,single nucleotide variant,NM_000061.3(BTK):c.1563C>A (p.Asp521Glu),695,BTK,HGNC:1133,Likely pathogenic,1,"Jul 22, 2025",-1,...,T,-,-,-,-,-,-,SCV007611240,-,-

### test script with fewer genes

In [ ]:
loci = [
    "ABCD1",
    "ALPL",
    "AR",
    "ATP7B"]

terms = ["Pathogenic", "Likely pathogenic"]

for gene in loci:
    filtered = vardata[
        (vardata["GeneSymbol"] == gene )&
        (vardata["ClinicalSignificance"].isin (terms)) &
        (vardata["Type"] == "single nucleotide variant")
        ]
    filtered.to_csv(f"clinvar/{gene}.txt", sep="\t", index= False)
    print(f"{gene}: {len(filtered)} rows written")

## Run this
### This code extracts variants of interest as .txt file, per gene, from the dadatabase file

In [72]:
os.chdir('C:\\Users\\adesi\\Documents\\GitHub\\kondrashov')

In [73]:
run kondrashov

In [75]:
terms = ["Pathogenic", "Likely pathogenic", "Pathogenic/Likely pathogenic", "Pathogenic, low penetrance", "Likely pathogenic, low penetrance"]

for gene in loci:
    filtered = vardata[
        (vardata["GeneSymbol"] == gene )&
        (vardata["ClinicalSignificance"].isin (terms)) &
        (vardata["Type"] == "single nucleotide variant") &
        (vardata["Assembly"] == "GRCh38")
        ]
    filtered.to_csv(f"clinvar/{gene}.txt", sep="\t", index= False)
    print(f"{gene}: {len(filtered)} variants written to clinvar/{gene}.txt")

ABCD1: 327 variants written to clinvar/ABCD1.txt
ALPL: 404 variants written to clinvar/ALPL.txt
AR: 269 variants written to clinvar/AR.txt
ATP7B: 424 variants written to clinvar/ATP7B.txt
BTK: 245 variants written to clinvar/BTK.txt
CASR: 209 variants written to clinvar/CASR.txt
CBS: 198 variants written to clinvar/CBS.txt
CFTR: 773 variants written to clinvar/CFTR.txt
CYBB: 141 variants written to clinvar/CYBB.txt
F7: 80 variants written to clinvar/F7.txt
F8: 515 variants written to clinvar/F8.txt
F9: 274 variants written to clinvar/F9.txt
G6PD: 207 variants written to clinvar/G6PD.txt
GALT: 247 variants written to clinvar/GALT.txt
GBA1: 293 variants written to clinvar/GBA1.txt
GJB1: 201 variants written to clinvar/GJB1.txt
HBB: 183 variants written to clinvar/HBB.txt
HPRT1: 71 variants written to clinvar/HPRT1.txt
IL2RG: 113 variants written to clinvar/IL2RG.txt
KCNH2: 320 variants written to clinvar/KCNH2.txt
KCNQ1: 365 variants written to clinvar/KCNQ1.txt
L1CAM: 146 variants written to clinvar/L1CAM.txt
LDLR: 1096 variants written to clinvar/LDLR.txt
MPZ: 143 variants written to clinvar/MPZ.txt
MYH7: 412 variants written to clinvar/MYH7.txt
TYR: 237 variants written to clinvar/TYR.txt
PAH: 692 variants written to clinvar/PAH.txt
PMM2: 174 variants written to clinvar/PMM2.txt
RHO: 173 variants written to clinvar/RHO.txt
TP53: 417 variants written to clinvar/TP53.txt
TTR: 130 variants written to clinvar/TTR.txt
VWF: 310 variants written to clinvar/VWF.txt

### Using pandas I'll convert my already filtered variants in .txt to .csv

In [ ]:
import pandas as pd
myvardata = pd.read_table('clinvar/ABCD1.txt', sep= '\t')

In [ ]:
myvardata.to_csv('pathogenic/ABCD1.csv', index=False)

### test script with fewer genes

In [ ]:
loci = ["ABCD1",
        "RHO",
        "F7"]
for gene in loci:
        myvardata = pd.read_table('clinvar/' + gene + '.txt', sep='\t')
        myvardata.to_csv('pathogenic/' + gene + '.csv', index = False)

## Run this

### Note: '/clinvar' and '/pathogenic' directories contain same file contents in .txt and .csv formats respectively

In [77]:
run kondrashov

In [78]:
for gene in loci:
        myvardata = pd.read_table('clinvar/' + gene + '.txt', sep='\t')
        myvardata.to_csv('pathogenic/' + gene + '.csv', index = False)

In [9]:
os.chdir('c:\\Users\\adesi\\Documents\\GitHub\\kondrashov\\pathogenic')

In [11]:
os.listdir()

['ABCD1.csv',
 'ALPL.csv',
 'AR.csv',
 'ATP7B.csv',
 'BTK.csv',
 'CASR.csv',
 'CBS.csv',
 'CFTR.csv',
 'CYBB.csv',
 'F7.csv',
 'F8.csv',
 'F9.csv',
 'G6PD.csv',
 'GALT.csv',
 'GBA1.csv',
 'GCDP_filtered.csv',
 'GCDP_filtered.html',
 'GJB1.csv',
 'HBB.csv',
 'HPRT1.csv',
 'IL2RG.csv',
 'KCNH2.csv',
 'KCNQ1.csv',
 'L1CAM.csv',
 'LDLR.csv',
 'MPZ.csv',
 'MYH7.csv',
 'PAH.csv',
 'PMM2.csv',
 'RHO.csv',
 'TP53.csv',
 'TTR.csv',
 'TYR.csv',
 'VWF.csv']