### let's Validate the CPDs in "C:\Users\adesi\Documents\GitHub\kondrashov\invalidated_CPDs_match_JUL31.tsv"

In [1]:
run kondrashov

In [2]:

align = AlignIO.read("ATP7B_NP_000044.2_match.aln", "fasta")

FileNotFoundError: [Errno 2] No such file or directory: 'ATP7B_NP_000044.2_match.aln'

In [25]:
print(align.get_alignment_length())

1584

In [8]:
import os

#os.mkdir("C://Users/adesi/Documents/kondrashov/")
#os.chdir("C:/Users/adesi/Documents/GitHub/kondrashov/")
os.chdir("/Users/adesinamary/Documents/kondrashov/Outputs_primates")

In [11]:
import pandas as pd
df = pd.read_csv("AllGenes_potential_CPDs.csv", sep=",")
df.head(10)
#df.keys()
#print(df['Transcript'])
#df.columns
#row = df.iloc[1]
#print(row)

     gene   transcript      protein  site wilds muts variable_amino_acids
0   ACADM  NM_000016.6  NP_000007.1    29     R    L      ['P', 'L', 'Q']
1   ACADM  NM_000016.6  NP_000007.1    31     R    H      ['H', 'G', 'C']
2   ACADM  NM_000016.6  NP_000007.1   103     F    L                ['L']
3   ACADM  NM_000016.6  NP_000007.1    29     R    Q      ['P', 'L', 'Q']
4  ACADVL  NM_000018.4  NP_000009.1   174     V    M                ['M']
5  ACADVL  NM_000018.4  NP_000009.1   219     P    S                ['S']
6  ACADVL  NM_000018.4  NP_000009.1   286     R    K                ['K']
7  ACADVL  NM_000018.4  NP_000009.1   647     V    M                ['M']
8   ACAT1  NM_000019.4  NP_000010.1     1     M    L           ['D', 'L']
9   ACAT1  NM_000019.4  NP_000010.1     1     M    L           ['D', 'L']

In [ ]:
import pandas as pd
df = pd.read_csv("invalidated_CPDs_match_JUL31.tsv", sep="\t")

for gene in ['ATP7B', 'GALT', 'GBA']:
    get_alleles(gene, protein, site, True)



for each row in 'df' apply this function ; get_alleles(gene, protein, site, True)

_IncompleteInputError: incomplete input (2123714797.py, line 2)

#### This function calls; gene, protein, position, verbose

In [12]:
get_alleles('ATP7B', 'NP_000044.2', 335, True)

FileNotFoundError: [Errno 2] No such file or directory: 'fasta_lociii_match/ATP7B_NP_000044.2_match.fasta'

In [14]:
local_compare_to_human('ATP7B', translation['NM_000053.4'], 335, 'XP_012638109.2')

NameError: name 'translation' is not defined

### Step 1 
Run this function for all gene variants, identify what species has the identified variant

In [16]:
df

       gene   transcript      protein  site wilds muts variable_amino_acids
0     ACADM  NM_000016.6  NP_000007.1    29     R    L      ['P', 'L', 'Q']
1     ACADM  NM_000016.6  NP_000007.1    31     R    H      ['H', 'G', 'C']
2     ACADM  NM_000016.6  NP_000007.1   103     F    L                ['L']
3     ACADM  NM_000016.6  NP_000007.1    29     R    Q      ['P', 'L', 'Q']
4    ACADVL  NM_000018.4  NP_000009.1   174     V    M                ['M']
..      ...          ...          ...   ...   ...  ...                  ...
135     VHL  NM_000551.4  NP_000542.1   161     R    G                ['G']
136     VHL  NM_000551.4  NP_000542.1   170     V    L                ['L']
137     VWF  NM_000552.5  NP_000543.3   528     N    S                ['S']
138     WT1  NM_024426.6  NP_077744.4   341     S    G                ['G']
139    ZEB2  NM_014795.4  NP_055610.1  1049     H    R                ['R']

[140 rows x 7 columns]

In [19]:
os.getcwd()
os.chdir("/Users/adesinamary/Documents/kondrashov")

In [26]:
for _, row in df.iterrows():
    gene = row["gene"]
    protein = row["protein"]
    site = int(row["site"])

    result = get_alleles(gene, protein, site, True)

     Gene: ACADM
    Human: 29 R
Alignment: 117 R
R    20
P     6
L     4
-     3
Q     1
Name: count, dtype: int64

P XP_012516579.1 Propithecus coquereli
P XP_012657175.1 Otolemur garnettii
P XP_053447073.1 Nycticebus coucang
- XP_008053273.1 Carlito syrichta
P XP_012643243.1 Microcebus murinus
P XP_045403682.1 Lemur catta
P XP_069334191.1 Eulemur rufifrons
L XP_064228588.1 Aotus nancymaae
- XP_037595556.1 Cebus imitator
L XP_039329541.1 Saimiri boliviensis
L XP_035107801.2 Callithrix jacchus
L XP_032152462.1 Sapajus apella
R XP_063480144.1 Symphalangus syndactylus
Q XP_032011454.1 Hylobates moloch
R XP_009247163.2 Pongo abelii
R XP_054350511.1 Pongo pygmaeus
R XP_018875470.2 Gorilla gorilla gorilla
R NP_000007.1 Homo sapiens
R NP_001104286.1 Pan troglodytes
R XP_003830620.1 Pan paniscus
R XP_017707083.1 Rhinopithecus bieti
R XP_010366900.1 Rhinopithecus roxellana
R XP_023065093.1 Piliocolobus tephrosceles
R XP_033081217.1 Trachypithecus francoisi
R XP_011792328.1 Colobus angolensis palliatus
R XP_011937597.1 Cercocebus atys
R XP_005543049.3 Macaca fascicularis
R XP_021798821.1 Papio anubis
R XP_001101274.2 Macaca mulatta
R XP_050661074.1 Macaca thibetana thibetana
R XP_025240877.1 Theropithecus gelada
R XP_011741173.2 Macaca nemestrina
R XP_037857788.1 Chlorocebus sabaeus
- XP_011833234.1 Mandrillus leucophaeus
     Gene: ACADM
    Human: 31 R
Alignment: 119 R
R    26
-     3
H     2
G     2
C     1
Name: count, dtype: int64

C XP_012516579.1 Propithecus coquereli
H XP_012657175.1 Otolemur garnettii
H XP_053447073.1 Nycticebus coucang
- XP_008053273.1 Carlito syrichta
R XP_012643243.1 Microcebus murinus
G XP_045403682.1 Lemur catta
G XP_069334191.1 Eulemur rufifrons
R XP_064228588.1 Aotus nancymaae
- XP_037595556.1 Cebus imitator
R XP_039329541.1 Saimiri boliviensis
R XP_035107801.2 Callithrix jacchus
R XP_032152462.1 Sapajus apella
R XP_063480144.1 Symphalangus syndactylus
R XP_032011454.1 Hylobates moloch
R XP_009247163.2 Pongo abelii
R XP_054350511.1 Pongo pygmaeus
R XP_018875470.2 Gorilla gorilla gorilla
R NP_000007.1 Homo sapiens
R NP_001104286.1 Pan troglodytes
R XP_003830620.1 Pan paniscus
R XP_017707083.1 Rhinopithecus bieti
R XP_010366900.1 Rhinopithecus roxellana
R XP_023065093.1 Piliocolobus tephrosceles
R XP_033081217.1 Trachypithecus francoisi
R XP_011792328.1 Colobus angolensis palliatus
R XP_011937597.1 Cercocebus atys
R XP_005543049.3 Macaca fascicularis
R XP_021798821.1 Papio anubis
R XP_001101274.2 Macaca mulatta
R XP_050661074.1 Macaca thibetana thibetana
R XP_025240877.1 Theropithecus gelada
R XP_011741173.2 Macaca nemestrina
R XP_037857788.1 Chlorocebus sabaeus
- XP_011833234.1 Mandrillus leucophaeus
     Gene: ACADM
    Human: 103 F
Alignment: 191 F
F    32
L     1
-     1
Name: count, dtype: int64

F XP_012516579.1 Propithecus coquereli
F XP_012657175.1 Otolemur garnettii
F XP_053447073.1 Nycticebus coucang
F XP_008053273.1 Carlito syrichta
F XP_012643243.1 Microcebus murinus
L XP_045403682.1 Lemur catta
F XP_069334191.1 Eulemur rufifrons
F XP_064228588.1 Aotus nancymaae
F XP_037595556.1 Cebus imitator
F XP_039329541.1 Saimiri boliviensis
F XP_035107801.2 Callithrix jacchus
F XP_032152462.1 Sapajus apella
F XP_063480144.1 Symphalangus syndactylus
F XP_032011454.1 Hylobates moloch
F XP_009247163.2 Pongo abelii
F XP_054350511.1 Pongo pygmaeus
F XP_018875470.2 Gorilla gorilla gorilla
F NP_000007.1 Homo sapiens
F NP_001104286.1 Pan troglodytes
F XP_003830620.1 Pan paniscus
F XP_017707083.1 Rhinopithecus bieti
F XP_010366900.1 Rhinopithecus roxellana
F XP_023065093.1 Piliocolobus tephrosceles
F XP_033081217.1 Trachypithecus francoisi
F XP_011792328.1 Colobus angolensis palliatus
F XP_011937597.1 Cercocebus atys
F XP_005543049.3 Macaca fascicularis
F XP_021798821.1 Papio anubis
F XP_001101274.2 Macaca mulatta
F XP_050661074.1 Macaca thibetana thibetana
F XP_025240877.1 Theropithecus gelada
F XP_011741173.2 Macaca nemestrina
F XP_037857788.1 Chlorocebus sabaeus
- XP_011833234.1 Mandrillus leucophaeus
     Gene: ACADM
    Human: 29 R
Alignment: 117 R
R    20
P     6
L     4
-     3
Q     1
Name: count, dtype: int64

P XP_012516579.1 Propithecus coquereli
P XP_012657175.1 Otolemur garnettii
P XP_053447073.1 Nycticebus coucang
- XP_008053273.1 Carlito syrichta
P XP_012643243.1 Microcebus murinus
P XP_045403682.1 Lemur catta
P XP_069334191.1 Eulemur rufifrons
L XP_064228588.1 Aotus nancymaae
- XP_037595556.1 Cebus imitator
L XP_039329541.1 Saimiri boliviensis
L XP_035107801.2 Callithrix jacchus
L XP_032152462.1 Sapajus apella
R XP_063480144.1 Symphalangus syndactylus
Q XP_032011454.1 Hylobates moloch
R XP_009247163.2 Pongo abelii
R XP_054350511.1 Pongo pygmaeus
R XP_018875470.2 Gorilla gorilla gorilla
R NP_000007.1 Homo sapiens
R NP_001104286.1 Pan troglodytes
R XP_003830620.1 Pan paniscus
R XP_017707083.1 Rhinopithecus bieti
R XP_010366900.1 Rhinopithecus roxellana
R XP_023065093.1 Piliocolobus tephrosceles
R XP_033081217.1 Trachypithecus francoisi
R XP_011792328.1 Colobus angolensis palliatus
R XP_011937597.1 Cercocebus atys
R XP_005543049.3 Macaca fascicularis
R XP_021798821.1 Papio anubis
R XP_001101274.2 Macaca mulatta
R XP_050661074.1 Macaca thibetana thibetana
R XP_025240877.1 Theropithecus gelada
R XP_011741173.2 Macaca nemestrina
R XP_037857788.1 Chlorocebus sabaeus
- XP_011833234.1 Mandrillus leucophaeus
     Gene: ACADVL
    Human: 174 V
Alignment: 221 V
V    34
M     1
Name: count, dtype: int64

V XP_053423543.1 Nycticebus coucang
V XP_003791220.1 Otolemur garnettii
M XP_012511118.1 Propithecus coquereli
V XP_012632557.1 Microcebus murinus
V XP_045426011.1 Lemur catta
V XP_069338073.1 Eulemur rufifrons
V XP_008059122.1 Carlito syrichta
V XP_035155682.2 Callithrix jacchus
V XP_012312866.1 Aotus nancymaae
V XP_003929185.1 Saimiri boliviensis
V XP_017387177.1 Cebus imitator
V XP_032136424.1 Sapajus apella
V XP_011909030.1 Cercocebus atys
V XP_008008286.2 Chlorocebus sabaeus
V XP_011850018.1 Mandrillus leucophaeus
V XP_045231401.2 Macaca fascicularis
V XP_025216966.1 Theropithecus gelada
V XP_011725107.2 Macaca nemestrina
V XP_003912269.1 Papio anubis
V XP_050621267.1 Macaca thibetana thibetana
V XP_014973924.2 Macaca mulatta
V XP_023040339.1 Piliocolobus tephrosceles
V XP_011813867.1 Colobus angolensis palliatus
V XP_033040701.1 Trachypithecus francoisi
V XP_017705894.1 Rhinopithecus bieti
V XP_010375640.1 Rhinopithecus roxellana
V XP_055114570.1 Symphalangus syndactylus
V XP_003282188.3 Nomascus leucogenys
V XP_031995619.2 Hylobates moloch
V XP_054314073.1 Pongo pygmaeus
V XP_024090154.1 Pongo abelii
V XP_016786900.1 Pan troglodytes
V XP_003810154.1 Pan paniscus
V NP_000009.1 Homo sapiens
V XP_004058497.4 Gorilla gorilla gorilla
     Gene: ACADVL
    Human: 219 P
Alignment: 266 P
P    30
S     5
Name: count, dtype: int64

P XP_053423543.1 Nycticebus coucang
P XP_003791220.1 Otolemur garnettii
P XP_012511118.1 Propithecus coquereli
P XP_012632557.1 Microcebus murinus
P XP_045426011.1 Lemur catta
P XP_069338073.1 Eulemur rufifrons
P XP_008059122.1 Carlito syrichta
P XP_035155682.2 Callithrix jacchus
P XP_012312866.1 Aotus nancymaae
P XP_003929185.1 Saimiri boliviensis
P XP_017387177.1 Cebus imitator
P XP_032136424.1 Sapajus apella
P XP_011909030.1 Cercocebus atys
P XP_008008286.2 Chlorocebus sabaeus
P XP_011850018.1 Mandrillus leucophaeus
P XP_045231401.2 Macaca fascicularis
P XP_025216966.1 Theropithecus gelada
P XP_011725107.2 Macaca nemestrina
P XP_003912269.1 Papio anubis
P XP_050621267.1 Macaca thibetana thibetana
P XP_014973924.2 Macaca mulatta
P XP_023040339.1 Piliocolobus tephrosceles
P XP_011813867.1 Colobus angolensis palliatus
P XP_033040701.1 Trachypithecus francoisi
P XP_017705894.1 Rhinopithecus bieti
P XP_010375640.1 Rhinopithecus roxellana
S XP_055114570.1 Symphalangus syndactylus
S XP_003282188.3 Nomascus leucogenys
S XP_031995619.2 Hylobates moloch
P XP_054314073.1 Pongo pygmaeus
P XP_024090154.1 Pongo abelii
S XP_016786900.1 Pan troglodytes
S XP_003810154.1 Pan paniscus
P NP_000009.1 Homo sapiens
P XP_004058497.4 Gorilla gorilla gorilla
     Gene: ACADVL
    Human: 286 R
Alignment: 333 R
R    29
K     6
Name: count, dtype: int64

K XP_053423543.1 Nycticebus coucang
K XP_003791220.1 Otolemur garnettii
K XP_012511118.1 Propithecus coquereli
K XP_012632557.1 Microcebus murinus
K XP_045426011.1 Lemur catta
K XP_069338073.1 Eulemur rufifrons
R XP_008059122.1 Carlito syrichta
R XP_035155682.2 Callithrix jacchus
R XP_012312866.1 Aotus nancymaae
R XP_003929185.1 Saimiri boliviensis
R XP_017387177.1 Cebus imitator
R XP_032136424.1 Sapajus apella
R XP_011909030.1 Cercocebus atys
R XP_008008286.2 Chlorocebus sabaeus
R XP_011850018.1 Mandrillus leucophaeus
R XP_045231401.2 Macaca fascicularis
R XP_025216966.1 Theropithecus gelada
R XP_011725107.2 Macaca nemestrina
R XP_003912269.1 Papio anubis
R XP_050621267.1 Macaca thibetana thibetana
R XP_014973924.2 Macaca mulatta
R XP_023040339.1 Piliocolobus tephrosceles
R XP_011813867.1 Colobus angolensis palliatus
R XP_033040701.1 Trachypithecus francoisi
R XP_017705894.1 Rhinopithecus bieti
R XP_010375640.1 Rhinopithecus roxellana
R XP_055114570.1 Symphalangus syndactylus
R XP_003282188.3 Nomascus leucogenys
R XP_031995619.2 Hylobates moloch
R XP_054314073.1 Pongo pygmaeus
R XP_024090154.1 Pongo abelii
R XP_016786900.1 Pan troglodytes
R XP_003810154.1 Pan paniscus
R NP_000009.1 Homo sapiens
R XP_004058497.4 Gorilla gorilla gorilla
     Gene: ACADVL
    Human: 647 V
Alignment: 694 V
V    30
M     5
Name: count, dtype: int64

M XP_053423543.1 Nycticebus coucang
M XP_003791220.1 Otolemur garnettii
V XP_012511118.1 Propithecus coquereli
M XP_012632557.1 Microcebus murinus
M XP_045426011.1 Lemur catta
M XP_069338073.1 Eulemur rufifrons
V XP_008059122.1 Carlito syrichta
V XP_035155682.2 Callithrix jacchus
V XP_012312866.1 Aotus nancymaae
V XP_003929185.1 Saimiri boliviensis
V XP_017387177.1 Cebus imitator
V XP_032136424.1 Sapajus apella
V XP_011909030.1 Cercocebus atys
V XP_008008286.2 Chlorocebus sabaeus
V XP_011850018.1 Mandrillus leucophaeus
V XP_045231401.2 Macaca fascicularis
V XP_025216966.1 Theropithecus gelada
V XP_011725107.2 Macaca nemestrina
V XP_003912269.1 Papio anubis
V XP_050621267.1 Macaca thibetana thibetana
V XP_014973924.2 Macaca mulatta
V XP_023040339.1 Piliocolobus tephrosceles
V XP_011813867.1 Colobus angolensis palliatus
V XP_033040701.1 Trachypithecus francoisi
V XP_017705894.1 Rhinopithecus bieti
V XP_010375640.1 Rhinopithecus roxellana
V XP_055114570.1 Symphalangus syndactylus
V XP_003282188.3 Nomascus leucogenys
V XP_031995619.2 Hylobates moloch
V XP_054314073.1 Pongo pygmaeus
V XP_024090154.1 Pongo abelii
V XP_016786900.1 Pan troglodytes
V XP_003810154.1 Pan paniscus
V NP_000009.1 Homo sapiens
V XP_004058497.4 Gorilla gorilla gorilla
     Gene: ACAT1
    Human: 1 M
Alignment: 115 M
M    26
-     2
D     1
L     1
Name: count, dtype: int64

M XP_037601130.1 Cebus imitator
M XP_012629178.2 Microcebus murinus
D XP_017710761.1 Rhinopithecus bieti
M XP_032023195.1 Hylobates moloch
M XP_055128972.1 Symphalangus syndactylus
M XP_003253143.2 Nomascus leucogenys
M XP_008018937.2 Chlorocebus sabaeus
L XP_011840136.1 Mandrillus leucophaeus
- XP_050614664.1 Macaca thibetana thibetana
M XP_003910695.1 Papio anubis
M XP_011921893.1 Cercocebus atys
M XP_025214176.1 Theropithecus gelada
M XP_065385026.1 Macaca fascicularis
M NP_001252622.1 Macaca mulatta
M XP_033063540.1 Trachypithecus francoisi
M XP_011782059.1 Colobus angolensis palliatus
M XP_054297509.1 Pongo pygmaeus
M XP_030871760.2 Gorilla gorilla gorilla
M NP_000010.1 Homo sapiens
M XP_003828394.3 Pan paniscus
M XP_035120332.1 Callithrix jacchus
M XP_012330013.2 Aotus nancymaae
M XP_032141572.1 Sapajus apella
M XP_003923792.1 Saimiri boliviensis
M XP_053450024.1 Nycticebus coucang
M XP_023371827.1 Otolemur garnettii
- XP_008053486.1 Carlito syrichta
M XP_012514692.1 Propithecus coquereli
M XP_069327022.1 Eulemur rufifrons
M XP_045412622.1 Lemur catta
     Gene: ACAT1
    Human: 1 M
Alignment: 115 M
M    26
-     2
D     1
L     1
Name: count, dtype: int64

M XP_037601130.1 Cebus imitator
M XP_012629178.2 Microcebus murinus
D XP_017710761.1 Rhinopithecus bieti
M XP_032023195.1 Hylobates moloch
M XP_055128972.1 Symphalangus syndactylus
M XP_003253143.2 Nomascus leucogenys
M XP_008018937.2 Chlorocebus sabaeus
L XP_011840136.1 Mandrillus leucophaeus
- XP_050614664.1 Macaca thibetana thibetana
M XP_003910695.1 Papio anubis
M XP_011921893.1 Cercocebus atys
M XP_025214176.1 Theropithecus gelada
M XP_065385026.1 Macaca fascicularis
M NP_001252622.1 Macaca mulatta
M XP_033063540.1 Trachypithecus francoisi
M XP_011782059.1 Colobus angolensis palliatus
M XP_054297509.1 Pongo pygmaeus
M XP_030871760.2 Gorilla gorilla gorilla
M NP_000010.1 Homo sapiens
M XP_003828394.3 Pan paniscus
M XP_035120332.1 Callithrix jacchus
M XP_012330013.2 Aotus nancymaae
M XP_032141572.1 Sapajus apella
M XP_003923792.1 Saimiri boliviensis
M XP_053450024.1 Nycticebus coucang
M XP_023371827.1 Otolemur garnettii
- XP_008053486.1 Carlito syrichta
M XP_012514692.1 Propithecus coquereli
M XP_069327022.1 Eulemur rufifrons
M XP_045412622.1 Lemur catta
     Gene: ADA
    Human: 15 H
Alignment: 54 H
H    32
P     1
Name: count, dtype: int64

H XP_008065101.1 Carlito syrichta
H XP_053429777.1 Nycticebus coucang
H XP_012659258.1 Otolemur garnettii
H XP_075867256.1 Microcebus murinus
H XP_012513400.1 Propithecus coquereli
H XP_069351986.1 Eulemur rufifrons
H XP_045385118.1 Lemur catta
P XP_017733490.1 Rhinopithecus bieti
H XP_032119629.1 Sapajus apella
H XP_017396666.1 Cebus imitator
H XP_010345201.1 Saimiri boliviensis
H XP_002747684.1 Callithrix jacchus
H XP_012322665.1 Aotus nancymaae
H XP_011853020.1 Mandrillus leucophaeus
H XP_050662503.1 Macaca thibetana thibetana
H NP_000013.2 Homo sapiens
H XP_033042389.1 Trachypithecus francoisi
H XP_011784375.1 Colobus angolensis palliatus
H XP_023083619.1 Piliocolobus tephrosceles
H XP_025255097.1 Theropithecus gelada
H XP_008014692.1 Chlorocebus sabaeus
H XP_003904754.1 Papio anubis
H XP_011921136.1 Cercocebus atys
H XP_028684274.1 Macaca mulatta
H XP_011765112.1 Macaca nemestrina
H XP_004062252.3 Gorilla gorilla gorilla
H XP_001144517.1 Pan troglodytes
H XP_003825981.1 Pan paniscus
H XP_031999201.1 Hylobates moloch
H XP_003253658.1 Nomascus leucogenys
H XP_055122373.1 Symphalangus syndactylus
H XP_054322460.1 Pongo pygmaeus
H XP_024094500.1 Pongo abelii
     Gene: ADA
    Human: 17 H
Alignment: 56 H
H    32
P     1
Name: count, dtype: int64

H XP_008065101.1 Carlito syrichta
H XP_053429777.1 Nycticebus coucang
H XP_012659258.1 Otolemur garnettii
H XP_075867256.1 Microcebus murinus
H XP_012513400.1 Propithecus coquereli
H XP_069351986.1 Eulemur rufifrons
H XP_045385118.1 Lemur catta
P XP_017733490.1 Rhinopithecus bieti
H XP_032119629.1 Sapajus apella
H XP_017396666.1 Cebus imitator
H XP_010345201.1 Saimiri boliviensis
H XP_002747684.1 Callithrix jacchus
H XP_012322665.1 Aotus nancymaae
H XP_011853020.1 Mandrillus leucophaeus
H XP_050662503.1 Macaca thibetana thibetana
H NP_000013.2 Homo sapiens
H XP_033042389.1 Trachypithecus francoisi
H XP_011784375.1 Colobus angolensis palliatus
H XP_023083619.1 Piliocolobus tephrosceles
H XP_025255097.1 Theropithecus gelada
H XP_008014692.1 Chlorocebus sabaeus
H XP_003904754.1 Papio anubis
H XP_011921136.1 Cercocebus atys
H XP_028684274.1 Macaca mulatta
H XP_011765112.1 Macaca nemestrina
H XP_004062252.3 Gorilla gorilla gorilla
H XP_001144517.1 Pan troglodytes
H XP_003825981.1 Pan paniscus
H XP_031999201.1 Hylobates moloch
H XP_003253658.1 Nomascus leucogenys
H XP_055122373.1 Symphalangus syndactylus
H XP_054322460.1 Pongo pygmaeus
H XP_024094500.1 Pongo abelii
     Gene: AGXT
    Human: 156 G
Alignment: 260 G
G    34
A     1
Name: count, dtype: int64

G XP_032609172.2 Hylobates moloch
G XP_030658870.1 Nomascus leucogenys
G XP_055143864.1 Symphalangus syndactylus
G XP_054334986.2 Pongo pygmaeus
G NP_001125018.1 Pongo abelii
G NP_000021.1 Homo sapiens
G XP_018878332.3 Gorilla gorilla gorilla
G XP_024210943.1 Pan troglodytes
G XP_003813122.2 Pan paniscus
G XP_007965133.1 Chlorocebus sabaeus
G XP_025260587.1 Theropithecus gelada
G XP_003908226.1 Papio anubis
G XP_011896991.1 Cercocebus atys
G XP_011851782.1 Mandrillus leucophaeus
G XP_005574906.2 Macaca fascicularis
G XP_011726084.1 Macaca nemestrina
G XP_050607986.1 Macaca thibetana thibetana
G XP_001090301.2 Macaca mulatta
G XP_017716141.1 Rhinopithecus bieti
G XP_011784959.1 Colobus angolensis palliatus
G XP_010375322.1 Rhinopithecus roxellana
G XP_033085427.1 Trachypithecus francoisi
G XP_023050886.1 Piliocolobus tephrosceles
G XP_012320482.2 Aotus nancymaae
G XP_074254842.1 Saimiri boliviensis
G XP_002750020.4 Callithrix jacchus
G XP_032125387.1 Sapajus apella
G XP_017366221.1 Cebus imitator
G XP_008052438.1 Carlito syrichta
G XP_053454048.1 Nycticebus coucang
A XP_003798296.1 Otolemur garnettii
G XP_012611190.1 Microcebus murinus
G XP_012517881.1 Propithecus coquereli
G XP_069352953.1 Eulemur rufifrons
G XP_045415864.1 Lemur catta
     Gene: AGXT
    Human: 260 Y
Alignment: 364 Y
Y    34
C     1
Name: count, dtype: int64

Y XP_032609172.2 Hylobates moloch
Y XP_030658870.1 Nomascus leucogenys
Y XP_055143864.1 Symphalangus syndactylus
Y XP_054334986.2 Pongo pygmaeus
Y NP_001125018.1 Pongo abelii
Y NP_000021.1 Homo sapiens
Y XP_018878332.3 Gorilla gorilla gorilla
Y XP_024210943.1 Pan troglodytes
Y XP_003813122.2 Pan paniscus
Y XP_007965133.1 Chlorocebus sabaeus
Y XP_025260587.1 Theropithecus gelada
Y XP_003908226.1 Papio anubis
Y XP_011896991.1 Cercocebus atys
Y XP_011851782.1 Mandrillus leucophaeus
Y XP_005574906.2 Macaca fascicularis
Y XP_011726084.1 Macaca nemestrina
Y XP_050607986.1 Macaca thibetana thibetana
Y XP_001090301.2 Macaca mulatta
C XP_017716141.1 Rhinopithecus bieti
Y XP_011784959.1 Colobus angolensis palliatus
Y XP_010375322.1 Rhinopithecus roxellana
Y XP_033085427.1 Trachypithecus francoisi
Y XP_023050886.1 Piliocolobus tephrosceles
Y XP_012320482.2 Aotus nancymaae
Y XP_074254842.1 Saimiri boliviensis
Y XP_002750020.4 Callithrix jacchus
Y XP_032125387.1 Sapajus apella
Y XP_017366221.1 Cebus imitator
Y XP_008052438.1 Carlito syrichta
Y XP_053454048.1 Nycticebus coucang
Y XP_003798296.1 Otolemur garnettii
Y XP_012611190.1 Microcebus murinus
Y XP_012517881.1 Propithecus coquereli
Y XP_069352953.1 Eulemur rufifrons
Y XP_045415864.1 Lemur catta
     Gene: AGXT
    Human: 82 G
Alignment: 105 G
G    33
A     2
Name: count, dtype: int64

G XP_032609172.2 Hylobates moloch
G XP_030658870.1 Nomascus leucogenys
G XP_055143864.1 Symphalangus syndactylus
A XP_054334986.2 Pongo pygmaeus
A NP_001125018.1 Pongo abelii
G NP_000021.1 Homo sapiens
G XP_018878332.3 Gorilla gorilla gorilla
G XP_024210943.1 Pan troglodytes
G XP_003813122.2 Pan paniscus
G XP_007965133.1 Chlorocebus sabaeus
G XP_025260587.1 Theropithecus gelada
G XP_003908226.1 Papio anubis
G XP_011896991.1 Cercocebus atys
G XP_011851782.1 Mandrillus leucophaeus
G XP_005574906.2 Macaca fascicularis
G XP_011726084.1 Macaca nemestrina
G XP_050607986.1 Macaca thibetana thibetana
G XP_001090301.2 Macaca mulatta
G XP_017716141.1 Rhinopithecus bieti
G XP_011784959.1 Colobus angolensis palliatus
G XP_010375322.1 Rhinopithecus roxellana
G XP_033085427.1 Trachypithecus francoisi
G XP_023050886.1 Piliocolobus tephrosceles
G XP_012320482.2 Aotus nancymaae
G XP_074254842.1 Saimiri boliviensis
G XP_002750020.4 Callithrix jacchus
G XP_032125387.1 Sapajus apella
G XP_017366221.1 Cebus imitator
G XP_008052438.1 Carlito syrichta
G XP_053454048.1 Nycticebus coucang
G XP_003798296.1 Otolemur garnettii
G XP_012611190.1 Microcebus murinus
G XP_012517881.1 Propithecus coquereli
G XP_069352953.1 Eulemur rufifrons
G XP_045415864.1 Lemur catta
     Gene: AHI1
    Human: 383 D
Alignment: 397 D
D    33
G     1
-     1
Name: count, dtype: int64

G XP_012520629.1 Propithecus coquereli
D XP_021571896.1 Carlito syrichta
D XP_030665581.1 Nomascus leucogenys
D XP_063487309.1 Symphalangus syndactylus
D XP_032015475.1 Hylobates moloch
D XP_054349527.2 Pongo pygmaeus

In [22]:
for _, row in df.iterrows():
    gene = row["gene"]
    protein = row["protein"]
    site = int(row["site"])
    print(f"Processing gene: {gene}, protein: {protein}, site: {site}")
    result_species = get_alleles_with_species(gene, protein, site)
    #print(result_species)

Processing gene: ACADM, protein: NP_000007.1, site: 29
Processing gene: ACADM, protein: NP_000007.1, site: 31
Processing gene: ACADM, protein: NP_000007.1, site: 103
Processing gene: ACADM, protein: NP_000007.1, site: 29
Processing gene: ACADVL, protein: NP_000009.1, site: 174
Processing gene: ACADVL, protein: NP_000009.1, site: 219
Processing gene: ACADVL, protein: NP_000009.1, site: 286
Processing gene: ACADVL, protein: NP_000009.1, site: 647
Processing gene: ACAT1, protein: NP_000010.1, site: 1
Processing gene: ACAT1, protein: NP_000010.1, site: 1
Processing gene: ADA, protein: NP_000013.2, site: 15
Processing gene: ADA, protein: NP_000013.2, site: 17
Processing gene: AGXT, protein: NP_000021.1, site: 156
Processing gene: AGXT, protein: NP_000021.1, site: 260
Processing gene: AGXT, protein: NP_000021.1, site: 82
Processing gene: AHI1, protein: NP_001128302.1, site: 383
Processing gene: AIRE, protein: NP_000374.1, site: 21
Processing gene: AIRE, protein: NP_000374.1, site: 1
Processing gene: ALMS1, protein: NP_001365383.1, site: 2378
Processing gene: ALMS1, protein: NP_001365383.1, site: 1155
Processing gene: ALMS1, protein: NP_001365383.1, site: 2465
Processing gene: ALPL, protein: NP_000469.3, site: 51
Processing gene: ALPL, protein: NP_000469.3, site: 82
Processing gene: ALPL, protein: NP_000469.3, site: 82
Processing gene: ALPL, protein: NP_000469.3, site: 85
Processing gene: ALPL, protein: NP_000469.3, site: 93
Processing gene: ALPL, protein: NP_000469.3, site: 295
Processing gene: ARSB, protein: NP_000037.2, site: 97
Processing gene: ARSB, protein: NP_000037.2, site: 85
Processing gene: ARSB, protein: NP_000037.2, site: 152
Processing gene: ARSB, protein: NP_000037.2, site: 95
Processing gene: ASL, protein: NP_000039.2, site: 113
Processing gene: ASL, protein: NP_000039.2, site: 146
Processing gene: ASL, protein: NP_000039.2, site: 241
Processing gene: ATP7B, protein: NP_000044.2, site: 969
Processing gene: ATP7B, protein: NP_000044.2, site: 335
Processing gene: ATP7B, protein: NP_000044.2, site: 1407
Processing gene: ATP7B, protein: NP_000044.2, site: 1217
Processing gene: BCKDHA, protein: NP_000700.1, site: 438
Processing gene: BEST1, protein: NP_004174.1, site: 15
Processing gene: BEST1, protein: NP_004174.1, site: 17
Processing gene: BTD, protein: NP_001268652.2, site: 489
Processing gene: BTD, protein: NP_001268652.2, site: 282
Processing gene: CBS, protein: NP_000062.1, site: 65
Processing gene: CERKL, protein: NP_963842.1, site: 283
Processing gene: CFTR, protein: NP_000483.3, site: 13
Processing gene: CFTR, protein: NP_000483.3, site: 1
Processing gene: CLN3, protein: NP_000077.1, site: 295
Processing gene: CNGB3, protein: NP_061971.3, site: 309
Processing gene: CPS1, protein: NP_001116105.2, site: 1173
Processing gene: CRB1, protein: NP_957705.1, site: 564
Processing gene: CRB1, protein: NP_957705.1, site: 611
Processing gene: CRB1, protein: NP_957705.1, site: 539
Processing gene: CYP11B1, protein: NP_000488.3, site: 88
Processing gene: CYP17A1, protein: NP_000093.1, site: 82
Processing gene: ERCC6, protein: NP_001263987.1, site: 934
Processing gene: EYS, protein: NP_001136272.1, site: 2502
Processing gene: F8, protein: NP_000123.1, site: 2038
Processing gene: F8, protein: NP_000123.1, site: 2157
Processing gene: F9, protein: NP_000124.1, site: 75
Processing gene: FANCA, protein: NP_000126.2, site: 936
Processing gene: FANCA, protein: NP_000126.2, site: 358
Processing gene: G6PD, protein: NP_000393.4, site: 3
Processing gene: G6PD, protein: NP_000393.4, site: 12
Processing gene: G6PD, protein: NP_000393.4, site: 166
Processing gene: GALC, protein: NP_000144.2, site: 1
Processing gene: GALC, protein: NP_000144.2, site: 1
Processing gene: GALNS, protein: NP_000503.1, site: 318
Processing gene: GALNS, protein: NP_000503.1, site: 388
Processing gene: GALNS, protein: NP_000503.1, site: 94
Processing gene: GALNS, protein: NP_000503.1, site: 496
Processing gene: GALNS, protein: NP_000503.1, site: 113
Processing gene: GALT, protein: NP_000146.2, site: 223
Processing gene: GBA1, protein: NP_000148.2, site: 502
Processing gene: GBA1, protein: NP_000148.2, site: 535
Processing gene: GBA1, protein: NP_000148.2, site: 227
Processing gene: GBA1, protein: NP_000148.2, site: 351
Processing gene: GBA1, protein: NP_000148.2, site: 350
Processing gene: GBA1, protein: NP_000148.2, site: 416
Processing gene: GBA1, protein: NP_000148.2, site: 426
Processing gene: GBA1, protein: NP_000148.2, site: 230
Processing gene: GBA1, protein: NP_000148.2, site: 351
Processing gene: GBA1, protein: NP_000148.2, site: 391
Processing gene: GCDH, protein: NP_000150.1, site: 298
Processing gene: GCDH, protein: NP_000150.1, site: 191
Processing gene: HBB, protein: NP_000509.1, site: 102
Processing gene: HGD, protein: NP_000178.2, site: 53
Processing gene: IVD, protein: NP_002216.3, site: 47
Processing gene: IVD, protein: NP_002216.3, site: 147
Processing gene: KCNQ1, protein: NP_000209.2, site: 114
Processing gene: KCNQ1, protein: NP_000209.2, site: 115
Processing gene: KCNQ1, protein: NP_000209.2, site: 125
Processing gene: KCNQ1, protein: NP_000209.2, site: 117
Processing gene: KCNQ1, protein: NP_000209.2, site: 119
Processing gene: LDLR, protein: NP_000518.1, site: 46
Processing gene: LDLR, protein: NP_000518.1, site: 583
Processing gene: LDLR, protein: NP_000518.1, site: 579
Processing gene: LDLR, protein: NP_000518.1, site: 88
Processing gene: LDLR, protein: NP_000518.1, site: 301
Processing gene: LDLR, protein: NP_000518.1, site: 718
Processing gene: LDLR, protein: NP_000518.1, site: 853
Processing gene: MUTYH, protein: NP_001121897.1, site: 386
Processing gene: MUTYH, protein: NP_001121897.1, site: 83
Processing gene: NAGLU, protein: NP_000254.2, site: 35
Processing gene: NAGLU, protein: NP_000254.2, site: 309
Processing gene: NAGLU, protein: NP_000254.2, site: 1
Processing gene: NPC1, protein: NP_000262.2, site: 372
Processing gene: NPC1, protein: NP_000262.2, site: 167
Processing gene: OCA2, protein: NP_000266.2, site: 780
Processing gene: PAH, protein: NP_000268.1, site: 164
Processing gene: PAH, protein: NP_000268.1, site: 176
Processing gene: PAH, protein: NP_000268.1, site: 413
Processing gene: PAH, protein: NP_000268.1, site: 156
Processing gene: PAX6, protein: NP_001245391.1, site: 1
Processing gene: PKHD1, protein: NP_619639.3, site: 760
Processing gene: PKHD1, protein: NP_619639.3, site: 222
Processing gene: PMM2, protein: NP_000294.1, site: 237
Processing gene: PMM2, protein: NP_000294.1, site: 239
Processing gene: RECQL4, protein: NP_004251.4, site: 1021
Processing gene: RP1, protein: NP_006260.1, site: 793
Processing gene: SACS, protein: NP_055178.3, site: 1
Processing gene: SLC26A4, protein: NP_000432.1, site: 422
Processing gene: SYNE1, protein: NP_892006.3, site: 815
Processing gene: TCIRG1, protein: NP_001427481.1, site: 558
Processing gene: TMEM67, protein: NP_714915.3, site: 92
Processing gene: TTR, protein: NP_000362.1, site: 142
Processing gene: TTR, protein: NP_000362.1, site: 127
Processing gene: TTR, protein: NP_000362.1, site: 82
Processing gene: TTR, protein: NP_000362.1, site: 77
Processing gene: TTR, protein: NP_000362.1, site: 126
Processing gene: USH2A, protein: NP_996816.3, site: 3719
Processing gene: VHL, protein: NP_000542.1, site: 151
Processing gene: VHL, protein: NP_000542.1, site: 132
Processing gene: VHL, protein: NP_000542.1, site: 154
Processing gene: VHL, protein: NP_000542.1, site: 114
Processing gene: VHL, protein: NP_000542.1, site: 161
Processing gene: VHL, protein: NP_000542.1, site: 170
Processing gene: VWF, protein: NP_000543.3, site: 528
Processing gene: WT1, protein: NP_077744.4, site: 341
Processing gene: ZEB2, protein: NP_055610.1, site: 1049

In [25]:
result_species

[]

In [1]:
run kondrashov

In [24]:
for _, row in df.iterrows():

    gene = row["gene"]
    protein = row["protein"]
    site = int(row["site"])
    mut = row["muts"]

    result_species = get_alleles_with_species(gene, protein, site)

    for variant in result_species:
        # Only compare the species carrying the ClinVar mutant
        if variant["amino_acid"] == mut:
            variant_protein = variant["protein"]

            print(
                gene,
                protein,
                site,
                mut,
                variant["species"],
                variant_protein
            )

            local_compare_to_human(
                gene,
                protein,
                site,
                variant_protein
            )

ACADVL NP_000009.1 286 K Nycticebus coucang XP_053423543.1
-10 K K
-9 E E
-8 K K
-7 I I
-6 T T
-5 A A
-4 F F
-3 V V
-2 V V
-1 E E
0 R K
1 G S
2 F F
3 G G
4 G G
5 I V
6 T T
7 H H
8 G G
9 P P
10 P P
ACADVL NP_000009.1 647 M Nycticebus coucang XP_053423543.1
-10 I I
-9 S S
-8 K T
-7 A A
-6 L L
-5 V V
-4 E E
-3 R R
-2 G G
-1 G G
0 V M
1 V V
2 T T
3 S S
4 N N
5 P P
6 L L
7 G G
8 F F
9 outside sequence
10 outside sequence
AHI1 NP_001128302.1 383 G Propithecus coquereli XP_012520629.1
-10 E -
-9 H -
-8 T -
-7 G -
-6 Q -
-5 Y -
-4 V -
-3 K -
-2 K -
-1 D -
0 D G
1 S F
2 G E
3 R R
4 P P
5 V V
6 S S
7 S S
8 Y Y
9 Y Y
10 E E
ALMS1 NP_001365383.1 1155 Y Carlito syrichta XP_008054818.1
-10 S W
-9 Q -
-8 H H
-7 R G
-6 E K
-5 K K
-4 P P
-3 S D
-2 I I
-1 F F
0 H Y
1 Q Q
2 Q Q
3 A V
4 L L
5 P P
6 G D
7 T S
8 H H
9 I L
10 P S
ALMS1 NP_001365383.1 2465 L Carlito syrichta XP_008054818.1
-10 S S
-9 I I
-8 T T
-7 D D
-6 S S
-5 R R
-4 E E
-3 E E
-2 E E
-1 G G
0 V L
1 S S
2 E E
3 S S
4 E E
5 D D
6 G G
7 G G
8 G G
9 S S
10 S S
ARSB NP_000037.2 97 R Carlito syrichta XP_021566074.1
-10 T L
-9 Q K
-8 P A
-7 L H
-6 C L
-5 T S
-4 P W
-3 S C
-2 R W
-1 S R
0 Q R
1 L L
2 L V
3 T S
4 G A
5 R Q
6 Y R
7 Q N
8 I I
9 R H
10 T T
ARSB NP_000037.2 85 H Carlito syrichta XP_021566074.1
-10 G A
-9 G G
-8 V L
-7 - R
-6 - P
-5 - S
-4 L I
-3 L L
-2 D T
-1 N F
0 Y H
1 Y V
2 T L
3 Q K
4 P A
5 L H
6 C L
7 T S
8 P W
9 S C
10 R W
ARSB NP_000037.2 152 Q Carlito syrichta XP_021566074.1
-10 M M
-9 V V
-8 G G
-7 K K
-6 W W
-5 H H
-4 L L
-3 G G
-2 M M
-1 Y Y
0 R Q
1 K K
2 E E
3 C C
4 L L
5 P P
6 T T
7 R R
8 R R
9 G G
10 F F
ARSB NP_000037.2 95 W Carlito syrichta XP_021566074.1
-10 Y H
-9 Y V
-8 T L
-7 Q K
-6 P A
-5 L H
-4 C L
-3 T S
-2 P W
-1 S C
0 R W
1 S R
2 Q R
3 L L
4 L V
5 T S
6 G A
7 R Q
8 Y R
9 Q N
10 I I
ASL NP_000039.2 146 P Cebus imitator XP_037587702.1
-10 L P
-9 W W
-8 E E
-7 L I
-6 I L
-5 R -
-4 T -
-3 M -
-2 V -
-1 D D
0 R P
1 A S
2 E F
3 A R
4 E E
5 R C
6 D D
7 V V
8 L L
9 F F
10 P P
BCKDHA NP_000700.1 438 H Macaca thibetana thibetana XP_050624431.1
-10 A A
-9 R G
-8 H Q
-7 L V
-6 Q A
-5 T A
-4 Y A
-3 G N
-2 E K
-1 H K
0 Y H
1 P -
2 L -
3 D -
4 H -
5 F -
6 D -
7 K -
8 outside sequence
9 outside sequence
10 outside sequence
BTD NP_001268652.2 489 S Carlito syrichta XP_021563154.1
-10 F F
-9 L T
-8 T V
-7 S T
-6 G Q
-5 M R
-4 T P
-3 L G
-2 E Q
-1 V A
0 P S
1 D A
2 Q V
3 L V
4 G G
5 W F
6 E E
7 N P
8 D G
9 H H
10 Y V
BTD NP_001268652.2 282 R Carlito syrichta XP_021563154.1
-10 F L
-9 G G
-8 I V
-7 N N
-6 V V
-5 L L
-4 A A
-3 A A
-2 N N
-1 V I
0 H R
1 H H
2 P P
3 V A
4 L L
5 G G
6 M M
7 T T
8 G G
9 S S
10 G G
CBS NP_000062.1 65 L Cercocebus atys XP_011892990.1
-10 Q P
-9 L L
-8 G H
-7 R R
-6 P G
-5 A L
-4 S S
-3 E Q
-2 S G
-1 P I
0 H L
1 H H
2 H R
3 T H
4 A L
5 P A
6 A A
7 K A
8 S A
9 P P
10 K N
CPS1 NP_001116105.2 1173 P ammonia], mitochondrial, partia XP_012516669.1
-10 P K
-9 V I
-8 V A
-7 L K
-6 T A
-5 K F
-4 F A
-3 V I
-2 E S
-1 G G
0 A P
1 R F
2 E N
3 V V
4 E Q
5 M F
6 D L
7 A V
8 V K
9 G G
10 K N
CYP17A1 NP_000093.1 82 D Carlito syrichta XP_021564209.1
-10 T E
-9 T P
-8 V -
-7 I -
-6 V P
-5 G G
-4 H C
-3 H C
-2 Q S
-1 L L
0 A D
1 K E
2 E K
3 V -
4 L -
5 I -
6 K -
7 K -
8 G -
9 K -
10 D -
G6PD NP_000393.4 12 L Nycticebus coucang XP_053436618.1
-10 G G
-9 R E
-8 R W
-7 G D
-6 S R
-5 A A
-4 P V
-3 G G
-2 N N
-1 G C
0 R L
1 T A
2 L -
3 R -
4 G -
5 C -
6 E E
7 R R
8 G G
9 G G
10 R R
GALNS NP_000503.1 94 L Piliocolobus tephrosceles XP_026303165.1
-10 A A
-9 A R
-8 L I
-7 L L
-6 T H
-5 G S
-4 R S
-3 L Q
-2 P S
-1 I A
0 R L
1 N A
2 G G
3 F P
4 Y F
5 T V
6 T P
7 N M
8 A T
9 H G
10 A L
HBB NP_000509.1 102 Q Microcebus murinus XP_012642085.1
-10 L L
-9 H H
-8 C C
-7 D D
-6 K K
-5 L L
-4 H H
-3 V V
-2 D D
-1 P P
0 E Q
1 N N
2 F F
3 R T
4 L L
5 L L
6 G G
7 N N
8 V V
9 L L
10 V V
IVD NP_002216.3 47 K Carlito syrichta XP_008068042.1
-10 D D
-9 A A
-8 I I
-7 N N
-6 G G
-5 L L
-4 S S
-3 E E
-2 E E
-1 Q Q
0 R K
1 Q Q
2 L L
3 R R
4 Q Q
5 T T
6 M V
7 A A
8 K K
9 F F
10 L L
LDLR NP_000518.1 88 K Carlito syrichta XP_021573646.1
-10 R R
-9 V I
-8 N N
-7 R R
-6 C C
-5 I I
-4 P P
-3 Q Q
-2 F F
-1 W W
0 R K
1 C C
2 D D
3 G G
4 Q Q
5 V V
6 D D
7 C C
8 D E
9 N N
10 G G
LDLR NP_000518.1 853 I Carlito syrichta XP_021573646.1
-10 D D
-9 G G
-8 Y Y
-7 S T
-6 Y Y
-5 P P
-4 S S
-3 R R
-2 Q Q
-1 M M
0 V I
1 S S
2 L L
3 E E
4 D D
5 D D
6 V A
7 A A
8 outside sequence
9 outside sequence
10 outside sequence
MUTYH NP_001121897.1 386 R Microcebus murinus XP_012631449.1
-10 L L
-9 E E
-8 Q Q
-7 P P
-6 G R
-5 A A
-4 L L
-3 G G
-2 - G
-1 A A
0 Q R
1 I I
2 L L
3 L L
4 V V
5 Q Q
6 R R
7 P P
8 N K
9 S S
10 G G
MUTYH NP_001121897.1 83 P Microcebus murinus XP_012631449.1
-10 E E
-9 E E
-8 V V
-7 V V
-6 L L
-5 Q Q
-4 A A
-3 S S
-2 V I
-1 S S
0 S P
1 Y Y
2 H H
3 L L
4 F F
5 R R
6 D D
7 V T
8 A A
9 E E
10 V V
SLC26A4 NP_000432.1 422 I Carlito syrichta XP_021565405.1
-10 V V
-9 Q Q
-8 E E
-7 S S
-6 T T
-5 G G
-4 G G
-3 K K
-2 T T
-1 Q Q
0 V I
1 A A
2 G G
3 I I
4 I I
5 S S
6 A A
7 A V
8 I I
9 V V
10 M M
TTR NP_000362.1 127 V Saimiri boliviensis XP_010333768.1
-10 A A
-9 N N
-8 D E
-7 S S
-6 G G
-5 P P
-4 R R
-3 R H
-2 Y Y
-1 T I
0 I V
1 A A
2 A A
3 L L
4 L L
5 S S
6 P P
7 Y Y
8 S S
9 Y Y
10 S S
TTR NP_000362.1 126 I Saimiri boliviensis XP_010333768.1
-10 T A
-9 A A
-8 N N
-7 D E
-6 S S
-5 G G
-4 P P
-3 R R
-2 R H
-1 Y Y
0 T I
1 I V
2 A A
3 A A
4 L L
5 L L
6 S S
7 P P
8 Y Y
9 S S
10 Y Y
VHL NP_000542.1 151 L Pan paniscus XP_024783971.1
-10 N -
-9 V M
-8 D E
-7 G N
-6 Q T
-5 P F
-4 I L
-3 F L
-2 A G
-1 N R
0 I L
1 T T
2 L D
3 P A
4 V K
5 Y T
6 T G
7 L T
8 K S
9 E Q
10 R G
VHL NP_000542.1 132 P Pan paniscus XP_024783971.1
-10 A -
-9 G -
-8 T -
-7 H -
-6 D -
-5 G -
-4 L V
-3 L L
-2 V M
-1 N T
0 Q P
1 T V
2 E G
3 L Q
4 F F
5 - C
6 - V
7 V V
8 P P
9 S A
10 L L
VHL NP_000542.1 154 A Pan paniscus XP_024783971.1
-10 G N
-9 Q T
-8 P F
-7 I L
-6 F L
-5 A G
-4 N R
-3 I L
-2 T T
-1 L D
0 P A
1 V K
2 Y T
3 T G
4 L T
5 K S
6 E Q
7 R G
8 C H
9 L V
10 Q G
VHL NP_000542.1 161 G Pan paniscus XP_024783971.1
-10 I L
-9 T T
-8 L D
-7 P A
-6 V K
-5 Y T
-4 T G
-3 L T
-2 K S
-1 E Q
0 R G
1 C H
2 L V
3 Q G
4 V A
5 V G
6 R R
7 - A
8 - D
9 - H
10 - V
VHL NP_000542.1 170 L Pan paniscus XP_024783971.1
-10 - D
-9 - H
-8 - V
-7 - W
-6 - H
-5 - G
-4 - K
-3 - L
-2 S T
-1 L Y
0 V L
1 K P
2 P A
3 E G
4 N R
5 Y W
6 R R
7 R G
8 L C
9 D G
10 I C
VWF NP_000543.3 528 S Carlito syrichta XP_021573487.1
-10 C S
-9 G G
-8 N S
-7 - P
-6 - H
-5 - S
-4 - L
-3 - K
-2 - A
-1 Y Y
0 N S
1 G G
2 N P
3 Q Q
4 - D
5 - V
6 - G
7 - T
8 G G
9 D T
10 D R
WT1 NP_077744.4 341 G Carlito syrichta XP_021562474.1
-10 V V
-9 K K
-8 W W
-7 T T
-6 E E
-5 G G
-4 Q Q
-3 S S
-2 N N
-1 H H
0 S G
1 T A
2 G G
3 Y Y
4 E E
5 S S
6 D D
7 N N
8 H H
9 T T
10 T T

### Step 2 
Investigate the vicinity of the sequence, 10 amino acids on either side of the site

In [28]:
local_compare_to_human('ATP7B', 'NP_000044.2', 335, 'XP_012638109.2')

-10 V V
-9 S S
-8 L L
-7 P P
-6 D D
-5 G G
-4 A A
-3 E E
-2 G G
-1 S S
0 G E
1 T T
2 D D
3 H P
4 R G
5 S P
6 S S
7 S G
8 S C
9 H H
10 S S

(5, 0, 0)